### ISSUE TITLE
Make dialog boxes look native

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#103]
![screenshot](https://user-images.githubusercontent.com/2480569/48704319-7f002c00-ebf6-11e8-9f6b-701cf59319c3.png)

This screen looks "alien" on Xubuntu since it ignores the system theme. Why is this? After all, I am using a deb package and one would think it would be using system Qt. Isn't it?

**Comment by TheAssassin** [comment]
It works fine on my system (xubuntu 18.04). I wonder why this is an issue. Are there any theme packages the package should depend on?

**Comment by probonopd** [comment]
If only I knew that...! I am using `xubuntu-18.04-desktop-amd64.iso` in case you would like to investigate.

**Comment by probonopd** [comment]
I installed the deb that does not have the "bionic" in its name. Should that have made a difference? Lemme try...

**Comment by TheAssassin** [comment]
> I installed the deb that does not have the "bionic" in its name.

I wonder why that worked _at all_...

Yes, it should make a difference, as the bionic package is also _built_ on bionic. That sort-of tells us there must be some theme missing.

**Comment by TheAssassin** [comment]
Can't make things look "more native" with our Debian packages. Closing.

**Comment by probonopd** [comment]
Please reopen. I am talking about the AppImageLauncher Lite AppImage. Need to

```
########################################################################
# Build Plaform Theme for Gtk+
########################################################################

git clone http://code.qt.io/qt/qtstyleplugins.git
cd qtstyleplugins
qmake
make -j$(nproc)
make install 
cd -
```

Then also deploy `platformthemes/libqgtk2.so` and `styles/libqgtk2style.so`  but do _not_ deploy their Gtk dependencies.

**Comment by TheAssassin** [comment]
Last time I tried these platform themes didn't work with the kind of old Qt we are bound to use with AIL builds (as in, didn't build first, then segfaulted).

**Comment by probonopd** [comment]
Starting with Qt 5.9ish or so it is working fine for me.

**Comment by TheAssassin** [comment]
> the kind of old Qt we are bound to use with AIL builds 

https://packages.ubuntu.com/de/xenial/qt5-default yields Qt 5.5.x.

**Comment by probonopd** [comment]
Let's use beineri's one.

**Comment by TheAssassin** [comment]
Err, no, surely not. We're making native packages, and there's a working build infra for everything. I'm not going to make any special treatment for anything there. It's enough work already, and this is purely cosmetical.

**Comment by probonopd** [comment]
Cosmetical is important. Personally I only care about the AILL AppImage, if worst comes to worst we can use a different Qt version for that alone.
