### ISSUE TITLE
There are only Bionic packages in the releases link, where are the other packages?

### ISSUE THREAD

**Issue by phd21** [TheAssassin/AppImageLauncher#106]
Hello TheAssassin,

There are only Bionic packages in the current releases link, where are the other packages for the other versions of Linux?

Best regards,
Phil (phd21)

**Comment by TheAssassin** [comment]
I must've screwed up something in CMake, which builds fine on my system but confuses the one on Travis CI. I'll be fixing those as soon as possible.

Meanwhile, please refer to https://artifacts.assassinate-you.net/artifactory/list/AppImageLauncher/travis-414/, the last stable build, which contains working binaries.
