### ISSUE TITLE
ignore /tmp cached files?

### ISSUE THREAD

**Issue by star-buck** [TheAssassin/AppImageLauncher#11]
Trying this appimage after having installed appimangelauncher:
https://www.opendesktop.org/p/1175480/

if I choose to run / install the opendesktop-app.appimage, it does call another appimage that temporary gets extracted in a cache, which then is detected again by AppImageLauncher and suggested to run or move (which it doesnt need, since the app once started takes care of anything by itself).
Now if one does press "install" again for that temp appimage in cache, it gets removed from its location and installed under .bin, where the opendesktop-app.appimage cannot find it anymore afterwards and therefore doesnt work, even if started once again :)

![screenshot_20180403_163752](https://user-images.githubusercontent.com/840070/38267753-abbd7d30-377c-11e8-848f-025c7bc08b7d.png)

Any ideas for how to handle this corner case welcome.

**Comment by TheAssassin** [comment]
That's a really interesting use case... AppImages in AppImages.

It should be fairly easy to ignore paths starting with `/tmp/.mount_*`, which tell us it's an AppImage's mounted contents.

Also, IIRC, ocs-manager is a "CLI" tool (well, a service application running headlessly, so its desktop file has set `Terminal=true`), therefore the issue could be solved by implementing #2 as well. But I'd like to implement the "ignoring AppImages in AppImages" idea as well.

**Comment by probonopd** [comment]
I would not ask the user to move anything if the AppImage is on a read-only partition.

**Comment by star-buck** [comment]
Its not really about moving, its annoying and unneeded by itself popping up
at all, as the appimage should and does already take care of everything
else, including the second appimage.

**Comment by TheAssassin** [comment]
> I would not ask the user to move anything if the AppImage is on a read-only partition. Even informing the user would be just disturbing, because it probably is on a read-only medium for a purpose.

Well, in case it's on a "read-only" partition, you can still copy the file normally... I mean, how to check whether it's a read-only medium? You could only really check the permissions of a file, or just try to copy the file.

In case of ocs-manager, the AppImage isn't meant to be integrated. It's an integral part of the OCS-Store application, and isn't meant to be moved out of this directory.

Maybe we even need a desktop file key that tells us not to integrate desktop files at all? I think we could re-use `NoDisplay=true`.

**Comment by TheAssassin** [comment]
Fixed in https://github.com/TheAssassin/AppImageLauncher/commit/a7b57b835edc8689e4b6ea614c5fda8daaacd64b.
