### ISSUE TITLE
Error when installing from source on Arch Linux

### ISSUE THREAD

**Issue by makeworld-the-better-one** [TheAssassin/AppImageLauncher#110]
Here's the compiling error I get when installing on Arch Linux. `makeworld` is the username on my system, and `yay` is the AUR installer I used, so you can ignore that part in the log below.

```
/home/makeworld/.cache/yay/appimagelauncher-git/src/AppImageLauncher/lib/AppImageUpdate/lib/zsync2/lib/cpr/cpr/error.cpp: In static member function ‘static cpr::ErrorCode cpr::Error::getErrorCodeForCurlError(int32_t)’:
/home/makeworld/.cache/yay/appimagelauncher-git/src/AppImageLauncher/lib/AppImageUpdate/lib/zsync2/lib/cpr/cpr/error.cpp:41:9: error: duplicate case value
         case CURLE_SSL_CACERT:
         ^~~~
/home/makeworld/.cache/yay/appimagelauncher-git/src/AppImageLauncher/lib/AppImageUpdate/lib/zsync2/lib/cpr/cpr/error.cpp:25:9: note: previously used here
         case CURLE_PEER_FAILED_VERIFICATION:
         ^~~~
make[2]: *** [lib/AppImageUpdate/lib/zsync2/lib/cpr/cpr/CMakeFiles/cpr.dir/build.make:115: lib/AppImageUpdate/lib/zsync2/lib/cpr/cpr/CMakeFiles/cpr.dir/error.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2459: lib/AppImageUpdate/lib/zsync2/lib/cpr/cpr/CMakeFiles/cpr.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: appimagelauncher-git
```

You can view the AUR package [here](https://aur.archlinux.org/packages/appimagelauncher-git/). The PKGBUILD (file used to install it) is [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=appimagelauncher-git). The offending section of that PKGBUILD that led to the error is repeated below:

```
cmake . -DCMAKE_INSTALL_PREFIX:PATH=/usr/ -DCMAKE_INSTALL_LIBDIR=/usr/lib
make
```

The log seems to suggest the error lies with `zsync2`.

**Comment by TheAssassin** [comment]
It seems curl broke backwards compatibility in some way, and our [C++ wrapper](https://github.com/whoshuu/cpr) hasn't been updated in over a year and starts to make problems on more recent operating systems, including Arch etc.

As you correctly found out, the problem lies within zsync2, and there's an open issue for which you might want to subscribe: https://github.com/AppImage/zsync2/issues/30

**Comment by TheAssassin** [comment]
This specific issue should be fixed. We still plan to replace the HTTP backend eventually.
