### ISSUE TITLE
if answering "Run" the first time just to try an appimage before installing it, AIL should continue to ask every time unless (as suggested) a "TICK" to never ask again settles this

### ISSUE THREAD

**Issue by star-buck** [TheAssassin/AppImageLauncher#114]
This is superimportant, but eve then when clicked "never ask again" for a certain app, it may still be that one would like to integrate an app into the desktop environment at some point, so a smart way needs to be found to handle these requirements.

Maybe AIL also adds a "right-click" option to "integrate" when the app still isnt that can always be invoked?

**Comment by star-buck** [comment]
second idea seems to have been already solved :+1:

**Comment by TheAssassin** [comment]
The second suggestion is what is implemented using MIME type integration. That's also why you can double-click any AppImage on the system even if it's not executable yet, and allows for opening AppImages through AppImageLauncher directly from the browser after downloading, etc.
