### ISSUE TITLE
Installation with Cosmic

### ISSUE THREAD

**Issue by peerwal** [TheAssassin/AppImageLauncher#116]
Which DEB package should I install on Kubuntu 18.10? I tried the **bionic** package. It works fine but it does not provide the **update** function.

**Comment by TheAssassin** [comment]
`bionic` should work on all newer distros, too. The only reason for a separate package is that Ubuntu renamed a dependency.

The official packages do contain the update helper, however the "update" entry is only available when the AppImage supports it. This has been changed recently, as it's quite irritating to show such a context menu entry when the AppImage doesn't support it anyway.

**Comment by peerwal** [comment]
Thanks a lot for the information.
