### ISSUE TITLE
Missing Icon from app menu and task bar( openshot)appimages type-1?

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#117]
Hi, I downloaded a openshot from here: https://github.com/OpenShot/openshot-qt/releases/download/v2.4.3/OpenShot-v2.4.3-x86_64.AppImage. After integrated it with appimagelauncher version 1.0.1 , the icon from taskbar and appmenu not appear. I must to say openshot appimage is type-1, and every appimage type-1 that I tried has the same issue. Whiteboard https://github.com/michaelpb/whiteboard/releases/download/v0.0.43/whiteboard-app-0.0.43-x86_64.AppImage. and many others.
 I am using Linuxmint 19.1 64 bits Cinnamon 4.0.1 
Thanks !

**Comment by TheAssassin** [comment]
@azubieta what was the explanation for that again?

**Comment by azubieta** [comment]
On it, I have found that some Type 1 AppImage use "Hard Links" for the ".DirIcon" file. Which is not supported currently.

**Comment by TheAssassin** [comment]
@azubieta I have huge doubts the AppImages linked above are type 1 AppImages...

**Comment by Lvaskz** [comment]
Hi, here https://github.com/TheAssassin/AppImageLauncher/issues/55 it  indicated openshot as type1. The others was indicated by old appimagelauncher( inferior version to 1) when launching.

**Comment by TheAssassin** [comment]
You're right, they're all type 1 AppImages. My bad, I was thinking of another issue. I will update libappimage later, then release a new version which should fix this issue.

**Comment by Lvaskz** [comment]
OK Thanks!!

**Comment by TheAssassin** [comment]
Please test and report back.

**Comment by Lvaskz** [comment]
Ok I will.

**Comment by Lvaskz** [comment]
Hi, I can not integrate any type 2 or type one


Atte Luis Vasquez Rugama

**Comment by Lvaskz** [comment]
For some reason that I can't understand every time I want integrate some appimage type 2 or 1 , appimagelauncher try to run but popup window integration inmediatly crashes and the apps just run, without integration.
I used this version
![imagen](https://user-images.githubusercontent.com/29207169/51539726-570d8e80-1e1a-11e9-8750-4a29f6fe2da7.png)
I notice that bionic package is not build. No more bionic package?

**Comment by TheAssassin** [comment]
@Lvaskz the build must've failed on Travis once again... unfortunately, with this stuff you're quite limited in terms of auto-rebuilds or notifications (either you don't activate them, or you receive a huge load of mails...).

Triggering a rebuild asap.

**Comment by TheAssassin** [comment]
Binaries are back. Was a rare race condition where two builds finished in the exact same moment. Happens from time to time.

**Comment by Lvaskz** [comment]
OK I will try, thanks

**Comment by Lvaskz** [comment]
nope, not working

**Comment by TheAssassin** [comment]
"is not working" is the least precise way of reporting a problem. Please _always_ describe your problem more detailedly.

**Comment by Lvaskz** [comment]
Ok, I installed appimagelauncher appimagelauncher_1.0.3-travis484.git20190121.49abe5a.bionic_amd64.deb. I double click on an appimage and nothing happens. No integrate appimage not run appimage

**Comment by TheAssassin** [comment]
Please try from the commandline like `AppImageLauncher <my.AppImage>` and provide the output. This is quite strange.

**Comment by Lvaskz** [comment]
lvaskz@lvaskz-Inspiron-3442:~$ AppImageLauncher <my.AppImage>
bash: error sintáctico cerca del elemento inesperado `newline'

**Comment by TheAssassin** [comment]
You must subsitute `<my.AppImage>` with a path to an AppImage of course...

**Comment by Lvaskz** [comment]
AppImageLauncher </home/lvaskz/Applications> like this ?

**Comment by Lvaskz** [comment]
oh right here is 
lvaskz@lvaskz-Inspiron-3442:~$ AppImageLauncher /home/lvaskz/Applications/PapagayoNG-1.4.2-2017.07.31-65704-linux-64bit.appimage
qt5ct: using qt5ct plugin

** (AppImageLauncher:13843): WARNING **: 13:54:58.636: Pixbuf theme: Cannot load pixmap file /usr/share/themes/Mint-Y/gtk-2.0/assets/trough-progressbar.png: No se ha podido cargar la imagen «/usr/share/themes/Mint-Y/gtk-2.0/assets/trough-progressbar.png»: Error fatal en el archivo gráfico PNG: bad parameters to zlib


(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

** (AppImageLauncher:13843): WARNING **: 13:54:58.636: Invalid borders specified for theme pixmap:
        /usr/share/themes/Mint-Y/gtk-2.0/assets/trough-progressbar.png,
borders don't fit within the image

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GdkPixbuf-CRITICAL **: 13:54:58.636: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:13843): GLib-CRITICAL **: 13:54:58.859: g_file_test: assertion 'filename != NULL' failed

(AppImageLauncher:13843): Gtk-WARNING **: 13:54:58.895: Error loading theme icon 'dialog-question' for stock: Error fatal leyendo el archivo gráfico PNG: bad parameters to zlib
Violación de segmento (`core' generado)
lvaskz@lvaskz-Inspiron-3442:~$

**Comment by Lvaskz** [comment]
Other file here:
vaskz@lvaskz-Inspiron-3442:~$  AppImageLauncher /home/lvaskz/Applications/OpenShot-v2.4.3-x86_64.AppImage
qt5ct: using qt5ct plugin

** (AppImageLauncher:14280): WARNING **: 14:00:01.696: Pixbuf theme: Cannot load pixmap file /usr/share/themes/Mint-Y/gtk-2.0/assets/trough-progressbar.png: No se ha podido cargar la imagen «/usr/share/themes/Mint-Y/gtk-2.0/assets/trough-progressbar.png»: Error fatal en el archivo gráfico PNG: bad parameters to zlib


(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

** (AppImageLauncher:14280): WARNING **: 14:00:01.696: Invalid borders specified for theme pixmap:
        /usr/share/themes/Mint-Y/gtk-2.0/assets/trough-progressbar.png,
borders don't fit within the image

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.696: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GdkPixbuf-CRITICAL **: 14:00:01.697: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:14280): GLib-CRITICAL **: 14:00:01.789: g_file_test: assertion 'filename != NULL' failed

(AppImageLauncher:14280): Gtk-WARNING **: 14:00:01.821: Error loading theme icon 'dialog-question' for stock: Error fatal leyendo el archivo gráfico PNG: bad parameters to zlib
Violación de segmento (`core' generado)
lvaskz@lvaskz-Inspiron-3442:~$

**Comment by TheAssassin** [comment]
@azubieta did you break something here?

**Comment by azubieta** [comment]
The AppImage `.DirIcon` is a hard link. I have done some work on this topic but it affects only to `appimage_extract_file_following_symlinks` and `appimage_read_file_into_buffer_following_symlinks` which are not used in this scenario.

Therefore trivial file extraction as done at `traverse_handler_extract_relevant_desktop_integration_files` will not work. The solution will imply using the above-mentioned functions to extract the files. Notice that it implies traversing several times the same AppImage file.

**Comment by TheAssassin** [comment]
Thanks for looking into it. I'd rather print a warning or so, and call it an "edge case".

**Comment by Lvaskz** [comment]
hi there, I downloaded this yesterday
![imagen](https://user-images.githubusercontent.com/29207169/52221402-bcc03880-2866-11e9-8e72-5d408481c2c0.png)
I double click on appimages type 1, openshot, downline and the apps are integrated but icon from app menu is missing again. Is this the normal behavier ?

**Comment by TheAssassin** [comment]
As @azubieta pointed out, the OpenShot AppImages are broken (i.e., they use some hardlinks for some reason, but we can not add support any more in the old series of libappimage, since it's not quite trivial).

**Comment by Lvaskz** [comment]
![imagen](https://user-images.githubusercontent.com/29207169/52547076-30dc6e00-2d8a-11e9-8f69-012dbbb604e7.png)
I see, So this is normal too
![2](https://user-images.githubusercontent.com/29207169/52547104-7600a000-2d8a-11e9-83a8-c1c682726ee2.png)
![2 apl](https://user-images.githubusercontent.com/29207169/52547105-7600a000-2d8a-11e9-8332-6a413e74b775.png)

**Comment by TheAssassin** [comment]
Not normal, but there's not much we can do about it. Tell those people to use appimagetool and use a PNG for their icon (at least the one in the root directory, there may be others in `usr/share/icons`).

**Comment by Lvaskz** [comment]
> 
> 
> 
> 
> By the way, 1) you don't need to quote every reply (especially not the last one, also not whenever the context is clear)
Ok, Only I trying to make sure

2) using screenshots for quoting is super annoying as I can't see these in a mail (you can quote with ease with GitHub's Markdown, there's even a "Quote reply" button).
Thank you very much, I was trying to locate this option.

**Comment by Lvaskz** [comment]
> 
> 
 
> By the way, 1) you don't need to quote every reply (especially not the last one, also not whenever the context is clear)

Ok, Only I am trying to make sure
>  2) using screenshots for quoting is super annoying as I can't see these in a mail (you can quote with ease with GitHub's Markdown, there's even a "Quote reply" button).

Thank you very much, I was trying to locate this option.
