### ISSUE TITLE
Godot Engine is not recognized by appimagelauncher

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#118]
Hi, I have been trying to integrate Godot Engine https://downloads.tuxfamily.org/godotengine/3.0.6/Godot_v3.0.6-stable_x11.64.zip with appimagelauncher 1.0.3 but is not possible. The app run inmediatelly, but appimagelauncher message it does not even appear.
Linuxmint 19.1
64 bit
Cinnamon 4.0.1

**Comment by Calinou** [comment]
@TheAssassin The official Godot Linux releases aren't AppImages, they're statically-linked binaries. Is AppImageLauncher able to handle those?

**Comment by Lvaskz** [comment]
mmm.... so, they are not appimage. https://appimage.github.io/apps/ should not be add like appimage.
![imagen](https://user-images.githubusercontent.com/29207169/51342090-8d34c200-1a58-11e9-884e-4bba521b8b6c.png)

**Comment by TheAssassin** [comment]
Valid point, @Lvaskz... @probonopd please fix.

**Comment by probonopd** [comment]
https://github.com/AppImage/appimage.github.io/commit/a85819ef1613f3a9096062182d74cfb766ca603d has https://archive.hugo.pro/builds/godot/editor/godot-linux-nightly-x86_64.AppImage
