### ISSUE TITLE
Ignore AppImages whose desktop file has set X-AppImage-Integrate=false

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#12]
As we recently found (#11), some AppImages may have other AppImages contained in them, that provide e.g., daemons that need to run in the background for IPC. Such an application is the openDesktop app, which uses the ocs-manager helper to perform all the real work.

The fix for #11 was fairly easy, as AppImageLauncher simply ignores AppImages running from a temporary AppImage mountpoint. But actually, such AppImages should get a chance to tell AppImageLauncher and any other software using libappimage that it doesn't want to be integrated.

The desktop entry specification describes a key `NoDisplay` that, when set to `true`, means that any application that processes the file shall not display the AppImage (e.g., in launchers).

It happens that ocs-manager's desktop file even has set `NoDisplay=true`, see https://github.com/opendesktop/ocs-manager/blob/master/desktop/ocs-manager.desktop. Therefore, this "real" fix should be implemented soon, to properly prevent these situations.

**Comment by TheAssassin** [comment]
Renaming the issue as we decided to use a custom key instead of `NoDisplay`. We don't want to change the meaning of this standard key.

TODO: add this key to the ocs-manager AppImage.

**Comment by probonopd** [comment]
> The fix for #10 was fairly easy, as AppImageLauncher simply ignores AppImages running from a temporary AppImage mountpoint.

Looks like it's solved then?

> But actually, such AppImages should get a chance to tell AppImageLauncher and any other software using libappimage that it doesn't want to be integrated.

Why? What would be a scenario in which this is needed?

**Comment by TheAssassin** [comment]
> But actually, such AppImages should get a chance to tell AppImageLauncher and any other software using libappimage that it doesn't want to be integrated.

https://github.com/TheAssassin/AppImageLauncher/issues/10

**Comment by TheAssassin** [comment]
Going to work on this next.

CC @akiraohgaki: I will send a PR for ocs-manager once `X-AppImage-Integrate=false` is available.
