### ISSUE TITLE
Version 1.0.3 causes no ability to pin apps to the launcher

### ISSUE THREAD

**Issue by zot** [TheAssassin/AppImageLauncher#126]
I'm using Ubuntu 18.10 and version 1.0.2 works fine but when I install version 1.0.3, the icon for a running appimage doesn't have an option to add to favorites.

**Comment by zot** [comment]
Hmm, I just ran into the same problem with 1.0.2 and it looks like the *.desktop files it made were untrusted. I double clicked on one and made it trusted and that did the trick.

**Comment by TheAssassin** [comment]
@zot desktop environments like GNOME constantly try to annoy people who don't use their ecosystem with some bogus "security" related arguments.

What does "making trusted" mean? Shall we just make them executable or anything? Do you have any idea how we can avoid this annoyance?

**Comment by zot** [comment]
Doing a little experimentation, it seems that "trusted" MIGHT just mean executable. Can't be positive at this point though.

Is it possible that AppImageLauncher made a non-executable *.desktop file? Sorry, I haven't looked through your code yet...

**Comment by TheAssassin** [comment]
Yes, quite likely. I remember that desktop files need to be made executable, just as binaries, to be able to double-click-launch them, etc.

I will push a little make-executable-to-make-GNOME-behave commit later.

**Comment by TheAssassin** [comment]
@zot mind to try the latest continuous release? It makes desktop files executable.

**Comment by TheAssassin** [comment]
I would like to close this issue before releasing a new version.

**Comment by zot** [comment]
Checking now. I was able to duplicate the error this way: I ran [Ganache](https://truffleframework.com/ganache), quit, and removed it from favorites. Then I opened ~/.local/share/applications in nautilus and double clicked the ganache desktop file and got the "untrusted application launcher" error. I'll try the latest release now.

**Comment by zot** [comment]
The continuous build doesn't work for me, I get this in my icon doc:

![non-ganache-icon](https://user-images.githubusercontent.com/26665/52184476-3c9fc180-27d9-11e9-96e0-b7610666d81e.png)

It's stubbornly staying in my dock but it has an "Add to Favorites" menu option, not a "Remove from favorites". If I click Add to Favorites, nothing appears to happen and "Add to Favorites" stays on the icon menu, without a "Remove from Favorites" option. Clicking on "Show Details" pops up "Ubuntu Software" with "No Application Found" in it.

I can't restart my computer right now because I'm in the middle of development and I have context in my active terminal tabs. Version 1.0.3 does appear to work and it replaces the "unknown program" looking icon. If I remove it from favorites, it stays in the dock but this time it has the Ganache icon.

I hope this helps. Maybe you can try the [above test](https://github.com/TheAssassin/AppImageLauncher/issues/126#issuecomment-460098131) and see if you get the same behavior.

**Comment by TheAssassin** [comment]
You may want to `systemctl --user restart appimagelauncherfs.service`. Make sure to close all open AppImages, otherwise they will just crash.

**Comment by TheAssassin** [comment]
Should've been fixed long ago. Please reopen if the issue persists.
