### ISSUE TITLE
Increased loading times when launching from appimagelauncher

### ISSUE THREAD

**Issue by wonx** [TheAssassin/AppImageLauncher#128]
Apart from no loading indicator, I noticed that apps launched with AppImageLauncher took a little longer to start. I made a quick comparison, launching Kdenlive (kdenlive-18.12.1b-x86_64) with and without AppImageLauncher. 

It took, on average 5.5 seconds to start without AppImageLauncher, and around 9.5 seconds with AppImageLauncher, which I think it's a significative increase.

Is this something that could be mitigaged?

**Comment by TheAssassin** [comment]
Oh, and 1-2 seconds delay might just come from Qt being "booted" for no reason (when just launching apps, it isn't really necessary, but I couldn't come up with a not-super-complex workflow where the Qt app would be created only when _really_ necessary, i.e., just before a dialog should be shown).
This is probably easier to optimize away, the other delay is a technical limitation right now.

Can you please open a terminal, run `journalctl --user -u appimagelauncherfs.service -f` there and watch it while running e.g., Kdenlive? Please estimate the time between "pressed launch button" and a line saying "AppImage already registered" or "Registered new AppImage" in the log, and report it here.

**Comment by wonx** [comment]
I am not sure if that's exactly what you are asking, but these are the only two lines I see in the log when I launch an appimage (kdenlive in this case): 

```
de febr. 03 13:34:03 laptop-TM1703 appimagelauncherfs[25367]: /home/user/Applications/kdenlive-18.12.1b-x86_64_e569994ef8da3958a488e99d25d6c90d.appimage
de febr. 03 13:34:03 laptop-TM1703 appimagelauncherfs[25367]: AppImage already registered: /home/user/Applications/kdenlive-18.12.1b-x86_64_e569994ef8da3958a488e99d25d6c90d.appimage

```

Previously I had used the "time" command, and I got values like these: (as in: time ./kdenlive-18.12.1b-x86_64_e569994ef8da3958a488e99d25d6c90d.appimage )

I ran it four times, to obtain several datapoints. The "real" time includes the time it takes me to press Alt+F4 once the main interface appears, which should be less than half a second.

```
real	0m9,899s
user	0m5,393s
sys	0m0,485s

real	0m9,526s
user	0m5,307s
sys	0m0,435s

real	0m9,545s
user	0m5,282s
sys	0m0,497s

real	0m9,961s
user	0m5,303s
sys	0m0,525s


```

**Comment by TheAssassin** [comment]
Closing as obsolete. See #361 for more information.
