### ISSUE TITLE
Programs in launcher show duplicated icon when app is executed

### ISSUE THREAD

**Issue by wonx** [TheAssassin/AppImageLauncher#129]
It happens at least in Gnome in Ubuntu 18.04 with software in the appimage format, and using AppImageLauncher 1.0.3.

How to replicate: 

1. Add program to launcher (search program in menu, right click "Add to favorites").
2. Observe that launcher with the proper icon has been created.
3. Launch that program by clicking that icon.
4. Observe how a second identical icon appears in the launcher.

So, one icon is just for starting the program, and the second icon is just for selecting the window of the program.

**Comment by TheAssassin** [comment]
Interesting. Can you please try to uninstall AppImageLauncher and launch the AppImage directly? Are there two icons in your launcher, too?

**Comment by wonx** [comment]
Ok, I just checked. Here's the thing: apparently Gnome doesn't let you add anything to the panel/dash unless it's a .desktop file[[1]](https://unix.stackexchange.com/questions/103213/how-can-i-add-an-application-to-the-gnome-window-manager). So there's no way to add a running app to the dash by right-clicking on it or anything like that (as you would do it in Unity, for instance).

So I uninstalled appimagelauncher, I rebooted (that seems to be a necessary step), and the .desktop file created by appimagelauncher is still there (in my case, I tried it with kdenlive). That menu entry still works, as also works running the .appimage directly. And yes, gnome treats them as two separate entitites, so the same icon appears twice in the dash.

Here's a visual example of what happens if you launch kdenlive by it's shortcut in the dash (created automatically by appimagelauncher):

![captura de pantalla de 2019-01-31 19-35-15](https://user-images.githubusercontent.com/2736639/52095003-62d22100-258f-11e9-92ae-5d18495578bf.png)

**Comment by TheAssassin** [comment]
Not sure if AppImageLauncher could help avoid duplicate entries. I'll think about a solution, but I'm not sure if it can be done.

**Comment by wonx** [comment]
Ok. It's possibly an issue with the appimage format itself, as I remember it happening in older ubuntu versions with Unity (where you could just drag and drop a program to the dash/panel. Anyway, thanks for your time :)

**Comment by TheAssassin** [comment]
@probonopd any ideas? The problem doesn't seem to be limited to AppImageLauncher.

**Comment by TheAssassin** [comment]
Ah, makes absolutely sense to utilize `StartupWMClass` to group windows of the same kind on such desktop environments where launchers and taskbar items are the same.

I will set the key in our own desktop file ASAP.

@wonx please open issues at the projects' issue trackers or contact the authors directly otherwise and tell them to add `StartupWMClass=...` with the right value. You can find out about the right value by calling `xprop WM_CLASS`, and clicking on the window in question. For AppImageLauncher, this looks like:

```sh
> xprop WM_CLASS
WM_CLASS(STRING) = "AppImageLauncher", "AppImageLauncher"

**Comment by abdurrahmanyildirim** [comment]
@TheAssassin  I still have same problem. Icons duplicate at left menu. WM_CLASS is "AppImageLauncher", "AppImageLauncher". Is there other solution?

**Comment by pepa65** [comment]
Is there a way to remove all AppImage entries from the menu? I can no longer find how to un-integrate AppImages...
