### ISSUE TITLE
Button order in the main dialog differs from distro to distro

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#13]
There must be a reason why the button order in the main dialog is different from distro to distro. The button order should be fixed, so that the dialog looks the same across all distributions.

**Comment by TheAssassin** [comment]
Could never find out a reason for that, probably defined by the themes. I guess we can expect people to read the buttons before clicking.

**Comment by azubieta** [comment]
@TheAssassin you are right in a theme you can define were the option buttons are placed. So there is nothing for us to do here should.

**Comment by TheAssassin** [comment]
Well, just for completion, we *could* hardcode our buttons. But we rather want to use preexisting Qt elements, that works much better.
