### ISSUE TITLE
Failed to register AppImage in AppImageLauncherFS: could not open map file

### ISSUE THREAD

**Issue by linsui** [TheAssassin/AppImageLauncher#130]
I got this when I start appimage.

**Comment by TheAssassin** [comment]
@linsui would you please provide more information on your system (especially the OS) and also the version of AppImageLauncher you installed?

**Comment by linsui** [comment]
@TheAssassin  Ubuntu18.10 , AppImageLauncher 1.0.3. 
First I try to reinstall AppimageLauncher but it didn't work. After I restart system it works.

**Comment by TheAssassin** [comment]
Interesting. Normally, the AppImageLauncherFS service is started on first run by AppImageLauncher, if needed. But there's some timing issues sometimes, the service might take a bit to boot. Glad it works now.

**Comment by Igetin** [comment]
I’m experiencing this problem with AppImageLauncher 1.1.1 (installed via the deb package), running on Xubuntu 18.04. I don’t think there are any timing issues, since I get the error message even after my system has been on for hours. When I look at my process list, it looks like appimagelauncherfs is just restarting itself over and over again.

The software was working fine just yesterday when I first installed it, but after rebooting my system that is no longer the case.

**Comment by TheAssassin** [comment]
@Igetin your issue must be different, would you mind opening a new issue? Perhaps you can try to run `systemd --user stop appimagelauncherfs` to deactivate the restarting and then manually run `appimagelauncherfs` in order to gain some information (there should be some logs in your terminal) and then put all that info that new issue.

**Comment by probonopd** [comment]
Looks like the issue persists:

https://forum.manjaro.org/t/appimage-problems-kde-stable/85522

![](https://forum.manjaro.org/uploads/default/original/3X/5/1/510aa1db0b92625e762c6457828c98cd08dbae8c.png)

**Comment by TheAssassin** [comment]
> so had uninstalled/reinstalled it, then rebooted, and could run appimages again

Not quite...

**Comment by probonopd** [comment]
Best answer directly in https://forum.manjaro.org/t/appimage-problems-kde-stable/85522 because I suspect the people there don't read here.

**Comment by TheAssassin** [comment]
I'm not willing to provide support on third-party forums. The amount of mails etc. I have to work with _already_ are way more than enough.

**Comment by colemanlee** [comment]
Hi,
I also meet this problem when I run `./pling-store-5.0.1-1-x86_64.AppImage` in ROOT graphical interface.
* My system information:
```
Linux debian 5.3.0-1-686-pae #1 SMP Debian 5.3.7-1 (2019-10-19) i686 GNU/Linux
```
* deb package information：
```
# apt-cache show appimagelauncher
Package: appimagelauncher
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 56454
Maintainer: TheAssassin
Architecture: i386
Version: 2.0.2-travis883~f5ac870+buster
Description: AppImageLauncher built using CMake
Description-md5: 604b265bc489c2475cd6e25aabba693d
```
![PIC__28](https://user-images.githubusercontent.com/10258421/68522719-7d3ce600-02e9-11ea-9483-e2ea6e416915.jpg)

**Comment by TheAssassin** [comment]
> Hi,
> I also meet this problem when I run ./pling-store-5.0.1-1-x86_64.AppImage in ROOT graphical interface.

You mean you are running your system as `root`?

**Comment by colemanlee** [comment]
> > Hi,
> > I also meet this problem when I run ./pling-store-5.0.1-1-x86_64.AppImage in ROOT graphical interface.
> 
> You mean you are running your system as `root`?

Yes, I modified the system and log in the system graphical interface with `root` for some test purpose.
Then I tried to login normal user mode in the graphical interface, and run the command:
```
sudo ./HastyHeroes-1.0.0-x86_64.AppImage 
```
The error appear:
```
[sudo] jeff 's password：
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Failed to connect to bus: no files or dir
Failed to connect to bus: no files or dir
---->dialog box "Desktop Intergration—AppImageLauncher" appear.
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 565, resource id: 10653673, major code: 40 (TranslateCoords), minor code: 0
---->Click "Run Once" button
Failed to connect to bus: no files or dir
Failed to connect to bus: no files or dir
---->dialog box "Error—AppImageLauncher" appear and click "OK" button.
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 699, resource id: 10654207, major code: 40 (TranslateCoords), minor code: 0
```
![PIC__33](https://user-images.githubusercontent.com/10258421/68528706-50142600-0331-11ea-9f44-1fade9f38ca4.jpg)
![PIC__34](https://user-images.githubusercontent.com/10258421/68528707-51455300-0331-11ea-956a-801266c14fd1.jpg)

If I run the command:
```
./HastyHeroes-1.0.0-x86_64.AppImage
```
The error appears when I click the "Run once" button:
```
execv() failed: executable file format error
```
![PIC__35](https://user-images.githubusercontent.com/10258421/68528730-9ec1c000-0331-11ea-8161-971e58e13fc4.jpg)

I have no idea how to run AppImage on Debian 10 now.

**Comment by probonopd** [comment]
> I have no idea how to run AppImage on Debian 10 now.

`apt-get remove appimagelauncher` would be one short-term option.

**Comment by TheAssassin** [comment]
@colemanlee I've tested the application on Debian 10, so this is not a general issue but more of an issue specific to your system. Please open a new issue in order to allow for debugging.

**Comment by colemanlee** [comment]
> @colemanlee I've tested the application on Debian 10, so this is not a general issue but more of an issue specific to your system. Please open a new issue in order to allow for debugging.

OK。

**Comment by jocimarweb** [comment]
Também estou com este erro no Debian 10 KDE
"Failed to register AppImage in AppImageLaucherFS: could not open map file"
