### ISSUE TITLE
Add real icon to AppImageLauncher

### ISSUE THREAD

**Issue by wonx** [TheAssassin/AppImageLauncher#131]
Not a big deal, but it looks like this:

![captura de 2019-02-03 13-31-18](https://user-images.githubusercontent.com/2736639/52180911-adcf7c80-27b9-11e9-995a-3cc45f84b701.png)

Note the black and red icon with the forbidden sign in it in the first entry of the context menu.

I noticed in some occasions, when AppImageLauncher shows a dialog, the same icon appears Gnome's dash/panel, but I couldn't replicate right now (it showed a "default" icon instead of the forbidden sign).

**Comment by TheAssassin** [comment]
AppImageLauncher doesn't have an icon right now. It's an empty file, which is invalid and therefore shown like so.

Icon contributions welcome!

**Comment by Lvaskz** [comment]
what about this ? 
![appima](https://user-images.githubusercontent.com/29207169/52444752-e25f7300-2aee-11e9-8bda-3ecfce9f9459.png)

**Comment by Lvaskz** [comment]
or maybe this? 
![appima2](https://user-images.githubusercontent.com/29207169/52445227-23a45280-2af0-11e9-975a-49d411907a1b.png)

**Comment by Lvaskz** [comment]
Obviously I must to resize the icon

**Comment by TheAssassin** [comment]
The first one is way too detailed. Imagine a 16x16 version, you couldn't recognize the "AppImage symbols".

The second one is not "square" enough.

I like the color scheme of red, instead of dark red I'd recommend using a really dark (>80%) gray.

**Comment by Lvaskz** [comment]
![imagen](https://user-images.githubusercontent.com/29207169/52484035-f51f8980-2b7a-11e9-8cf6-457f0512fcd8.png)
What you mean when you say " square enough"? The icon must be in square frame ? or the rocket must have a square form?

**Comment by Lvaskz** [comment]
![rocket](https://user-images.githubusercontent.com/29207169/52486518-fb186900-2b80-11e9-9bdf-dd15deeb3b77.png)
48x48 pixels, mixes red gray 
Better?

**Comment by Lvaskz** [comment]
![rocket 518x518](https://user-images.githubusercontent.com/29207169/52486772-aaedd680-2b81-11e9-840e-4c093714183b.png)

**Comment by TheAssassin** [comment]
Much better, but the "main elements" are stretched horizontally too much and also not perfectly centered.

What do others think? @azubieta @wonx any opinions?

**Comment by Lvaskz** [comment]
No perfect yes . It is a scketch

**Comment by Lvaskz** [comment]
I Will Fix it soon

**Comment by Lvaskz** [comment]
![appimagelauncher icon](https://user-images.githubusercontent.com/29207169/52801343-4203d400-3043-11e9-8a55-a9b0e9fb41bb.png)
This is my apport to this issue, If you guys are accord just telll me what you need.

**Comment by Lvaskz** [comment]
![apl-2](https://user-images.githubusercontent.com/29207169/55032499-9ac97380-4fd6-11e9-8b35-110ea4c68062.png)
I was thinking in this ....

**Comment by jjangga0214** [comment]
@Lvaskz 
Good enthusiasm.. but 
* Why are all icons so radical by the way?
* Are ⚙️ and ⬇️ suitable? To me, the former looks like "setting" or "tweak" sign, the latter "download" or "install", which are far from "launcher"

In my opinion, the icon should be concise. simple, bold and elegant so it would be fit with small size without loosing its meaning of existence.

**Comment by jjangga0214** [comment]
@TheAssassin Let me know the list of icon sizes. Only 16x16 is needed?

**Comment by TheAssassin** [comment]
Yeah, I also think that @Lvaskz suggestion is a bit "too much".

@jjangga0214 @Lvaskz is trying to incorporate the AppImage logo (see e.g., https://appimage.org).

Ideally, your icon works for 16x16 as well as it works for 256x256. The small icon is for use in taskbars etc. (up to 1080p, 4k etc. need 32x32 and even larger for that already), the higher-res icon is used in app launchers and such stuff.

**Comment by Lvaskz** [comment]
> Yeah, I also think that @Lvaskz suggestion is a bit "too much".

Hi, well I just try to help. I like to draw anyway. This is my last shot. ![APP-LAU](https://user-images.githubusercontent.com/29207169/55240667-03933480-51ff-11e9-8709-dbbaed6154d1.png) I would like to see more artists suggesting icons. I am not forcing anybody to choose my desing. If anybody has a better one ... great for me.
Cualquier sugerencia es bien recibida. Gracias!!!!!

**Comment by 2635599** [comment]
LOL i swear you're all war mongers. those icon suggestions, NOT.

**Comment by TheAssassin** [comment]
@2635599 maybe provide a better suggestion? This kind of offensive and insulting feedback isn't appropriate.
@Lvaskz is at least trying to help, and I'm very grateful that there are community members who invest time into the development of this application. @jjangga0214 for instance provided some clear design guidelines which I like a lot.
I also am not such a big fan of rockets or anything weapon-related for the icon, but hey, better than nothing, right? I didn't have any better idea yet. And it could always be changed for a more pacifistic icon.

**Comment by 2635599** [comment]
first the truth is NEVER offensive., second NOTHING inappropriate about my comment.

**Comment by Lvaskz** [comment]
>     * No complex object. Shape have to be simple.
Well, I tried to be simple, with next one.
>     * No gradation and shadow
No more shadows
>     * No double or more signs.... If needed, sign have to be only one.
Sorry, I don't know how, I am trying.
>     * No hard-to-distinguish color. Most systems use light or dark (e.g. see @wonx 's screenshot ) color as background of UI widget. Icon color should be distinctive.
Well, let me see if white and black is enought



Well, I tried this one.
![OTHER IDEA](https://user-images.githubusercontent.com/29207169/55255954-7f9e7400-5221-11e9-9922-78ea8e4143c6.png)

**Comment by TheAssassin** [comment]
That looks much better. We might add some color (replacing the black, e.g., with a dark blue). Might also remove that "spike" on the bottom, then it looks like a stylized A (which would suit the name "AppImageLauncher".

**Comment by Lvaskz** [comment]
Working on it !!!
![APL](https://user-images.githubusercontent.com/29207169/55260440-0d805c00-522e-11e9-921f-378a31834446.png)
What do you think?

**Comment by TheAssassin** [comment]
Might add a little green to that blue (~10-20/255 in RGB).

How about making the ring a real circle and centering the "stylized A"?

By the way, did you try that at a size of 16x16 already?

**Comment by Lvaskz** [comment]
> How about making the ring a real circle and centering the "stylized A"?

Color of the circle?
The stylized A is white.
 

> By the way, did you try that at a size of 16x16 already?

the size is not a problem, I can make many changes from inkscape. I tried yes, but with the war plane. Looks good.

**Comment by TheAssassin** [comment]
> Color of the circle?
> The stylized A is white.

I'm just referring to the shape. Right now, it's an ellipsoid, but it probably looks better as a real circle with the "A" properly centered.

> the size is not a problem, I can make many changes from inkscape. I tried yes, but with the war plane. > Looks good.

Good. As long as you test it after every change, everything's fine.

**Comment by Lvaskz** [comment]
> I'm just referring to the shape. Right now, it's an ellipsoid, but it probably looks better as a real circle with the "A" properly centered.

Ok I will.

> Might add a little green to that blue (~10-20/255 in RGB).
Do want it darker?

**Comment by TheAssassin** [comment]
Not necessarily darker, but a bit more like turquoise. I meant to write 100-120, by the way.

Tried some colors, here's my suggestion:

![screenshot_2019-03-29_22-37-07](https://user-images.githubusercontent.com/4503202/55264001-34ad4c80-5273-11e9-86d6-e7a1ff322250.png)

That's #00415a (RGB 0, 65, 90).

**Comment by Lvaskz** [comment]
> That's #00415a (RGB 0, 65, 90). What do you think?

No problem

**Comment by Lvaskz** [comment]
Well, Here it is.
![appimagelaucher v1](https://user-images.githubusercontent.com/29207169/55266731-111edd80-5244-11e9-88b2-0ad7b76f49c9.png)

**Comment by TheAssassin** [comment]
Cool! Nearly perfect. Might be nitpicking, but can we make the corners perfectly round, too?

**Comment by Lvaskz** [comment]
![appimagelaucher v2](https://user-images.githubusercontent.com/29207169/55267877-b341c400-524a-11e9-8b1d-2d8c4cc9f158.png)
like this?

**Comment by TheAssassin** [comment]
I guess you misunderstand me. Now the corner cut-off is just bigger. The problem is that the cutoff is stretched vertically, i.e., not concentric with the inner circle, which makes it look inconsistent.

**Comment by 2635599** [comment]
Lvaskz the last two really look great.

**Comment by Lvaskz** [comment]
Can you take my picture and mark the zone with the problem? I will try to fix it
An image speak more than a many words

**Comment by TheAssassin** [comment]
It would make more sense to just send me the SVG. I'll fix it then and will share a preview.

**Comment by Lvaskz** [comment]
Oh right


Atte Luis Vasquez Rugama

**Comment by Lvaskz** [comment]
Done 
[APL2000.svg.zip](https://github.com/TheAssassin/AppImageLauncher/files/3024990/APL2000.svg.zip)

**Comment by TheAssassin** [comment]
![screenshot_2019-03-30_02-48-23](https://user-images.githubusercontent.com/4503202/55269650-4c49fc80-5296-11e9-87e7-20cb1f00c607.png)

[AppImageLauncher_logo.svg.zip](https://github.com/TheAssassin/AppImageLauncher/files/3025014/AppImageLauncher_logo.svg.zip)

**Comment by Lvaskz** [comment]
I did some changes for the 16x16 version, see:
![16x16](https://user-images.githubusercontent.com/29207169/55277630-0c037200-52c8-11e9-903b-03a2a832de59.png)
This is the icon full size:
![apl](https://user-images.githubusercontent.com/29207169/55277676-67356480-52c8-11e9-89d0-ca6170b26809.png)
What do you think, about 16x16 version?

**Comment by TheAssassin** [comment]
That's it, I guess. Great job! Thanks a lot. Please upload an SVG (or send a PR).
Are you okay with using the MIT license for the file? 

@wonx @jjangga0214 how do you like it?

**Comment by Lvaskz** [comment]
> Are you okay with using the MIT license for the file?

Sorry, about my ignorance, but is that free license? No problem


> Please upload an SVG

Sure
[AppImageLauncher_logo v2.svg.zip](https://github.com/TheAssassin/AppImageLauncher/files/3025606/AppImageLauncher_logo.v2.svg.zip)

**Comment by TheAssassin** [comment]
It's a permissive free software license that is used by the entire project. As you are the author of this file, you must tell us whether it's okay to license this file under the terms of the MIT license. Seems like you're okay with this.

**Comment by Lvaskz** [comment]
> Seems like you're okay with this.

Sure, ok
Well, Thanks all you.
I hope see the icon in the next release if that is possible.
Nos vemos en el futuro!!!!

**Comment by TheAssassin** [comment]
Included the icon, release build is on the way. Thanks again @Lvaskz!
