### ISSUE TITLE
Support portable home with AppImageLauncherFS

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#132]
Currently, AppImages are launched by just calling the virtual files AppImageLauncher creates. This however breaks the portable home/config directory stuff in the runtime:

```
... appimagelauncherfs[28063]: Error: could not find registered AppImage: /0006.AppImage.home
... appimagelauncherfs[28063]: Error: could not find registered AppImage: /0006.AppImage.config
```

The easiest way to solve this is to allow for overriding the locations in the AppImage runtime. This could be done by e.g., implementing environment variables, either specifying the full path of both locations or specifying the base path where both directories shall be located.

The most reliable and backwards-compatible way would be to re-implement the whole system in AppImageLauncher, which would set the same environment variables as the runtime.

**Comment by azubieta** [comment]
Just for the record, please correct me if I'm wrong. This has nothing to do with AILL.

**Comment by TheAssassin** [comment]
No, it has not. Why would you think so?

**Comment by azubieta** [comment]
This issue was pointed by @probonopd as required to make AILL feature complete. It's just to clarify that.

**Comment by TheAssassin** [comment]
Didn't see that anywhere...

**Comment by probonopd** [comment]
Looks like AILL has no issues with portable home.

**Comment by TheAssassin** [comment]
Closing as obsolete. See #361 for more information.
