### ISSUE TITLE
Manpage for AppImageLauncher

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [TheAssassin/AppImageLauncher#134]
Hi :) I created a manpage for appimagelauncher - please review and include in source if possible. Thanks!
[https://salsa.debian.org/sgclark-guest/appimagelauncher/blob/master/debian/AppImageLauncher.1](url)

**Comment by TheAssassin** [comment]
Sure! Looks good, thanks. There's a few more commandline options (can be queried with `--appimagelauncher-help`) that we could include in the man page, too. Can you show me how? I have no clue about writing man pages.

**Comment by ScarlettGatelyMoore** [comment]
I am only just learning how myself :) here is a good source of info:
http://www.linuxhowtos.org/System/creatingman.htm
I am more than happy to update it though. I found another mistake, it should be a man 1 not 8.

**Comment by ScarlettGatelyMoore** [comment]
I am not seeing the other options :( 

cher-1.0.3+dfsg/debian/appimagelauncher/usr/bin/AppImageLauncher --appimagelauncher-help
AppImageLauncher version 1.0.3 (git commit ), built on 2019-02-28 13:27:20 UTC

Usage: appimagelauncher-1.0.3+dfsg/debian/appimagelauncher/usr/bin/AppImageLauncher [options] <path>
Desktop integration helper for AppImages, for use by Linux distributions.

Options:
  --appimagelauncher-help     Display this help and exit
  --appimagelauncher-version  Display version and exit

Arguments:
  path                        Path to AppImage (mandatory)

**Comment by TheAssassin** [comment]
Well, especially the version parameter is important for debugging. And simply `--help` couldn't be used, as it would interfere with AppImages run through this app. Since the `--appimagelauncher-` prefix isn't too obvious to users, we should include both parameters in the man page.

**Comment by ScarlettGatelyMoore** [comment]
Ah that makes sense, will add those two options and my fix. Thanks!

**Comment by ScarlettGatelyMoore** [comment]
[https://github.com/TheAssassin/AppImageLauncher/issues/url](url)

Updated :)

**Comment by TheAssassin** [comment]
Installing into `<prefix>/share/man/man1` is okay? Shouldn't the man page name be lower case (just asking, I don't mind using mixed case)?

**Comment by TheAssassin** [comment]
Fixed by https://github.com/TheAssassin/AppImageLauncher/commit/a7b1c9e6303e4d7185b97b4e924969047e8aadb0.

**Comment by TheAssassin** [comment]
Thanks @ScarlettGatelyMoore! Please let me know if the file is installed into the right place, it seems to work.
