### ISSUE TITLE
Viber Broke Appinage Launcher

### ISSUE THREAD

**Issue by 2635599** [TheAssassin/AppImageLauncher#137]
i went looking for cross-platform messaging apps yesterday and settled on viber. got it installed on my phone and in linux with no issues that i knew of. this morning i downloaded a appimage of franz to compare to wavebox and when clicked on it for appimage launcher to install it i got the following. not sure if it's something in appimage launcher that doesn't like viber or vice-versa so i'm posting for help here and on their site. any help getting both to play nice would be greatly appreciated. thanks

![appimage launcher broken](https://user-images.githubusercontent.com/22320686/53696136-02debe00-3d79-11e9-9886-c6572739a6a1.png)

**Comment by TheAssassin** [comment]
Try the `bionic` package, it's linked against `libcurl4` instead of `libcurl3`. Then, installing both should work.

**Comment by 2635599** [comment]
of viper?

**Comment by TheAssassin** [comment]
Of AppImageLauncher.

**Comment by 2635599** [comment]
ok thanks

**Comment by 2635599** [comment]
actually i had bionic

**Comment by TheAssassin** [comment]
Hm, I see, I misinterpreted the screepshot... so viper needs `libcurl3`? You might try the non-bionic/cosmic version, which does link against `libcurl3`. But it seems you got the wrong package of viper.

**Comment by 2635599** [comment]
this did the trick.

appimagelauncher_1.0.3-travis517.git20190301.01a1586_amd64.deb

**Comment by 2635599** [comment]
i'm adding support at viber to this cause this looks to be their issue. cause no matter how viber is installed it breaks appimage launcher and playonlinux.
