### ISSUE TITLE
The ~/Applications directory is always being recreated

### ISSUE THREAD

**Issue by wsdfhjxc** [TheAssassin/AppImageLauncher#138]
Despite changing the destination directory in `appimagelauncher.cfg` to another location, every time I launch an AppImage program while `appimagelauncherd` is running, the `~/Applications` directory is being recreated. It shouldn't be created unless it's configured as a destination directory.

I'm using version 1.1.0.

**Comment by TheAssassin** [comment]
Did you restart `appimagelauncherd` ever since you made the change?

`systemctl --user restart appimagelauncherd`

**Comment by wsdfhjxc** [comment]
Yes, I've done that. But it seems there are still some hardcoded parts related to this directory, e.g. https://github.com/TheAssassin/AppImageLauncher/blob/9b752d332da788c8c9cc92f9d4574f064219907b/src/trashbin/trashbin.cpp#L23-L25
I'm not sure if this is the actual reason though. Can you reproduce that issue?

**Comment by TheAssassin** [comment]
Thanks for pointing me there. I've fixed that hardcoding in 4fd1d69c9dcfd4e135bd366829aa94995b9533f6. There's only one other location (in appimagelauncherfs), but there it's not a problem.

I don't have time to try to reproduce it now, but it should be fixed now.

**Comment by wsdfhjxc** [comment]
Yes, it's fixed. Thank you.
