### ISSUE TITLE
Solus support

### ISSUE THREAD

**Issue by ReubenBTalbott** [TheAssassin/AppImageLauncher#139]
Could you please consider adding Solus support.

Thanks!

Reuben Talbott

**Comment by TheAssassin** [comment]
You mean, package it for Solus? The software itself should run anywhere.

**Comment by ReubenBTalbott** [comment]
Yes

Reuben Talbott

**Comment by ReubenBTalbott** [comment]
I am not experienced in building from source and I see no instructions on how to do so.

**Comment by TheAssassin** [comment]
It's a regular CMake project. You can build it from the source tarball provided on the release page. These instructions should work for the latest stable release. You must install all dependencies in advance, I can't give a list of packages to install for your distro in advance unfortunately.

```bash
# download the latest release tarball
# you can also build directly from git, but the tarball contains everything you need already
https://github.com/TheAssassin/AppImageLauncher/releases/download/v1.1.1/appimagelauncher-git20190312.a3a556a.source.tar.xz
cd appimagelauncher*.source/
# git version:
#git clone --recursive https://github.com/TheAssassin/AppImageLauncher/
#cd AppImageLauncher

# create separate build directory for so-called out-of-source build
# that way, to start over, rm -r build && mkdir build will be sufficient
mkdir build
cd build

# configure build with CMake
# we want to build optimized release binaries
cmake .. -DCMAKE_BUILD_TYPE=Release

# now, build!
make -j$(nproc)

# you may now try the binary directly (call src/ui/AppImageLauncher <some.AppImage>), or install the software with sudo make install
# warning: uninstallation is not supported at this point via make uninstall! it's recommended to try AppImageLauncher only this way; if it works, please ask your distribution to package the application properly

**Comment by ReubenBTalbott** [comment]
Thank you very much! I’ll try installing later today.

**Comment by axelmeunier** [comment]
@ReubenBTalbott did you manage to install it on Solus ? I'd like to do the same.

**Comment by ReubenBTalbott** [comment]
I never got a chance to try. My solus install got messed up by windows.

**Comment by axelmeunier** [comment]
oh ok sorry about that. I might try it as well when I have time.

**Comment by silvernode** [comment]
I just installed Solus again (it's been over a year so I decided to check it out) and came across this project. I figured there would be an Appimage of this but I guess that would be an oxymoron. It was was a bit of an ironic coincidence that someone opened this issue fairly recently. I'm going to build the launcher myself and report back. As a side not, I was thinking how fun it would be to make this a flatpak or a snap! It would be more for laughs than anything but also kind of cool at the same time.

**Comment by silvernode** [comment]
> ```shell
> cmake .. -DCMAKE_BUILD_TYPE=Release
> ```

It's probably worth noting that some system packages are needed.

```
sudo eopkg install -c system.devel
sudo eopkg it libcairo-devel qt5-base-devel fuse-devel libboost-devel qt5-tools-devel
```

**Comment by TheAssassin** [comment]
Seems like @silvernode's and my instructions should allow any Solus user to install AIL. If not, please ask Solus directly to make packages. We can't provide such packages.

**Comment by ReubenBTalbott** [comment]
I finally got around to trying to install AppImageInstaller again. It installed successfully but when It try to run `appimagelauncherd` I get `appimagelauncherd: error while loading shared libraries: libappimageupdate.so: cannot open shared object file: No such file or directory.

**Comment by TheAssassin** [comment]
How did you "install" it?

You can opt-out from the update feature for further testing. Try adding `-DENABLE_UPDATE_HELPER=Off` to your CMake command.

**Comment by ReubenBTalbott** [comment]
I used sudo make install. I'll try `-DENABLE_UPDATE_HELPER=Off` now.

**Comment by TheAssassin** [comment]
Please beware that `sudo make install` isn't really tested _at all_. Perhaps try `-DCMAKE_INSTALL_PREFIX=/usr` when trying to use with `make install`.

**Comment by ReubenBTalbott** [comment]
I tried again with `-DENABLE_UPDATE_HELPER=Off` And now I get `appimagelauncherd: error while loading shared libraries: libappimage.so.0: cannot open shared object file: No such file or directory`

**Comment by TheAssassin** [comment]
AppImageLauncher builds and installs a few libraries into a "hidden" ("private") location. Those are mainly libappimage and libappimageupdate. Looks like the so-called `rpath` (`DT_RUNPATH`) isn't set by CMake on your system.

Mind to post the `make install` output?

**Comment by ReubenBTalbott** [comment]
Here you go

`[  1%] Automatic MOC and UIC for target filesystemwatcher
[  1%] Built target filesystemwatcher_autogen
[  5%] Built target filesystemwatcher
Updating '/home/reuben/appimagelauncher-git20190805.5016cf4.source/build/i18n/generated/l10n/ui.de.qm'...
    Generated 86 translation(s) (86 finished and 0 unfinished)
    Ignored 8 untranslated source text(s)
Updating '/home/reuben/appimagelauncher-git20190805.5016cf4.source/build/i18n/generated/l10n/ui.en.qm'...
    Generated 94 translation(s) (94 finished and 0 unfinished)
Updating '/home/reuben/appimagelauncher-git20190805.5016cf4.source/build/i18n/generated/l10n/ui.es.qm'...
    Generated 64 translation(s) (63 finished and 1 unfinished)
    Ignored 30 untranslated source text(s)
Updating '/home/reuben/appimagelauncher-git20190805.5016cf4.source/build/i18n/generated/l10n/ui.fr.qm'...
    Generated 64 translation(s) (63 finished and 1 unfinished)
    Ignored 30 untranslated source text(s)
Updating '/home/reuben/appimagelauncher-git20190805.5016cf4.source/build/i18n/generated/l10n/ui.pt.qm'...
    Generated 64 translation(s) (63 finished and 1 unfinished)
    Ignored 30 untranslated source text(s)
Updating '/home/reuben/appimagelauncher-git20190805.5016cf4.source/build/i18n/generated/l10n/ui.ru.qm'...
    Generated 53 translation(s) (51 finished and 2 unfinished)
    Ignored 41 untranslated source text(s)
Updating '/home/reuben/appimagelauncher-git20190805.5016cf4.source/build/i18n/generated/l10n/ui.zh_Hans.qm'...
    Generated 82 translation(s) (82 finished and 0 unfinished)
    Ignored 12 untranslated source text(s)
[  5%] Built target l10n
[  5%] Automatic MOC and UIC for target translationmanager
[  5%] Built target translationmanager_autogen
[  8%] Built target translationmanager
[ 11%] Built target libappimage_hashlib
[ 16%] Built target libappimage_shared
[ 25%] Built target xz-EXTERNAL
[ 34%] Built target squashfuse-EXTERNAL
[ 43%] Built target libarchive-EXTERNAL
[ 45%] Built target xdg-basedir
[ 51%] Built target libappimage
[ 53%] Automatic MOC and UIC for target shared
[ 53%] Built target shared_autogen
[ 54%] Automatic MOC and UIC for target trashbin
[ 54%] Built target trashbin_autogen
[ 56%] Built target shared
[ 60%] Built target trashbin
[ 62%] Automatic MOC and UIC for target appimagelauncherd
[ 62%] Built target appimagelauncherd_autogen
[ 67%] Built target appimagelauncherd
[ 68%] Automatic MOC and UIC for target AppImageLauncher
[ 68%] Built target AppImageLauncher_autogen
[ 74%] Built target AppImageLauncher
[ 75%] Automatic MOC and UIC for target AppImageLauncherSettings
[ 75%] Built target AppImageLauncherSettings_autogen
[ 79%] Built target AppImageLauncherSettings
[ 81%] Automatic MOC and UIC for target remove
[ 81%] Built target remove_autogen
[ 86%] Built target remove
[ 87%] Automatic MOC and UIC for target appimagelauncherfs
[ 87%] Built target appimagelauncherfs_autogen
[ 91%] Built target appimagelauncherfs
[ 92%] Automatic MOC and UIC for target cli_commands
[ 92%] Built target cli_commands_autogen
[ 96%] Built target cli_commands
[ 97%] Automatic MOC and UIC for target ail-cli
[ 97%] Built target ail-cli_autogen
[100%] Built target ail-cli
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/binfmt.d/appimage.conf
-- Installing: /usr/local/lib/systemd/user/appimagelauncherfs.service
-- Installing: /usr/local/lib/systemd/user/appimagelauncherd.service
-- Installing: /usr/local/bin/appimagelauncherd
-- Set runtime path of "/usr/local/bin/appimagelauncherd" to "$ORIGIN/../lib64/appimagelauncher"
-- Installing: /usr/local/bin/AppImageLauncher
-- Set runtime path of "/usr/local/bin/AppImageLauncher" to "$ORIGIN/../lib64/appimagelauncher"
-- Installing: /usr/local/bin/AppImageLauncherSettings
-- Set runtime path of "/usr/local/bin/AppImageLauncherSettings" to "$ORIGIN/../lib64/appimagelauncher"
-- Installing: /usr/local/lib64/appimagelauncher/remove
-- Set runtime path of "/usr/local/lib64/appimagelauncher/remove" to "$ORIGIN"
-- Installing: /usr/local/bin/appimagelauncherfs
-- Installing: /usr/local/bin/ail-cli
-- Set runtime path of "/usr/local/bin/ail-cli" to "$ORIGIN/../lib64/appimagelauncher"
-- Up-to-date: /usr/local/share/mime
-- Up-to-date: /usr/local/share/mime/packages
-- Up-to-date: /usr/local/share/mime/packages/appimage.xml
-- Up-to-date: /usr/local/share/icons//hicolor
-- Up-to-date: /usr/local/share/icons//hicolor/160x160
-- Up-to-date: /usr/local/share/icons//hicolor/160x160/apps
-- Up-to-date: /usr/local/share/icons//hicolor/160x160/apps/AppImageLauncher.png
-- Up-to-date: /usr/local/share/icons//hicolor/384x384
-- Up-to-date: /usr/local/share/icons//hicolor/384x384/apps
-- Up-to-date: /usr/local/share/icons//hicolor/384x384/apps/AppImageLauncher.png
-- Up-to-date: /usr/local/share/icons//hicolor/192x192
-- Up-to-date: /usr/local/share/icons//hicolor/192x192/apps
-- Up-to-date: /usr/local/share/icons//hicolor/192x192/apps/AppImageLauncher.png
-- Up-to-date: /usr/local/share/icons//hicolor/32x32
-- Up-to-date: /usr/local/share/icons//hicolor/32x32/apps
-- Up-to-date: /usr/local/share/icons//hicolor/32x32/apps/AppImageLauncher.png
-- Up-to-date: /usr/local/share/icons//hicolor/512x512
-- Up-to-date: /usr/local/share/icons//hicolor/512x512/apps
-- Up-to-date: /usr/local/share/icons//hicolor/512x512/apps/AppImageLauncher.png
-- Up-to-date: /usr/local/share/icons//hicolor/128x128
-- Up-to-date: /usr/local/share/icons//hicolor/128x128/apps
-- Up-to-date: /usr/local/share/icons//hicolor/128x128/apps/AppImageLauncher.png
-- Up-to-date: /usr/local/share/icons//hicolor/16x16
-- Up-to-date: /usr/local/share/icons//hicolor/16x16/apps
-- Up-to-date: /usr/local/share/icons//hicolor/16x16/apps/AppImageLauncher.png
-- Up-to-date: /usr/local/share/icons//hicolor/64x64
-- Up-to-date: /usr/local/share/icons//hicolor/64x64/apps
-- Up-to-date: /usr/local/share/icons//hicolor/64x64/apps/AppImageLauncher.png
-- Up-to-date: /usr/local/share/icons//hicolor/scalable
-- Up-to-date: /usr/local/share/icons//hicolor/scalable/apps
-- Up-to-date: /usr/local/share/icons//hicolor/scalable/apps/AppImageLauncher.svg
-- Up-to-date: /usr/local/share/icons//hicolor/256x256
-- Up-to-date: /usr/local/share/icons//hicolor/256x256/apps
-- Up-to-date: /usr/local/share/icons//hicolor/256x256/apps/AppImageLauncher.png
-- Up-to-date: /usr/local/share/applications/appimagelauncher.desktop
-- Up-to-date: /usr/local/share/applications/appimagelaunchersettings.desktop
-- Installing: /usr/local/share/man/man1/AppImageLauncher.1
-- Up-to-date: /usr/local/share/appimagelauncher/l10n
-- Installing: /usr/local/share/appimagelauncher/l10n/ui.pt.qm
-- Installing: /usr/local/share/appimagelauncher/l10n/desktopfiles.pt.json
-- Installing: /usr/local/share/appimagelauncher/l10n/ui.ru.qm
-- Installing: /usr/local/share/appimagelauncher/l10n/desktopfiles.de.json
-- Installing: /usr/local/share/appimagelauncher/l10n/desktopfiles.zh_Hans.json
-- Installing: /usr/local/share/appimagelauncher/l10n/ui.es.qm
-- Installing: /usr/local/share/appimagelauncher/l10n/desktopfiles.pt_PT.json
-- Installing: /usr/local/share/appimagelauncher/l10n/desktopfiles.fr.json
-- Installing: /usr/local/share/appimagelauncher/l10n/ui.zh_Hans.qm
-- Installing: /usr/local/share/appimagelauncher/l10n/desktopfiles.ru.json
-- Installing: /usr/local/share/appimagelauncher/l10n/ui.en.qm
-- Installing: /usr/local/share/appimagelauncher/l10n/desktopfiles.en.json
-- Installing: /usr/local/share/appimagelauncher/l10n/ui.fr.qm
-- Installing: /usr/local/share/appimagelauncher/l10n/desktopfiles.es.json
-- Installing: /usr/local/share/appimagelauncher/l10n/ui.de.qm`

**Comment by TheAssassin** [comment]
So, setting the rpath works to some extent:

```
-- Set runtime path of "/usr/local/bin/ail-cli" to "$ORIGIN/../lib64/appimagelauncher"
```

I'm missing the installation of the binaries, though. And I think I remember the issue.

There's a problem in the CMake scripts where I had to choose between making too many assumptions vs. just running CMake after building again, i.e., before installing. The latter was easier for me as it keeps my scripts simple.

You have to `cmake . && sudo make install` I guess.

**Comment by ReubenBTalbott** [comment]
It would appear to work! Thanks for the help!

**Comment by ReubenBTalbott** [comment]
I take that back it appears to have installed everything and the daemon starts without errors, but the settings don't work.

**Comment by ReubenBTalbott** [comment]
It appears to kinda work since it integrates an app image I tried, but the settings appear broken.

**Comment by TheAssassin** [comment]
What setting? Please post more information.

**Comment by ReubenBTalbott** [comment]
The AppImageInstallerSettings app.

**Comment by TheAssassin** [comment]
It's called AppImageLauncher Settings. Anyway, "appear broken" is like the second least helpful description of your issue (the least useful would be to say nothing). Please add more details. What's the issues you experience? What commit are you on?

**Comment by ReubenBTalbott** [comment]
The latest commit, The app simply does not launch, going to try launching it from terminal now.

**Comment by ReubenBTalbott** [comment]
```reuben@devpc ~ $ /usr/share/applications/appimagelaunchersettings.desktop 
/usr/share/applications/appimagelaunchersettings.desktop: line 1: [Desktop: command not found
/usr/share/applications/appimagelaunchersettings.desktop: line 4: fg: no job control
/usr/share/applications/appimagelaunchersettings.desktop: line 5: Settings: command not found
/usr/share/applications/appimagelaunchersettings.desktop: line 9: X-AppImage-Integrate=false: command not found
reuben@devpc ~ $ ```

**Comment by ReubenBTalbott** [comment]
This is what is inside of appimagelaunchersettings.desktop 
```
[Desktop Entry]
Version=1.0
Type=Application
Exec=AppImageLauncherSettings %f
Name=AppImageLauncher Settings
Icon=AppImageLauncher
Terminal=false
Categories=Utility;
X-AppImage-Integrate=false
StartupWMClass=AppImageLaunch
```

**Comment by TheAssassin** [comment]
You cannot "launch" a desktop file like an executable. You need to use `xdg-open my.desktopfile`.

But there's a much simpler solution; just call `AppImageLauncherSettings`.

**Comment by ReubenBTalbott** [comment]
Oh that makes sense. I tried that and the error is 
```
AppImageLauncherSettings: error while loading shared libraries: libappimage.so.0: cannot open shared object file: No such file or directory
```

**Comment by TheAssassin** [comment]
Please post the output of `readelf -a $(which AppImageLauncherSettings) | grep -i runpath`.

**Comment by ReubenBTalbott** [comment]
There is no output.
```
reuben@devpc ~ $ readelf -a $(which AppImageLauncherSettings) | grep -i runpath
reuben@devpc ~ $ 
```

**Comment by TheAssassin** [comment]
That's what it should look like:

```
> readelf -a (which AppImageLauncherSettings ) | ag runpath
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib/x86_64-linux-gnu/appimagelauncher]
```

According to the install log you showed, the `rpath` should've been set correctly...

**Comment by ReubenBTalbott** [comment]
alright, I think since it installed my app image just fine I'll leave it be for now. 
  Someone did request that AppImageLauncher be packaged for Solus in main repo but currently they closed it in favor of appimaged, I am hoping they will reconsider at some point.

 Thanks for all the help!

**Comment by TheAssassin** [comment]
appimaged is being deprecated within the next few days. Mind to post a link to https://github.com/TheAssassin/AppImageLauncher/issues/182 at that forum?

**Comment by ReubenBTalbott** [comment]
is there a post about appimged being deprecated that I can post in the request issue on solus's issue tracker?
