### ISSUE TITLE
unable to uninstall Digikam from ubuntu 18.10 x64

### ISSUE THREAD

**Issue by jawz101** [TheAssassin/AppImageLauncher#140]
installed
appimagelauncher_1.1.1-travis529.git20190312.a3a556a.cosmic_amd64.deb

launched with appimagelauncher which installed
https://download.kde.org/stable/digikam/6.0.0/digikam-6.0.0-x86-64.appimage.mirrorlist

Right clicked on app in the Gnome launcher & tried to uninstall but icon remains and app is still installed

How do I manually uninstall both digikam and this app since I don't need either now?

**Comment by TheAssassin** [comment]
I suspect the entries are still cached. Please run `gtk-update-icon-cache-3.0  ~/.local/share/icons/hicolor/ -t; gtk-update-icon-cache  ~/.local/share/icons/hicolor/ -t` and see if it helps. These commands should be run upon removal automatically, but that might have failed. If that doesn't help, please try the commands without further parameters.

**Comment by jawz101** [comment]
the 2nd command succeeds but gtk-update-icon-cache-3.0 says command not found.  Is that a package I should see in the ubuntu repositories?  I see the gtk-update-icon-cache package but I don't see gtk-update-icon-cache-3.0

**Comment by TheAssassin** [comment]
Did it help? The second command is normally an alias for the first, you never know which one to expect, hence both are attempted, so don't worry, if the first one worked it should be fixed.

**Comment by jawz101** [comment]
unfortunately no.  The app is still there.  I actually have a digikam 6.0 and 6.1 beta I'd installed.  The 6.1 doesn't launch anything and the 6.0 does run the program but neither will uninstall from right clicking on its launcher in gnome and uninstalling via the AppImageLauncher context menu item

**Comment by TheAssassin** [comment]
Is the file still in `~/Applications`?

**Comment by jawz101** [comment]
yep

**Comment by TheAssassin** [comment]
Then I wonder why it didn't get removed completely when you were using our "removal helper", but it explains why it's got re-integrated. As long as the device is in `~/Applications`, the appimagelauncherd daemon will keep it integrated until the file disappears. What happens if you remove the file manually?

**Comment by jawz101** [comment]
Well, I reinstalled ubuntu yesterday.  Since I can no longer troubleshoot it I'll close this issue.  Thank you anyways
