### ISSUE TITLE
AppImageLauncherFS fails to launch

### ISSUE THREAD

**Issue by Igetin** [TheAssassin/AppImageLauncher#142]
I’m using AppImageLauncher 1.1.1 (installed via the deb package), running on Xubuntu 18.04. When I launch an AppImage, I get this error:
```
Failed to register AppImage in AppImageLauncherFS: could not open map file
```
When I look at my process list, it looks like AppImageLauncherFS is just restarting itself over and over again.

After stopping the service via `systemctl --user stop appimagelauncherfs`, I tried running `appimagelauncherfs` manually, which gives me this output:

```
FUSE version: 2.9
fusermount: entry for /run/user/1000/appimagelauncherfs not found in /etc/mtab
rmdir: failed to remove '/run/user/1000/appimagelauncherfs/': Directory not empty
mountpoint: /run/user/1000/appimagelauncherfs/
Starting FUSE filesystem
terminate called after throwing an instance of 'AlreadyRunningError'
  what():  
Aborted (core dumped)
```

There is no `appimagelauncherfs` process running despite the AlreadyRunningError.

**Comment by TheAssassin** [comment]
Please `ls -al /run/user/1000/appimagelauncherfs`.

**Comment by Igetin** [comment]
```
dr-xr-x---  2 igetin igetin        0 「 30.03.2019 | 14.02 」 .
drwx------ 12 igetin igetin      280 「 30.03.2019 | 14.11 」 ..
-r-xr-xr-x  1 igetin igetin 83107744 「 23.03.2019 | 20.01 」 0000.AppImage
-r-xr-xr-x  1 igetin igetin 87628640 「 30.03.2019 | 14.18 」 0001.AppImage
-r--r--r--  1 igetin igetin      195 「 30.03.2019 | 14.02 」 map
-rw-rw----  1 igetin igetin       80 「 30.03.2019 | 14.02 」 register
```

I’ve restarted my computer again after the previous try, and everything seems to be working fine now. Not sure what caused it not to work last time. I’ve tried multiple AppImages now, and they all launch & get integrated without problems.

**Comment by TheAssassin** [comment]
Well, I guess there _has_ been another instance running... Well, glad it works now. We're already working on a type 3 AppImage spec, which makes AppImageLauncherFS obsolete again.

**Comment by Ahmeed2m** [comment]
@TheAssassin 
I have the same error but my output is 
```drwxr-x---  2 ahmed ahmed  60 Apr 12 07:59 .
drwx------ 13 ahmed ahmed 560 Apr 12 07:59 ..
-rw-r--r--  1 ahmed ahmed 168 Apr 12 08:02 register
```
