### ISSUE TITLE
how to build from source archive

### ISSUE THREAD

**Issue by oberon-manjaro** [TheAssassin/AppImageLauncher#145]
Hi there. I am trying to build this from the source archive available from [here](https://github.com/TheAssassin/AppImageLauncher/archive/v1.2.2.tar.gz), but cmake is still trying to get the version from git.
```
CMake Warning at cmake/versioning.cmake:37 (message):
  Failed to gather commit ID via git command, trying to read cache file
Call Stack (most recent call first):
  CMakeLists.txt:6 (include)

CMake Error at cmake/versioning.cmake:43 (message):
  Could not find git commit cache file, git commit ID not available for
  versioning
Call Stack (most recent call first):
  CMakeLists.txt:6 (include)

-- Configuring incomplete, errors occurred!
```
How can I circumvent this step? Or is it actually not possible to build without cloning the repo?
Thanks

**Comment by azubieta** [comment]
Hi, as a workaround you can try:
`echo "tag" > ${SOURCES_DIR}/cmake/GIT_COMMIT`
this will create a fake git commit id

**Comment by oberon-manjaro** [comment]
Hm. This gives me
```
CMake Warning at cmake/versioning.cmake:37 (message):
  Failed to gather commit ID via git command, trying to read cache file
Call Stack (most recent call first):
  CMakeLists.txt:6 (include)


-- Git commit: v1.2.2
fatal: not a git repository (or any of the parent directories): .git
date: option requires an argument -- 'd'
Try 'date --help' for more information.
```

**Comment by oberon-manjaro** [comment]
Well, it's no big deal. I can git clone before building. That's fine, too.

**Comment by TheAssassin** [comment]
@azubieta the commit ID was recognized from the cache file correctly. This cache file was added to the tarball on purpose: it makes it independent from the tarball.

I'll be looking into it.

**Comment by TheAssassin** [comment]
@oberon-manjaro you downloaded the wrong source tarball, it seems. GitHub's tarballs are incomplete, but can't be turned off even if you provide one. The one on the release page works fine.

**Comment by oberon-manjaro** [comment]
which realease page do you mean? I used this one:

![release](https://user-images.githubusercontent.com/11800714/55919224-5c969b80-5bf5-11e9-9318-0fd5f69f5433.png)

**Comment by TheAssassin** [comment]
Check the third entry.

**Comment by oberon-manjaro** [comment]
Ok. Well, that doesn't really help me for creating a PKGBUILD, since I will need to investigate the commit for the proper link each time... Will just stick with git clone then.
Thanks.

**Comment by TheAssassin** [comment]
Well, that's not that hard with some scripting. But yeah, git clone will work better, I guess.

Just try to use the `continuous` tags, that branch indicates that at least one Travis build has worked. That's what was used in the previous Arch recipes.

**Comment by oberon-manjaro** [comment]
Thank you :smiley: All is well. The aim is to provide a stable release package in Manjaro repos. I will simply use git tags.

**Comment by TheAssassin** [comment]
Even better. Shall we get rid of the AUR thingy then? It's out of date and I have no interest in maintaining it.

**Comment by oberon-manjaro** [comment]
We could get rid of the -git package there maybe if nobody wants to maintain it. But I can offer to upload our stable build PKGBUILD. Will not be any additiional work for me, since we will maintain the Manjaro package anyway.

**Comment by TheAssassin** [comment]
We could patch it even to just use the latest `continuous` tag. If you want to take over, that'd be great, thanks for the kind offer. Please tell me what I need to do.

**Comment by oberon-manjaro** [comment]
https://aur.archlinux.org/packages/appimagelauncher

**Comment by oberon-manjaro** [comment]
I have now also sent a request to adopt the -git version in the AUR. You will just need to orphan the pkg. Or you can add me as co-maintainer, that will also work. My AUR handle is oberon2007
