### ISSUE TITLE
Failure of registering RawTherapee

### ISSUE THREAD

**Issue by peerwal** [TheAssassin/AppImageLauncher#146]
I installed Rawtherapee 5.5 on my Kubuntu 18.10 system and ran the system integration using AppImageLauncherFS 1.0.2, which seemed to have worked fine. Hower, when starting the app I get the error message:

**Failed to register AppImage in AppImageLauncherFS: could not open map file**.

Is there any debugging I can do?

**Comment by peerwal** [comment]
The problem also occurs after updating to AppImageLauncher 1.2.2.

**Comment by TheAssassin** [comment]
Does the appimagelauncherfs run? Try to reboot.

**Comment by peerwal** [comment]
Thanks a lot for your reply. Actually, a reboot did not solve the issue but installing appimagelauncherfs 1.2.2 and rebooting did. Great job!

**Comment by TheAssassin** [comment]
Just want to highlight that

> appimagelauncherfs

is just a component. The package is called AppImageLauncher. The filesystem is only a minor component.

**Comment by peerwal** [comment]
Yeah, sorry I know. Didn't express myself correctly.
