### ISSUE TITLE
libappimageupdate.so not found on Arch-based systems

### ISSUE THREAD

**Issue by oberon-manjaro** [TheAssassin/AppImageLauncher#147]
It looks like this issue existed in the past already. However, it seems to be not possible to launch current latest release on Archlinux based systems:
```
$ AppImageLauncher 
AppImageLauncher: error while loading shared libraries: libappimageupdate.so: cannot open shared object file: No such file or directory
```

**Comment by oberon-manjaro** [comment]
One user in the AUR reports that version 1.1.0 built with the appimagelauncher-git PKGBUILD is working fine. The only difference in this build is that it uses tag='continuous' ...

**Comment by TheAssassin** [comment]
@oberon-manjaro that doesn't have anything to do with the fact it's Arch. Can you send me a link to the PKGBUILD and ideally a build log?

**Comment by oberon-manjaro** [comment]
Thank you @TheAssassin for looking into it! :smiley: 
-  [PKGBUILD](https://gitlab.manjaro.org/packages/community/appimagelauncher/blob/master/PKGBUILD)
- [buildlog](https://gist.github.com/oberon-manjaro/ec9a691ad56d69d2ce9036cc7e49cd59)

**Comment by oberon-manjaro** [comment]
Alright. Seems I forgot to re-run cmake like is done in the -git package! :stuck_out_tongue_winking_eye: 
working now, sorry!

**Comment by TheAssassin** [comment]
Ah yeah, _that_ thing. There's a warning in the CMake source code that this is necessary. I couldn't work around this limitation yet.
Sorry for wasting your time.
