### ISSUE TITLE
clipgrab no icon task bar no icon appmenu

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#148]
Hi, I downloaded this appimagelauncher_1.2.2-travis556.git20190414.ba13bec.bionic_amd64.deb. With this version clipgrab appimage has no icon in the task bar or appmenu. With the previous appimagelauncher to 1.2.2 no problem with clipgrab 
https://download.clipgrab.org/ClipGrab-3.8.2-x86_64.AppImage

**Comment by TheAssassin** [comment]
Might be an issue within the Clipgrab AppImage. The embedded icon has an invalid resolution (80x80, but is put into 64x64).

Nothing has changed within appimagelauncher. Just updated translations and that stuff.

**Comment by Lvaskz** [comment]
Hi, I reported to clipgrab developers 
closing...
