### ISSUE TITLE
AppImageLauncher won't install in Ubuntu 19.04

### ISSUE THREAD

**Issue by LineAxe** [TheAssassin/AppImageLauncher#149]
_AppImageLauncher version I have been trying with Ubuntu 19.04 is:_                    appimagelauncher_1.2.2-travis552.git20190331.7279b50.bionic_amd64.deb

When I try to install it only says 0 percent and then stops... Don't know what to do, I just tested another version on my Ubuntu 16.04 system and it works there.

**Comment by TheAssassin** [comment]
Erm... what percentage? This tool doesn't have any dialogs with progress bars or anything. Please provide more information.

For 19.04 I'd recommend at least the cosmic version.

**Comment by LineAxe** [comment]
Hi , I have now also tried the cosmic install , here is a picture of what I get 
![Screenshot from 2019-04-18 16-58-14](https://user-images.githubusercontent.com/20873354/56398248-5491b980-61fc-11e9-80cd-04338bc07551.png)

**Comment by LineAxe** [comment]
nice to get ahead of the pack for version 19 :()

**Comment by TheAssassin** [comment]
Please try with the commandline, I don't know very much about this weird software center, and why it might be broken. I can't give support for Ubuntu's miserys, you might want to ask them.

To install with the CLI, open a terminal in `~/Downloads`, and then run `sudo dpkg -i <filename of the .deb>`.

**Comment by LineAxe** [comment]
Yo, that worked...Funny how them various Linux packages can screw up the basic dpkg commands that they are supposed to implement :)

**Comment by TheAssassin** [comment]
I guess we can close the issue then. Feel free to reopen if you have more issues, or just open new issues.
