### ISSUE TITLE
Arcolinux systemd filesystem service does not start at boot [Solution]

### ISSUE THREAD

**Issue by smac89** [TheAssassin/AppImageLauncher#152]
I noticed some of my app images do not auto start at boot, most notably the intellij toolbox appimage does not autostart.

Taking a look at the two systemd services that needed to be running, I saw that the `appimagelauncherfs` serivice did not run. It was enabled, but the status always said `Inactive`.

The changes I made to get it to start working was to open the `/usr/lib/systemd/user/appimagelauncherfs.service` file and in the `[Instal]` section, I changed it to:

```
[Install]
WantedBy=default.target
```

It works for me now after rebooting that all appimages are mounted. If this is ok, I can make a PR for this

**Comment by TheAssassin** [comment]
I totally missed this issue, sorry for the long delay!

This is totally okay, thanks for the hint. I will just quickly do it myself, but credit you.
