### ISSUE TITLE
Do not ask to move AppImages around if running from Live ISO

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#153]
User story:
I as the user have downloaded a distribution Live ISO which contains AppImageLauncher by default. I am annoyed by the fact that AppImageLauncher asks me questions, especially the question whether I want to move AppImages to `$HOME/Applications`, since a Live ISO will forget its state anyway as soon as it is rebooted. I expect an AppImage to "just work" = open when I double click it, with no questions asked.

Possible solution:
Check if `/proc/cmdline` contains the string `.iso`, and if it does, assume we are running on a Live ISO. In this case, do not ask the user any questions.

```
me@host:~$ cat /proc/cmdline 
(...) iso-scan/filename=/boot/iso/xubuntu-18.04-desktop-amd64.iso (...)
```

This was discussed with @azubieta a while ago.

**Comment by shoogle** [comment]
Not sure I agree with this. People use LiveISOs to test every aspect of how a distribution behaves without risking their installed OS. If you start special-casing LiveISOs then this kind of testing no longer gives an accurate result. It also violates the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

A better alternative would be to offer some kind of keyboard shortcut to disable integration. For example, don't attempt integration if the Shift key is held when the user double-clicks on the AppImage. This shortcut would work on a normal install as well as inside a LiveISO, so there is not the problem of special-casing different environments and assuming certain usage patterns.

**Comment by probonopd** [comment]
> If you start special-casing LiveISOs then this kind of testing no longer gives an accurate result. 

Most Live ISOs are already special-casing the system, e.g., by disabling update checks, by hardcoding a default user, disabling automatic initramfs regeneration, and so on.

> People use LiveISOs to test 

Some people also use Live ISOs for productive work, myself included. The great advantage of doing so is that the system is virtually "maintenance free" since it is in a defined "factory new" state after each reboot, hence almost eliminating the need for "system administration".

**Comment by TheAssassin** [comment]
> The great advantage of doing so is that the system is virtually "maintenance free" since it is in a defined "factory new" state after each reboot, hence almost eliminating the need for "system administration".

The big disadvantage is the lack of all security features on the average live CD, since they're not meant for that use. You should probably settle for special distros meant for that. Knoppix, Kali etc. can be used safely.

I do see your point and want to create an option for you to disable that stuff. Can your SystemImageKit not just put a file into `/etc` that, when existing, sets up the workflow so it works best for you? That's more explicit then. I really consider this a @probonopd-only feature.

**Comment by probonopd** [comment]
This is not about my personal itch, but this is part of turning AIL into a user experience that I could accept so that we could recommend it in place of `appimaged`. (Another point is to have "never ask again" checkboxes, and a replacement for the FUSE filesystem that eats 10% performance, but @azubieta had an idea for this as well.)

**Comment by TheAssassin** [comment]
I do see both the arguments for making what you suggested the default on live CDs, but the points against are also valid. Let me recap the most notable arguments quickly:

Pro:
- in live CDs there's no persistent `$HOME`, there's no point in moving stuff to `$HOME`; there's virtually no one mounting a permanent location there, except for a few very rarely used images (I think Knoppix is a good example)

Con:
- different behavior on live ISOs which deviates from the experience on other setups
- makes testing awkward, which mostly happens on those live CDs

Especially the difficulty of testing is a big problem for my testing workflow. Here's the solutions I came up with while thinking about this for a minute or two. They make the assumption we successfully detected a live CD environment:

- ask the user on the first AppImage launch whether to go into "fuck off" mode (i.e., don't ask questions)
- add opt-out feature (e.g., putting a file into some location in `$HOME` or even system wide in `/etc`) to allow for ignoring the live CD check

I think both are worth a discussion. I know it's a bit ironic to ask with a dialog whether to ask for dialogs, but I think UX wise it's pretty much the best we can do if we want to ask the user on startup.
The second option is a sort of "hidden opt out", and doesn't require a UI IMO, it's more of an "expert" feature.

What do you think? Which option shall we implement? Feedback very welcome.

(Note: I'm tending to the first option, and I guess asking for *1* mouse click isn't asked too much for.)

**Comment by probonopd** [comment]
Or
* Add opt-in for asking questions

**Comment by TheAssassin** [comment]
@probonopd that's pretty much what I meant with "opt out from live CD detection". This way it makes more sense. If there are other features ever in the future that might get deactivated by that check, we rather want a "catch-all opt in/out", right?

**Comment by probonopd** [comment]
What I mean is, by default the questions should be disabled when running from Live ISO. If for testing reasons one wants to see the questions on a Live ISO, then one should opt into the questions.

**Comment by TheAssassin** [comment]
Again, *that's the second option I suggested*... "opt out" refers to the deactivation of things due to this check...

> add opt-out feature (e.g., putting a file into some location in $HOME or even system wide in /etc) to allow for ignoring the live CD check

**Comment by shoogle** [comment]
I don't think it is a good idea to make assumptions about usage patterns based on the users environment. @TheAssassin's solutions all sound perfectly reasonable to me. They involve a tiny amount of effort on the part of the user (create a file or click never ask again), but this is a small price to pay in return for keeping the behaviour the same across all systems.

If those really are too much effort for you @probonopd, what about my original suggestion:

> don't attempt integration if the Shift key is held when the user double-clicks on the AppImage

If you don't know about that option (or forget it exists) then the worst that would happen is you would be greeted by the usual dialog with its "never ask again" option.

**Comment by probonopd** [comment]
> Again, that's the second option I suggested... "opt out" refers to the deactivation of things due to this check...
>
>> add opt-out feature (e.g., putting a file into some location in $HOME or even system wide in /etc) to allow for ignoring the live CD check

👍 I had misread originally. I thought you meant "...allow for disabling the dialog". Yes, I think what you are suggesting is the way to go @TheAssassin.

@shoogle again, it is not about myself at all, it is about normal users who see an AppImage on a Live ISO for the first time and "just want it to run". It's about "[discoverability](https://whatis.techtarget.com/definition/discoverability-in-UX-design)". No one knows that they have to press Shift.

**Comment by shoogle** [comment]
I think holding Shift is more discoverable than creating a file in a magic location :wink: Anyway, these options are not mutually exclusive. Creating a file is a good method from the command line but not so good for users who prefer a GUI. Holding Shift is a good method on the GUI but doesn't work on the command line. The "never ask again" option is the discoverable one; it exists as a fallback for users who don't know that the magic file or magic shortcut exist.

**Comment by TheAssassin** [comment]
> think holding Shift is more discoverable than creating a file in a magic location

You also got it wrong. If we decide to go for that "file" thing, it'd be like, deactivate by default, unless that file exists (i.e., _I_ can restore its functionality during development, anyone else won't use that).

The "holding shift" thing would work, too, I'd say (with my little Qt experience).

I also think the "never ask again" thing is most discoverable, and least error prone one.

**Comment by shoogle** [comment]
> You also got it wrong.

Yes, sorry.

My vote would still be to keep the default behaviour the same on all systems, but it's up to you.

**Comment by TheAssassin** [comment]
@shoogle well, we have other requests to allow for deactivating moving AppImages, too. So here's my new approach: we show that dialog every time we don't find a config file (assuming that this is a fresh install) and ask the user to choose whether to move or not.

Advantages:
  - no behavioral differences on different systems
  - allows non-live-ISO users to choose about default behavior, too
  - can be extended with more options, e.g., the integration dir (might be shown in a so-called "spoiler area")
  - I always wanted to implement some config panel to allow for configuring from a UI, this is the chance to do that

I think this is what I'm going to implement, yeah. It's the best trade-off between all mentioned options.

**Comment by TheAssassin** [comment]
Preview:

![screenshot_2019-05-16_03-28-35](https://user-images.githubusercontent.com/4503202/57819955-06d08880-778b-11e9-8662-1c79b0454737.png)

**Comment by TheAssassin** [comment]
@SolarLiner any suggestions are highly welcome.

**Comment by TheAssassin** [comment]
Everyone please try the latest build.

**Comment by shoogle** [comment]
I think this is the right approach, but there's too much text. How about this instead:

---

Titlebar - AppImageLauncher: First run

__Welcome to AppImageLauncher!__

When running an AppImage for the first time...

- [ ] Move it to your applications folder and add it to system menus, then run it
- [ ] Just run it
- [x] Ask me what to do

Location to use as applications folder:

- ~/Applications    [Customize]

---

Some comments:

- Those should be radio buttons rather than checkboxes. Alternatively it could be a dropdown list.
- If you don't like the "Move" option, replace it with "Offer to move" and drop "Ask me what to do".
- The location selector should be disabled (i.e. greyed out) when "Just run it" is selected.

**Comment by shoogle** [comment]
Slightly different wording:

---

Before running an AppImage for the first time...

◎ Move it to my applications folder and add it to system menus
◎ Do nothing (i.e. just run it)
◉ Ask me what to do

**Comment by TheAssassin** [comment]
> ◎ Move it to my applications folder and add it to system menus, then run it

That's not going to happen. AppImageLauncher will never just move things around. The reason is that sometimes you just don't want to move AppImages around, you quickly want to run them as they are. There must be a way to do so, always.

> ◎ Do nothing (i.e. just run it)

That's a bad wording IMO. "Do nothing" is like "okay, but if it does nothing, why would I need that software?"... AppImageLauncher does "more than nothing", even if it just makes the AppImage executable that's more than nothing.

The choice is binary, either we ask or we don't. A checkbox portrays that perfectly fine IMO. But we can also use radio buttons, if you want to. I'm open to that option.

I also think there's too much text, but what you suggest is way too short and might lay a false tray in the user's understanding of AppImageLauncher. We need to avoid that.

**Comment by probonopd** [comment]
Why distinguish between the first and subsequent launches? Why not combine this with the "Do you want to move...." question? E.g.:

```
Do you want to move this application to ~/Applications before launching it?
[Yes] [No]
[x] Do not ask again (you can change this in the control panel)
```

Imho this is really all that's needed. No explaining about AppImages, no "Save", no "Cancel", no "Settings".

Where do I find the "control panel" btw?

**Comment by TheAssassin** [comment]
Because that only really works on a per-AppImage basis...

**Comment by probonopd** [comment]
What do you mean by this? If the user selects "Do not ask again" I mean "...ever, for all AppImages".

**Comment by TheAssassin** [comment]
First of all, your own wording implies that: it contains the word "this", doesn't it?
Second, UX wise it makes much more sense to separate such a ("final") decision from the normal dialog. You get to choose once, then you don't have to think about that again. If you always get that stupid checkbox and then accidentally hit it once or twice and have to go to some control panel to reset... way too complex stuff. Even without that word "this", it's a bad UX.

**Comment by probonopd** [comment]
The other way around, I miss to click the checkbox on the initial run and then I am not asked anymore?

I am striving for Apple-like minimalism and elegance...

**Comment by TheAssassin** [comment]
You need to be able to expect *some* effort from the users.

And, again, Apple's UX for applications sucks in very many ways, too. And: this is not macOS, it's Linux. Trying to do the best with what we got using UX elements Linux users are used to.

**Comment by TheAssassin** [comment]
Mind to try AppImageLauncher Lite? It doesn't ship the integration dialog *at all*.

**Comment by probonopd** [comment]
Yes, AppImageLauncher Lite seems to target the functionality I am looking for. Maybe a check could be added to AppImageLauncher telling the user to use Lite in case a Live ISO is detected.

**Comment by TheAssassin** [comment]
If you don't want these dialogs please use AIL Lite. This won't need to be implemented any more.
