### ISSUE TITLE
Package for Elementary OS

### ISSUE THREAD

**Issue by xeroxkid** [TheAssassin/AppImageLauncher#155]
AppImageLauncher on Elementary OS

**Comment by TheAssassin** [comment]
Please add more details to your request. Do you want Elementary OS to ship AppImageLauncher? In that case, please go there and ask them to do it.

**Comment by TheAssassin** [comment]
We won't make native ElementaryOS packages. You're welcome to ask the Elementary team yourself to make packages, we can provide some assistance even.
