### ISSUE TITLE
Failed to register Appimage in system via libappimage

### ISSUE THREAD

**Issue by 2635599** [TheAssassin/AppImageLauncher#156]
i get the following when clicking on an appimage to integrate "ailed to register Appimage in system via libappimage". it wom't drop the file into applications but does delete the file.  i just did a fresh install of kde neon.  thanks

**Comment by TheAssassin** [comment]
It doesn't delete the file I guess, but most likely moved it and then failed to integrate with libappimage. Check your apps dir, I bet it's in there.

If any, it should probably just move the file back to the original location.

Mind to share the AppImage? If that's not possible, please run [appimagelint](https://github.com/TheAssassin/appimagelint/releases/tag/continuous) on it and post the results. That'll help debug the issue, but isn't as good as getting hands on the file itself (at least not yet).

**Comment by 2635599** [comment]
it deleted it. i looked there to see if it was moved and no it wasn't in there. well on a sided note i tested 4 files, 3 i didn't care about and the one i did, all were out and out deleted. after that decided to just remove appimagelauncher. unlike cinnamon with neon i have plenty of options for creating shortcuts / links wherever i want. i did enjoy using ail, but after just doing a fresh install i need a bit of a break from trouble shooting things. i'll give ail another run in a week or two. thanks for getting back to me so fast.

**Comment by TheAssassin** [comment]
@2635599 weird indeed. Neon is right now packaging AIL actually. Did you use that version, or the one shipped here?

**Comment by 2635599** [comment]
shipped here. when i wsent to uninstall i took the chance that it might be in synaptic. like i said alls good. doesn't seem to be a real need for ail in neon unlike mint cinnamon.

**Comment by TheAssassin** [comment]
Should be fixed, please reopen if the issue persists.

**Comment by violetu** [comment]
Same problem in Archlinux KDE when I wnat to run copytranslator.appimage.

**Comment by maplepy** [comment]
Got this issue with stratz for dota 2

**Comment by maplepy** [comment]
https://minio.stratz.com/stratz-plus/STRATZ-v0.10.6.AppImage
