### ISSUE TITLE
Failed to register AppImage in AppImageLauncherFS

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#157]
https://forum.manjaro.org/t/solved-appimage-woes-when-building-package/86654/9

![](https://forum.manjaro.org/uploads/default/original/3X/1/c/1c694db544e42efef7b73be7e493872c95d684e1.png)

It says "solved" in the title but the last entry reads

> Either the (AUR pkg) maintainers have gotten a few things wrong or appimage is buggy or our implementation/packaging of appimage is buggy.
> 
> Which/what is hard to say at the moment .. especially for those of us who dont use it :wink:

**Comment by rvrichards** [comment]
Every program I run that is an AppImage gives me the error: 
![AppImageError](https://user-images.githubusercontent.com/7088711/57989710-c192ac00-7a53-11e9-88ab-e6024ccafa3b.png)
I have grabbed the latest version of appimagelauncher, and still get this. My laptop froze  I did have to do a hard boot and noticed that this happened after that.
Running Bionic Beaver 18.04

**Comment by TheAssassin** [comment]
Sometimes the filesystem doesn't start up properly after installation. This bug occurs quite inconsistently, it seems like it depends highly on what's running otherwise on the users' computers. I haven't found a real cause yet. Most of the time, rebooting a few times helps.

The freeze is weird, though... never heard about that before.

**Comment by probonopd** [comment]
>  rebooting a few times

Ouch!

**Comment by TheAssassin** [comment]
According to that forum post it might be a Kernel 5.0 issue. None of the major distros ships that kernel, it's really really new. Will try Manjaro later.

**Comment by 2635599** [comment]
most likely not the kernel. i'm running 5.1 and have run 5.0 and i never had the above issue.

**Comment by TheAssassin** [comment]
I also never could reproduce these issues. Therefore I think it's due to the fact that Arch based systems tend to differentiate between users quite much. Most likely it's broken due to user interaction, if it works fine on fresh systems.
