### ISSUE TITLE
libcurl3 dependency problem on Debian 9 install after v 1.1.1

### ISSUE THREAD

**Issue by michael-wenyon** [TheAssassin/AppImageLauncher#158]
Installation fails with libcurl3 dependency message on version 1.2.0 and newer on Debian 9 (Buster or testing). Version 1.1.1 installs and works.

**Comment by TheAssassin** [comment]
Try the bionic package version, it depends on `libcurl4-something`.

**Comment by michael-wenyon** [comment]
GDebit Package Manager says that installation of that version 'Requires the installation of 103 packages'. Maybe that is OK, but I am wondering: is that correct?

**Comment by TheAssassin** [comment]
Without knowing what exactly it wants to install, I can't give you an answer. Not sure what it does want to install. There's no dedicated Debian 9 version (yet), I might just try myself later. But at least there's no conflicts.

If you want an actual answer to your question, please try to get the list of dependencies, so I can look through them.

**Comment by michael-wenyon** [comment]
I did not know I could do this, but here is the output from gdebi installer:

`michael@thinkpad-debian:~/Downloads$ sudo gdebi appimagelauncher_1.2.2-travis552.git20190331.7279b50.bionic_i386.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
Requires the installation of the following packages: glib-networking:i386 libacl1:i386 libarchive13:i386 libatk-bridge2.0-0:i386 libatk1.0-0:i386 libatspi2.0-0:i386 libattr1:i386 libblkid1:i386 libcairo-gobject2:i386 libcairo2:i386 libcolord2:i386 libcom-err2:i386 libcups2:i386 libcurl4:i386 libdatrie1:i386 libdouble-conversion1:i386 libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libegl-mesa0:i386 libegl1:i386 libelf1:i386 libepoxy0:i386 libevdev2:i386 libfribidi0:i386 libfuse2:i386 libgbm1:i386 libgdk-pixbuf2.0-0:i386 libgl1-mesa-dri:i386 libgl1:i386 libglib2.0-0:i386 libglvnd0:i386 libglx-mesa0:i386 libglx0:i386 libgraphite2-3:i386 libgssapi-krb5-2:i386 libgtk-3-0:i386 libgudev-1.0-0:i386 libharfbuzz0b:i386 libinput10:i386 libjson-glib-1.0-0:i386 libk5crypto3:i386 libkeyutils1:i386 libkrb5-3:i386 libkrb5support0:i386 liblcms2-2:i386 libmount1:i386 libmtdev1:i386 libnghttp2-14:i386 libpango-1.0-0:i386 libpangocairo-1.0-0:i386 libpangoft2-1.0-0:i386 libpciaccess0:i386 libpcre2-16-0:i386 libpcre3:i386 libpixman-1-0:i386 libproxy1v5:i386 libpsl5:i386 libqt5core5a:i386 libqt5dbus5:i386 libqt5gui5:i386 libqt5network5:i386 libqt5svg5:i386 libqt5widgets5:i386 librest-0.7-0:i386 librtmp1:i386 libselinux1:i386 libsoup-gnome2.4-1:i386 libsoup2.4-1:i386 libsqlite3-0:i386 libssh2-1:i386 libthai0:i386 libwacom2:i386 libwayland-client0:i386 libwayland-cursor0:i386 libwayland-egl1:i386 libwayland-server0:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-icccm4:i386 libxcb-image0:i386 libxcb-keysyms1:i386 libxcb-present0:i386 libxcb-randr0:i386 libxcb-render-util0:i386 libxcb-render0:i386 libxcb-shape0:i386 libxcb-shm0:i386 libxcb-sync1:i386 libxcb-util0:i386 libxcb-xfixes0:i386 libxcb-xinerama0:i386 libxcb-xkb1:i386 libxcomposite1:i386 libxcursor1:i386 libxkbcommon-x11-0:i386 libxkbcommon0:i386 libxshmfence1:i386 libxxf86vm1:i386 qt5-gtk-platformtheme:i386 
`

**Comment by TheAssassin** [comment]
Well, you downloaded the 32-bit version (note the `i386` part in the package name), and your system is very likely a 64-bit one (Debian calls that `amd64`). Just get the 64-bit bionic package and try again.

**Comment by michael-wenyon** [comment]
Ooops! Yes, quite so [embarassed]. Please excuse me.

Installs OK with the 64-bit version. Thank you!
