### ISSUE TITLE
arch linux tar.gz

### ISSUE THREAD

**Issue by star-buck** [TheAssassin/AppImageLauncher#16]
Can someone simply build a tar.gz arch package from released source code and AppImageLauncher should work on arch or any derivative like Manjaro/Netrunner Rolling the same as the .deb package does for Debian or Ubuntu/Mint/etc.?

**Comment by TheAssassin** [comment]
A simple tarball containing all sources including the external resources is sufficient, right? I'll set up CPack to build such a tarball, and will configure my release uploading to upload these tarballs, too.

**Comment by TheAssassin** [comment]
Seems like the tarballs built on Travis CI are empty for some reason. I cannot reproduce this behavior locally. I'll be checking the logs for hints.

**Comment by TheAssassin** [comment]
Fixed in 11c2409.
