### ISSUE TITLE
AppImage of AppImageLauncher that does not need root

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#161]
For users who are not root on their machines there is a need for an AppImage of AppImageLauncher that does not need root when being set up. Similar to what `appimaged` has today.

Overall, I'd highly recommend to get rid of everything that needs root during setup or use.

Selected use cases:

* As a corporate or university lab user, I cannot install packages because I am not root
* Concerned about system integrity, I do not want to install packages or run anything as root that that does not come with my distribution
* As a SystemImageKit user, [I need something I can put inside](https://github.com/probonopd/SystemImageKit/issues/44) an ExtensionImage (be aware that SystemImageKit is the sister project to AppImageKit and the two are really designed for each other, so if AIL ever wants to become part of the AppImage project it really needs to work flawless with SystemImageKit)

**Comment by TheAssassin** [comment]
Just for completion: focus is on something that can install itself using user-space configs for systemd etc.

**Comment by probonopd** [comment]
Probably much of the `appimaged.AppImage` can be reused?

**Comment by TheAssassin** [comment]
That was what I wanted to check out, yes. But first I need to make some adjustments to actually be able to ship appimagelauncherd as an AppImage.

**Comment by TheAssassin** [comment]
It's called AppImageLauncher Lite and there's a PR open for that. See #178. Please test.

**Comment by probonopd** [comment]
AppImageLauncher Lite implements this. Thank you.
