### ISSUE TITLE
No icons or shortcuts in Ubuntu

### ISSUE THREAD

**Issue by loaderini** [TheAssassin/AppImageLauncher#162]
I installed **appimagelauncher_1.2.2-travis552.git20190331.7279b50.bionic_amd64.deb** on Ubuntu 18.04.2 and I opened some appimages. The message appeared and asked if I wanted to integrate them, I clicked "integrate and run", the appimage opened normally but there's no icon or shortcut anywhere. Nothing on the desktop or the dock bar or the applications button.
The integrated appimages were moved to `Home/Applications`.

I must have done something wrong. Is there a way for me to fix the problem?

**Comment by TheAssassin** [comment]
Some AppImages have broken icons. You can check that using [appimagelint](https://github.com/TheAssassin/appimagelint/releases), which you just run from a terminal like `./appimagelint-*.AppImage <my.AppImage>`.

If you tell us what AppImage is broken for you, I can also have a closer look. I don't want to guess too much, though.

**Comment by loaderini** [comment]
I've tried **electrum 334.appimage**, **etcher 1524.appimage** and **peek 1310.appimage**.
But _just now_, I thought _"Maybe the space in the file's name is the problem?"_ and it was! So all I needed to do was simply delete the appimages from the `Home/Applications` folder, re-download them, re-run and re-integrate them but without any spaces in the filename this time and their icons actually show up in the Gnome applications menu! So I solved it!
Thank you for this awesome software! It would be nice to be able and rename the icons though. Right now, the names in the Gnome app menu are **"ElectrumBitc..."**, **"balenaEtcher (1)"** and **"Peek"**. It is a general problem in the Ubuntu Gnome menu, app names or icons cannot be changed. But if someday you create a control panel for the app, maybe you can put in an option to rename the appimage!

**Comment by TheAssassin** [comment]
You need to provide links.

Spaces in filenames normally aren't problematic, but now that you mention it, I'll have a look at that.

Regarding renaming, that's a technical debt from the so-called Desktop Entry standard. These are not supposed to be mutable. AIL actually relies on that a bit even.

**Comment by TheAssassin** [comment]
I have to correct myself, spaces are definitely a problem in the desktop files, see #170. Fixing the escaping issues might fix your problem.

**Comment by TheAssassin** [comment]
Should be resolved since #214.
