### ISSUE TITLE
Update desktop action in Actions key although no action has been defined

### ISSUE THREAD

**Issue by RogueScholar** [TheAssassin/AppImageLauncher#171]
I've had a minor issue for the past few months and thought I'd take a few moments this morning to fill you in on it and solicit your thoughts. It relates to the .desktop files AppImageLauncher generates in my ~/.local/share/applications directory and how they're handled by kbuildsycoca5 (Kubuntu 19.04 system, KDE Plasma 5.16.1). Everytime I install or update packages, naturally, a desktop file or two is going to get added/modified/removed and so kbuildsycoca5 gets called automatically in the background to rebuild the launcher menu, which always results in a couple dozen of these entries stuffed in my .xsession-errors file:

`kf5.kservice.services: The desktop file "~/.local/share/applications/appimagekit_67dc1bb89aafede6eb7002d4e5f53f4c-yada-yada-yada.desktop" references the action "Update" but doesn't define it`

Between the fact that I'm a fan of the packaging format and thus have a few dozen AppImages and being admittedly a bit neurotic about my DE launcher menus (lots of tinkering), this has led to needing a cron job to truncate my .xsession-errors file a few times a day. Do you think this is something unique to my setup or is there indeed a snafu in AppImageLauncher? Examining the files in question does indeed show the following line it each of them:

`Actions=Remove;Update;`

...yet all of them have only a `[Desktop Action Remove]` stanza but no `[Desktop Action Update]` stanza. Let me know what you think when you have a minute, if you could.

And while I'm here, may I also ask if you might consider adding a mechanism whereby overrides for some of these desktop file fields could be placed in a configuration file that AppImageLauncher parses when it's messing with them so that we could change the icon name for instance? Quite a few of my AppImages are also packaged as deb/rpm files and thus have icons available in several popular icon themes and it would be great to have a mechanism to apply them.

Thanks again for all the hard work and being so attentive.

**Comment by TheAssassin** [comment]
Interesting catch. `Update` is only available when the AppImage supports AppImageUpdate. Could be we don't insert `Update` conditionally though. Most DEs just ignore missing desktop actions, I guess.

Your feature request has been posted as #90 already, back then we rejected it as it would be too much work to keep things synchronized there. We'd need to exactly tag AppImage files somehow, that'd involve computing some sort of digest and put that into a config file along with the modifications. Names might be viable, icons would be a lot of work.

I think as a feature request, we could pick up this idea again, let me reopen #90 therefore, you can put your use case descriptions there. Your suggestion differs from #90 a bit, so please put your ideas there.

This issue will be used to track the conditional action thing.

**Comment by TheAssassin** [comment]
Has been fixed in the latest master already. I really need to make a release...

**Comment by TheAssassin** [comment]
So I re-checked and noticed that that fix hadn't been published on GitHub yet. I will therefore make a bugfix release to the 1.3.0 I released today soon-ish, which will then contain that fix. Please stay tuned!
