### ISSUE TITLE
Cant run Appimages after computer crash

### ISSUE THREAD

**Issue by Zaldor** [TheAssassin/AppImageLauncher#172]
"Failed to register AppImage in AppImageLauncherFS: could not open map file"
![image](https://user-images.githubusercontent.com/4072338/59977538-a6770700-95d2-11e9-809a-3041bf2528ef.png)

**Comment by TheAssassin** [comment]
Have you rebooted your computer again? That should fix the issue.

A quick fix might be to run this in a terminal: `systemctl --user restart appimagelauncherfs.service`

**Comment by Zaldor** [comment]
i'll try thanks

**Comment by TheAssassin** [comment]
Assuming your problem is fixed. Please reopen if the issue persists.

**Comment by ireggiani** [comment]
Suddenly, the same problem. When opening appimages, I get prompted to integrate or just open. I choose just open, yet I get that error and the file is never opened. It seems like a sudden problem.

**Comment by TheAssassin** [comment]
Has your computer crashed as well? *What* issue do you get? What error message? Please post more information.

**Comment by ireggiani** [comment]
Sorry about that. The error is a pop-up window saying "Failed to register AppImage in AppImageLauncherFS: could not open map file". My computer shut down properly and has not crashed in a long time. It's just when I tried to open a few appimages, I got that error for all of them after being prompted to choose whether to integrate them or just open them. I always chose the latter and a few moments later got that error. I might open a new issue, since I don't have a crash, like the original user. Thanks.

**Comment by TheAssassin** [comment]
Please `ls -al /run/user/$(id -u)/appimagelauncherfs`.

**Comment by ireggiani** [comment]
I get a no such file or directory. I don't know if the "user" in that command is supposed to be my username, but that didn't work either. Trying to launch appimagelauncherfs
 looks it at `/run/user/1000/appimagelauncherfs/` but it cannot be found.

**Comment by TheAssassin** [comment]
`appimagelauncherfs` must be running. Try `systemctl --user start appimagelauncherfs.service`.

**Comment by ireggiani** [comment]
Now I get a proper output from the previous command listing two files called _map_ and _register_. And now I can open AppImages again and they don't crash. Must I add this command somewhere so it starts with the system?

**Comment by TheAssassin** [comment]
It's supposed to be started with the system, the installer sets it up that way. You can call `systemctl --user enable appimagelauncherfs.service` if you want to make sure this is the case.

Furthermore AppImageLauncher itself should internally try to launch the filesystem and issue an error message normally:

https://github.com/TheAssassin/AppImageLauncher/blob/adae2d6d1419a196254250f042afcfb370c79d91/src/ui/main.cpp#L68-L75

I wonder why this doesn't seem to work. I'll have to re-check this, I guess. After all, the process seems to run fine and doesn't crash or anything, so it seems the check is not working.

**Comment by ireggiani** [comment]
When I run the command you suggested,
`systemctl --user enable appimagelauncherfs.service`
then I can open AppImages again through the "execute once" option (the one that does not integrate the AppImage). Thanks. This at least lets me access my AppImages again.
Should I add an order to run this command on start-up?

**Comment by TheAssassin** [comment]
Enabling means "start when system starts". As said, this is what the installer installs and also AppImageLauncher runs both commands whenever it's executed. I'm not sure why this doesn't work on your system. Maybe your systemd installation is broken, I can't tell remotely. The appimagelauncherfs process seems to work fine when you start it manually, so it appears auto starting doesn't work as expected.

As said, I'll re-check the code inside AppImageLauncher and the packages, but I need a clean test system for that. I'll report back here then.
