### ISSUE TITLE
Does removing integrated AppImages Remove the config files?

### ISSUE THREAD

**Issue by blueray453** [TheAssassin/AppImageLauncher#174]
Some AppImages have config files. Ex. Kdenlive (`~/.config/kdenlive-appimage/kdenlive-appimagerc`).

Does removing integrated AppImages, also remove these files alongside the desktop integration.

What about the persistent data. For example, Thunderbird Appimage, will removing integrated AppImages will remove the spam filter settings, mails etc as well?

**Comment by TheAssassin** [comment]
"Removing" an AppImage only deletes desktop integration relevant data, e.g., the app launcher entry definition, icons and MIME data. We don't control what the app writes to your system, and cannot delete that therefore.

**Comment by blueray453** [comment]
Thanks

**Comment by blueray453** [comment]
Thanks
