### ISSUE TITLE
Extraneous launcher entries in KDE Plasma

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#180]
On `neon-devedition-gitunstable-current.iso`, press the SUPER key, then enter `appimage`. You will see entries that are not applications: 

![menu](https://user-images.githubusercontent.com/2480569/60454805-5debc900-9c24-11e9-9d7d-af5fb7d3c59a.png)

Those should be hidden/not show up there.

**Comment by TheAssassin** [comment]
Please complain at KDE, not here. That's the desktop actions. I don't control how they are displayed.

**Comment by probonopd** [comment]
`Hidden=true` maybe?

**Comment by TheAssassin** [comment]
Please don't guess wildly. You can look up the desktop entry spec, you'll see there's just 2 keys available. `Hidden` is not one of them.

**Comment by probonopd** [comment]
Maybe it should be? :100:

**Comment by TheAssassin** [comment]
Please let me know once you added that to the icon spec and then convince every DE of supporting it and when that code is shipped so we can reopen the issue.

**Comment by probonopd** [comment]
Looks more like a KDE bug to me. If those "actions" are supposed to be right-click menu options, they should not be showing up in the launcher when one searches for "AppImage". At least imho.

**Comment by TheAssassin** [comment]
Well, if you type "new tab" and your browser does that, it might come in handy. I don't see the big issue here.

**Comment by kerick91** [comment]
Duplicate of #
