### ISSUE TITLE
Suppress desktop integration scripts in AppImages

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#181]
When AIL is running, desktop integration scripts in AppImages should be suppressed.

![Screenshot_2019-07-03_05-15-47](https://user-images.githubusercontent.com/2480569/60560845-03945a80-9d41-11e9-8c81-f8c95409ad30.png)

https://github.com/AppImage/AppImageSpec/blob/master/draft.md#desktop-integration says

>  The software inside the [AppImage] **MAY** integrate into the desktop environment (e.g., by installing a [.desktop file] into the host system) on the user's behalf. However if it does so, it *SHOULD* ensure to get the explicit permission of the user, e.g., by asking for permission in a GUI window, or by reacting to a command line argument.
> 
> The software inside the [AppImage] **SHOULD NOT** attempt to do desktop integration if at least one of the following conditions are met:
> 
> * A file `$HOME/.local/share/appimagekit/no_desktopintegration` exists on the [target system]
> * A file `/usr/share/appimagekit/no_desktopintegration` exists on the [target system]
> * A file `/etc/appimagekit/no_desktopintegration` exists on the [target system]
> * A process named `appimaged` is running on the system
> * The environment variable `$DESKTOPINTEGRATION` is not empty

**Comment by probonopd** [comment]
So the easiest option would be to rename `appimagelauncherd` to `appimaged` (2.0).

**Comment by TheAssassin** [comment]
We can create `$HOME/.local/share/appimagekit/no_desktopintegration` during the `install` operation.

**Comment by probonopd** [comment]
Yes please. And also take care of it at `uninstall`.

**Comment by azubieta** [comment]
Just a side note on this.
Neither `$HOME/.local/share/` or `usr/share` are the places for configs. Instead we should use `/etc` and `$HOME/.config`.

**Comment by probonopd** [comment]
This is not a config. It is an indication, provided by whatever application claims to manage AppImage desktop integration, that it is doing so.

**Comment by TheAssassin** [comment]
@azubieta can you send a PR that updates AILL's AppRun script to install and uninstall that file for users?

We don't need to install the file system-wide, regular AIL suppresses desktop integration already using the env var.

**Comment by probonopd** [comment]
Thank you.
