### ISSUE TITLE
Update fails if AppImage location is not writeable by user

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#186]
Update fails if the AppImage is stored in `/isodevice/Applications` where the normal user cannot write (but sudo is needed). In those cases the user should be asked for a root password, or (if none is needed) the action should perform. 

For comparison, https://github.com/antony-jr/AppImageUpdater works.

```
me@host:~$ /home/me/.local/lib/appimagelauncher-lite/appimagelauncher-lite.AppImage cli --version
ail-cli version 1.3.1 (git commit b9b466a), built on 2019-07-04 00:23:30 UTC

me@host:~$ cat .config/appimagelauncher.cfg 
[AppImageLauncher]
ask_to_move=false
destination=/isodevice/Applications
enable_daemon=true
```

**Comment by probonopd** [comment]
Left: AILL `update`, right: [AppImageUpdater](https://github.com/antony-jr/AppImageUpdater) by @anthony-jr

![](https://user-images.githubusercontent.com/2480569/60643290-1468cd00-9e22-11e9-9ca8-b8234756f0d0.png)

**Comment by TheAssassin** [comment]
Please refer to the issue in AppImageUpdate. This should be implemented there in the reusable UI, then this tool can benefit from that, too.

**Comment by TheAssassin** [comment]
Please try the latest build, it contains code to relaunch if there's likely a permissions problem.

**Comment by TheAssassin** [comment]
Fixed in https://github.com/TheAssassin/AppImageLauncher/commit/ebf491926dc372a46ffc5af625741c7807c80190.

**Comment by probonopd** [comment]
>  I don't need this

Please keep in mind that I developed AppImageKit and SystemImageKit to be used together. If you were using both (like me) you'd certainly also need this, and think different about its importance. In any case, thank you :+1:
