### ISSUE TITLE
Rename "Remove" to "Delete" and simplify

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#189]
I think I have brought this up earlier, but the checkbox in this dialog is utterly confusing. I as the user select a menu entry to remove an application, then a dialog box comes up asking me whether I really want to remove the application, and then there is a checkbox that again asks me whether the file should really be removed.

In accordance with the project's [design principles](https://github.com/AppImage/AppImageKit/wiki/Design-principles#end-user-experience), We should make this simpler. As the user, I don't understand the word "remove". But I do understand "delete". So use that word, and get rid of the confusing extra checkbox.

![remove](https://user-images.githubusercontent.com/2480569/60643536-e768ea00-9e22-11e9-8ae5-e528012e5283.png)

We never want to get into a state where the user has an AppImage in e.g., `$HOME/Applications` but it is _not_ integrated. Because moving an AppImage there precisely means "please do integrate".

**Comment by probonopd** [comment]
Also, the title of the dialog box is technobabble. "Please confirm -- AppImageLauncher remove"? The Mac would never put something like that into a title. Those are technicalities a normal user won't understand.

> Are you sure you want to delete /isodevice/Applciations/QMediathekVIew-bbd3b30-x86_64.AppImage?" 

would be more understandable.

By the way, if this action actually just moves the file to the trash, then it should be worded "Move to Trash" and no confirmation shall be needed at all.

**Comment by TheAssassin** [comment]
These project "design principles" have just been put online randomly somewhere without any discussion or anything. I don't intend to just accept anything just put online as "truth". That's not how free software projects work. As this is a third party project as of now, these don't apply as of now anyway. Please don't try to enforce any rules this weird way. Put things online for discussion or at least for review and don't just put things online and then advertise them as the only truth that has been a rule for like years...
And please stop constantly belittling users. That's really counterproductive and off-putting.
The claim that any of the above was technobabble is complete nonsense, too.The most technobabble-ish would be the word "system".

"Remove" is standard English. While reading that comment, I was a bit like, "what the heck?"...
Delete, remove, it's very similar, language wise. I mean, after all, the Unix command to "delete files" is `rm`, short for "remove". Only Windows calls this "delete". You could even say "delete" was imprecise as only metadata is "deleted" but the contents don't vanish immediately.
I haven't seen any Linux desktop file manager call this operation "delete". I might be wrong, please show me screenshots then. In accordance with `rm`, I would always name such a window "remove XYZ".

I don't care very much which one is used, though. But it's quite weird to read that "remove" was impossible to understand, while "delete" was. Please take into account my argumentation above.

The window title can be discussed, sure. It's Qt that is to blame here IMO -- you set your application name (that's the part right of the --), then you give the window a title (left part). 

> We never want to get into a state where the user has an AppImage in e.g., $HOME/Applications but it is not integrated. Because moving an AppImage there precisely means "please do integrate".

That's not entirely true, you don't consider a lot of scenarios here. First of all, there's users who do not use appimagelauncherd for the same reason they never used appimaged. Then there's developers who need to be able to remove desktop integration bits only but retain the files. There is a reason the checkbox exists but is checked by default.

I don't see any reason to remove this checkbox. It's needed for development, and by users who switch off appimagelauncherd. The rest can be changed, I'm fine with that, but let's discuss the "remove vs. delete" before changing code there yet.

**Comment by probonopd** [comment]
The design principles have been my design principles for AppImage all the time, I just realized I need to write them down so that everyone knows them.

You have asked me to deprecate appimaged and promote AILL as an official project instead, so we need to work to make AILL conform to the design principles for AppImage.

**Comment by probonopd** [comment]
> I don't care very much which one is used, though. But it's quite weird to read that "remove" was impossible to understand, while "delete" was. Please take into account my argumentation above.

Right-click on a file in Xfce, there is "Delete" in the menu but not "Remmove". "Remove" is not a word the user knows what it does. Especially if you can "Remove" without removing from "the file system". Does "remove" delete the AppImage file or not? Even I am not sure, even now.

I guarantee you with 100% certainty that "mere mortals" don't even begin to understand what this is supposed to do.

**Comment by probonopd** [comment]
If we have to discuss this at length, it may be easier to just remove the whole "Remove" functionality altogether. The user is supposed to use the file manager to manage AppImages anyway, and can move them to the trash there.

**Comment by TheAssassin** [comment]
> "Remove" is not a word the user knows what it does. Especially if you can "Remove" without removing from "the file system". Does "remove" delete the AppImage file or not? Even I am not sure, even now.
> 
> I guarantee you with 100% certainty that "mere mortals" don't even begin to understand what this is supposed to do.

Please show me *any* evidence that this word is more understandable. So far I don't see any real proof, it's just a tendency of some projects to use `delete` instead of `remove`.

It is not going to be removed entirely. It's an important part of the workflow. Don't see why features should be removed as long as they don't get in the users' way. We can improve the wording though, that's probably a good idea.

**Comment by probonopd** [comment]
> Please show me any evidence that this word is more understandable. 

![image](https://user-images.githubusercontent.com/2480569/60767996-3dea5880-a0af-11e9-8a85-89c8c86c0d24.png)

**Comment by probonopd** [comment]
> It is not going to be removed entirely. It's an important part of the workflow.

Why not tell the user to go to the file manager and throw it in the trash there?

**Comment by TheAssassin** [comment]
It's cool to just be able to delete your app from your launcher without having to do anything but open launcher, search for app, remove.

**Comment by TheAssassin** [comment]
Decided to do as suggested and simplify the dialog by removing the checkbox and preferring the word "delete". I can compensate the missing "unintegrate-but-do-not-delete-file" bit with a CLI command.

**Comment by probonopd** [comment]
Thank you so much, makes me like the tool much more now.
