### ISSUE TITLE
Remove fails if AppImage location is not user writeable

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#190]
![removefail](https://user-images.githubusercontent.com/2480569/60643901-12077280-9e24-11e9-8ca5-1b4ef06f0395.png)

If AppImage location is not user writeable, the user should be asked for root credentials if needed. Check https://github.com/antony-jr/AppImageUpdater/blob/ff85721bf285a7483fada6c4aed0ee79884da482/AuthorizationDialog.cc.

**Comment by probonopd** [comment]
What is a "trash bin directory"? 

The sentence is technobabble. "Could not move to Trash" would do.

**Comment by TheAssassin** [comment]
That thing *is* supposed to be "technobabble" (I doubt that word or what it means exists to be honest). This error message is so unlikely to happen it's worth opening issues.

You can't force everything with a crowbar... Why not be helpful and describe how this situation was created instead of complaining about the wording of the issue...

**Comment by probonopd** [comment]
> That thing is supposed to be "technobabble"

Avoiding technobabble is one of the [design principles](https://github.com/AppImage/AppImageKit/wiki/Design-principles#end-user-experience) of the AppImage project.

> This error message is so unlikely to happen it's worth opening issues.

This error is 100% likely when you are using SystemImageKit, which AppImageKit is the "sister project" of.

**Comment by TheAssassin** [comment]
>> You can't force everything with a crowbar... Why not be helpful and describe how this situation was created
> 
> Use SystemImageKit, put applications into /isodevice/Applications (normal users cannot write there).

99.999999999994789991% of all users of AppImage don't care about your personal other projects. That might be a sister project for you, but not for me or anyone else. Therefore this issue can be considered an issue, but doesn't have any priority as it doesn't affect a large user base.

> folders

Folder is a completely wrong and silly way of naming directories. I have been taught not to use that word ever again, therefore I got used to using directory everywhere. Users do know what directories are. Show me some evidence that proves that novices understand folder over directory...

**Comment by probonopd** [comment]
![](https://user-images.githubusercontent.com/2480569/60768037-dda7e680-a0af-11e9-9a7b-238b5b1e9571.png)

"Directory" is a developer word. It comes from UNIX. "Folder" is a user word. It comes from the Macintosh System 1 GUI. In early versions of the Macintosh (before HFS) folders were technically not even based on directories.

**Comment by probonopd** [comment]
Again, I don't want to _discuss_ this stuff.

**Comment by probonopd** [comment]
> Therefore this issue can be considered an issue, but doesn't have any priority as it doesn't affect a large user base.

AppImage is made for THOSE use cases, not for the 99.999999999994789991% of "Linux" users who are "happy" with package managers and the fact that they have only one location where to put applications. Please understand that the __reason__ why there is an AppImage project comes __directly__ from the fact that I wanted to store and keep my applications on removable USB drives. It is not some crude side aspect of the project, it is its very __reason to exist__.

**Comment by TheAssassin** [comment]
Please try the latest build, it contains code to relaunch if there's likely a permissions problem. It isn't rock solid (in terms of detecting permissions errors; there could and should be more checks, I guess; but after all, I don't need this and don't have the time to think this through thoroughly), though.

**Comment by probonopd** [comment]
Going to try `appimagelauncher-lite-2.0.0-alpha-1-travis796.adae2d6-x86_64.AppImage`.

_(Placeholder for results)_

**Comment by probonopd** [comment]
Blocked by https://github.com/TheAssassin/AppImageLauncher/issues/240.

**Comment by probonopd** [comment]
Now getting

![dialog](https://user-images.githubusercontent.com/2480569/65392444-9652fd00-dd64-11e9-8604-bca4ec43f8ec.png)

The language of this dialog is written from a programmer's perspective and is only understandable by programmers, not by mere mortals.

I wanted to delete something, not "launch" or "relaunch" something.

So an appropriate wording might be: 

> File /isodevice/Applications/Firefox-67.0.4.glibc2.4-x86_64.AppImage is owned by another user: root
>
> __Delete anyway?__

**Comment by TheAssassin** [comment]
This thingy is an automatic message relaunching the *entire* process with appropriate permissions. It's the easiest and most portable solution I could come up without having to implement some crappy subprocessing with `sudo rm` or something, that'd be a lot more annoying to handle.

**Comment by probonopd** [comment]
Again, _I_ know what is going on. But a normal _user_ just wants to delete an app. The user does not know what a _process_ is, or that one is needed to delete an application. When doing GUI, let's always think from the user's side, not from the developer's.

I've designed a fair share of consumer IT products aimed at nontechnical people, so believe me ;)

**Comment by TheAssassin** [comment]
I understand this, but what you want is a *lot* of work to implement for a really small user base. My plan is to change this eventually, but keep it as-is to finally be able to advance to 2.0.0. Could you live with this for the next time? Otherwise the feature will be dropped again completely and I'll release 2.0.0 without it. But I think as it is currently it already has some use to people.

After all, your entire argument is based on "normal users". But "normal users" will never get into a situation where they'd have to deal with this dialog if they use AppImageLauncher normally. Power users like you, as you say, know what's going on. I think this is good enough until someone creates a better alternative, or regular users have to face this kind of dialog more often.

**Comment by probonopd** [comment]
> I understand this, but what you want is a lot of work to implement for a really small user base. 

I'm merely suggesting a different wording, a cosmetic change.

**Comment by TheAssassin** [comment]
It's not a simple cosmetic change you're requesting. You want a different kind of dialog.

This dialog is automatically displayed and is application agnostic. As is it also works for the update helper. What you want however is something *much* more integrated. What we have doesn't provide that.

You haven't replied to my other question.

**Comment by probonopd** [comment]
> Could you live with this for the next time? Otherwise the feature will be dropped again completely and I'll release 2.0.0 without it.

"The feature" as in: Deleting AppImages from the menu? Yes, I could live without that for the next time. Users can use the file manager to do these things. (People delete normal documents in the file manager, too.)

**Comment by TheAssassin** [comment]
No. The feature as in "ask whether to re-exec with pkexec".

> Users can use the file manager to do these things. (People delete normal documents in the file manager, too.)

That's not the UX of AppImageLauncher. This is never going to be removed, in fact it's one of the most popular features. Documents aren't AppImages.

**Comment by TheAssassin** [comment]
After thinking about this for quite a while, I decided it might be easiest to remove the "ask whether to relaunch" dialog. The regular user won't reject this, right? They can still press "cancel" in the message displayed by `gksu[do]`.

However, I found a somewhat simple way to implement the custom message. I'll implement that first.

**Comment by TheAssassin** [comment]
![screenshot_2019-10-12_01-36-01](https://user-images.githubusercontent.com/4503202/66690518-cf5dfd80-ec90-11e9-970d-1121423f8f2f.png)

I had to re-read your post with the initial suggestion. After all, all that'd be needed was to change the message displayed in the second line. That was really easy to implement.

**Comment by TheAssassin** [comment]
Fixed in https://github.com/TheAssassin/AppImageLauncher/commit/ebf491926dc372a46ffc5af625741c7807c80190.

**Comment by probonopd** [comment]
Much better now!
