### ISSUE TITLE
Bundle Qt Gtk theme in AILL AppImage

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#199]
Bundle Qt Gtk theme in AILL AppImage so that it looks native e.g., on Xfce and Gnome.

https://github.com/TheAssassin/AppImageLauncher/edit/master/travis/build-lite.sh should build

```
plugins/styles/libqgtk2style.so
plugins/platformthemes/libqgtk2.so
```

e.g., like this:

```
apt-get update
apt-get -y install libgtk2.0-dev
git clone http://code.qt.io/qt/qtstyleplugins.git
cd qtstyleplugins
qmake # be sure to use the one from the Qt installation you are using for the application
make -j$(nproc)
sudo make install 
cd -
```

Then,

```
plugins/styles/libqgtk2style.so
plugins/platformthemes/libqgtk2.so
```
need to be deployed into the AppImage.

**Comment by TheAssassin** [comment]
This requires a lot of additional work, since we'd need to add yet another build environment, just for AIL Lite, which, as of now, is just a byproduct of the other builds.

**Comment by probonopd** [comment]
Yes, it does need this additional work because without it, it looks "alien" and hence violates the AppImage Design Principles.

> AIL Lite, which, as of now, is just a byproduct of the other builds.

AILL is the one which you want to replace `appimaged` with, right? So it needs to be top-notch.

**Comment by TheAssassin** [comment]
> AppImage design principles

Just to clarify, that's nothing I ever signed off nor ever had to do with, so noone is bound to that. That's how free software projects work: you collaborate on things, that makes sure everyone's on the same line. Trying to force people to follow the own line doesn't work, you need to justify your stuff with arguments. Otherwise, contributors are for sure going to jump off or just do it the way they like and with proper governance.

**Comment by probonopd** [comment]
The AppImage design principles had been there since day 1 of the project a decade ago, they just weren't written down. Of course they only apply to the repositories within https://github.com/AppImage but I was under the impression that you were interested in eventually moving this repository there.

**Comment by TheAssassin** [comment]
Again:

> Trying to force people to follow the own line doesn't work, you need to justify your stuff with arguments. Otherwise, contributors are for sure going to jump off or just do it the way they like and with proper governance.

This "boss-like" behavior doesn't work. You should rethink whether you really want to act like that...

**Comment by probonopd** [comment]
I think this is getting off-topic. To me it is self-evident that AppImages should look and feel as native as possible (especially those that we put out ourselves), and bundling the Qt Gtk theme achieves that e.g., for Xfce systems.

**Comment by TheAssassin** [comment]
I can only reiterate that it's not the content, it's the methods...

**Comment by TheAssassin** [comment]
![screenshot_2019-07-30_22-33-02](https://user-images.githubusercontent.com/4503202/62163176-1edf8f00-b31a-11e9-83be-e3ada7945f35.png)

I don't think that looks great, all the icons are missing. Please advise.

**Comment by probonopd** [comment]
I can confirm that it is working for me on Xubuntu 18.04 but icons are missing.

**Comment by TheAssassin** [comment]
Well, you brought up the idea of using these themes. I think this is worse than before. Please find out how to fix the icons, or we will have to revert. I'd rather take something that looks not-*as*-native than something like *that*.

**Comment by probonopd** [comment]
The icons are not that important imho. Fonts and colors are native now, which was the goal.

**Comment by probonopd** [comment]
Can we have the buttons use no icons?

**Comment by TheAssassin** [comment]
No. It's Qt (and also all other tools) standard to have icons there. Icons are *really* important.

You always tell about looking "native". "Native look" includes standard icons *and* also right button sizes. The size of that "choose path" button is way too small, compared to other tools.

**Comment by probonopd** [comment]
Fwiw, this is how it looks on KDE neon developer:

![](https://user-images.githubusercontent.com/2480569/62208304-f1c8c600-b385-11e9-808a-bd7d9a269d13.png)

**Comment by probonopd** [comment]
I like how the order of "OK" and "Cancel" adopt to the system being run :+1:

**Comment by azubieta** [comment]
I'm doing more tests, it looks good on ubuntu 18.04

**Comment by azubieta** [comment]
I'm doing more tests, it looks good on ubuntu 18.04

> I can confirm that it is working for me on Xubuntu 18.04 but icons are missing.

I'm looking into xubuntu icon theme and can confirm that it's incomplete. The 'gtk-ok' and 'gtk-cancel' are un-official defaults. What can we do? Set custom icons this will solve the missing icons issue but will prevent the app from using the system theme icons.

**Comment by probonopd** [comment]
>  The 'gtk-ok' and 'gtk-cancel' are un-official defaults.

Smells like yet another [Desktop Linux Platform Issue](https://gitlab.com/probono/platformissues)...?

What we cannot be sure to find on all target systems we need to bundle privately.

**Comment by azubieta** [comment]
> Smells like yet another Desktop Linux Platform Issue...?

It is. Ok, I'll embed custom icons and make them default.

**Comment by TheAssassin** [comment]
I hate adding more complexity just for this really minor "issue"...

**Comment by azubieta** [comment]
I thought that I had found a beam of hope, while reading this "https://openapplibrary.org/dev-tutorials/qt-icon-themes". I crafted a custom icon theme and add it to the Qt app. It works perfectly with the qt style but the qt-gtk style ignores it :(

**Comment by azubieta** [comment]
After that I tried to fix the set the icons fixed using the qt resources and this is the result: 
![appimagelaunchersettings](https://user-images.githubusercontent.com/1138094/62335879-3d1cca80-b493-11e9-9028-902f54054e2b.png)

The qt-gtk-style is missing this feature and only support icons coming from the system theme. The only option I see left here is installing such icons. But that will attempt against the AppImage principle of not altering the target system.

The correct solution in this scenario is to fix qt-gtk-style to respect the Qt settings regarding icons and themes. But that is totally out of the AppImage project.

IMHO, having a native gtk look is just a nice to have feature. Not something critical. The qt style provides already our user all they need.

**Comment by TheAssassin** [comment]
After having invested 2 working days in this, the point has come to stop this project and focus on more relevant things. It's not worth the effort at all. @probonopd you should not recommend this weird Qt Gtk+ theme to anyone. There must be a reason it's mostly undocumented and not included anywhere, right?

**Comment by probonopd** [comment]
I agree that we should not have to spend days on something as simple as making a Qt GUI look native. As for AILL, I'd prefer it to have no GUI at all anyway.

**Comment by Lvaskz** [comment]
> ![appimagelaunchersettings](https://user-images.githubusercontent.com/1138094/62335879-3d1cca80-b493-11e9-9028-902f54054e2b.png)


Hi there I don't know if this is related about the issue, but linuxmint 19.2-19.1 has the interface some broken. I can not select the options available, see:

![Interface broken linuxmint](https://user-images.githubusercontent.com/29207169/62545110-4785ee00-b81e-11e9-9f51-a4ba95c51075.png)

If is not related I will open new one.
By the way, linuxmint 19.2 is a new fresh installation.
64 bits
Cinnamon desktop

**Comment by TheAssassin** [comment]
Nothing has changed there, this is IMO unrelated.

**Comment by Lvaskz** [comment]
So I will open new one.

**Comment by probonopd** [comment]
Desktop Linux is [such a mess](https://media.ccc.de/v/ASG2018-174-2018_desktop_linux_platform_issues), really.

**Comment by TheAssassin** [comment]
Yep. Therefore @azubieta and I tend to forcing a single style on all platforms, since that then at least works consistently. Functionality is the most important design goal after all.

**Comment by probonopd** [comment]
Uh, which means it will be "alien" almost everywhere? (Like a Java app)

**Comment by azubieta** [comment]
Sadly, that's the only way we have so far on ensuring that UI will be fully functional.

**Comment by probonopd** [comment]
KDE and GNOME are hosting the Linux App Summit (LAS) with topics such as "Platform" and "App Ecosystem". PLEASE submit a talk to LAS 2019 until 2019-08-31 explaining this issue and what the desktops could do to remove this mess:

https://linuxappsummit.org/cfp/

**Comment by azubieta** [comment]
I already did it, I would love to have you as partner in the talks. Would you be able to attend?
