### ISSUE TITLE
PPA Build for Ubuntu

### ISSUE THREAD

**Issue by shoogle** [TheAssassin/AppImageLauncher#201]
Would you like me to create a Launchpad PPA build for Ubuntu? I've these up in the past for MuseScore so it shouldn't be too difficult, though I can't promise anything soon.

It's a fully automated process. Basically Launchpad [pulls in the latest GitHub code](https://help.launchpad.net/Code/Git#Mirroring_repositories_from_other_sites) every few hours and [builds it once per day](https://help.launchpad.net/Packaging/SourceBuilds) according to a [recipe](https://help.launchpad.net/Packaging/SourceBuilds/GettingStarted). Meanwhile users get automatic updates every day, so you would find out about issues very quickly, and be able to release fixes just as fast.

If people complain about the constant updates then you can tell Launchpad to build a non-master branch which you bring up-to-date with master once per week, or once per month, etc.

**Comment by TheAssassin** [comment]
I wouldn't mind if you created a PPA. There's packaging available in Debian which you can make use of.

Regarding changes, can't you just say "use the latest stable GitHub release"? Do we really have to maintain a branch? That's work that is likely to be forgotten, and would have to be automated.

**Comment by TheAssassin** [comment]
Any progress on this?

**Comment by shoogle** [comment]
Not yet, sorry. I might have time to look at this later in the month, though September is more likely. Feel free to go down a different route in the meantime if you prefer.

**Comment by TheAssassin** [comment]
Ah nevermind, there's no plans right now to build anything. Just wanted to hear whether there was something to review or link to already. Glad you're willing to help, after all!

**Comment by Xerus2000** [comment]
I'd like having a ppa, the version in Ubuntu's repos is obviously outdated, so I guess i have to manually update it now, which is rather annoying.

**Comment by Cervoxx** [comment]
Any news on this?

**Comment by shoogle** [comment]
I managed to set up a PPA build for Ubuntu 19.04 Disco Dingo at https://code.launchpad.net/~shoogle/+archive/ubuntu/appimagelauncher-daily.

19.04 is the only Ubuntu recent enough to have libappimage in the default repositories. I hope to get it working for older distros too, but that will probably involve setting up a separate PPA build for libappimage itself. Same goes for AppImageUpdate.

If you want to try it yourself but don't want to risk your machine, the easiest way is to download an [19.04 ISO](http://releases.ubuntu.com/19.04/) and open it in GNOME Boxes. This is a super-easy method to create a virtual machine. (Turn off the "express install" option and do manual setup, but you can leave all other preferences at their defaults. Once the VM is running, click "Try Ubuntu" - no need to install the OS within the VM.)

**Comment by TheAssassin** [comment]
Nice work. Please consider adding a 19.10 build as well.

**Comment by shoogle** [comment]
@TheAssassin, PPA has been updated with a 19.10 build.

I looked into enabling PPA builds for earlier Ubuntu versions. Sadly this is not possible because they are missing libsquashfuse-dev.

**Comment by 2635599** [comment]
so where is the ppa cause personally i'd like to give it a run. be nice to have appimagelauncher autoupdate.

**Comment by TheAssassin** [comment]
> https://github.com/TheAssassin/AppImageLauncher/issues/201#issuecomment-552309122

**Comment by mcorossigo** [comment]
> I managed to set up a PPA build for Ubuntu 19.04 Disco Dingo at code.launchpad.net/~shoogle/+archive/ubuntu/appimagelauncher-daily.

This is great. Any chance you can make one for the stable releases (not daily/continous)?

**Comment by shoogle** [comment]
@mcorossigo, possibly. Releases are quite regular in this project and I personally don't have time to keep checking for them and manually uploading them to the PPA. However it is possible to automate the task.

@TheAssassin, could you maintain a `stable` branch that always points to the latest release? That would enable me to tell Launchpad to track this branch instead of `master`. (Unfortunately Launchpad can't track releases on its own.)

Let's assume you have just created a new tagged release on the `master` branch. All you have to do to bring `stable` up-to-date is this:

```bash
git checkout stable
git rebase master
git push origin stable
```

You could add that to a script you use for releases or something and then its no extra work for you either.

**Comment by TheAssassin** [comment]
Can't you just say "dear Launchpad, please use the latest release"? I could maintain such a branch, sure, but I want to make sure it's absolutely required.

**Comment by shoogle** [comment]
@TheAssassin, it's required, unfortunately, unless you want to use Travis CI to trigger the builds, which involves duplicating certain Launchpad features here on GitHub.

The build happens in three stages using a separate worker VM for each stage:

__1. Code imported__ from GitHub (creates a [mirror Git repository](https://code.launchpad.net/appimagelauncher) on Launchpad).
__2. [Recipe](https://code.launchpad.net/~shoogle/+recipe/appimagelauncher-daily) creates DEB source package__ (adds debian subfolder and bundles everything into a tarball).
__3. [PPA](https://code.launchpad.net/~shoogle/+archive/ubuntu/appimagelauncher-daily) builds DEB binary package__ (unpacks tarball and runs code inside).

The worker VMs for stages 2 and 3 do not have internet access, so they can only use what they are given by the previous stage, plus some configuration settings on the Lauchpad control panel.

__Stage 1__ has internet access, but it is only given a repository URL as input. I can't make it do anything other than clone the specified repository, but clone includes all branches and tags.

__Stage 2__ is where we say which branch or tag we want to use for the build. Unfortunately this stage is controlled via a limited [recipe syntax](https://help.launchpad.net/Packaging/SourceBuilds/Recipes), and is no way to say "use the latest tag"; you have to give a specific name. Even if I could do that, the latest tag in this repository is always "continuous", which is not helpful here.

__Stage 3__ is the only stage that can run arbitrary Bash commands, but it uses a tarball, not a git repository, so there is no opportunity to switch to a different branch or tag than the one given in Stage 2.

In theory it should be possible to perform stages 1 and 2 on Travis CI, which would then upload the source package to the Launchpad PPA for stage 3. Naturally, this involves extra work:

- writing the code necessary to do this
- setting up signing keys for Launchpad

However, there is actually a __big advantage__ to doing it this way: you get to include anything you like in the source package that gets uploaded to Launchpad. This means you can build dependencies yourself rather than relying on whatever is in the Ubuntu repositories, which makes it easier to support older systems. 

There's no doubt that this involves more work though, so I think it is better (certainly easier) to stick to using Launchpad recipies for the time being. That's all setup and ready to go, and only requires you run one extra command each time you create a new tagged release.

**Comment by TheAssassin** [comment]
I'll start maintaining a new branch `stable` by hand for now. If I should forget to update it, please feel free to send a PR or just inform me in some way. I might be automating this at some point, but for now it's not too much work.

**Comment by mcorossigo** [comment]
> Stage 2 is where we say which branch or tag we want to use for the build. Unfortunately this stage is controlled via a limited recipe syntax, and is no way to say "use the latest tag"; you have to give a specific name. Even if I could do that, the latest tag in this repository is always "continuous", which is not helpful here.

While I am not a Launchpad expert, I think this may not be true.

Quoting https://help.launchpad.net/Packaging/SourceBuilds/Recipes

> For git, a revision specifier may be anything that you could pass to git rev-parse in a clone of the given repository.

And according to https://git-scm.com/docs/git-rev-parse `git rev-parse` is pretty versatile. In fact running `git rev-parse :/Release` (using this syntax: https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt-emlttextgtemegemfixnastybugem) return `4f7bc8e9fae72005935143d255b83a7ee6572f4a` which is the correct ref for v2.0.3

So, the always working revision could be `:/Release`
Don't know if this can help, just my 2 cents.

**Comment by shoogle** [comment]
@mcorossigo, interesting find, thanks!

I tested it now and it seems to work, but I'm not sure how reliable it will be once new commits start coming in.

In theory the build will only happen on days where the code actually changes. If we track the `stable` branch then hopefully that means no new builds until the next release. If we track "the latest commit with message starting 'Release'", as your code does, then it is possible that the same commit will get rebuilt everyday from now until the next version. Besides the wasted resources, each rebuild could trigger a new update for users via `apt`, which is not what we want to happen (until something actually changes).

I'll leave it using your method for the next few days so we can see what happens as new commits come in.

**Comment by mcorossigo** [comment]
@shoogle Sorry if I'm getting something wrong, but now new commits have been made on master and even a new continous release and according to https://code.launchpad.net/~shoogle/+archive/ubuntu/appimagelauncher-daily/+builds?build_text=&build_state=all no new build have been triggered.

If everything sounds right to you, can you create an appimagelauncher PPA with the `:/Release` method and restore appimagelauncher-daily as it was before?

**Comment by shoogle** [comment]
PPA builds are now here:

- Daily PPA - https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/daily
- Stable PPA - https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable

I created a new Lauchpad team called [AppImageLauncher Maintainers](https://launchpad.net/~appimagelauncher-team) to manage the PPA. @TheAssassin and the current Debian / Ubuntu maintainers are welcome to join if they wish (CC. @ScarlettGatelyMoore).

**Comment by shoogle** [comment]
@mcorossigo, `:/Release` was a good suggestion. I was all set to use it, but then it occured to me that it would include beta releases, which is probably not something we want in the stable PPA, and the regex to prevent this happening is non-trivial. `git rev-parse` doesn't like `^` or `$`, and Lauchpad's recipe syntax is unlikely to accept newlines or spaces. You'd probably end up with something like this:

```
git rev-parse :/Release.v?[0-9]+\.[0-9]+\.[0-9]+[^ -]
```

This is liable to break if the commit message format changes in future.

I decided to stick with tracking the `stable` branch for now, but this could be changed in future depending on what @TheAssassin wants to do.

**Comment by shoogle** [comment]
@TheAssassin, `stable` branch needs updating.

```bash
git checkout master
git push origin master:stable
```

(Assuming latest commit on `master` is a release commit.)

**Comment by zilti** [comment]
An alternative would be to just build packages for all distributions on build.opensuse.org including repositories, instead of having half a dozen places where some build scripts get triggered.

**Comment by Jimbolino** [comment]
https://github.com/TheAssassin/AppImageLauncher/commits/v2.1.0 -> last commit Dec 1, 2019
https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable -> 2019-11-25

is stable not updating, or am i missing something?

**Comment by shoogle** [comment]
Stable branch is indeed some way behind the latest release
https://github.com/TheAssassin/AppImageLauncher/tree/stable

**Comment by Akuukis** [comment]
@shoogle Running on Ubuntu 20.04
```
Err:2 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
...
E: The repository 'http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu focal Release' does not have a Release file.
```

Would you please add for Ubuntu 20.04 also?

**Comment by TheAssassin** [comment]
There already has been an issue for this, see #319. @shoogle can you please double check you added focal?

**Comment by shoogle** [comment]
Done, thanks.

Closing this issue since we now have a PPA. Feel free to tag me in future issues relating to the PPA.

**Comment by shoogle** [comment]
@TheAssassin, somebody with your username asked to join the PPA team on Launchpad. Was this you?

**Comment by TheAssassin** [comment]
Yes. After some fiddling I managed to recover this account. I figured I could potentially help you maintain this PPA a bit.

**Comment by shoogle** [comment]
@TheAssassin, OK cool! I've given you admin rights so feel free to make changes to build scripts etc. as you see fit. I'll be on IRC in case you have any questions for me, such as why have I done things a certain way, etc.
