### ISSUE TITLE
[Settings] add tooltips with extended explanations

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#202]
Some people might have trouble to understand what an "auto integration daemon" for instance is. We should add tooltips explaining the single options.

**Comment by azubieta** [comment]
Something like this ?
![Screenshot_20190715_192809](https://user-images.githubusercontent.com/1138094/61257466-a47f0e80-a760-11e9-8de6-3bc6d4fbd531.png)

**Comment by TheAssassin** [comment]
Solved satisfyingly in #208. We could add more in the future.
