### ISSUE TITLE
Messing existing AppImages after uninstalling

### ISSUE THREAD

**Issue by Javanmardi** [TheAssassin/AppImageLauncher#205]
Removing AppImageLauncher from system with help of _apt_ (`sudo apt purge appimagelauncher`) caused some errors.
For example OCS-Store won't run anymore.

I saw same issues. But none helped. Also I did lots of reboots.
Is it related to FUSE or something else.

https://github.com/TheAssassin/AppImageLauncher/issues/86
https://github.com/TheAssassin/AppImageLauncher/issues/48

**Comment by TheAssassin** [comment]
"some errors" isn't quite useful for debugging. Can you please provide some more precise description of your issues? What OS do you use?

AppImageLauncher does not edit AppImage files, so these kinds of issues are quite surprising to hear about.

**Comment by Javanmardi** [comment]
I'm on Ubuntu 18.04.2 with the lastest update.
It's also kind of surprised me as well.
True, it won't affect them, is there any kind of report I can take?
After purging this app, I installed the AppImage Daemon but it could not show AppImage thumbnails. So the lastest snapshot saved the day. But I can turn over though.

**Comment by TheAssassin** [comment]
Which version have you had installed?

**Comment by Javanmardi** [comment]
appimagelauncher_1.3.1-travis612.git20190622.91697b4.bionic_amd64.deb

**Comment by TheAssassin** [comment]
I still miss information on what the exact issue you're facing is? Can you still run AppImages? What's the big issue that brought you here?

**Comment by Javanmardi** [comment]
Let me be honest, I have installed and removed this app and appimaged three times for each simultaneously.
I mean install both remove both reboot and so.
But it can't be appimaged. It's just an AppImage.
Also I removed any remaining file from ~/.cache.

**Comment by Javanmardi** [comment]
They won't open anymore except subsurface and AppImageUpdate.
Also I don't have lots of them (2 out of 5 are working).
I download and run a couple of more tomorrow to get more results or an answer.

**Comment by TheAssassin** [comment]
Can you please call the AppImages from a terminal and watch for strange output from the single runs? Please post the result (of course, after anonymizing any data from you) here in this issue, and I'll try to help you, even if it might not be an AppImageLauncher issue.

**Comment by Javanmardi** [comment]
Thanks, such a busy week! Anyway!
This is what I did
```
$ ls
AppImageUpdate-x86_64.AppImage      ocs-store-4.1.1-1-x86_64.AppImage
Inviska_Rename-9.0-x86_64.AppImage
$ chmod a+x ocs-store-4.1.1-1-x86_64.AppImage

$ ./ocs-store-4.1.1-1-x86_64.AppImage
bash: ./ocs-store-4.1.1-1-x86_64.AppImage: No such file or directory

```
I kind of solved this problem. But I don't know exactly which was what I did.

- First, I searched root directory and I remove any files containing the string `appimagelauncher`
- Second, in the `/home` folder, any files containing the string `appimagekit` and `appimage` was removed. Most of them existed in `~/.local/share`.
- Third, I tried to extract one of the AppImage files and run it, surprisingly it was running great<sup> [source](https://docs.appimage.org/user-guide/run-appimages.html)</sup>.
- And at last I downloaded and changed the name of one of the unsupported AppImages. And it ran flawlessly.

**Comment by TheAssassin** [comment]
The issue "No such file or directory" is most likely related to the magic bytes we embed to mark executables as AppImages. Can you please try the following bad hack and see if the AppImages run again?

```
sed -i 's|AI\x02|\x00\x00\x00|' ocs-store*.AppImage

**Comment by Javanmardi** [comment]
Sorry, I didn't respond any sooner. Lots to do in no time!
Anyway

It's not running with this error:

```
~/Applications$ ls 
AppImageUpdate-x86_64.AppImage      ocs-store-4.1.1-1-x86_64.AppImage
Inviska_Rename-9.0-x86_64.AppImage

~/Applications$ sed -i 's|AI\x02|\x00\x00\x00|' ocs-store-4.1.1-1-x86_64.AppImage

~/Applications$ ./ocs-store-4.1.1-1-x86_64.AppImage
/tmp/.mount_ocs-stALWncs/AppRun: line 22:  7543 Bus error               (core dumped) ${PREFIX}/usr/lib/ocs-store-linux-x64/ocs-store

```

My personal suggestion is to download any AppImage again.
You see after downloading it again:

```

~/Applications$ ./ocs-store-4.1.1-1-x86_64.AppImage
[ocs-manager] Websocket server started at: "ws://127.0.0.1:36001"

```
And it's trying to connect to its server (I had no internet connection so nothing happened after but main window opened).

**Comment by TheAssassin** [comment]
Well, I clearly can't see any relation to AppImageLauncher, no proven facts (like hash sums before/after), can't be reproduced, so I don't know how to help you there...

**Comment by TheAssassin** [comment]
Cannot reproduce this issue. It seems you resolved the issue by re-downloading the AppImages. Let's call it a day and hope this won't happen again.

We can reopen this if this ever occurs again.

**Comment by chorca** [comment]
Just had this happen to me, Ubuntu 18.04.3, latest release of AppImageLauncher (2.11).
Installed AppImageLauncher via deb, installed a program, found it wouldn't work (Etcher, due to previous root bug) so uninstalled the AppImage and then removed AppImageLauncher via `apt remove appimagelauncher`.
After doing that, my existing appimages (which had not been installed or integrated) failed to run.
I attempted to logout and log back in, but had the same issue, even images which were freshly downloaded after this.
Rebooting the system fixed it, so wondering if there is something left running during the deb uninstall that is preventing appimages from being able to execute?
I can play around with this a little more and see if a process or something is still running.

**Comment by TheAssassin** [comment]
@chorca can you please check whether your issue is related to #308?

**Comment by chorca** [comment]
I'm unsure if it's related, as I'm not compiling/moving these images around, but it appears that the uninstall script in the deb package isn't properly shutting down the software during removal:

```
$ sudo apt remove appimagelauncher 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  appimagelauncher
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 48.9 MB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 208277 files and directories currently installed.)
Removing appimagelauncher (2.1.1-travis931~f6d5926+bionic) ...
Removing AppImageLauncher as interpreter for AppImages
+ systemctl restart systemd-binfmt
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for shared-mime-info (1.9-2) ...
Unknown media type in type 'chemical/x-alchemy'
[...]
Unknown media type in type 'chemical/x-xyz'
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
$ ps ax|grep image
 4052 ?        Ssl    0:00 /usr/bin/appimagelauncherd
 4560 ?        Ssl    0:00 /usr/bin/appimagelauncherfs
 5030 pts/0    S+     0:00 grep --color=auto image
$ ./OpenSCAD-x86_64.AppImage 
bash: ./OpenSCAD-x86_64.AppImage: No such file or directory
```
I'd assume that during an uninstall the removal scripts in the deb would shutdown the processes and remove any configs preventing an appimage from running, but not sure that this is the case.
I can do some more troubleshooting if there's anything else you'd like me to try with it.

**Comment by Javanmardi** [comment]
@chorca I did removed everything related to AppImageLauncher from `~/.cache` and `~/.locale`.
I guess you should do so. And check the SHA256 of remaining AppImages with a newly downloaded one (install `digest` on `nautilus` with this command: `sudo apt install nautilus-gtkhash`; it will make everything easier). Mine was damaged somehow which I am not sure if it was because of this piece of program or something else happened.

**Comment by TheAssassin** [comment]
Those services are configured as `systemd` user services. You can (permanently) stop them by executing `systemd --user stop appimagelauncher[fs,d]` in a terminal. Automating this step in the uninstall scripts is not easy, hence we recommend to reboot after uninstalling, it's the cleanest way and ensures everything's working as before.

**Comment by chorca** [comment]
Cool, I don't think that's too much to ask.
It might be helpful to include a comment during removal that a reboot may be necessary to finish removal or if encountering issues with AppImages afterwards?

**Comment by TheAssassin** [comment]
That's a good idea, I'll add a comment to the uninstallation script. Just for the sake of completeness, the main problem is not that the services keep running, but `binfmt_misc` which cannot easily be reset (i.e., to make it no longer call AppImages through AppImageLauncher). A reboot is really the cleanest way.

**Comment by TheAssassin** [comment]
I pushed two commits to improve the situation. The first one introduces a visual warning that a reboot is required which will be printed to the console during the uninstallation.

Then I remembered there was that "reboot required" message shown by some packages. I found that there is a package called `update-notifier-common` which provides a script you can call from a package's uninstallation script which will inform the system that a reboot is required. I've implemented this as well.

If you have further suggestions that improve the UX (even small ones like these!), please don't hesitate to open new issues. We shouldn't discuss more off-topic stuff here.

**Comment by Javanmardi** [comment]
@TheAssassin Yes, I agree. @chorca at least log out if you are using your OS as a server. Then clean all the redundancies (a bunch of file with this name `appimagekit` on your `/home` folder) and you are good to go.

**Comment by TheAssassin** [comment]
> @TheAssassin Yes, I agree. @chorca at least log out if you are using your OS as a server. Then clean all the redundancies (a bunch of file with this name appimagekit on your /home folder) and you are good to go.

That only works in Ubuntu/Debian as far as I can tell, that's the problem. Launching AppImages will, on many systems, end in some error message that states that `/usr/bin/AppImageLauncher` couldn't be found. That's because Ubuntu/Debian do not use `systemd-binfmt` or at least handle it in a better way.

The files in `~/.local/share/...` you mention won't hurt by the way. It's at most a few MiB of deprecated data. The desktop files will only remain valid until the AppImage they belong to goes away, so that's also less of an issue.

Is there a need for some proper "remove all data you created" thingy (ideally can be called from the settings) to allow users to *completely* remove most if not all traces?

**Comment by Javanmardi** [comment]
@TheAssassin I believe before I introduced to this piece of software there was a daemon which we could have installed locally and the name was I guess `appimaged.AppImage`. Anyway, after I wanted to uninstall it [obviously] I had to run the uninstall command in Terminal but I remember it warned me to run a command and it easily searched and removed any file in `/home` folder made by this daemon.  I could have just write the command but I stuck with Windows for a while but it would do the charm.
Cheers! ;)

**Comment by DrecDroid** [comment]
Restarting solves the problem

**Comment by AlpSha** [comment]
Finally found the solution here—rebooting fixes the issue. That said, this software was incredibly frustrating to deal with. It created duplicate desktop entries, constant popups, and after uninstalling, none of my AppImages worked anymore. I genuinely thought I had to reinstall my system just to get back to normal. Please, at the very least, show a clear warning that a reboot is required after uninstalling. I swore a lot during this mess—just so you know.

**Comment by TheAssassin** [comment]
Both `apt` and `dnf` etc. (RPM) show a warning that you need to reboot and create a file that should cause your desktop to prompt you to reboot. I don't know what else you would expect to see.
