### ISSUE TITLE
mumble icon missing from appmenu

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#209]
Mumble appimage after integrate it with appimagelauncher has no icon from appmenu 
ubuntu 18.04 , gnome desktop 3.28, 64 bits 
![Captura de pantalla de 2019-07-17 22-26-54](https://user-images.githubusercontent.com/29207169/61429181-7b868700-a8e2-11e9-9a6a-1f5f38feaef1.png)

https://github.com/mumble-voip/mumble/releases/download/continuous/Mumble-467cbd9-x86_64.AppImage

ubuntu 18.04
gnome 3.28
64 bits
I am using this appimagelauncher_1.3.1-travis692.git20190710.6ce8449.bionic_amd64.deb

**Comment by TheAssassin** [comment]
Not an AIL issue:

```
appimagelint.icon_check[5164] [INFO] Extracting icon name from desktop file: /tmp/.mount_MumbledmCq3I/mumble.desktop
appimagelint.icon_check[5164] [INFO] Checking resolution of icon: /tmp/.mount_MumbledmCq3I/mumble.svg
appimagelint.icon_check[5164] [INFO] [✔] Valid icon in AppDir root
appimagelint.icon_check[5164] [INFO] Checking resolution of icon: /tmp/.mount_MumbledmCq3I/.DirIcon
appimagelint.icon_check[5164] [INFO] [✔] Valid icon file in .DirIcon
appimagelint.icon_check[5164] [INFO] Checking resolution of icon: /tmp/.mount_MumbledmCq3I/usr/share/icons/scalable/apps/mumble.svg
appimagelint.icon_check[5164] [WARNING] Icon scalable/apps/mumble.svg is in non-standard location
appimagelint.icon_check[5164] [WARNING] Could not find icon resolution at expected position in path, trying to guess from entire path
appimagelint.icon_check[5164] [WARNING] no other icons found
appimagelint.icon_check[5164] [INFO] [✖] Other integration icons valid
```

Please report the issue upstream.

**Comment by probonopd** [comment]
What is wrong exactly, and what exactly would upstream need to do to fix it?

**Comment by probonopd** [comment]
Move `usr/share/icons/scalable/apps/mumble.svg` to `usr/share/icons/hicolor/scalable/apps/mumble.svg`?

**Comment by TheAssassin** [comment]
Yes, most likely.
