### ISSUE TITLE
Suppress deprecated desktop integration script bundled by some AppImages

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#22]
Some AppImages still ship the no longer maintained, deprecated desktop integration script that some people still like, but that interferes with libappimage's desktop integration.

When using AppImageLauncher, the script is not necessary anyway, and should be suppressed, if possible. IIRC, there's an environment variable that can be set. I hope the variable is unique enough so it is safe to set it always, but if it's not, we'd probably have to inspect the AppImages, and check whether the script is being used.

**Comment by TheAssassin** [comment]
Looking at the source code, the name of the environment variable is `SKIP`. Setting it might cause issues with payload applications.

@probonopd how dangerous do you think setting this variable by default is?

**Comment by probonopd** [comment]
@TheAssassin that script (or anything that does desktop integration from _within_ the AppImage shall exit if one of these conditions are met, which are here for exactly this reason:

* There is a file `$HOME/.local/share/$VENDORPREFIX/no_desktopintegration` (this is meant to be set by the user)
* There is a file `/usr/share/$VENDORPREFIX/no_desktopintegration` or `/etc/$VENDORPREFIX/no_desktopintegration` (this is meant to be set by the system administrator)
- A process called `appimaged` is running
- The environment variable `$DESKTOPINTEGRATION` is not empty (suggesting something else is managing desktop integration on this system)

So I recommend you export `$DESKTOPINTEGRATION=AppImageLauncher`.

**Comment by TheAssassin** [comment]
@probonopd I just saw that `SKIP` once, and didn't look into alternatives. Thanks for telling me about `DESKTOPINTEGRATION`, it'll work just fine.
