### ISSUE TITLE
.deb package installs files into /usr/share/icons that don't belong there

### ISSUE THREAD

**Issue by darealshinji** [TheAssassin/AppImageLauncher#223]
The package `appimagelauncher_1.4.0-beta-2-travis736.git20190801.f9ddaf8.bionic_amd64.deb` installs the files `generate-icons.sh` and `AppImageLauncher_inkscape.svg` directly into `/usr/share/icons/`, which shouldn't. I can understand that cmake doesn't produce packages that are 100% conform with packaging guidelines, but I would assume this issue should be easy to fix?

**Comment by TheAssassin** [comment]
Ah, great catch. It can be fixed, sure.
