### ISSUE TITLE
.deb package: icons not installed correctly

### ISSUE THREAD

**Issue by darealshinji** [TheAssassin/AppImageLauncher#225]
The icons path inside the .deb package is `/usr/share/hicolor/` when it should be `/usr/share/icons/hicolor/`, so the icon is missing from AppImageLauncherSettings menu entry.

**Comment by TheAssassin** [comment]
Made a mistake in the previous commit. Fixed in 48b86de.

**Comment by TheAssassin** [comment]
Just checked, it's corrected in all packages in the continuous release. Thanks again for reporting.
