### ISSUE TITLE
Clear Linux support?

### ISSUE THREAD

**Issue by sedlund** [TheAssassin/AppImageLauncher#228]
It's a rolling release distribution with its out software bundling system.

**Comment by TheAssassin** [comment]
@sedlund we don't do packages for every distro. First of all, it's a ton of work that we just can't do. Second there's special knowledge required which we also would have to learn about first. We use standard distros mainly, such as Debian-based Ubuntu flavors etc.

Please ask the Clear Linux developers to make packages. We will happily support them if they have questions. But we won't be able to provide packages for Clear Linux or any other non-standard distribution.

See also #139.

Fun fact: the packages provided for download are generated semi-automatically by CMake, so there was very little effort involved to get that to work. If CMake had a creator for Clear Linux packages, that'd be an option.

Please feel free to ask further questions by replying here or opening another issue.
