### ISSUE TITLE
Run locally for testing purposes

### ISSUE THREAD

**Issue by azubieta** [TheAssassin/AppImageLauncher#229]
I'm getting this error while trying to run AIL from the build environment. Is there a cheats sheet where is described how properly do it. With out installing the `appimagelauncherfs` service.

![Screenshot_20190807_183152](https://user-images.githubusercontent.com/1138094/62664597-d0e21100-b941-11e9-89b8-50afea3334b8.png)

**Comment by TheAssassin** [comment]
It is sufficient to simply run an appimagelauncherfs process, no matter how it's got on your system. Running from the IDE will do just fine. That's how appimagelauncherfs is debugged as well.
