### ISSUE TITLE
WSL2(Windows sub system) install failed and uninstall also failed.

### ISSUE THREAD

**Issue by lengthmin** [TheAssassin/AppImageLauncher#231]
Debian 10 
![image](https://user-images.githubusercontent.com/13938334/62935984-295e5600-bdfb-11e9-86c2-965ee0542db0.png)

![image](https://user-images.githubusercontent.com/13938334/62936658-f7e68a00-bdfc-11e9-943d-0eef942083f6.png)

so I cannot do anything with apt and dpkg, it will show the error every time when I use dpkg.

**Comment by TheAssassin** [comment]
Windows weird system lacks essential features and therefore we cannot integrate AppImageLauncher deeply enough to make it work. Also I'm not sure if WSL supports AppImages at all. It just doesn't provide a real Linux system with a real kernel, but only some userspace tool set.

The packages will not work for you I guess. You might try AppImageLauncher Lite, though. Download the AppImage from our release page and call it with `install`. Please beware that it lacks many features. But it will provide a basic system for you.

We're about to document the differences between Lite and regular AppImageLauncher.

**Comment by lengthmin** [comment]
is there any other way to uninstall this package? 
using `dpkg` will raise an error...

**Comment by TheAssassin** [comment]
Well, `dpkg` is the way to go. I don't know if there's a way to suppress the post-install scripts. You need to ask in a Debian forum. Or ask the vendors of WSL 2.

**Comment by lengthmin** [comment]
Alright~ thanks for your answer, I will close this issue
