### ISSUE TITLE
[ARCH] libappimageupdate.so: : No such file or directory

### ISSUE THREAD

**Issue by GleitonCampos** [TheAssassin/AppImageLauncher#237]
Hello! I installed the AppImageLauncher via  AUR and yaourt (https://aur.archlinux.org/packages/appimagelauncher-git) and if I try to open the AppImageLauncherSettings, nothing happens. If I try to open a AppImage file, I receive a  "/usr/bin/AppImageLauncher: error while loading shared libraries: libappimageupdate.so: cannot open shared object file: No such file or directory"
 
I'm using Arch + KDE Plasma 5. Attached the installation stdout

Thanks
[AppImageLauncher.log](https://github.com/TheAssassin/AppImageLauncher/files/3560449/AppImageLauncher.log)

**Comment by TheAssassin** [comment]
There's a bug in that AUR file, there needs to be a second CMake run after building for the first time. It's a workaround for a limitation in CMake regarding path resolving.

Please see https://github.com/TheAssassin/AppImageLauncher/blob/33e7814c9232187eb0caafd33a10c95f07af66f6/travis/build-lite.sh#L56-L66.

Can you please fix the AUR pkgbuild stuff? I'm not maintaining it. Or perhaps contact the upstream maintainer?

**Comment by GleitonCampos** [comment]
Tks for the info! I'll try this and send this to the upstream maintainer. Thank you.

**Comment by TheAssassin** [comment]
You can also send my apologies for the crappy workflow.

Closing as resolved. Please feel free to reopen if there's more issues.
