### ISSUE TITLE
Uninstalling appimagelauncher on ubuntu 19.04 appears to break appimage completely

### ISSUE THREAD

**Issue by pellcorp** [TheAssassin/AppImageLauncher#238]
Now I cannot run any Applmages I get a No such file or directory error :-(

**Comment by pellcorp** [comment]
Never mind, a restart of the computer and all is working again, very odd.

**Comment by TheAssassin** [comment]
It's systemd's binfmt_misc stuff that can't be reset properly, which requires a restart after removing AppImageLauncher. Sorry for the inconvenience. As soon as I ever find a way to flush systemd-binfmt, I'll implement it asap.
