### ISSUE TITLE
Integration of Jetbrains-toolbox fails, the appimage doesn't work anymore

### ISSUE THREAD

**Issue by Furqan136** [TheAssassin/AppImageLauncher#239]
I Integrated the Jetbrains-toolbox appimage and it failed. Any subsequent attempts to open the app failed. sometimes it gave the error that the software is already integrated. I tried completely removing the app and its configuration, fails on new install.
gives error:
"Failed to register AppImage in system via libappimage"
and then:
"Failed to register AppImage in AppImageLauncherFS: could not open map file"
and the file gets deleted and ~/Applications/jetbrains-toolbox_00000000000000000000000000000000 is created. Opening this file also gives econd error

In case I choose not to integrate, the second error occurs but the file is not deleted.
OS: KDE Neon 5.16
App link: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.15.5796.tar.gz

**Comment by tiguchi** [comment]
I'm also affected by this problem. I filed a Jetbrains bug ticket here: https://youtrack.jetbrains.com/issue/TBX-3948

**Comment by probonopd** [comment]
Possibly `X-AppImage-Integrate=false` in the desktop file might help @TheAssassin? But then it would not show up in the menu either, correct? So wouldn't we need a `X-AppImageLauncher-Move=false`?

**Comment by TheAssassin** [comment]
It's not the moving that really breaks here. But it's part of the issue. libappimage 1.0.0 broke, as I already expected, many, many old contracts of functions. It changed behavior, ignoring the existing implementation. That's why I was reluctant of moving on to it in the first place,  cause now I have to fix these one by one...

**Comment by kisss256** [comment]
Can a simple solution be to enable an integration blacklist?
Simply: "Ignore this file, it doesn't play nice, it's doing it's own thing, don't prompt me again."

**Comment by smac89** [comment]
For any Arch users, I created an arch package which allows toolbox to be ignored by AppImageLauncher.
https://aur.archlinux.org/packages/jetbrains-toolbox-fix/
