### ISSUE TITLE
arch linux package

### ISSUE THREAD

**Issue by star-buck** [TheAssassin/AppImageLauncher#24]
Is this file the arch package:
https://github.com/TheAssassin/AppImageLauncher/releases/download/continuous/appimagelauncher-git20180419.0e72c1b.source.tar.xz

If so maybe replace .source. with.arch.

**Comment by TheAssassin** [comment]
The package is a source tarball that can be used to build packages for the application.

I am not sure what _exactly_ you refer to with an "Arch tarball". I can't find any real docs on it (other than something on the AUR), and I have never seen any project release such tarballs on GitHub. Could you please elaborate on what needs to be packaged?

**Comment by star-buck** [comment]
Is there any arch tar.gz binary package of AIL?
I thought there was one under releases, and it was that package...

**Comment by TheAssassin** [comment]
There is not, at least not yet.

CMake can generate an arbitrary tarball containing the same file layout as the other packages, just like creating a tarball of the directory created with `make install DESTDIR=<out>`. I can set this up within a few minutes. It's nothing Arch Linux specific, though.

@NuLogicSystems has provided a PKGBUILD file in https://github.com/netrunner-rolling/2018.01/issues/56, which will be bundled in the `docs` directory soon, too.

**Comment by star-buck** [comment]
Yeah, it was James pkgbuild that i was thinking if and assumed there was an
arch tar.gz binary package already... Arch is pretty important these days,
especially with Manjaro being at the top of distrowatch and netrunner
rolling based on manjaro kde, so an official tar.gz of AIL under releases
would be pretty nice to have besides rpm and deb.

**Comment by TheAssassin** [comment]
So, I should try to build an Arch Linux package with that PKGBUILD file?

I'm new to Arch Linux packaging. I'll read some of the documentation, and will try to publish such packages soon.

**Comment by NuLogicSystems** [comment]
I already built one that is in our netrunner repository:
http://arch.netrunner.com/netrunner/x86_64/appimagelauncher-1alpha+git20180413.08ff6b8-1-x86_64.pkg.tar.xz

**Comment by star-buck** [comment]
Can we automate this from the pkbuild like deb and rpm?

**Comment by TheAssassin** [comment]
@star-buck I think it should suffice if we add a link to these packages, then?

@NuLogicSystems how often is this package going to be updated? AppImageLauncher uses continuous deployment, i.e., packages are built for every new release.

**Comment by NuLogicSystems** [comment]
I'm not sure, cmake has a way of doing this for deb and rpm built in.

**Comment by NuLogicSystems** [comment]
@TheAssassin,
I update packages when I notice updates, I'd have to monitor your github for updated releases.
If you can find a way to automate this with cpack, that would be a better solution.

**Comment by TheAssassin** [comment]
@NuLogicSystems you mean, build packages you can import? I thought you might have a platform for building packages that monitors version control systems. Similar to the openSUSE build service.

**Comment by TheAssassin** [comment]
Regarding the docs, as we have your PKGBUILD file (which seems to work fine), it's more of a "set up the environment" issue than "write the configs". I'll look into a container based solution next week.

**Comment by TheAssassin** [comment]
So, in order to get automatic packaging for this application, we'd have to ask Manjaro to package it upstream, right?

**Comment by NuLogicSystems** [comment]
Yea, that probably is not going to happen. The Manjaro team is very picky about what ends up in their repositories, not as picky as Arch, but still picky non the less.

**Comment by TheAssassin** [comment]
I see. Manjaro is a derivative of Arch, and Netrunner Rolling derives from Manjaro, therefore (transitivity) Netrunner Rolling and Manjaro have native AUR support.

Would you be willing to maintain the PKGBUILD script on AUR, @NuLogicSystems? I could eventually do it as well, I guess, but that'd require some amount of testing, and will therefore take me a few days.

**Comment by NuLogicSystems** [comment]
Yes, I could do that.
However, it will be a couple of days before even I can get to it. 
My system for working with the AUR is still down.

**Comment by NuLogicSystems** [comment]
I'll work on getting that system back up and running then.

**Comment by TheAssassin** [comment]
Thank you very much, @NuLogicSystems.

**Comment by NuLogicSystems** [comment]
Done: https://aur.archlinux.org/packages/appimagelauncher-git

**Comment by TheAssassin** [comment]
Thanks, great job, highly appreciated. I doubt we'll switch away from the "continuous release scheme" we use at the moment too soon, though.

**Comment by NuLogicSystems** [comment]
That's fine, however I still have to go by the arch packaging standards when adding pkgbuilds to the AUR.

**Comment by TheAssassin** [comment]
Do continuous releases which use the git revision ID violate their standards? I've seen other `-git` packages on AUR before, but I never looked at their version numbers.

**Comment by TheAssassin** [comment]
I see. I implemented this as a workaround to get an `update-binfmts` binary on RPM based systems (but I got in touch with openSUSE to request packaging of binfmt-support, although that won't make the workaround obsolete).

I will make this installation directive optional. That'll take just a couple of minutes.

**Comment by NuLogicSystems** [comment]
I still don't understand why it built fine last week and now it is not.

**Comment by NuLogicSystems** [comment]
Nevermind I found it. I built the package on the 4/13, the change was made after that.

**Comment by NuLogicSystems** [comment]
No issues, it happens from time to time. If you ever do get an AUR account let me know, I can add you as a co-maintainer.

**Comment by TheAssassin** [comment]
I'll set one up as soon as I finished working on #25.

**Comment by NuLogicSystems** [comment]
@TheAssassin 
In the PKGBUILD added under doc, the email address for the maintainer string is wrong.
Could you change it to james@nulogicsystems.com please.

**Comment by NuLogicSystems** [comment]
Thanks.
Now I'm getting:

> [ 93%] Linking CXX shared library libappimageupdate.so
> /usr/bin/ld: cannot find -lzsync2_zlib
> collect2: error: ld returned 1 exit status
> make[2]: *** [lib/AppImageUpdate/src/CMakeFiles/libappimageupdate.dir/build.make:102: lib/AppImageUpdate/src/libappimageupdate.so] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2712: lib/AppImageUpdate/src/CMakeFiles/libappimageupdate.dir/all] Error 2
> make: *** [Makefile:152: all] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...
>

**Comment by TheAssassin** [comment]
@NuLogicSystems the issue has been resolved.

**Comment by NuLogicSystems** [comment]
@TheAssassin 
Should I set the PKGBUILD to a specific commit so that breakages don't occur for AUR users?

**Comment by TheAssassin** [comment]
@NuLogicSystems if I would make use of PRs more, that would be less likely to happen.

Question: do failing builds break AUR packages? If not, we can just keep everything as is. Failing Travis builds won't be uploaded to the release page either.

**Comment by NuLogicSystems** [comment]
There are no "packages" in the AUR per say, the PKGBUILD is a set of instructions for makepkg to compile and/or extract, package, and install the application in question. So, yes, it will break.

**Comment by TheAssassin** [comment]
I see. I'm still new to this whole topic.

Is there some kind of API that can be used to update the revision if we switch to manual updates? Then, the Travis job could update the revision ID after success.

**Comment by NuLogicSystems** [comment]
NO, but what we can do is on each release use that commit in the pkgbuild, like so:

source=("git://github.com/TheAssassin/$_pkgname#commit=77b0f08260a1cdd9e4520ff5e05921b85977a6a3")

**Comment by TheAssassin** [comment]
That is what I want to do, but I want to automate the process, i.e., whenever the Travis build succeeds, the version number in the PKGBUILD file should be updated.

I am just looking for an alternative to using Git...

**Comment by NuLogicSystems** [comment]
The version number in the PKGBUILD gets updated each time it's built actually, that's what this does:

> pkgver() {
>   cd "$srcdir/$_pkgname"
> 
>   printf "1alpha+git`date +%Y%m%d -u -d "$(git show -s --format=%ci $(git rev-parse HEAD))"`.%s" "$(git rev-parse --short HEAD)"
> }
>

**Comment by TheAssassin** [comment]
> source=("git://github.com/TheAssassin/$_pkgname.git#commit=77b0f08260a1cdd9e4520ff5e05921b85977a6a3")

I am talking about _this_ commit ID. The one we'd have to hardcode.

**Comment by NuLogicSystems** [comment]
Oh, so automate editing the pkgbuild to change the commit in the source line prior to build like a sed would do? That might just work.

**Comment by TheAssassin** [comment]
Exactly. That seems like the best way of avoiding build errors on people's computers. We trust the Travis build to bring up build errors.

I'll have to check how I can set this auto-editing of a file in a Git repository up. I don't like to give Travis CI full access to my AUR account. Maybe I'll set up something like an intermediate repository in one of my Gitea installations, or I'll write some micro service in Python that does the job.

**Comment by NuLogicSystems** [comment]
Yea, I don't think giving a service like Travis your ssh key to access the AUR would be a good thing to do either.

**Comment by TheAssassin** [comment]
We could only add a second user that has exclusive access to this package. But I'd prefer to reduce the amount of functionality performed on Travis CI, I'd rather outsource the Git processes, and pass the commit ID to some sort of service. That allows to verify the processes.

AUR really needs deploy keys. And, while we're at it, 2FA.

**Comment by NuLogicSystems** [comment]
Are you using the public key or did you generate your own like the wiki tells you too?
https://wiki.archlinux.org/index.php/Arch_User_Repository#Authentication

I have another IDEA, how about travis generates a source tar.xz or tar.gz after each successful build with the same name, and then we can just point the PKGBUILD to that file on Travis?

**Comment by TheAssassin** [comment]
Just tried on Manjaro KDE. MIME type integration works fine now. However, there is no binfmt support yet, which is one of the key features.

@NuLogicSystems there _is_ a source tarball uploaded to the release page on every build. I assume you'd need some "consistent" file name.

uploadtool, the tool used to upload to GitHub releases, internally works by tagging the currently built commit as `continuous`, creating a "release" for it, and uploading the files. Now, the "source" tarball containing _all_ the sources (i.e., the submodules, `ExternalProject` stuff isn't included (yet)) filename is generated with information from the build.

However, we have a Git tag on GitHub after the upload has begun. Therefore, we have two options to get the source code for the current `continuous` tag: Clone and check out this tag, or get a release tarball from GitHub for that tag. As we already clone AppImageLauncher, we could just switch to using the `continous` tag on AUR.

**Comment by NuLogicSystems** [comment]
I'm not sure you can have multiple tags with the same text, but if that works, #tag= is just as easy as #commit=.

**Comment by TheAssassin** [comment]
I'm working on the file at the moment anyway, so I'll commit that soon.

Another question. How can I depend on a package from AUR? I'd need to depend on `binfmt-support`, which is unfortunately not available from the Arch repos yet.

**Comment by TheAssassin** [comment]
Thinking about it, we could use the `continuous` branch for a `appimagelauncher` package (aka "stable" package), and let `appimagelauncher-git` users live on the "bleeding edge". That'd be an adaption of the continuous release scheme to AUR's constraints.

**Comment by NuLogicSystems** [comment]
Sorry, I missed the question. You depend on them the same way you depend on repository dependencies. The difference is you need to build and install them first, or use an aur helper.

**Comment by NuLogicSystems** [comment]
One of these might be what your looking for:
https://wiki.archlinux.org/index.php/AUR_helpers#Workarounds

**Comment by TheAssassin** [comment]
I see. Then I can just commit them as I have them now. Thanks.

**Comment by NuLogicSystems** [comment]
You have to run a build on the PKGBUILD first to update the version string.
and then you need to update the .SRCINFO before pushing a commit to the AUR.

**Comment by TheAssassin** [comment]
That's annoying. I think I need a `makepkg` AppImage for use on my Ubuntu dev system...

**Comment by NuLogicSystems** [comment]
Arch can be annoying, but then, it's not intended for the timid, LOL.

**Comment by TheAssassin** [comment]
Arch just sucks at working _together_ with anybody. They're annoying for any maintainer. They constantly break compatibility. Arch sucks.

**Comment by NuLogicSystems** [comment]
It's more or less the version number the aur lists matching what ends up in the end users package.
even though the date in our string will change when the end user compiles, the commit string at the end will still match. The .srcinfo also need to match the pkgbuild, more of a security thing.

**Comment by NuLogicSystems** [comment]
It actually usually upstream that breaks compatibility, It usually just takes longer for other slower distributions to be effected. Not to say that Arch doesn't sometimes break compatability themselves, However, they do tend to stick closer to upstream than most, things like not splitting packages, using odd paths for libraries, etc.

**Comment by TheAssassin** [comment]
I've built a more or less working AppImage for this purpose now. Running the command at the moment.

**Comment by NuLogicSystems** [comment]
I already fixed it, but that sound good as well.

**Comment by NuLogicSystems** [comment]
Sorry for my ignorance, but what exactly does binfmt do?

**Comment by NuLogicSystems** [comment]
Never mind I looked it up. Arch uses systemd-binfmt for this.
Binfmt registration lines can be placed in a file in /etc/binfmt.d.

**Comment by NuLogicSystems** [comment]
However, unless your building binfmt-support as a static library and shipping it in your package, having it a makedepends will not work. The install script is run after installation and makedepends are only used during build, they are not installed to the end users system.
https://wiki.archlinux.org/index.php/PKGBUILD#Dependencies

**Comment by TheAssassin** [comment]
@NuLogicSystems `binfmt-support-git` provides `binfmt-support`, so one can safely depend on `binfmt-support`. When building on e.g., Manjaro, `yaourt` tells that there's this package.

I wrote an `.install` script that is supposed to take care of installing and removing the binfmt support. I am trying not to use config files, and rather share these snippets calling `update-binfmts` across all supported distros.

Regarding the `*depends`, `binfmt-support` is listed in both `makedepends` and `depends`. I don't recall why I added it to `makedepends`, though, and will therefore remove it.

We already use pacman hooks for MIME type integration etc.

By the way `binfmt-support` is not required for some library here, but to have access to the `update-binfmts` tool.

If you think we should instead directly use a config file for binfmt support, we can switch to that approach, but we should then consider doing it on all platforms.

**Comment by NuLogicSystems** [comment]
When I pulled the PKGBUILD, binfmt-support was only in the makedepends array, I wasn't trying to be misleading. Since this package would be needed during install, depends would be the place for it.

Yes, I agree. Using the opendesktop standard would be more compatible across distributions.

**Comment by TheAssassin** [comment]
Just for the record: `binfmt-support` is an implementation of this standard. It creates the config file in the right location.

Could you please have a look why the postinstall/preremove scripts don't seem to work?

**Comment by NuLogicSystems** [comment]
Yes, I'll take a look at them as soon as I get back to the office in a couple of hours.
I'm working onsite for customer ATM.

**Comment by NuLogicSystems** [comment]
Yes, the package in the repository still works.
At quick glance, I think the reason your install script isn't working is the parentheses you have around the command. But that will take testing, but since I'm not in front of my work system I can't test that out ATM.

**Comment by TheAssassin** [comment]
@NuLogicSystems the bash script itself is fine, syntax wise. Check out their examples. These are correct function definitions.

I'll check out the systemd binfmt stuff later. I noticed that the directory `/usr/lib/binfmt.d` exists on Ubuntu/Debian, too. Maybe we can simply install a single config file on all platforms via CMake. That'd be a lot less maintenance work than working on these maintainer scripts...

**Comment by NuLogicSystems** [comment]
@TheAssassin,
If you look at the other binfmt settings packages for like java and qemu online, they all pretty much use /usr/lib/binfmt.d, this is why I suggested it. ;)

**Comment by TheAssassin** [comment]
I will check them out, thanks. See #26.

**Comment by TheAssassin** [comment]
We have a config on AUR now. Hence closing this issue as resolved.
