### ISSUE TITLE
Cannot install AppImage

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#240]
```
me@host:~$ /run/Extensions/aill.ExtensionImage/usr/lib/appimagelauncher-lite.AppImage install
Error: no option passed, use --help for more information

me@host:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.04"
VERSION_ID="19.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```

I would not be surprised if changing

```
exec "$this_dir"/AppRun.wrapped "$@"
```

to 

```
exec "$this_dir"/AppRun.wrapped "$@"
```

would do.

**Comment by TheAssassin** [comment]
You have seen your two lines are exactly the same? But I think I know what you're referring to.

I have recently fixed linuxdeploy to include `"$@"` in the generated scripts. See https://github.com/linuxdeploy/linuxdeploy/commit/0ba33879b090aa4dd76cb186bf5441e02d91d52b. Let me re-build the AppImage and it'll be fixed.

**Comment by probonopd** [comment]
Err. Edited above.

**Comment by TheAssassin** [comment]
Build's done, should work again. Please reopen otherwise.

**Comment by probonopd** [comment]
Strange, GitHub Releases page still says " TheAssassin released this 9 days ago"...

**Comment by TheAssassin** [comment]
But I deleted the files and retriggered Travis. uploadtool for some reason doesn't overwrite existing files. The only way to properly rebuild and reupload stuff, since GitHub removed this "delete release" feature a while ago.

**Comment by probonopd** [comment]
> GitHub removed this "delete release" feature a while ago.

Aaah, _**that's**_ why!

**Comment by TheAssassin** [comment]
There's also no reason to waste energy and rebuild the other artifacts...

**Comment by probonopd** [comment]
I don't get it... every git commit should trigger a new continuous build, delete the old continuous release and add a new one, shouldn't it?

How do I test this now?

**Comment by TheAssassin** [comment]
There was no reason to make a new commit?

**Comment by probonopd** [comment]
Ah, I just make a new commit usually which triggers a new build. And gets a new SHA1 :)
