### ISSUE TITLE
Cannot install deb

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#241]
https://www.reddit.com/r/kde/comments/d4i9qk/appimage_launcher_error/

> Whenever I'm installing any package I'm encountering this following error -

```
dpkg: error processing package appimagelauncher (--configure):
package is in a very bad inconsistent state; you should
reinstall it before attempting configuration
Errors were encountered while processing:
appimagelauncher
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

> Can anyone help resolve this?

```
System Configuration
Operating System: KDE neon 5.16
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.61.0
Qt Version: 5.12.3
Kernel-Version: 5.0.0-27-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i3-6100U CPU @ 2.30GHz
Memory: 7.7 GiB of RAM
```

**Comment by TheAssassin** [comment]
The question is, what did the person do to get to this point? I can't provide support over at Reddit, nor do I want to have you play relay. Send them here please! 

In general, https://askubuntu.com/questions/148715/how-to-fix-package-is-in-a-very-bad-inconsistent-state-error might help, but as said without knowing what happened, I can't help.

**Comment by probonopd** [comment]
Done that.

**Comment by ChitranshuV** [comment]
I'm the guy who asked the solution on Reddit. 
The way I encountered this problem was, that I was updating my system using 
`pkcon refresh` and `pkcon update`. After the end of installation the following lines of error appeared 

 

> dpkg: error processing package appimagelauncher (--configure):
> package is in a very bad inconsistent state; you should
> reinstall it before attempting configuration
> Errors were encountered while processing:
> appimagelauncher
> E: Sub-process /usr/bin/dpkg returned an error code (1)

I tried to update the system multiple times and each time appimagelauncher showed this error. 
Someone commented on Reddit to use this 
`sudo apt install dpkg-dev` . Upgrading system then prompted me to update appimagelauncher which instead of showing error like earlier cases was successfully installed

**Comment by TheAssassin** [comment]
Have you used the system packages? If yes, see #242, KDE Neon broke something. I have no influence on their packaging, so I don't know what has changed to break, all I can tell is that indeed `dpkg-dev` was likely missing.

If you are interested in details, please refer to the KDE Neon team. You need to differentiate between "the person who creates the software" and "the person that builds the packages you install". In this case, as the package installation broke, it's not very likely that the software author made breaking changes, but the packagers. As said, no idea what broke, nor why it started working again. 

I consider this issue resolved.

**Comment by probonopd** [comment]
> If you are interested in details, please refer to the KDE Neon team. You need to differentiate between "the person who creates the software" and "the person that builds the packages you install". 

This is why I love AppImage. There the two are the same. :+1:
