### ISSUE TITLE
KDE neon - cannot update appimagelauncher

### ISSUE THREAD

**Issue by KenrickJa** [TheAssassin/AppImageLauncher#242]
Operating System: KDE neon 5.16
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.61.0
Qt Version: 5.12.3
Kernel Version: 5.0.0-27-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-5600U CPU @ 2.60GHz
Memory: 7,5 GiB of RAM
Thinkpad 450s

In Discover: 
appimagelauncher1.2.2.+dfsg-1+18.04+bionic+build3->%2(I18N_ARGUMENT_MISSING)

Error message after trying to install:
Package failed to install
Error while installing package: there is no script in the new version of the package - giving up

**Comment by TheAssassin** [comment]
Have you tried to install the packages from here? Or what's the exact issue?

The packages built here are of low quality, and not meant to be mixed with whatever your distribution provides.

**Comment by KenrickJa** [comment]
Tried to install as part of a normal update with Discover. All other packages installed, appimagelauncher did not. Have tried with Discover again, problem persists. Should I try asking KDE neon?

**Comment by KenrickJa** [comment]
OK, found a solution here: https://forum.kde.org/viewtopic.php?f=309&t=162360&p=422126&hilit=appimagelauncher#p422126
Closing this issue.

**Comment by TheAssassin** [comment]
Good it's fixed. I have no influence on distro packages, so it's always good to ask upstream. Interesting method, though. I have no idea how this breakage could occur, hence I was asking for more information.
