### ISSUE TITLE
Change Applications directory name

### ISSUE THREAD

**Issue by ireggiani** [TheAssassin/AppImageLauncher#245]
My KDE Neon system is in **Spanish** and I already use a directory for applications on the home directory, both AppImages as well as some others that don't get installed as .deb packages. I have no use for the "Applications" directory that _appimagelauncherd_ creates every time I run it; but would actually use the integration feature if it pointed to my own Spanish-language directory.

Is there a way to change the directory? If I need to change the source code and compile a version for myself, I'll do it; but I would need directions.

Alternatively, as I'm not currently using the integration feature; is there a way to disable the creation of the directory?

**Comment by TheAssassin** [comment]
How about changing your Applications directory in the settings to that other directory then? appimagelauncherd will then monitor that directory instead.

Technical background: appimagelauncherd monitors a directory using so-called inotify. To set up inotify monitoring, the directory has to exist. Therefore the daemon must create it. If you change your directory in the settings, it'll use that instead.

![screenshot_2019-09-28_16-56-41](https://user-images.githubusercontent.com/4503202/65818348-1835a100-e211-11e9-965c-651ab70daa84.png)

Big advantage: whenever you move AppImages into this directory now, the daemon will automatically integrate them. And if you have the launcher dialog activated, if you choose "Integrate and run" on first launch, the AppImages will end up in your own applications directory as well.

**Comment by ireggiani** [comment]
Apologies, but I have never seen a settings screen. How do I access it?

**Comment by TheAssassin** [comment]
It's available from your launcher and should be in your system's control panel under "AppImageLauncher Settings".

Please feel free to send a PR adding more translations for this application title to our desktop file. See https://github.com/TheAssassin/AppImageLauncher/blob/master/resources/appimagelaunchersettings.desktop#L6.

**Comment by ireggiani** [comment]
I might be having a special issue here: there is no settings option. I have installed _appimagelauncher_ from the repositories (this distro uses Ubuntu 18.04 ones) but I have no settings option. I tried running that .desktop file, but the same problem happened: no such command. What am I missing?

**Comment by TheAssassin** [comment]
Wait, you're saying we're in the Ubuntu 18.04 repos? That can't be, the app was born in April 2018 and included in any relevant repos *waaaay* later. This just cannot be. Please post your distribution and version.

This application is quite young, and is under constant development. You should probably use the packages provided in our releases section (you have to install them manually, unfortunately), until a PPA is available (see #201 for more information).

**Comment by ireggiani** [comment]
You had me doubting I even had the program in question here. I just checked my software sources to make sure I didn't have a PPA that might be adding the AppImageLauncher package. No, it must be from the official repositories.

I have **KDE Neon 5.16**, which is based off the _Ubuntu 18.04 repositories_ (they make a point of using LTS repos only), but it seems they actually include packages of their own (hence why you can update KDE packages beyond what Ubuntu 18.04 allows), so they might also have your program here.

The version of AppImageLauncher in the repositories is 1.2.2, which might be why it lacks a settings feature. That's where you'd know more. Other than that, I get to launch and integrate applications and everything looks like in the screenshots here.

**Comment by TheAssassin** [comment]
KDE Neon are one of the few distros to ship AppImageLauncher, that's how you got it, makes sense so far.

The version you have is really, really old. I wonder whether they don't provide up-to-date packages. I thought they were shipping newer versions sooner. I'll check that.

**Comment by ireggiani** [comment]
Yes, I never had to compile the source code. I think it was pre-installed, too. At least I don't remember installing it to make AppImages work.

Thanks. I'd appreciate it if they add a newer version with settings on it.

**Comment by TheAssassin** [comment]
P.S.: You can always install the `.deb`s from our release page.

**Comment by ireggiani** [comment]
Well, I'll be a son of a gun. I always assumed that was just the version I had already installed. OK, then: problem solved. No more undesired directory. Thanks a lot!
