### ISSUE TITLE
Failed to parse service type, ignoring: exec

### ISSUE THREAD

**Issue by ubuntupunk** [TheAssassin/AppImageLauncher#246]
getting this error in my logs
Ubuntu 18.04

/usr/lib/systemd/user/appimagelauncherfs.service:6: Failed to parse service type, ignoring: exec

**Comment by TheAssassin** [comment]
Please provide the contents of `/usr/lib/systemd/user/appimagelauncherfs.service`, and tell me about the version of AppImageLauncher you're using and how you installed it.

**Comment by ubuntupunk** [comment]
which shows
app is in /usr/bin/AppImageLauncher,
doesn't have a --version hook
was installed about two weeks ago from git
If I check /usr/bin: 

- AppImageLauncher                    
-  appimagelauncherd                 
-  appimagelauncherfs                  
-  AppImageLauncherSettings

contents of /usr/lib/systemd/user/appimagelauncherfs.service

[Unit]
Description=AppImageLauncher daemon

[Service]
ExecStart=/usr/bin/appimagelauncherd
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target

**Comment by ubuntupunk** [comment]
man Appimagerlauncher shows:
1.5.0

**Comment by TheAssassin** [comment]
How have you installed AppImageLauncher?

**Comment by ubuntupunk** [comment]
Installed from appimagelauncher_1.5.0-travis780.git20190816.cc1a7ad.bionic_amd64.deb
I think what is going on is that the launcher daemon is supposed to scan a folder, and what I need to do is to launch each appimage individually like $appimagelauncher <directory-to-appimage> eg: ClipGrab-3.7.1-x86_64.AppImage

But when I do this I get: AppImageLauncher ClipGrab-3.7.1-x86_64.AppImage 
Created symlink /root/.config/systemd/user/default.target.wants/appimagelauncherd.service → /usr/lib/systemd/user/appimagelauncherd.service.
Created symlink /root/.config/systemd/user/default.target.wants/appimagelauncherfs.service → /usr/lib/systemd/user/appimagelauncherfs.service.
Error: Failed to register AppImage in AppImageLauncherFS: could not open map file

**Comment by TheAssassin** [comment]
The service appimagelauncherfs is absolutely required. You seem to have an issue with your systemd installation. Are you sure you're using a "vanilla" Ubuntu 18.04? Can you please try to call `systemctl --user start appimagelauncherfs` and provide the console output?

**Comment by ubuntupunk** [comment]
I reinstalled my graphics driver, now 

AppImageLauncher ClipGrab-3.7.1-x86_64.AppImage works

but 

systemctl --user start appimagelauncherfs

does nothing

**Comment by TheAssassin** [comment]
Interesting that installing a graphics driver fixes such a bug.

If it outputs nothing, it means it worked. Great. The issue should be resolved by now. I think we can close this. Please feel free to reopen if the issue persists.
