### ISSUE TITLE
Version 2 fails to run on Ubuntu 19.10

### ISSUE THREAD

**Issue by camckay** [TheAssassin/AppImageLauncher#252]
Get the following error when trying to run version 2 on Ubuntu 19.10...

AppImageLauncher: symbol lookup error: AppImageLauncher: undefined symbol: _Z7qt_hashRK7QString, version Qt_5

Build 1.5.0, however, runs as expected.

**Comment by ThisNekoGuy** [comment]
Same issue here on Pop_OS 19.04

**Comment by TheAssassin** [comment]
The issue can only be solved by *again* building packages for these distributions separately... Kind of annoying, but it is what it is. I'm testing the build scripts already, fix will be available soon.

I thought I had tested on 19.04 by the way, but I just checked and it seems the VM tagged with 19.04 was actually a bionic VM. My bad!

**Comment by Cervoxx** [comment]
Installing version 2.0.1 (Bionic deb) on pop os 19.10 still produces the same error from the original poster.

**Comment by TheAssassin** [comment]
I seem to have made a mistake there, which caused the CI not to produce eoan packages for 2.0.1. Please use the continuous binaries. I'm going to push a 2.0.2 version asap.

**Comment by Cervoxx** [comment]
> I seem to have made a mistake there, which caused the CI not to produce eoan packages for 2.0.1. Please use the continuous binaries. I'm going to push a 2.0.2 version asap.

Works good! Thanks!
