### ISSUE TITLE
Appimage  don't  run in ubuntu 16.04 

### ISSUE THREAD

**Issue by cmatomic** [TheAssassin/AppImageLauncher#258]
here is the following problem

`user@userpc:~/Transferências$ ./appimagelauncher-lite-2.0.2-travis879-29526eb-x86_64.AppImage AppImageLauncherSettings
/tmp/.mount_appima174cOQ/usr/bin/AppImageLauncherSettings: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /tmp/.mount_appima174cOQ/usr/bin/../lib/libappimageupdate.so)
/tmp/.mount_appima174cOQ/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_appima174cOQ/usr/bin/../lib/libappimage.so.1.0)
/tmp/.mount_appima174cOQ/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_appima174cOQ/usr/bin/../lib/libpng16.so.16)
/tmp/.mount_appima174cOQ/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_appima174cOQ/usr/bin/../lib/libsystemd.so.0)
/tmp/.mount_appima174cOQ/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_appima174cOQ/usr/bin/../lib/libsystemd.so.0)
/tmp/.mount_appima174cOQ/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_appima174cOQ/usr/bin/../lib/libcrypto.so.1.1)
/tmp/.mount_appima174cOQ/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_appima174cOQ/usr/bin/../lib/libgssapi_krb5.so.2)
/tmp/.mount_appima174cOQ/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_appima174cOQ/usr/bin/../lib/libgnutls.so.30)
/tmp/.mount_appima174cOQ/usr/bin/AppImageLauncherSettings: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_appima174cOQ/usr/bin/../lib/libcrypt.so.1)     `

**Comment by TheAssassin** [comment]
AppImageLauncher Lite is only supported on Ubuntu bionic and newer systems (due to a problem with one of the dependencies on older systems). I'll note that down in the README.
