### ISSUE TITLE
Use config file instead of update-binfmts for binfmt support

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#26]
Follow-up for #24.

Currently, binfmt-support packages are only available on Debian platforms. @NuLogicSystems brought up an alternative: use config files as described in the [freedesktop standard](https://www.freedesktop.org/software/systemd/man/binfmt.d.html). They should work out of the box with all systemd based distros. We just need to restart a service, as it seems, unless the system has some hooks for binfmt support in their package management system, which will have to be tested on the distros listed as supported in the README.

**Comment by TheAssassin** [comment]
@NuLogicSystems you said in #24 that you have checked some packages which use these config files. I'd like to see how they did it, too, but all the packages I got from the Arch mirrors (mostly Java) don't contain such files. Could you tell me which packages you inspected?

**Comment by NuLogicSystems** [comment]
I checked Arch, Suse, Mangea, fedora. You have to click the file list button to see them.
In the case of Arch, look in the pkgbuild  file, and at the conf files themselves:
https://aur.archlinux.org/cgit/aur.git/tree/?h=binfmt-qemu-static
https://aur.archlinux.org/cgit/aur.git/tree/?h=binfmt-java

**Comment by TheAssassin** [comment]
I was checking the wrong packages, apparently. At least I am doing it right for AppImageLauncher, looking at these packages. And there seems to be a binfmt hook that restarts systemd-binfmts in pacman, which is good to know, too.

**Comment by NuLogicSystems** [comment]
Yes, I saw that as well.

**Comment by TheAssassin** [comment]
I wrote and tested a config file:

```
# Launch AppImages with AppImageLauncher
:appimage-type2:M:8:414902::@CMAKE_INSTALL_PREFIX@/bin/AppImageLauncher::
```

Works fine. However, there's some unwanted side effects.

First of all, on Debian, the maintainer scripts have to `systemctl restart systemd-binfmt` _manually_. On installation, it installs the binfmt support perfectly fine. On removal, however, the config remains enabled, leading to broken system behavior. AppImages can't be run any more. `update-binfmts --remove <...>` however unregisters the format perfectly fine, as it communicates with the kernel.

On systems without systemd (or, rather, `systemd-binfmt` command), the binfmt support wouldn't be set up any more.

IMO we should continue to bundle and set up binfmt support with `binfmt-support`'s `update-binfmts` command, at least on Debian/Ubuntu, where a `binfmt-support` package is available we can depend on.
On other systems (namely RPM and Arch), we need to check whether installing the file into `/usr/lib/binfmt.d` will work as intended. If not, we should continue to bundle `update-binfmts` for RPM packages. On Arch, there is no such package, therefore we should just bundle the config I posted and check whether we need to manually restart `systemd-binfmt`.

**Comment by NuLogicSystems** [comment]
Question, how does the existing hook work?
We may need a hook of our own to run systemctl restart systemd-binfmt on removal (after the conf files are removed)

**Comment by NuLogicSystems** [comment]
Question, is cmake installing the files to the proper location, or do we need to do it in packaging?

**Comment by NuLogicSystems** [comment]
OK, I just looked at your code and it doesn't look right.

**Comment by TheAssassin** [comment]
Why doesn't it look right?

The config file is installed into `/usr/lib/binfmt.d`. See https://github.com/TheAssassin/AppImageLauncher/pull/27/files#diff-87364c4677e09f50088671831b8ad597R64.

In the install hook, it is now checked whether `update-binfmts` is available, either on the system or bundled. Otherwise, the script restarts the `systemd-binfmt` service. https://github.com/TheAssassin/AppImageLauncher/pull/27/files#diff-48ec4b1ac96b51dfe488c7d15ab99605R24

**Comment by NuLogicSystems** [comment]
In debian both methods are available, so if it's looking for update-binfmts, that is what it will use. And since it was done outside the systemd service, restarting the service again would do nothing.

**Comment by NuLogicSystems** [comment]
Ill take another look, but binfmt-support uses initd scripts (non systemd method) for starting and stopping.

**Comment by NuLogicSystems** [comment]
OK, actually it's using it's own systemd service not the one bundles with systemd

**Comment by NuLogicSystems** [comment]
usr/lib/systemd/system/binfmts.service

**Comment by TheAssassin** [comment]
I'm not sure whether I get your point. Anyway, we should discuss issues with the PR _in_ the PR. I tested it on openSUSE Tumbleweed in the meanwhile by the way, the method works fine there, too. I tend to merging the PR soon.

**Comment by NuLogicSystems** [comment]
Opps, what's PR?

**Comment by TheAssassin** [comment]
PR #27. The changes I developed today (and am testing right now) have been proposed, but they're not merged yet. I did this to have you review them, which you apparently did.

**Comment by NuLogicSystems** [comment]
Ahh.

**Comment by TheAssassin** [comment]
Closing as resolved.
