### ISSUE TITLE
Gnome search functionality mildly worse for Balena etcher

### ISSUE THREAD

**Issue by Cervoxx** [TheAssassin/AppImageLauncher#260]
OS: Pop!_OS 19.10 

Appimage: https://www.balena.io/etcher/ 

Appimage launcher ver: appimagelauncher_2.0.2-travis878.4986e77.eoan_amd64.deb

Issue: If I install balena etcher via the .deb/ubuntu repo's I can just type 'etcher' into gnome search and the application will show up. If I use appimagelauncher to integrate the appimage for Balena typing 'etcher' wont present Balena etcher, instead forcing me to type 'Balena' for the application to show up. 

(Pardon the poor title)

**Comment by TheAssassin** [comment]
@Cervoxx you need to ask these Balena guys to fix their AppImage. AppImageLauncher takes the information contained in the AppImage, so if they put the wrong application title inside there, AppImageLauncher can't know it's wrong or broken or anything. This is nothing we could fix, it's not AppImageLauncher's fault. Please report the issue at the Etcher repo.
