### ISSUE TITLE
Appimagelauncher 2.0 not working

### ISSUE THREAD

**Issue by 2635599** [TheAssassin/AppImageLauncher#262]
i just installed kubuntu 19.10 64 bit and attempted to install appimagelauncher 2.0 and install a appimage, but when i click on any appimage nothing happen. checked the startmenu and appimagelauncher settings are there but click them and they don't open. any idea on why 2.0 isn't working? thanks

**Comment by 2635599** [comment]
i should add i removed appimagelauncher 2.0 and installed 1.5 and there are no issues with it. unless you have another suggestion i'm assuming this is yet another program where only the older version works on 19.10 ubuntu based systems. really beginning to not like the fact that ubuntu doesn't give the new os to the software creators befor the general public so the software makes can fix their apps for the new release prior to the public getting the new os. windows may have it's issues, but this is not one of them.

**Comment by jcmason-sd** [comment]
Can I add this is the same with Makululinux. I posted a separate issue but then realised it was the same as this so closed it.

Cheers,

John.

**Comment by TheAssassin** [comment]
There's a special version for that distro (tagged eoan) which works fine from my tests. You should always post what version (ideally just provide the filename) you installed.

**Comment by 2635599** [comment]
i grabbed the 2.0 version the same way i grabbed the 1.5 version and had no issue withe. just in case i did grab the wrong one i'll take another look at the download page.

**Comment by 2635599** [comment]
i downloaded the 2.0 version of that file.

appimagelauncher_2.0.2-travis878.4986e77.eoan_amd64.deb

**Comment by TheAssassin** [comment]
A quick fix might be to try to decouple AppImageLauncher from the update helper. Then, worst case, the update tool will crash, but AppImageLauncher itself should work again.

**Comment by 2635599** [comment]
so how would i go about decoupling the update helper?

**Comment by TheAssassin** [comment]
@2635599 the latest continuous build should be working again. Can you please check whether this is the case? Ideally you'd try the `bionic` package, as I'd like to remove most of the distro version specific builds again.

**Comment by 2635599** [comment]
closed? should of stayed open till we varified i have 2.0 or newer working. that said should i backup the appimages in the applications folder first, and should i uninstall ail 1.5 first? if so to the later you have good instruction for removing it? thanks

**Comment by TheAssassin** [comment]
@2635599 the AppImages are never modified by AppImageLauncher. There's no need to back anything up there.

You should be able to simply install the new package, the old one will be removed automatically.

**Comment by 2635599** [comment]
i played it safe and uninstalled 1.5 before installing 2.0. 1.5 was installed via discover and i installed 2.0 from the deb file. just launched plex media player, zoho mail, and etcher and they all worked without issue. trying to upgrade ail before always cause the appimages to stop working. seems like that issue at lease for me is resolved. thanks a lot.

**Comment by TheAssassin** [comment]
You're welcome. Developers are always happy to get to know about issues to get a chance to fix them.
