### ISSUE TITLE
AppImage Launcher on Makululinux

### ISSUE THREAD

**Issue by jcmason-sd** [TheAssassin/AppImageLauncher#263]
I was hoping to use AppImageLauncher on Makululinux Core. I checked which version of Linux it was based on. It is based on the Debian "Testing Branch". I therefor installed the version of AIL for bionic as that was the latest version of Debian listed.

Having installed the Appimage in question (AvideMux) when double clicked seems to do nothing (although it does activate the hourglass suggesting it is trying to run).

Uninstalling AIL only results in the AvideMux AppImage now erroring in the following way:
Failed to execute file "avidemux.appimage".
Failed to execute child process "/home/johnm/Downloads/ avidemux.appimage" (No such file or directory).

I would really love it if AppImageLauncher was able work on Makululinux as I use it on other systems and it works very well. However I would at the moment settle for be able to use appimages again on this system.  

Any advice as to how to achieve this would be much appreciated.
I have tried deleting and re downloading the appimage in case that sorted the issue.

If there is a better place to be posting this question let me know and I will post it there instead.

Thanks in advance for any help,

John

**Comment by jcmason-sd** [comment]
Ok Scratch that. Having been looking through the other posts here I tried using version 1.5 instead and it all works. So consider this one closed as it is the same issue and as this version of Linux uses a testing version of Debian then I suspect that using a slightly out dated version of AIL is probably going to be the only way to ensure it works consistently.

Cheers,

John.

**Comment by 2635599** [comment]
would be nice though if the post about 2.0 not working would be addressed.
