### ISSUE TITLE
changes made by AppImageLauncher

### ISSUE THREAD

**Issue by hiaselhans** [TheAssassin/AppImageLauncher#265]
Hi,
I tried to install&run AppImageLauncher on FC31.
A AppImage file that ran just fine before now isn't anymore. I uninstalled AppImageLauncher and rebooted + re downloaded the file but still the application hangs and doesn't come up.

Which are the modifications done to the system by the AppImageLauncher and "integrating" an AppImage?

thanks.

**Comment by jn64** [comment]
Try to run the appimage from terminal and post the error message.

**Comment by TheAssassin** [comment]
@hiaselhans you must provide more information. What version of AppImageLauncher have you installed, what OS do you use, what AppImage are you trying, ...

Also, providing the information suggested by @jn64's would likely hepl.

**Comment by claudegel** [comment]
I've similar problem. Oncentos 7 when I start appimagelauncher I get :
error while loading shared libraries: libQt5DBus.so.5: cannot open shared object file: No such file or directory
I want to run digikam appimage

**Comment by TheAssassin** [comment]
You have to install the package containing this library.
