### ISSUE TITLE
Failed to register AppImage in system via libappimage for Navicat

### ISSUE THREAD

**Issue by siedovolosyi** [TheAssassin/AppImageLauncher#273]
Hi! I have issue **Failed to register AppImage in system via libappimage** in creating shortcut for Navicat https://www.navicat.com/en/download/navicat-for-postgresql . Ubuntu 18.04. As I see you are fixed the same problem in OpenShot . 
Can I use AppImageLauncher for Navicat? Thanks.

**Comment by TheAssassin** [comment]
We cannot provide support for proprietary AppImages. But this specific issue is most likely caused by the AppImage being broken. Please get in touch with the software company. You may point them to https://github.com/TheAssassin/appimagelint.
