### ISSUE TITLE
Provide basic access to find new Appimages

### ISSUE THREAD

**Issue by luxzg** [TheAssassin/AppImageLauncher#279]
Nice project here, thanks!!

I'd like to suggest an enhancement that would help somewhat with new apps discoverability.

Either scrape https://appimage.github.io/apps/ or simply integrate it in Launcher, and allow the user to search the list. If they click download, just download AppImage and start the usual process.

It doesn't need to be full blown "app store" to be helpful and appreciated by end users.

And if all that could work somewhat in command line as well, it would be all that better!

Keep up the good work!

**Comment by TheAssassin** [comment]
App store (like) functionality is out of scope of this project. I recommend to e.g., check out the [Nitrux Software Center](https://github.com/Nitrux/nx-software-center), which is a fully featured client for https://appimage.github.io.

Please feel free to send a PR adding a small  section or extending an existing one to the README and linking to the Nitrux SC or similar projects.
