### ISSUE TITLE
Invalid dependencies on Ubuntu bionic

### ISSUE THREAD

**Issue by logix2** [TheAssassin/AppImageLauncher#28]
In Ubuntu 18.04 LTS, installing the AppImageLauncher deb requires libcurl3, but some packages require libcurl4, and the two can't be installed in the same time, resulting in something like this:
```
$ sudo apt install libcurl3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  cmake curl libcurl4 uget virtualbox-5.2
The following NEW packages will be installed:
  libcurl3
```

libcurl3 and libcurl4 conflict:
```
 libcurl3 : Conflicts: libcurl4 but 7.58.0-2ubuntu3 is to be installed
 libcurl4 : Conflicts: libcurl3 but 7.58.0-2ubuntu2 is to be installed
```
The solution (so it's backwards compatible) would be to use both libcurl3 and libcurl4 and have the package install with either of them by having this in the control file: "libcurl3 | libcurl4".

**Comment by TheAssassin** [comment]
@logix2 in older versions of Ubuntu both libcurl packages have been built from the same source package (IIRC libcurl3 is a meta package depending on libcurl4). Looking at the release versions, they look similar, so I assume something went wrong upstream, maybe some Ubuntu maintainer removed the libcurl3 alias package in the new versions.

I will check whether we can depend on libcurl4 instead of libcurl3 on the older platforms (trusty and upwards).

**Comment by TheAssassin** [comment]
According to https://packages.ubuntu.com/, there's a [libcurl3](https://packages.ubuntu.com/artful/libcurl3) package, but not a [libcurl4](https://packages.ubuntu.com/artful/libcurl4) package.

**Comment by TheAssassin** [comment]
Sorry, my bad, https://packages.ubuntu.com/source/bionic/curl.

**Comment by TheAssassin** [comment]
I've checked all alternatives, but it looks like we need a separate package for bionic and upwards, with a fixed dependency list. Thanks for bringing this up, I'll fix the issue asap in CMake.

By the way, just saw you're the author, nice article you wrote, already thought about linking to it in the README. It's a nice description of what AppImageLauncher does and how it's used from a non-developer perspective. I just wanted to inform you that it adds an "Update AppImage" entry to the launcher now, too. See #23.

**Comment by TheAssassin** [comment]
Fixed in https://github.com/TheAssassin/AppImageLauncher/commit/44f5a674c9c6d90a6bc992e3acc8706765802cd7. Please use the bionic packages for Ubuntu bionic.

**Comment by logix2** [comment]
Thanks for the info, I updated my article about AppImageLauncher. Regarding this bug, it's still not fixed. The Bionic package continues to depend on libcur3.

**Comment by TheAssassin** [comment]
@logix2 I checked my locally generated packages, they correctly depended on libcurl4, at least from the `Depends:` line in the `control` file. I'll download the released package, and check whether that's the case. If yes, then some package we depend on depends on libcurl3. That'd be highly annoying, though.

**Comment by TheAssassin** [comment]
List from the currenct control file:

> libqt5widgets5 (>= 5.2.1), libqt5gui5 (>= 5.2.1), libqt5core5a (>= 5.2.1), binfmt-support (>= 2.0), libcurl4, libc6 (>= 2.14), libcairo2 (>= 1.2.4), libcurl3 (>= 7.16.2), libgcc1 (>= 1:4.1.1), libglib2.0-0 (>= 2.39.4), libpipeline1 (>= 1.0.0), libqt5core5a (>= 5.2.0), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5widgets5 (>= 5.2.0), libstdc++6 (>= 4.5), zlib1g (>= 1:1.1.4)

I can see libcurl4 in there, but I must have missed the libcurl3 entry last time I checked. Yes, that's what is generated by `dpkg-shlibs`. I think the package must be built on bionic, then, to link it to `libcurl.so.4`.

**Comment by logix2** [comment]
It looks like it depends on both libcurl4 and libcurl3:

![image](https://user-images.githubusercontent.com/38005360/39396811-ea9ac8a2-4afd-11e8-839e-d0a3f07324d3.png)

**Comment by TheAssassin** [comment]
Working on a container based build. This is a little annoying...
