### ISSUE TITLE
AppImageLauncher install howto - not understood

### ISSUE THREAD

**Issue by deezplace** [TheAssassin/AppImageLauncher#280]
Hi, not a total newbie to Linux but this will make it seem so: I don't see how to install. I've always struggled to understand any command line "make" process, and the instructions mention calling `./appimagelauncher-lite...AppImage install` but I don't see this in the git repo files I just DLed, nor whether I should be including the "..." in the middle of that line - or does it mean this is two commands? 
Thank you.

**Comment by shag00** [comment]
Yeah! If you ain't a geek, you ain't welcome here! What surprises me is why build something good then make it so hard for the majority of the world to use it easily. Most people are not interested to learn how to compile a program they might need every 6,12 or 18 months and forgetting how to in the intervening period. If you know what you are doing it is actually quite straight forward and fast.

Just adopt a rule, no deb then forget it.

The people who own github, Microsoft are not exactly noted for their user friendly sites  and this is a good example, the fact that you actually have to search to find the downloads page is pretty poor. Anyway, get the deb file you want from here [https://github.com/TheAssassin/AppImageLauncher/releases](url)

**Comment by deezplace** [comment]
lol, does wanna-be-geek count for nothing ? :)
I write my own Python code to grunge my bank statements before dropping them into self styled spreadsheets rather than run something like MYOB... ok, I'll give up trying now.
Microsoft own it ... wow I missed that little nugget too. 
anyway, thanks for the heads up to the deb file, 'preciate it.
I'll go back and find my "make" notes now m(__)m

**Comment by lowviz** [comment]
> Most people are not interested to learn how to compile a program they might need every 6,12 or 18 months and forgetting how to in the intervening period. If you know what you are doing it is actually quite straight forward and fast.


Exactly, its been 2 years for me and I totally forgot.

Thanks from another wanna be geek

**Comment by deezplace** [comment]
It's not that I don't want to understand .. I enjoy doing things via the CLI, but I just struggle with this one. I've little time and somehow  this one (CLI make process) just won't ingrain.
e.g. the file tree that I might DL .. when I run the make and compile install are these files being copied elsewhere such that I just delete the folders I DLed after the process..? Or are these files somehow required ... intrinsically necessary to the program installed (yep, I know - go search it)
But the one that really sticks in my eye is
 ./appimagelauncher-lite...AppImage install
does "..." refer to an unknown/unspecified path?
is "install" the command expected or just a convenient label for the "make compile" process?
Having only come back to Linux in the last couple of years after Wintel and Mac machines (I did enjoy my iMac having their, what was it.. BSD / Darwin backbone) I find the Software Manager now ready to do most things. And progress being what it is I think it is great that AppImages have made it better / easier to install for both dev's and users. Then I trip over trying to implement a totally appropriate and worthwhile (apparently) piece of software to help with AppImages, and it is NOT Software (Installation) Managed.
<shrug>

**Comment by TheAssassin** [comment]
@deezplace if you can, it's recommended to install one of the `.deb` files from the [release page](https://github.com/TheAssassin/AppImageLauncher/releases). Lite is for people who don't have root access or don't want to install system-wide, it's a trimmed down version.

I don't see any instruction how to compile AppImageLauncher; actually, you shouldn't be required to do so. Therefore I wonder what you refer to by "make process".

You should be aware of the release system GitHub (and all the alternatives, including GitLab, Gitea, ...) use. There are *separate* release pages that host binaries you can use. Cloning a Git repository is *only* ever required when you're interested in the source code (which would only really be the case if there weren't pre-built binaries, in which case I'd consider a project unsuitable for people at your level of "geekiness").

@shag00 thanks for linking to the release page. I think we should probably include it ~5-10 times in the README. Anyone interested in sending a PR? As the author I don't have a  "noob view" on the documentation, and can't really judge where more information is required.

Regarding the `...`: If you check the Lite AppImages in the release page, they all contain a version number. I really don't feel like putting the *entire* name of the latest release in the README. I consider people smart enough to understand that those three dots are just a placeholder for the full version at least as soon as they see the filename of the actual AppImage. Correct me if this assumption is wrong. Linking to the release page next to this might be a good idea though.

**Comment by deezplace** [comment]
@TheAssassin thank you for replying. Yes I was too dumb to realise that "..." meant to insert the version number. It's all much clearer now. Perhaps "./appimagelauncher-lite<version no.>AppImage" or some such might weed out us dummies =)
In regard to instructions to (make) compile: I only felt it seemed like that was expected of me as I couldn't figure out clear instructions to do otherwise. Landing on a GIT page and staring at a (clonable) directory structure has always made me think that is what I'm meant/expected to do, that doing other is less somehow, that this was the essence of github. I will look again at the install of the .deb file - I think I fail there because I forget which package installation model my linux installation requires, ie. there's a red hat style, a deb style ...
But thank you all (@shag00 , @lowviz , @TheAssassin ) again for taking the time to clear the fog from my ageing eyes/brain.

**Comment by TheAssassin** [comment]
@deezplace if you're interested in helping make this app more accessible to "non-geeks", please feel free to send pull requests to the README to improve the description. There's some articles about AppImageLauncher already which describe how to install it which we may link more prominently, too.

**Comment by TheAssassin** [comment]
Closing as resolved.

**Comment by TheAssassin** [comment]
Follow-up: just found this: https://tutorialforlinux.com/2019/12/08/step-by-step-appimagelauncher-ubuntu-18-04-installation-guide/
