### ISSUE TITLE
AppImageLauncher silent integration (without showing dialog)

### ISSUE THREAD

**Issue by skipperTux** [TheAssassin/AppImageLauncher#281]
Is it possible to run AppImageLauncher to silently integrate an AppImage (move to `~/Applications` and create Desktop Launcher) without showing a dialog? Something like
```
AppImageLauncher --integrate ~/Downloads/myApp.AppImage
AppImageLauncher -i ~/Downloads/myApp.AppImage
```
and also remove an AppImage from the system
```
AppImageLauncher --remove ~/Downloads/myApp.AppImage
AppImageLauncher -r ~/Downloads/myApp.AppImage
```
The use-case is to install/remove AppImages using scripts or automation tools like [Ansible](https://docs.ansible.com/ansible/latest/index.html) without user interaction, just like apt/yum/dnf package managers. The story is a rollout scenario for Desktop Computers.

I have seen some related discussion in #80, #163 or [#150](https://github.com/TheAssassin/AppImageLauncher/issues/150#issuecomment-488704165) and I am also aware of the `appimagelauncherd` daemon. However I think the described use-case cannot be solved using the existing tooling. (Event though I cannot fully setup that daemon because the settings dialog crashes on my Fedora system; upstream bug, see #218.)

Edit: To be more precise, the AppImage shall also not be launched when silently integrating.

**Comment by TheAssassin** [comment]
@skipperTux have you seen `ail-cli`? It provides unattended integration already. Removing isn't supported as of yet, however we can extend the CLI if you want to. Removing is not as critical, though, as the desktop entries will be hidden once the AppImage is gone (and appimagelauncherd as well as AppImageLauncher, the UI, also clean up old desktop files occassionally).

**Comment by skipperTux** [comment]
@TheAssassin thank you for making me aware of `ail-cli`. It looks just like what I was looking for in my issue. Two remarks:

1. From the cli-help I see the commands
```bash
Available commands:
  integrate    Integrate AppImages passed as commandline arguments
  unintegrate  Unintegrate AppImages passed as commandline arguments
```
It seems a remove command is already supported, however I am not sure what argument to pass as AppImage. During integration, a new filename with a unique Id is generated. Passing this filename is not ideal for scripting, as it is unknown when writing the script (although workarounds exist).

2. Integration with the cli does not work, it returns an error - see below. The file is copied but the AppImage cannot be started. It works when double-clicking the file, or calling AppImageLauncher. I tested with three different AppImages, [Station](https://github.com/getstation/desktop-app-releases/releases), [balenaEtcher](https://github.com/balena-io/etcher/releases) and [draw.io Desktop](https://github.com/jgraph/drawio-desktop/releases/tag/v12.5.3). They all throw the same error of `Unknown AppImage format` on my Fedora 31 x86_64 system.

**Fails**
```bash
$ ail-cli integrate ~/Downloads/Station-1.63.4-x86_64.AppImage 
ail-cli: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
Processing /home/user/Downloads/Station-1.63.4-x86_64.AppImage
Moving AppImage to integration directory
ERROR: appimage_register_in_system : Unknown AppImage format: /home/user/Downloads/Station-1.63.4-x86_64.AppImage
Error: Failed to register AppImage in system via libappimage
```

**Works**
```bash
$ AppImageLauncher ~/Downloads/Station-1.63.4-x86_64.AppImage 
AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
[...]
WARNING: Unable to resize the application icon into a 128x128 image: "Unable to load image.". It will be written unchanged.
WARNING: Unable to resize the application icon into a 256x256 image: "Unable to load image.". It will be written unchanged.
gtk-update-icon-cache: Cache file created successfully.
[...]
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[...]
# AppImage is started successfully
```

**Comment by TheAssassin** [comment]
Please provide links to your AppImages, otherwise I cannot inspect the issue...

**Comment by skipperTux** [comment]
Links are already in my response, see
> I tested with three different AppImages, [Station](https://github.com/getstation/desktop-app-releases/releases), [balenaEtcher](https://github.com/balena-io/etcher/releases) and [draw.io Desktop](https://github.com/jgraph/drawio-desktop/releases/tag/v12.5.3).

**Comment by TheAssassin** [comment]
Those links don't link to the *AppImages*. They link to some release pages. I don't want to guess which ones you tested.

**Comment by skipperTux** [comment]
Sorry, my bad. I tested the latest releases of those AppImages
- https://github.com/getstation/desktop-app-releases/releases/download/1.63.4/Station-1.63.4-x86_64.AppImage
- https://github.com/balena-io/etcher/releases/download/v1.5.73/balenaEtcher-1.5.73-x64.AppImage
- https://github.com/jgraph/drawio-desktop/releases/download/v12.5.3/draw.io-x86_64-12.5.3.AppImage

**Comment by TheAssassin** [comment]
I see. There's two issues. First is that the integration directory isn't created automatically. Second the path used for the integration is the one before moving the file. The error message is entirely misleading. libappimage should report that the file is missing, not that the AppImage format is unknown...

**Comment by TheAssassin** [comment]
Both have been fixed in 59fecaf and 7771480. Please report if it works for you now.

**Comment by skipperTux** [comment]
Works like charm. Thank you for the quick fix and for your great work on AppImageLauncher! With your consent I will close this issue.

**Comment by mbnoimi** [comment]
I've the same issue `Failed to register AppImage in system via libappimage` with [gSubs](https://github.com/sanjevirau/gsubs/releases/download/v1.0.3/gSubs.1.0.3.AppImage
)
