### ISSUE TITLE
No Eoan asset in the v2.1.0 release -

### ISSUE THREAD

**Issue by Gestas** [TheAssassin/AppImageLauncher#282]
There is no Eoan compatible asset for the [v2.1.0 release](https://github.com/TheAssassin/AppImageLauncher/releases/tag/v2.1.0).

**Comment by shag00** [comment]
I was looking for it also.

**Comment by TheAssassin** [comment]
Shouldn't be needed any more explicitly. I've removed special builds as the bionic builds have proven to install fine on newer distros again. Please try the bionic binaries. If they don't work, please file a new issue.

Please see also our [compatibility table](https://github.com/TheAssassin/AppImageLauncher#system-wide-installation).
