### ISSUE TITLE
Symlinked appimages trigger integration dialog box

### ISSUE THREAD

**Issue by SolarLiner** [TheAssassin/AppImageLauncher#290]
I have installed the [Cutter](https://cutter.re/) app through AppImage, and added a symlink to my bin folder to be able to quickly open binaries from the command-line. However, this triggers the integration dialog, which asks me whether to re-integrate the AppImage ("The AppImage is integrated but not at the right place"). However, the target of the symlink is indeed at the right place, only the symlink isn't.

I would expect AIL to recognize the symlink and follow links, allowing this particular use-case.

```
$ which cutter
/home/solarliner/.local/bin/cutter
$ realpath `which cutter`
/home/solarliner/.local/Applications/Cutter-v1.10.0-x64.Linux_fe3b2dbd4dfcb812f17b83d3503e1b4b.AppImage
```

**Comment by TheAssassin** [comment]
Interesting limitation you found there. I also think checking whether the symlink target is integrated is sufficient. Hope I'll get to working on this soon.
