### ISSUE TITLE
AppImageLauncher is not opening in Linux Mint (ionic-amd64)

### ISSUE THREAD

**Issue by kristof-linux** [TheAssassin/AppImageLauncher#291]
Hello, 
If i try to run it, i get this failures in the terminal. Please can you help?
Thanks a lot!
Kristof 

```
$ AppImageLauncher
qt5ct: using qt5ct plugin

** (AppImageLauncher:11726): WARNING **: 12:40:54.809: Pixbuf theme: Cannot load pixmap file /usr/share/themes/Mint-Y/gtk-2.0/assets/trough-progressbar.png: Laden van afbeelding ‘/usr/share/themes/Mint-Y/gtk-2.0/assets/trough-progressbar.png’ mislukt: Fatale fout in PNG-afbeelding: bad parameters to zlib


(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

** (AppImageLauncher:11726): WARNING **: 12:40:54.809: Invalid borders specified for theme pixmap:
        /usr/share/themes/Mint-Y/gtk-2.0/assets/trough-progressbar.png,
borders don't fit within the image

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:11726): GdkPixbuf-CRITICAL **: 12:40:54.809: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
AppImageLauncher version 2.1.0 (git commit d1be7e7), built on 2019-12-01 00:44:00 UTC

Usage: AppImageLauncher [options] <path>
Desktop integration helper for AppImages, for use by Linux distributions.

Options:
  --appimagelauncher-help     Display this help and exit
  --appimagelauncher-version  Display version and exit

**Comment by TheAssassin** [comment]
AppImageLauncher is running normally. It isn't meant to be launched manually. It will run automatically as a wrapper for AppImages on your system. You can run it manually, but then you have to provide a path, as the help/usage text suggests.

The warnings ("errors") are related to your distribution/system. They're annoying but harmless.

**Comment by kristof-linux** [comment]
Thank you for your very quick answer!
I'm a linux newbie, so i like to apologize for my 'easy' question.
So it is normal i don't see the AppImage launcher in my mainmenu?
I only see on icon with the AppImageLauncher settings - see screenshot
If i check the AppImageLauncher settings interface, e.g. i cannot check "auto start auto-integration". is that normal - see screenshot.

Last question: i installed twice AppImageLauncher, so some maps i have twice and i can't delele e.g/appimagelauncherfs.service....if i try to delete: it says process is busy.
Is it necessary to delete and/or how can i do that? I have to finish the process in the systemmonitor?

Thanks a lot for your help!!

Kristof

[Schermafdruk van 2020-01-28 13-08-40.png] [Schermafdruk van 2020-01-28 13-08-03.png][Schermafdruk van 2020-01-28 13-06-21.png]
[Schermafdruk van 2020-01-28 13-13-26.png]

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Op dinsdag, januari 28, 2020 12:51 PM, TheAssassin <notifications@github.com> schreef:

**Comment by TheAssassin** [comment]
It is completely normal not to see any AppImageLauncher entry in your menu. That's how it works. Its job is to integrate AppImages, and that's realized by auto-launching it whenever you start an AppImage. Having to manually run it would be way more complicated.

You cannot send screenshots via mail. I cannot see any of those.

Have you tried to reboot to solve the "map issue"?

**Comment by kristof-linux** [comment]
Thanks for your answer again.
I think i attached the screenshots now correctly.

Rebooting doesn't help for the map. Or there other options?
Thanks!

[
![Schermafdruk van 2020-01-28 13-06-21](https://user-images.githubusercontent.com/58733661/73263957-f73a8800-41d1-11ea-9ceb-2b7781046239.png)
![Schermafdruk van 2020-01-28 13-08-03](https://user-images.githubusercontent.com/58733661/73263978-002b5980-41d2-11ea-8027-f096b17283af.png)
![Schermafdruk van 2020-01-28 13-08-40](https://user-images.githubusercontent.com/58733661/73263979-00c3f000-41d2-11ea-8a78-e5e5f585ecab.png)
![Schermafdruk van 2020-01-28 13-13-26](https://user-images.githubusercontent.com/58733661/73263980-00c3f000-41d2-11ea-87f7-d6eb4b47fc93.png)



](url)

**Comment by TheAssassin** [comment]
Is that Linux Mint? Their Qt theme is usually broken, that's why you cannot change the settings in that dialog. We cannot fix that.

You can also edit the file `.config/appimagelauncher.cfg` in your home directory.

The daemon is enabled by default. You probably haven't changed it, so it will be running.

Please post a screenshot with that "map issue".

**Comment by kristof-linux** [comment]
Indeed Linux Mint!
Concerning the apps - see screenshot in attachment. There you can see the "double" maps
![Schermafdruk van 2020-01-28 13-13-26](https://user-images.githubusercontent.com/58733661/73264296-bdb64c80-41d2-11ea-886b-ad21c44b229f.png)

**Comment by TheAssassin** [comment]
I am not sure what this "search" on your file system is supposed to prove. The screenshot doesn't tell anything useful. The highlighted entries are identical. Probably proves that AppImageLauncherFS is running. I'm not even sure what this "map type" thing is.
As the entries are identical, this is probably a bug in your "file search" thingy.

As there is no bug, closing this issue.
