### ISSUE TITLE
Build and provide ARM binaries

### ISSUE THREAD

**Issue by cityadpro** [TheAssassin/AppImageLauncher#293]
I'm developing an Electron app that I'd like to run on a Raspberry Pi 4B using latest Raspbian Buster.
I'm using electron-builder package to create the AppImage for my Electron App, and since electron-builder version 21 the recommended way to integrate the AppImage to Desktop is AppImage Launcher.
But there isn't any already built version of AppImage Launcher for Raspbian and I also cannot find any instructions on how to build it.

Is there anyone here that knows how to build and install AppImage Launcher on Raspbian Buster?

Thank you!

**Comment by TheAssassin** [comment]
You should be able to build just fine on Raspbian. This project is a regular CMake one. There's tons of guides out there, e.g., https://stackoverflow.com/a/7859663.

I've created a PR (#295) that is hopefully going to deliver official ARM64 binaries which should work on a RasPi like yours. Also it will make sure the project is buildable on such devices. I hardly ever test that manually.

**Comment by cityadpro** [comment]
Hello @TheAssassin ,

thank you for your fast answer.

I've done some tests using AppImage Launcher and running my Electron app on a Linux x86_64 computer and it seems that electron-updater and AppImage Launcher are not compatible at the moment, thus the Electron app is not able to auto update itself if using AppImage Launcher.

So at this moment, I'll not use AppImage Launcher until both can work together.

Thank you for your time!

**Comment by TheAssassin** [comment]
That's new to me. I have no problems using Electron based apps on my computer. But it's up to you to decide whether to use AppImageLauncher. Please feel free to open new issues if you find other problems

**Comment by cityadpro** [comment]
I don't think it is a problem with Electron or AppImageLauncher, but a problem with [electron-builder](https://www.electron.build/) and the way it handles auto updates through electron-updater package. I can also use AppImageLauncher without any problem with my Electron app, but when there's a new version to update it fails. This [issue](https://github.com/electron-userland/electron-builder/issues/4046#issue-467463215) has already been detected and it doesn't seem that there's any move on it....

**Comment by Finn0811** [comment]
Is the most recent "appimagelauncher_2.1.0-travis918.380cee8.bionic_arm64.deb" build the right one? I can't really install it on my raspberry pi 4.

``root@raspberrypi4-4G:~# dpkg -i /home/pi/Downloads/appimagelauncher_2.1.0-travis918.380cee8.bionic_arm64.deb
dpkg: error processing archive /home/pi/Downloads/appimagelauncher_2.1.0-travis918.380cee8.bionic_arm64.deb (--install):
 package architecture (arm64) does not match system (armhf)
Errors were encountered while processing:
 /home/pi/Downloads/appimagelauncher_2.1.0-travis918.380cee8.bionic_arm64.deb``

**Comment by TheAssassin** [comment]
Oh, I was thinking the ARM64 stuff was enabled by default, but I just looked it up and that seems to be wrong. Raspbian at least still provide 32-bit images, probably to ensure compatibility on *all* devices so first-time users don't have to choose.

There are already available 64-bit images like [Manjaro](https://www.manjaro.org/download/arm/raspberry-pi-4/arm8-raspberry-pi-4-xfce/) or [Gentoo](https://www.raspberrypi.org/forums/viewtopic.php?f=54&t=249248). On Raspbian you can get a 64-bit kernel, but I'm not sure if that allows for running ARM64 packages. I have doubts, but I try to find my RasPi 4 and try it out.

So, sorry for false advertising earlier.

References:
- https://raspberrypi.stackexchange.com/questions/100926/64-bit-os-on-raspberry-pi-4
- https://www.raspberrypi.org/forums/viewtopic.php?t=250730

**Comment by TheAssassin** [comment]
I've built AppImageLauncher on a Raspberry Pi in the meanwhile just fine. On Travis there's some weird errors as of yet, I'll have to check what's going on.

But the released, official ARM64 binaries work just fine on a Pinebook (first gen) that I had on hand with the latest KDE neon image. I tested all features. There's some minor UI issues in the settings dialog (broken symbols), but that's to be expected in KDE.

I tried against some random ARM AppImage I found (fre:ac). There's a linking issue I found in our runtime, I'll have to check whether that needs to be fixed upstream in AppImageKit (links to `libz.so` instead of `libz.so.1`, but the former is only a symlink that is installed by the `zlib1g-dev` package which is not installed by default).

**Comment by TheAssassin** [comment]
We're building `armhf` binaries now, which should work on a recent Raspberry Pi image. I haven't tested that yet, as all my RasPis are still running on some older Debian, but I intend to try it on my RasPi 4 later. If they work, they'll be part of the next release.

**Comment by Finn0811** [comment]
Awesome, thanks! I'll try asap and let you know how it works.

**Comment by TheAssassin** [comment]
Binaries work fine after a reboot. And I have an idea how to fix #286. Going to prepare the new release. Closing this issue as resolved.
