### ISSUE TITLE
Wiki-Home: wrong link

### ISSUE THREAD

**Issue by k066a** [TheAssassin/AppImageLauncher#299]
### Description
Link in the **Wiki** area is wrong.

>  **_Install on Ubuntu/Debian_**
_Aktually_
[https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-Debian](url)
_Proper_
[https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian](url)

best regards,
k066a

**Comment by TheAssassin** [comment]
Thanks. Our wiki is now publicly editable. Please feel free to fix such things yourself in the future.
