### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by NuLogicSystems** [TheAssassin/AppImageLauncher#30]
I'm getting the following error building:

> /build/appimagelauncher-git/src/AppImageLauncher/lib/AppImageKit/src/getsection.c:52:17: warning: passing argument 1 of ‘sprintf’ from incompatible pointer type [-Wincompatible-pointer-types]
>          sprintf(stderr, "Platforms other than 32-bit/64-bit are currently not supported!");
>                  ^~~~~~
> In file included from /build/appimagelauncher-git/src/AppImageLauncher/lib/AppImageKit/src/getsection.c:2:0:
> /usr/include/stdio.h:320:12: note: expected ‘char * restrict’ but argument is of type ‘struct _IO_FILE *’
>  extern int sprintf (char *__restrict __s,
>             ^~~~~~~
> /usr/bin/ld: cannot find -lbsd
> collect2: error: ld returned 1 exit status
> + cleanup
> + '[' -d /tmp/tmp.IScF7lOofe ']'
> + rm -r /tmp/tmp.IScF7lOofe
> make[2]: *** [lib/AppImageKit/src/CMakeFiles/runtime.dir/build.make:62: lib/AppImageKit/src/runtime] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1380: lib/AppImageKit/src/CMakeFiles/runtime.dir/all] Error 2
> make: *** [Makefile:152: all] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...
>

**Comment by TheAssassin** [comment]
AppImageLauncher's runtime depends on libbsd. But apparently I forgot to add a CMake check for this. I'll fix that. In the meanwhile, try installing libbsd.

**Comment by NuLogicSystems** [comment]
I build in a chroot, so I'll add it to the PKGBUILD.

**Comment by TheAssassin** [comment]
Sounds like a plan.

Actually, I think libbsd is used via `dlopen()`. See https://github.com/AppImage/AppImageKit/pull/764, especially https://github.com/AppImage/AppImageKit/pull/764/files#diff-78e827a76c059be2a244723e4814836bR289.

**Comment by NuLogicSystems** [comment]
> Are you using an old version? Or did I forget to update the submodule?

I'm pulling from git via the pkgbuild. I always build in a clean chroot so it can't be an old version.

**Comment by NuLogicSystems** [comment]
OK, so after reading all that it looks like a runtime dependency.

**Comment by TheAssassin** [comment]
Yep, accidentally linked to libbsd: https://github.com/AppImage/AppImageKit/pull/776

**Comment by NuLogicSystems** [comment]
So, I still need it installed as a dep?

**Comment by TheAssassin** [comment]
I would recommend to install it as a runtime dependency, yes. It is used to overwrite the process title and show which AppImage is run by the runtime. Without it, you just see `.../runtime`. But technically, it's an optional dependency that is opened via `dlopen()`.

There should be no other missing dependencies.

**Comment by NuLogicSystems** [comment]
OK, it builds now, thanks. I'll update the AUR in a bit..

**Comment by TheAssassin** [comment]
Thanks.
