### ISSUE TITLE
armhf binaries for Debian stretch

### ISSUE THREAD

**Issue by pinebookfan** [TheAssassin/AppImageLauncher#300]
Hello,

for the Pinebook Pro the armhf.deb should be the right installer. 
Problem is that the original Pinebook Pro Debian 9 / Strech is using
an old version of libc6 2.24. 
The deb need 2.27 or higher.
So i can't install the AppImageLauncher on it.
Can someone fix this? Or write an image for the Pinebook Pro?

Thanx!

**Comment by TheAssassin** [comment]
We support only stable (*buster*) and later releases. You can't install the official binaries on *stretch*. 

Also, for the Pinebook Pro, you should normally be able to use the *arm64* package.

**Comment by TheAssassin** [comment]
Hm... seems like there's no up to date Debian images for the Pinebook Pro linked from the wiki. Armbian is available with recent enough versions of Ubuntu and Debian, if you want to try that: https://www.armbian.com/pinebook-pro/

**Comment by pinebookfan** [comment]
With arm64 i get an error "wrong architecture". Can i do something about it?
There is a debian bullseye version to, but only the debian 9.9 version runs smooth on the pinebook.
 So i wait for debian 10 official release for the pinebook pro...

**Comment by pinebookfan** [comment]
Thanx!

**Comment by TheAssassin** [comment]
@pinebookfan we could set up build jobs to make binaries for stretch, too, but that increases our already pretty long build pipeline. See https://travis-ci.org/TheAssassin/AppImageLauncher. The build jobs require already one hour to complete, and that's only because I already implemented some performance optimizations...

Let's relabel this issue. Perhaps I'll get to adding the jobs in the next time.

**Comment by TheAssassin** [comment]
Regarding the *arm64* support, I don't know why they chose to use 32-bit for the Pinebook Pro image, but the CPU itself can in theory run *arm64* just fine. I've tested the *arm64* binaries on a regular Pinebook already, running Armbian. Perhaps some functionality would be broken there, the Armbian image doesn't fully work either.

**Comment by pinebookfan** [comment]
They chose armhf for widevine/Netflix support. A lot of user today want to watch netflix and amazon video.

**Comment by pinebookfan** [comment]
So i think the best solution is to wait for debian 10 upgrade

**Comment by pinebookfan** [comment]
*update

**Comment by TheAssassin** [comment]
Not so fast. I'll triage this as low priority enhancement. There is some work involved in making those packages, but it's possible.

**Comment by pinebookfan** [comment]
i love you :) Thanx for the support!

**Comment by TheAssassin** [comment]
The build is running, in about 20-30 minutes the binaries should be available. Please test them to make sure they work as intended.

**Comment by TheAssassin** [comment]
@pinebookfan a `xenial` binary for `armhf` is available now, it should work on your Pinebook Pro. Please test the binaries and provide some feedback. You can just reopen this issue if they don't work.
