### ISSUE TITLE
Cant'run App with --no-sandbox flag

### ISSUE THREAD

**Issue by davidganz** [TheAssassin/AppImageLauncher#302]
With AppImage with embedded Chrome Sanbox should be fine to find a way to fix the execution command.
Unable to execute AppImage: The SUID sandbox helper binary was found, but is not configured correctly.

**Comment by TheAssassin** [comment]
`setuid` is not supported in AppImages for security reasons. The image format, squashfs, prohibits the use of `setuid`.

Please refer to https://github.com/AppImage/AppImageKit for general questions on AppImage.
