### ISSUE TITLE
Files <NNN>.AppImage in the appimagelauncherfs directory shuffle randomly each login

### ISSUE THREAD

**Issue by cpw** [TheAssassin/AppImageLauncher#303]
**Describe the bug**
The files in `/run/user/<uid>/appimagelauncherfs/<NNN>.AppImage` shuffle randomly at each login, but are identified by the appimages as arg[0].

This means that for example, the keepassxc image is identified as `/run/user/<uid>/appimagelauncherfs/<NNN>.AppImage` by the keepassxc process. It drops a file in .mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json identifying itself as such.

If you install a new appimage, the numbers shuffle - I installed postman, logged out and in, and suddenly opening my browser caused postman to launch (the file above identified keepass as 000.appimage, but that had been replaced by postman, keepass was 001.appimage now).

**Expected behavior**
The numbers should remain stable.

**To Reproduce**
1. Install keepass appimage.
2. Install browser "plugin" from keepass.
3. Install another appimage.
4. Log out and in again.
5. See error

**System, software and AppImage information**
Debian Sid. KeepassXC 2.5.3, Postman

AppImageLauncher version installed: latest

**Comment by TheAssassin** [comment]
There are no guarantees on the order of these aliases, and nobody should make assumptions on these. The path of an AppImage can always change, not only with AppImageLauncherFS. It's up to the author of the app to make sure such files are up to date.

In case of KeePassXC, I can tell that I use KeePassXC myself, and I've reported the bug to them. Please see https://github.com/keepassxreboot/keepassxc/issues/3315 for a solution. I presume you've been using KeePassXC for a while *before* they made this option the default for new installations. To fix the problem, please go to the settings, "browser integration", and check the checkbox shown in the screenshot in https://github.com/keepassxreboot/keepassxc/issues/3315#issue-459646322.
