### ISSUE TITLE
Daemon searches home directory as well as specified directory

### ISSUE THREAD

**Issue by colinl** [TheAssassin/AppImageLauncher#305]
**Describe the bug**
The daemon searches /home/me as well as the directory specified in the destination directory

**Expected behavior**
It should only search the specified directory

**To Reproduce**
1. Enter an existing directory in the copy to field in the GUI
2. Enable the daemon
3. Monitor the log 

**System, software and AppImage information**
Ubuntu 19.10

AppImageLauncher version installed: 
2.1.1-travis931~f6d5926+bionic from release page

Syslog extract with /home/me/apps/appimages specified in the dialog
```
Feb 20 09:18:37 tigger systemd[3834]: Started AppImageLauncher daemon.
Feb 20 09:18:37 tigger appimagelauncherd[14589]: Searching for existing AppImages
Feb 20 09:18:37 tigger appimagelauncherd[14589]: Searching directory: /home/me
Feb 20 09:18:37 tigger appimagelauncherd[14589]: Searching directory: /home/me/apps/appimages
Feb 20 09:18:37 tigger appimagelauncherd[14589]: Found AppImage: /home/me/apps/appimages/Ultimaker_Cura-4.4.1_2baf12a636cb3a72dbbdd1fb57afe251.AppImage
Feb 20 09:18:37 tigger appimagelauncherd[14589]: AppImage integrated already, skipping
Feb 20 09:18:37 tigger appimagelauncherd[14589]: Watching directories: /home/me /home/me/apps/appimages
Feb 20 09:19:07 tigger appimagelauncherd[14589]: Directories to watch disappeared, unintegrating AppImages formerly found in there
```

**Comment by TheAssassin** [comment]
Observed this behavior in an Ubuntu VM, too. Not sure what causes this.

**Comment by TheAssassin** [comment]
Note for self: Qt's string splitting is weird on empty strings. It produces a list with an empty string as the only entry. These empty strings are, for some reason, considered to refer to the home directory.

I ignore all empty strings now, which also fixes this problem. Furthermore, non-absolute paths which also don't contain a `~` (which would be expanded to the home directory by my code) are ignored now, too, preventing further such weirdnesses.
