### ISSUE TITLE
 404  Not Found [IP: 91.189.95.83 80]

### ISSUE THREAD

**Issue by MMSuperD** [TheAssassin/AppImageLauncher#306]
sudo add-apt-repository ppa:appimagelauncher-team/stable

Ign:5 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic InRelease
Err:6 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by TheAssassin** [comment]
The PPA provides packages for Ubuntu 19.10 and above only.
