### ISSUE TITLE
DigiKam 6.4 app impage not being integrated

### ISSUE THREAD

**Issue by zilexa** [TheAssassin/AppImageLauncher#312]
**Describe the bug**
1. Before installing appimagelauncher via ppa, I could not launch .appimage files.
2. I have downloaded and moved the digikam-6.4.0.x86-64.appimage to the folder that has been set via appimagelauncher-settings. 
3. However when I double click on the image, the app starts up without any popup from appimagelauncher.

**Expected behavior**
I expected a popup asking me if I want to integrate the app (DigiKam) into the system. 
Now I can use the app, but I cannot pin it to Plank for example. 

**To Reproduce**
Steps mentioned above already. 

**Screenshots**
not applicable

**System, software and AppImage information**
Intel Core i3/32GB, Ubuntu Budgie 19.10
Digikam 64bit appimage downloaded directly from Digikam site. 

AppImageLauncher version installed: from ppa. 

**List of AppImages you tried:**
- Digikam

**Comment by zilexa** [comment]
Not a bug.
A user should NOT move the image to the folder that is being watched, instead run the app from the download folder and be a little patient. The popup will come and appimagelauncher will move the image to the right folder and take care of integration.

**Comment by TheAssassin** [comment]
You can move the file yourself, too, of course, but then the AppImage is integrated anyway through the daemon. It's not forbidden, it's explicitly supported. Once the AppImage is integrated, no matter how, the dialog is not needed anymore, that's why it's not shown in that case.
