### ISSUE TITLE
add-apt-repository  install errors

### ISSUE THREAD

**Issue by johnrosan** [TheAssassin/AppImageLauncher#313]
**Describe the bug**
During adding in PPA on Ubuntu 18 getting:
sudo add-apt-repository ppa:appimagelauncher-team/stable
Err:8 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                                                 
E: The repository 'http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Expected behavior**

**To Reproduce**

**Screenshots**

**System, software and AppImage information**
Your distribution and desktop environment (including version numbers): [...]

AppImageLauncher version installed: [...] (also include where you got it from, e.g., our release page, your distribution, ...)

**List of AppImages you tried:**
- [...]

**Comment by TheAssassin** [comment]
The PPA is only available for Ubuntu 19.04 and newer. For bionic/18.04, there's no packages available. Please install via the packages on the GitHub release page.

I need to update the README.
