### ISSUE TITLE
Ubuntu Bionic install issue

### ISSUE THREAD

**Issue by paulhew69** [TheAssassin/AppImageLauncher#316]
**Describe the bug**
Firstly I am not a Linux Superuser!
I have 2 apps that I use a lot - PrusaSlicer and Cura.
Without the interface, I cannot open stl's straight into either of the slicers.
And I like shortcuts!

**Expected behavior**
Not to start throwing errors!
Everytime I reboot and log on I get system errors.

I had problems updating the system also, reached out to Qnap and they said the appimaged daemon was causing it to throw errors and stopping the updates.

I have rebuilt the virtual machine 3 times today and about to do it again to try a different way to install appimagelauncher.

**System, software and AppImage information**
I am running Ubuntu 18.04.4 LTS
Processor Intel® Core™ i5-7500 CPU @ 3.40GHz × 4 
os type 64-bit
Virtualization LXC on a QNap NAS

AppImageLauncher version installed:I went here
https://github.com/TheAssassin/AppImageLauncher/releases/tag/v2.1.2
and selected
appimagelauncher_2.1.2-travis961.e405182.bionic_amd64.deb (after trying i386)
It asked to install and i let it.

**List of AppImages you tried:**
Prusa Slicer and Cura.

**Comment by Mpc46** [comment]
I can confirm XD the same problem happens with linux mint based on bionic

**Comment by Mpc46** [comment]
Heres the issue

![Screenshot_20200329_173022](https://user-images.githubusercontent.com/43671013/77863899-fa0e2500-71e2-11ea-8fd7-49f8696598bd.png)

**Comment by TheAssassin** [comment]
> Everytime I reboot and log on I get system errors

Please post more precise information. A "system error" could be anything.

> appimaged

appimaged is not part of AppImageLauncher. Do you mean appimaged or appimagelauncherd?

> AppImageLauncher version installed:I went here
https://github.com/TheAssassin/AppImageLauncher/releases/tag/v2.1.2
and selected
appimagelauncher_2.1.2-travis961.e405182.bionic_amd64.deb (after trying i386)

> I can confirm XD the same problem happens with linux mint based on bionic

Please post more details. What exactly is your problem?

**Comment by TheAssassin** [comment]
@Mpc46 your issue is likely not related as far as I can guess from the *very* few information @paulhew69 provided. Please open a new issue.

**Comment by Mpc46** [comment]
sorry, I meant to complain with the creator of the appimagem but multitasking is hard :v also nice app :v:

**Comment by TheAssassin** [comment]
@Mpc46 please also see https://docs.appimage.org/user-guide/run-appimages.html?highlight=fuse#i-get-some-errors-related-to-something-called-fuse for more information.

**Comment by TheAssassin** [comment]
Closing, as the reporter is unresponsive.
