### ISSUE TITLE
Add Release for Ubuntu 20.04 Focal Fossa on PPA/Launchpad Repo

### ISSUE THREAD

**Issue by ABotelho23** [TheAssassin/AppImageLauncher#319]
With the beta for Ubuntu 20.04 available, it would be great to include Focal in the release options for the Launchpad PPA Repo. https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable

Personally, I will be starting to use AppImageLauncher with Ubuntu 20.04, and I have been working on my "new install" script. I will be using ail-cli.

Cheers

**Comment by TheAssassin** [comment]
@shoogle your call.

**Comment by shoogle** [comment]
Done! @TheAssassin, thanks also for updating the stable branch.

**Comment by TheAssassin** [comment]
Thanks for updating the PPA!

**Comment by ABotelho23** [comment]
That's great, cheers!

**Comment by TheAssassin** [comment]
Indeed focal does not have a package on the PPA. Reopening therefore. @shoogle I'm not sure what went wrong. Perhaps due to the missing trigger since `stable` was not updated? Can you trigger a build by hand this time perhaps?

**Comment by shoogle** [comment]
Done, sorry! As you suspected, I had enabled automated builds for Focal but forgot to trigger a build to take place right away. I'd actually triggered one for the daily PPA and thought I'd wait for it to succeed before trying in the stable PPA, but forgot come back to do this later.

**Comment by TheAssassin** [comment]
@shoogle thanks, closing.
