### ISSUE TITLE
PPA packages have undeclared dependency

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#322]
@shoogle this one's for you, creating it here to keep track of it.

The PPA packages internally use `dpkg-architecture` to call the maintainer scripts. That indeed is fine and probably saves some code, but it creates a dependency on `dpkg-dev`. This dependency is not resolved, so on vanilla systems installation and/or uninstallation may fail.

Workaround: `apt-get install dpkg-dev`

Could you perhaps use some other tool to determine the path of the scripts?

Alternatively, we can have the scripts installed in `usr/share` (they are not binary dependent, so there is no point in having them in `usr/lib`). That would be my preferred solution.

P.S.: You forgot to escape the variable you create in your scripts where it's used. Not a big deal in this scenario, though.

**Comment by TheAssassin** [comment]
@shoogle is there any reason not to move the maintainer scripts' location? I don't see any apparent, but I'm not a packager, so maybe you have some input.

I'm preparing a minor release anyway, we could include the changes then.

**Comment by shoogle** [comment]
@TheAssassin, I copied all Debian code from here https://salsa.debian.org/sgclark-guest/appimagelauncher and only [changed two lines](https://git.launchpad.net/~appimagelauncher-team/appimagelauncher/+git/packaging/commit/?h=launchpad) necessary to make it build on Launchpad.

So the scripts are not mine and I don't know the reason for using `dpkg-architecture`, but I'm happy to add it as a dependency or change the scripts however you think best.

It's possible that `/usr/lib` is a Debian requirement, but Debian requirements are not important as far as the PPA is concerned, so feel free to use `/usr/share`.

BTW, where did this issue actually come up? Which system?

**Comment by TheAssassin** [comment]
Thanks for looking into this, @shoogle.

> BTW, where did this issue actually come up? Which system?

Someone tried the new focal `.deb` on a very fresh system. The issue was reported via IRC.

I then fetched the `.deb`, opened it up and found the code. I did assume it was your work. But apparently not.

> It's possible that /usr/lib is a Debian requirement, but Debian requirements are not important as far as the PPA is concerned, so feel free to use /usr/share.

Not as far as I know. It was my choice IIRC. I'll change to `/usr/share` then. I'll notify you via this channel. I guess we can test it using the `daily` PPA then. If it works, you have time to update the `stable` build scripts, and when I release the new version the issue will be fixed there, too.

**Comment by shoogle** [comment]
OK sounds good! I've disabled automatic builds for now so nobody ends up with a broken system. I'll reenable after the relevant scripts have been updated both there and here.

**Comment by TheAssassin** [comment]
@shoogle I've changed the path to `/usr/share/appimagelauncher/maintainer-scripts`, you can update your packaging.

**Comment by shoogle** [comment]
Done!

**Comment by TheAssassin** [comment]
When can we expect up to date packages for testing?

**Comment by shoogle** [comment]
Packages are in the [Daily PPA](https://code.launchpad.net/~appimagelauncher-team/+archive/ubuntu/daily) already.

**Comment by TheAssassin** [comment]
The scripts still use `dpkg-architecture`, which is no longer needed and needs to be removed:

```sh
DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)
export DEB_HOST_MULTIARCH
[...]
```

Please remove from `postinst` and `prerm`. Other than that, looks good!

**Comment by shoogle** [comment]
Oops! Fixed in latest daily builds.

**Comment by TheAssassin** [comment]
Testing right now!

**Comment by TheAssassin** [comment]
Just tried in a focal container:

```
Setting up appimagelauncher (202004182023-master-e1a93ad~ubuntu20.04.1) ...
/var/lib/dpkg/info/appimagelauncher.postinst: line 3: dpkg-architecture: command not found
dpkg: error processing package appimagelauncher (--configure):
 installed appimagelauncher package post-installation script subprocess returned error exit status 127
```

There are source packages for the new version available, but no binary ones yet. Do you happen to know how long it will take for them to be built?

The source packages look good, though. I think we can close the issue.

**Comment by TheAssassin** [comment]
Thanks @shoogle for fixing this issue in the packages.

**Comment by shoogle** [comment]
> There are source packages for the new version available, but no binary ones yet.

Strange. The binary ones normally show up immediately after the source ones.

[This page](https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/daily/+packages) shows the binary builds were successful, but the resulting file is still "pending publication" for some reason. Anyway, you can download the file by clicking on [amd64](https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/daily/+build/19179093) and scrolling down to "files resulting from this build".

Here's a direct link to the [Focal amd64 DEB](https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/daily/+build/19179093/+files/appimagelauncher_202004191857-master-e1a93ad~ubuntu20.04.1_amd64.deb).
