### ISSUE TITLE
Installing from PPA fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by cemeroncel** [TheAssassin/AppImageLauncher#325]
Installation from PPA on Ubuntu 20.04 fails with the following error:
```
...
Setting up appimagelauncher (202004142248-stable-e405182~ubuntu20.04.1) ...
/var/lib/dpkg/info/appimagelauncher.postinst: line 3: dpkg-architecture: command
 not found
dpkg: error processing package appimagelauncher (--configure):
 installed appimagelauncher package post-installation script subprocess returned
 error exit status 127
... 
 Errors were encountered while processing:
 appimagelauncher
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I could complete the installation after installing the `dpkg-dev` package.

**Comment by TheAssassin** [comment]
That has been reported in #322 and has been fixed already. I might have forgot to update my `stable` branch, so the `stable` packages haven't be built yet. I've just pushed, and the issue should go away the next time the packages are built on Launchpad, which should happen soon.

CC @shoogle

**Comment by shoogle** [comment]
Auto build happened and new packages are up. Let us know if you still have problems.
