### ISSUE TITLE
Ubuntu 20.04 (focal) Repo - installs fine but doesn't work

### ISSUE THREAD

**Issue by maltokyo** [TheAssassin/AppImageLauncher#327]
**Describe the bug**

As in title. I've installed focal and the first thing I installed after fresh OS install was Appimagelauncher from the official repo in the wiki here. And did a reboot after install. 

I've checked apt settings and the repo is correctly set as the Ubuntu focal PPA repo. Exactly installed as per the Wiki instructions here. 

When I double click on any of my appimages it does nothing at all. No errors but no actions. And app doesn't run. There is nothing after double clicking. 

**Expected behavior**

It asks me if I want to run or run and integrate as usual.

**Comment by TheAssassin** [comment]
@maltokyo I have tested the application on Ubuntu focal not even 30 minutes ago. Mind to tell us what flavor of Ubuntu you are using? Are you sure it is installed properly? Maybe reboot?

**Comment by maltokyo** [comment]
Hi @TheAssassin thank you for your fast reply. I'm on stock Ubuntu 20.04 desktop. The vanilla version with no extensions or anything. Have tried several reboots and several reinstalls. The app starts fine. I can see the preferences. It does say that the "updater" is nit available in red text there in the preferences.  Is there a log I can share?

**Comment by TheAssassin** [comment]
If you don't mind, you could try to call AppImageLauncher directly on an AppImage and see what that does. `AppImageLauncher my.non-integrated.AppImage`. It might be the `binfmt_misc` or MIME integration that broke on your system.

**Comment by TheAssassin** [comment]
Please try the `.deb` packages from the [release page](https://github.com/TheAssassin/AppImageLauncher/releases), too. The `bionic` one is for `focal`, too.

**Comment by maltokyo** [comment]
Will try on the weekend. Thank you

**Comment by TheAssassin** [comment]
Any update to this issue? I can still use AppImageLauncher just fine from the PPA on multiple focal VMs and computers.

**Comment by maltokyo** [comment]
I tried a complete reinstall and this time it works. Strange thing was that both times it was a fresh install.
Only issue now is that the updater says "status: not available" - do I need to do something to have that available?

**Comment by TheAssassin** [comment]
See #330.

Closing as resolved.

**Comment by personaaleatoria** [comment]
Had to install bionic package on focal for it to work.
