### ISSUE TITLE
"Content-aware" filenames broken due to MD5 digest not being encoded properly

### ISSUE THREAD

**Issue by aeropatron** [TheAssassin/AppImageLauncher#33]
Hi developpers, not sure If this is the place to add a problem,
I am using deepin linux wich is based on debian linux, after install appimagelauncher_1-alpha-travis151.git20180515.9b85939_amd64.deb , and click integrate and run.

I still can launch t from terminal with $ ./FreeCAD_0.17.13472.glibc2.17-x86_64.AppImage 

![deepinscreenshot_freecad-daily_20180515193609](https://user-images.githubusercontent.com/12184566/40073526-5c692902-5877-11e8-84b6-ed767b65ce71.png)
Launching from menu I get this error:

**Comment by TheAssassin** [comment]
@aeropatron this is the right place of course. If there's incompatibilities, they need to be reported here, so I can see and (hopefully) fix them.

I need to say that I've been using this version of FreeCAD for a while on my computer with AppImageLauncher. Could you please give me a link where you got this AppImage from? I think it might be an issue with the AppImage itself.

**Comment by aeropatron** [comment]
Hi TheAssassin,
I was about to paste the address https://github.com/FreeCAD/FreeCAD/releases .When I noticed there was a 0.18 new version!. Now, the bad news, as before, I can launch the appimage from terminal, but once I choose integrate and launch. The OS menu launcher doesnt start freecad ;(And this time silently, I mean no popup error window).

Also the appimage dissapears wich I imagine is an expected mechanism.

How can I debug with the launcher to provide you more info?, Thanks

**Comment by TheAssassin** [comment]
@aeropatron first of all, the AppImage doesn't "disappear", as the dialog says, it's moved to `$HOME/.bin` (a hidden directory, try `Ctrl+H` in your file browser).

I'll try to reproduce the issue myself in a VM.

**Comment by TheAssassin** [comment]
@aeropatron so, I launched a VM with a live Kubuntu 18.04 I happened to download for another purpose today, and I need to tell you that launching the FreeCAD AppImage works fine, even after integration. The AppImage runs fine.

Then, I tried the v17, and I found the issue that I think you're affected by. Yesterday, I implemented so-called "content-aware" filenames that should improve the user experience (see #8). Unfortunately, the MD5 digest that is calculated isn't added to the AppImages' filenames properly. It happens that there's a newline character in the v17's raw digest, which is not allowed, and therefore breaks the filename. I'm not sure why this is happening, but it should be easy to fix.

I'm not sure why Qt or the system doesn't prevent such stuff from happening, though...

**Comment by TheAssassin** [comment]
The lines in AppImageLauncher's source code appear correct to me: https://github.com/TheAssassin/AppImageLauncher/blob/master/src/shared.cpp#L344-L350 

So I suspect the problem is in libappimage's `appimage_hexlify`. I'll investigate this.

**Comment by TheAssassin** [comment]
Found the issue: I accidentally return the raw digest when there's a digest embedded in the AppImage already. I'll remove the wrong return statement, then the digest should be "hexlified" properly.

**Comment by TheAssassin** [comment]
@aeropatron please update, the issue has been resolved.
