### ISSUE TITLE
Remove make-install-ed version?

### ISSUE THREAD

**Issue by gsbhasin123** [TheAssassin/AppImageLauncher#334]
How can I remove the compiled version? I wish to do so because of this message:
```
/bin/AppImageLauncher: error while loading shared libraries: libappimageupdate.so: cannot open shared object file: No such file or directory
```
every time I run an appimage, even if I run it without appimagelauncher. How can I remove appimagelauncher, or **at least** get appimages to run again?

**Comment by TheAssassin** [comment]
I have no idea what system you are using (you have not posted the required information, but just erased the issue template). I cannot provide instructions for unknown systems. Neither my packages nor the PPA ones install anything into `/bin`.

I am also not sure if this is what you are asking for...

**Comment by gsbhasin123** [comment]
Solus linux, I compiled from source as the title indicates, with make; make install
```
ls /bin | grep A
```
this returns 
```
AppImageLauncher
AppImageLauncherSettings
```
If I move these files:
```
Failed to execute process './draw.io-x86_64-13.0.3.AppImage'. Reason:
The file './draw.io-x86_64-13.0.3.AppImage' does not exist or could not be executed.
```

**Comment by gsbhasin123** [comment]
@TheAssassin Any ideas? I can't use appimages until I get it to work...

**Comment by TheAssassin** [comment]
`make install` is not recommended, as it is not implemented in a way that allows for uninstalling without some CMake hacking.

I suspect it's the `binfmt_misc` integration that is causing the issues. Please check `install_manifest.txt` in the CMake build directory, it contains a list of all files which were installed. You can remove all these files by hand.

**Comment by gsbhasin123** [comment]
That did the trick... but didn't do the trick.
I still get
```
Failed to execute process './draw.io-x86_64-13.0.3.AppImage'. Reason:
The file './draw.io-x86_64-13.0.3.AppImage' does not exist or could not be executed.
```
, the same as when I simply moved the binaries.

**Comment by TheAssassin** [comment]
Once you removed the `binfmt.d` configs, you likely need to reboot once. That'll clear `binfmt_misc` on shutdown, and on boot it can't load the definitions any more.

`binfmt_misc` is a way on Linux to open arbitrary files with an interpreter or, in this case, launcher. It's pretty limited and annoying to use. To check its state, you should be able to `ls -al /proc/sys/fs/binfmt_misc/` on any distro. The two `appimage-type{1,2}` entries are created by AppImageLauncher.
Your error _sounds_ like `binfmt_misc` is trying to open AppImageLauncher on your application, however that fails because the executable is gone.
Once you removed the `binfmt_misc` configs and rebooted, it should work again.

**Comment by gsbhasin123** [comment]
Rebooted, didn't work.
From: `cat install_manifest.txt | grep binfmt`:
```
/usr/local/lib/binfmt.d/appimage.conf
```
`ls -al /proc/sys/fs/binfmt_misc/ | grep appimage`:
```
-rw-r--r-- 1 root root 0 May 22 12:03 appimage-type1
-rw-r--r-- 1 root root 0 May 22 12:03 appimage-type2
```
Can I remove those files?

**Comment by TheAssassin** [comment]
No, they're not real files, but virtual ones.

Have you deleted `/usr/local/lib/binfmt.d/appimage.conf` before rebooting?

**Comment by gsbhasin123** [comment]
yup, doesn't exist.

**Comment by TheAssassin** [comment]
Is solus using systemd?

**Comment by gsbhasin123** [comment]
Seems so.
```
codic@solus ~> which systemd
/bin/systemd
```

**Comment by gsbhasin123** [comment]
@TheAssassin Is there a systemd service I can disable?

**Comment by gsbhasin123** [comment]
@TheAssassin 
```
enabled
interpreter /bin/AppImageLauncher
flags: 
offset 8
magic 414901
```
Is the content of one of the appimage_type files. the other has a different magic number but is otherwise the same. I cannot move these files, so what can I do to get rid of them?

**Comment by TheAssassin** [comment]
@gsbhasin123 could you please join the AppImage IRC channel (see https://docs.appimage.org/contact.html#irc)? I think we need to do an interactive session, maybe I need to have a look at your computer.

**Comment by gsbhasin123** [comment]
sure, joined:
![image](https://user-images.githubusercontent.com/48339289/82930285-fc1e0700-9f39-11ea-8fa1-7c51cc7eb854.png)

**Comment by TheAssassin** [comment]
So, in a quick hands-on session, I was able to identify the likely cause. There were left-over configs in `/lib64/binfmt.d/appimage.conf`.

Note for self: `/usr/lib/systemd/systemd-binfmt --cat-config` (on systems > bionic) outputs the location of config files.

Also: echoing a `-1` into `/proc/sys/fs/binfmt_misc/appimage-type{1,2}` removes the integration (at least temporarily, it might be recreated on next boot if there's such `.conf` files on the system). See https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html for more information.

**Comment by TheAssassin** [comment]
Removing the file and restarting `systemd-binfmt.service` appears to work.
