### ISSUE TITLE
Appimages are stored with 4 incrementing digits as the file name, this causes issues

### ISSUE THREAD

**Issue by cyphercosis** [TheAssassin/AppImageLauncher#340]
**Describe the bug**
AppImages are stored under /run/user/1000/appimagelauncherfs/ as [D][D][D][D].AppImage. This starts with 0000.AppImage and increments. The problem is that sometimes these get renamed and that can cause issues. 

My specific issue occurred when using KeePassXC and the browser extension. The browser extension attempts to locate the KeePassXC client, which in my case is an AppImage. At some point my AppImage for KeePassXC was renamed from 0000.AppImage to 0001.AppImage, and as a result the settings for the KeePassXC browser extension became invalid. This caused the KeePassXC browser extension to open Wire Messenger instead of the KeePassXC appimage.

**Expected behavior**
Give  AppImages unique names to prevent issues like this from occurring. 

**System, software and AppImage information**
KDE Neon, up to date as of June 10th 2020.

**List of AppImages you tried:**
- Wire
- KeePassXC

**Comment by TheAssassin** [comment]
Closing as obsolete. See #361 for more information.
