### ISSUE TITLE
@Tiger862000 please ask the author of that AppImage to fix it. You can provide them the output of appimagelint, it contains the broken path (`usr/share/icons/hicolor/0x0/apps/joplin.png`).

### ISSUE THREAD

**Issue by Tiger862000** [TheAssassin/AppImageLauncher#347]
Accidentally created this. Sorry please delete

@Tiger862000 please ask the author of that AppImage to fix it. You can provide them the output of appimagelint, it contains the broken path (`usr/share/icons/hicolor/0x0/apps/joplin.png`).

_Originally posted by @TheAssassin in https://github.com/TheAssassin/AppImageLauncher/issues/323#issuecomment-660683567_

**Comment by TheAssassin** [comment]
Nevermind. Please feel free to link it back in #323.
