### ISSUE TITLE
Second Icon after Add to Favorites

### ISSUE THREAD

**Issue by brosskgm** [TheAssassin/AppImageLauncher#349]
Small error.

Ubuntu 18.04
PrusaSlicer 2.2.0 Linux x64

After integrating to applications, and then right click add to favorites. Puts an icon in task bar, but when you click to start the app, it adds another icon on the task bar for the appimage. You have two icons when app is running.

If you start the app in the applications it only adds one icon to task bar but does not give the right click option to add to favorites.

Thanks. Great app.

**Comment by mtking2** [comment]
I'm experiencing this issue as well on Ubuntu 20.04.1

Seems like there is a setting called `StartupWMClass` that needs to be set in the `.desktop` entry. Following the steps on [this askubuntu answer](https://askubuntu.com/a/975230) seemed to do the trick for me.

**Comment by brosskgm** [comment]
It doesn't put PrusaSlicer or variation of in the folder mentioned. Only Appimagelauncher is in the /usr/share/applications folder and it has two of them in there. Neither has PrusaSlicer listed in the file.

appimagelauncher.desktop
appimagelaunchersettings.desktop

The above two have in them
StartupWMClass=AppImageLauncher

Then in ~/.local/share/applications it has the Prusa desktop file, but does not have StartupWMClass=OBTAINED-VALUE
in it at all.

appimagekit_2a79544de84fe3fc328d35eaa44d19f1-PrusaSlicer.desktop
-----------------------------
[Desktop Entry]
Name=PrusaSlicer (2.2.0+linux.x64.glibc2.11)
Exec=/home/"user"/Applications/PrusaSlicer-2.2.0_linux-x64_9a2a72a31780bbd960246c33514bf3da.AppImage
Icon=appimagekit_2a79544de84fe3fc328d35eaa44d19f1_PrusaSlicer
Terminal=false
Type=Application
MimeType=model/stl;application/vnd.ms-3mfdocument;application/prs.wavefront-obj;application/x-amf;
Categories=Graphics;3DGraphics;
Keywords=3D;Printing;Slicer;
X-AppImage-Version=2.2.0+linux.x64.glibc2.11

TryExec=/home/"user"/Applications/PrusaSlicer-2.2.0_linux-x64_9a2a72a31780bbd960246c33514bf3da.AppImage
X-AppImage-Old-Icon=PrusaSlicer
X-AppImage-Old-Name=PrusaSlicer
X-AppImage-Identifier=2a79544de84fe3fc328d35eaa44d19f1
Actions=Remove;
X-AppImageLauncher-Version=2.1.4 (git commit 7cb4d70), built on 2020-07-25 07:04:46 UTC

[Desktop Action Remove]
Name=Remove AppImage from system
Icon=AppImageLauncher
Exec=/usr/lib/x86_64-linux-gnu/appimagelauncher/remove "/home/"user"/Applications/PrusaSlicer-2.2.0_linux-x64_9a2a72a31780bbd960246c33514bf3da.AppImage"
Name[ast]=Desaniciar AppImage del sistema
Name[de]=AppImage vom System entfernen
Name[en]=Remove AppImage from system
Name[es]=Eliminar Appimage del Sistema
Name[fr]=Supprimer l'AppImage du système
Name[it]=Rimuovi AppImage dal sistema
Name[nl]=AppImage deïnstalleren
Name[pl]=Usuń AppImage z systemu
Name[pt]=Remover AppImage do sistema
Name[pt_PT]=Remover AppImage do sistema
Name[ru]=Удалить AppImage из системы
Name[zh_Hans]=从系统中移除 AppImage

**Comment by mtking2** [comment]
@brosskgm Right, if it was installed with AppImageLauncher then it should already be in `~/.local/share/applications`. You will need edit your `.desktop` entry and add the `StartupWMClass`.

Here's what mine looks like:

```
[Desktop Entry]
Name=PrusaSlicer (2.2.0+linux.x64.glibc2.11)
Exec=/home/michael/Applications/PrusaSlicer-2.2.0+linux-x64-202003211856_9a2a72a31780bbd960246c33514bf3da.AppImage
Icon=appimagekit_03e478a9cdd55049166bd8edeef74ef4_PrusaSlicer
Terminal=false
Type=Application
MimeType=model/stl;application/vnd.ms-3mfdocument;application/prs.wavefront-obj;application/x-amf;
Categories=Graphics;3DGraphics;
Keywords=3D;Printing;Slicer;
X-AppImage-Version=2.2.0+linux.x64.glibc2.11
TryExec=/home/michael/Applications/PrusaSlicer-2.2.0+linux-x64-202003211856_9a2a72a31780bbd960246c33514bf3da.AppImage
X-AppImage-Old-Icon=PrusaSlicer
X-AppImage-Old-Name=PrusaSlicer
X-AppImage-Identifier=03e478a9cdd55049166bd8edeef74ef4
Actions=Remove;
X-AppImageLauncher-Version=2.1.3 (git commit 7408819), built on 2020-04-25 20:19:33 UTC
StartupWMClass=prusa-slicer

[Desktop Action Remove]
Name=Remove AppImage from system
Icon=AppImageLauncher
Exec=/usr/lib/x86_64-linux-gnu/appimagelauncher/remove "/home/michael/Applications/PrusaSlicer-2.2.0+linux-x64-202003211856_9a2a72a31780bbd960246c33514bf3da.AppImage"
```

**Comment by brosskgm** [comment]
Ahhh, ok. That helps. I'll do that now and see what happens.

Thanks

**Comment by brosskgm** [comment]
That worked. Thank you for your reply's/help on a Sunday even.

**Comment by brosskgm** [comment]
I will close it now.

**Comment by mtking2** [comment]
It would be nice if AppImageLauncher added `StartupWMClass` to the entry automatically. Maybe this could still be considered a bug that they could work on :thinking:

**Comment by TheAssassin** [comment]
@mtking2 we cannot just auto-fix every AppImage's desktop file unfortunately, as we'd have to make assumptions on applications, which is never really a good idea. Let's continue in #342. And thanks for helping @brosskgm.
