### ISSUE TITLE
Rofi Can't find Cura AppImage

### ISSUE THREAD

**Issue by Aksman0** [TheAssassin/AppImageLauncher#352]
I am using linux Mint 20.  

I installed Cura through apt, but it was an old version so I wanted to remove it.  I ran `sudo apt remove --purge cura`, `sudo apt autoclean` and`sudo apt autoremove` to remove it.

I installed the AppImage for cura and opened it through terminal, it worked.  I later installed AppImageLauncher so I could open it through rofi.  After opening the AppImage file with AppImagelauncher It moved it to a folder in /home called Applications.  It worked opening Cura with AppImageLauncher also.

I opened rofi , but could not locate Cura.  I did find CuraEngine, which is the terminal version without a gui.  CuraEngine did not open from rofi, so I think it might be residue from my attempt to remove the original install.

My problem is that I cannot open cura from rofi.  I can open it from the default mint menu and pin it the panel though.

Is there a way to make AppImages from ApImageLauncher open from rofi?

**Comment by TheAssassin** [comment]
I don't know what Rofi is, I have no idea what exactly you're trying to achieve, and you didn't use the issue template, so important information is missing. You seem to have misconceptions about AppImage in general. One does not install AppImages, they're just integrated by this tool into the desktop.

Please provide more information. I think the issue might not be in AppImageLauncher but in this Rofi tool. I presume it's some sort of file manager. Most other file managers implement the XDG/FreeDesktop standards with regards to MIME and therefore *can* open AppImages just fine, especially when AppImageLauncher is installed. Perhaps you need to file an issue with them.

**Comment by ByJumperX4** [comment]
rofi is a command launcher like dmenu, rofi doesn't support .desktop entries, it's only launching commands in your path, you may want to use Albert instead: https://albertlauncher.github.io . This one supports .desktop entries

**Comment by TheAssassin** [comment]
I suppose the issue is not within AppImageLauncher then. Thanks @ByJumperX4 for clarifying.

**Comment by rafaelpereiradeoliveira** [comment]
I use i3wm with rofi and was able to access creating a link to AppImage in /usr/bin
