### ISSUE TITLE
SUID sandbox helper not configured correctly

### ISSUE THREAD

**Issue by michael-wenyon** [TheAssassin/AppImageLauncher#353]
I've now had two apps (Joplin and Bitwarden) that won't launch after AppImageLauncher integration. Both gave similar error messages (below) when launch was attempted from the command line.

KeePassXC was installed and is launchable.

I installed AppImageLauncher by .deb file in a new installation of Debian testing (Bullseye), following the Debian dpkg install directions given here on GitHub. 

My version is:

appimagelauncher_2.1.4-travis987.7cb4d70.bionic_amd64.

```
./Joplin-1.0.233_7d1656b342c38ede4aa5e811cf0747e3.AppImage 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[9885:0817/113103.514410:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_JoplinamNOhD/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```

**Comment by michael-wenyon** [comment]
Just to elaborate, there is no longer a '.mount_JoplinamN0hD' folder in /tmp. But there is a similar one for pCloud, an AppImage that seems to work OK with AppImageLauncher. Here's the line of the 'ls -la' command for that folder:

`
drwxrwxr-x  5 root       root          0 Jul 27 06:48  .mount_pcloud8y8iRY
`

**Comment by TheAssassin** [comment]
This electron sandboxing stuff never works with AppImages, as root-owned files in AppImages would be a security nightmare. There are open issues about that in the relevant places. It's not AppImageLauncher's fault, the AppImages won't work even without it.

@probonopd could you please tell us the flag that one can pass to deactivate this sandboxing stuff temporarily to make the AppImages work?

**Comment by probonopd** [comment]
Electron's `--no-sandbox`?

**Comment by probonopd** [comment]
Or `sudo sysctl kernel.unprivileged_userns_clone=1`.

**Comment by michael-wenyon** [comment]
Downloading a new copy of Joplin, putting it in Applications and then launching it with this:
```
$ ./Joplin-1.0.233.AppImage --no-sandbox
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```
When the AppImageLauncher window came up, I chose  'run once', not integrate, but the second time I chose integrate, it also launched Joplin, and in the Terminal I got this:

```
$ ./Joplin-1.0.233.AppImage --no-sandbox
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Extracting usr/share/icons/hicolor/0x0/apps/joplin.png to "/home/michael/.local/share/icons/hicolor/0x0/apps/appimagekit_7cb2b0dd48a1f6bbfdc23da44b8aa43e_joplin.png"
WARNING: Unable to resize the application icon into a 128x128 image: "Unable to load image.". It will be written unchanged.
WARNING: Unable to resize the application icon into a 256x256 image: "Unable to load image.". It will be written unchanged.
gtk-update-icon-cache: Cache file created successfully.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

**Comment by michael-wenyon** [comment]
Anyway, thanks for the quick reply. I am at least able to download my Joplin notes that tell me how to set up Debian on the new installation!

I understand it is not an AppImageLauncher issue. With Bitwarden I am now running the flatpak which does not have this issue.

**Comment by probonopd** [comment]
What happens when you run  `sudo sysctl kernel.unprivileged_userns_clone=1`?

**Comment by michael-wenyon** [comment]
Now, I get: `kernel.unprivileged_userns_clone = 1`

I got something inconclusive before or an error.

**Comment by probonopd** [comment]
Does the AppImage run then?

**Comment by michael-wenyon** [comment]
Good question: my Joplin initital download is still running; I will try again when it finishes.

**Comment by michael-wenyon** [comment]
Answer: Joplin opened normally from the GUI.

**Comment by probonopd** [comment]
So it's the usual Chromium/Electron issue then.

**Comment by TheAssassin** [comment]
@probonopd do you have a GitHub issue link we could ping from here before closing?

**Comment by probonopd** [comment]
References:
* https://docs.appimage.org/user-guide/troubleshooting.html#i-have-issues-with-electron-based-appimages-and-their-sandboxing
* https://github.com/electron/electron/issues/17972
* https://github.com/AppImage/AppImageKit/issues/1039

**Comment by michael-wenyon** [comment]
You probably already know this, but `sudo sysctl kernel.unprivileged_userns_clone=1` does not persist between reboots of the system. Setting it again worked OK however.

**Comment by probonopd** [comment]
To permanently enable the feature, it is recommended to create a new file in `/etc/sysctl.d/`. For your convenience, we have prepared the following command which creates the file on the fly:

```
echo kernel.unprivileged_userns_clone = 1 | sudo tee /etc/sysctl.d/00-local-userns.conf
```

Source: https://docs.appimage.org/user-guide/troubleshooting.html#configure-unprivileged-sandboxes

**Comment by TheAssassin** [comment]
Thanks @probonopd. Closing.
