### ISSUE TITLE
After installing the software, replace the new AppImage application and open the old one

### ISSUE THREAD

**Issue by foreverhot** [TheAssassin/AppImageLauncher#355]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**Screenshots**

**System, software and AppImage information**
Your distribution and desktop environment (including version numbers): [...]

AppImageLauncher version installed: [...] (also include where you got it from, e.g., our release page, your distribution, ...)

**List of AppImages you tried:**
- [...]

**Comment by TheAssassin** [comment]
No content provided, not even the template was removed. That's a new record. Congratulations.

Closing as invalid.
