### ISSUE TITLE
Run app from command line

### ISSUE THREAD

**Issue by mariusa** [TheAssassin/AppImageLauncher#356]
**Is your feature request related to a problem? Please describe.**
I need to start apps from command line, not just from desktop. 

**Describe the solution you'd like**
```
ail-cli ls # list integrated apps
ail-cli run beekeeper arg1 arg2 # start 'beekeeper' app with given command line arguments
```

Note the short, friendly, no-spaces app name. It shouldn't be 'Beekeeper_d7fccc7b55a7ddc2d691ddc643f20d11'

**Describe alternatives you've considered**
Couldn't find in README how to do this.

**Comment by TheAssassin** [comment]
AppImages are all independent from each other. There's no concepts like "these 5 AppImages belong to the same app and can uniquely identified by the name `abcdefg`". This kind of management is outside the scope of AppImageLauncher anyway.

What we could do is provide an option in the settings to deactivate what I call "content-aware filenames" (i.e., the hashes which are inserted after the filename before the `.AppImage` extension).

**Comment by mariusa** [comment]
> What we could do is provide an option in the settings to deactivate what I call "content-aware filenames"

This would help.

My goal is to assign a keyboard shortcut to an app. For that, one needs a consistent command line (same between upgrades)
With this option implemented, what would be that command line to launch an app?

Thanks!

**Comment by shoogle** [comment]
You could create a "shim" for your AppImage. Create a text file at `~/bin/beekeeper` with this as its contents:

```sh
#!/bin/sh
exec "${HOME}/Applications/Beekeeper-X.Y.Z_d7fccc7b55a7ddc2d691ddc643f20d11.AppImage" "$@"
```
Make it executable and you can now call `beekeeper` on the command line.

Of course the shim will break if the AppImage name changes (e.g. if you install a new version). Use this instead to survive updates:

```sh
#!/bin/sh
exec "$(ls "${HOME}/Applications/Beekeeper-"*.AppImage | tail -n1)" "$@"
```

If multiple Beekeeper AppImages are installed then this runs the one with the highest version number.

**Comment by mariusa** [comment]
Thank you! It works. (note, it's Beekeeper_ instead of Beekeeper-)

What do you think about having the 2nd "shim"provided by ail-cli, so one can simply execute
```
ail-cli run Beekeeper arg1 arg2 # start 'Beekeeper' app with given command line arguments
```

One wouldn't need to create another script in this case, but would rely on provided ail-cli.

**Comment by TheAssassin** [comment]
> My goal is to assign a keyboard shortcut to an app. For that, one needs a consistent command line (same between upgrades)
With this option implemented, what would be that command line to launch an app?

Well, `ail-cli run` will never be implemented, the reasons were explained above. There's no 100% reliable way to do it.

I use a shell script to launch ReText as an AppImage from the CLI, which I called `retext`:

```sh
#! /bin/bash

set -x

appimage="$(find ~/Applications/ -type f -executable | grep -i retext | sort -h | tail -n1)"

exec "$appimage" "$@"
```

This works very well with specific AppImages like ReText.

You could generalize this script to just use its own name in the `grep` call. Then, you can create symlinks for all the applications you need.

**Comment by mariusa** [comment]
Appreciate your help. I'll use the script you provided.
