### ISSUE TITLE
Clarify context menu 'Remove AppImage from system'

### ISSUE THREAD

**Issue by mariusa** [TheAssassin/AppImageLauncher#357]
**Describe the bug**
README mentions a context menu, I'm not sure which one:
![screen](https://user-images.githubusercontent.com/1283842/91698834-04f72800-eb7c-11ea-818d-9acd51772da3.png)
![Screenshot from 2020-08-31 11-19-16](https://user-images.githubusercontent.com/1283842/91698839-058fbe80-eb7c-11ea-964f-39e4251b9428.png)

Assuming the 1st, since file manager right click has no context menu:

Context menu says 'Remove AppImage from system'

**Expected behavior**

I don't want that. 'AppImage' means the ability to run AppImages.

I want to 'Uninstall BeekeeperStudio' or  'Remove BeekeeperStudio from system'

**Comment by TheAssassin** [comment]
The README refers to the context menu you got in your lower screenshot, the one you can find in your apps launcher. AppImageLauncher features the management of AppImages through this context menu, it doesn't require additional UIs for basic tasks like updating or removing AppImages.

"Uninstall" is not applicable, AppImages are not installed but just integrated. They run fine without tools like AppImage.

Why would it make any sense to repeat the application name in the context menu if you can see it on the left anyway?

**Comment by mariusa** [comment]
> Why would it make any sense to repeat the application name in the context menu if you can see it on the left anyway?

Maybe it's just me (new AppImage user), but I've read that label as "Remove AppImage capabilities from system", which means to no longer be able to run AppImages. 
Understanding that "AppImage" refers to this particular app AppImage file, it makes sense now. Feel free to close this. Thanks

**Comment by TheAssassin** [comment]
I see, thanks for explaining your thoughts. Maybe inserting `this` would clarify it?

**Comment by mariusa** [comment]
Yes, that would clarify! Thanks

**Comment by TheAssassin** [comment]
Updated the names. It'll require some time until the translations will be in sync again. I'll push the changes soon.

By the way: the reason I want to keep the word "AppImage" in the text is perfectly demonstrated in your screenshot. Many desktops show the AppImageLauncher logo in front of the entries, but yours (GNOME?) doesn't. If the logo was shown, one could easily recognize that the entries are AppImage specific.
