### ISSUE TITLE
could not load map file

### ISSUE THREAD

**Issue by 1980s-housewife** [TheAssassin/AppImageLauncher#360]
**Describe te bug**
I'm on Manjaro KDE Plasma and cannot run AppImages, it says "Failed to register AppImage in AppImageFS, could not load map file" or something along those lines

**Expected behavior**
For it to open the appimage

**Screenshots**
![image](https://user-images.githubusercontent.com/17932849/93923785-bfa5c080-fd0b-11ea-9722-df586603ba61.png)
^ Issue and OS in Neofetch

**System, software and AppImage information**
KDE, Latest AppImage

AppImageLauncher version installed: [...] (also include where you got it from, e.g., our release page, your distribution, ...)
latest

**Comment by TheAssassin** [comment]
Tip for the future: in an issue template, you are supposed to replace the stubs with own content. I've edited them out of your post.

"Latest AppImage" is not an answer. Please note down your exact version number, where you got the application, ...

If you can, please try running the AppImage from the terminal and watch for messages related to the issue. If there's any, a screenshot would be appreciated.

**Comment by TheAssassin** [comment]
Closing as obsolete. See #361 for more information.
