### ISSUE TITLE
Apps can not start on ZorinOS 15 Lite, 32 bit.

### ISSUE THREAD

**Issue by bom64** [TheAssassin/AppImageLauncher#365]
AppImageLauncher is starting, but the AppImage is not started. The app you like start using AppImageLauncher do not showup.
Is it me that do something wrong?

But when I run
> sudo add-apt-repository ppa:appimagelauncher-team/stable
> sudo apt update
> sudo apt install appimagelauncher

> sudo apt update

give
Err:11 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]

Is it normal?

**Comment by TheAssassin** [comment]
Never heard of Zorin OS, and no intention to support exotic distros from an Ubuntu PPA.

bionic is not supported by the PPAs, which you could have found out:

- in the README
- on the PPA page
- by clicking on dist (http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu/dists/)

Also, template not followed.
