### ISSUE TITLE
Integrating Appimages Causes Other App Icons to Go Invisible

### ISSUE THREAD

**Issue by ThisNekoGuy** [TheAssassin/AppImageLauncher#366]
**Describe the bug**

Installing appimages causes some applications' KDE status panel icons to dissapear (like Discord and LBRY).
I've had it happen with Pop_OS, Manjaro, and Fedora.

**Expected behavior**

Installing appimages shouldn't indirectly affect the icons of other applications.

**To Reproduce**
1. Download an appimage
2. Run it with AppimageLauncher
3. _Integrate and run_
4. Icons of other applications go invisible

**Screenshots**

![image](https://user-images.githubusercontent.com/28468662/96503667-3eadec00-1219-11eb-93d6-dde219ebbe37.png)

**System, software and AppImage information**

Fedora 32 (KDE "Spin")

AppImageLauncher version installed: x86_64 RPM (Probably the 2.2.0 release? from the release page)

**List of AppImages you tried:**
- LBRY
- Glimpse

**Comment by TheAssassin** [comment]
We just call `update-desktop-database` and `gtk-update-icon-cache`. They might break the icons cache for some reason, I'm not sure. KDE's icon handling is quite buggy, we've discussed that a few times beforehand. You might want to open an issue there.

I won't be able to try to reproduce without exact versions of all tools and distros. There's a reason we have an issue template. I won't work on this issue unless you fill in the initially requested information.

**Comment by kmaterka** [comment]
I can confirm - it is a bug in KDE's system tray. I'll try to fix it in KDE.

**Comment by ThisNekoGuy** [comment]
It's finally been fixed in KDE Plasma 5.22
@kmaterka If you're the one who fixed it, thank you, it's been driving me nuts for ages.

**Comment by TheAssassin** [comment]
@ThisNekoGuy can you please provide a link, e.g., to a changelog?

**Comment by ThisNekoGuy** [comment]
@TheAssassin 
[The changelog](https://kde.org/announcements/changelogs/plasma/5/5.21.5-5.22.0/)
[The Bugzilla Report](https://bugs.kde.org/show_bug.cgi?id=433557)

I didn't see it in the changelog but it's in the bugzilla report and it worked properly for me after I updated to 5.22

**Comment by TheAssassin** [comment]
It is in the changelog:

> [dataengines/sni] Reapply IconThemePath on icon theme change. Commit. Fixes bug #433557
