### ISSUE TITLE
AppImage not launching in Solus 4.1

### ISSUE THREAD

**Issue by Mennaruuk** [TheAssassin/AppImageLauncher#374]
**Describe the bug**
I granted permission to the AppImage by right clicking it -> Properties -> Permissions -> check Allow executing file as program. Additionally, I ran in terminal `sudo chmod +x /home/name/Downloads/appimagelauncher-lite-2.2.0-travis1016-48662df-x86_64.AppImage`. AppImage refuses to launch even after waiting several minutes. I opened an AppImage of a different program ([youtube-dl-gui](https://github.com/jely2002/youtube-dl-gui)) and it launched. Unsure if this is an issue with the AppImage, Solus, or my computer.

**Expected behavior**
After granting the AppImage permission then executing it, it should properly launch.

**To Reproduce**
1. Download latest release. In my case, it is appimagelauncher-lite-2.2.0-travis1016-48662df-x86_64.AppImage.
2. Right click on AppImage file.
3. Click Properties.
4. Click Permissions tab.
5. Check the box for "Allow executing file as program."
6. Exit Properties.
7. Double-click AppImage file.

**Screenshots**
[Link to Streamable screen recording](https://streamable.com/cpgg77).

**System, software and AppImage information**
Solus 4.1 (Budgie)

AppImageLauncher version installed: 2.2.0 (obtained from Github releases)

**List of AppImages you tried:**
- appimagelauncher-lite-2.2.0-travis1016-48662df-x86_64.AppImage
- appimagelauncher-lite-2.2.0-travis1016-48662df-i386.AppImage

**Comment by christidisc** [comment]
This appears to be happening because AppImageLauncher requires an option to do anything, but double clicking executes it without any options. Try installing it from a terminal with `./appimagelauncher-lite-2.2.0-travis1016-48662df-x86_64.AppImage install`

**Comment by Mennaruuk** [comment]
> This appears to be happening because AppImageLauncher requires an option to do anything, but double clicking executes it without any options. Try installing it from a terminal with `./appimagelauncher-lite-2.2.0-travis1016-48662df-x86_64.AppImage install`

Your solution worked! Thanks a lot 🙏. I tried running the AppImage on another computer using a different district (Fedora), and again, it didn’t work. I had to run this precise command in terminal to get it installed. I don’t know why the regular method isn’t working to at least install AppImage Launcher.

**Comment by TheAssassin** [comment]
>  don’t know why the regular method isn’t working

I don't know what "the regular method" is supposed to be. In any case, this is a usage error. See https://github.com/TheAssassin/AppImageLauncher#differences-between-regular-and-lite-version for more information.

Please note that `sudo` is *not* required for the Lite version. That's the big difference to the regularly installed version.

Oh, and given that you're using Solus, perhaps check #139, someone's suggested AppImageLauncher for official packaging at https://dev.getsol.us/T7576. The folks at Solus seem to think appimaged was still an option, but it has been deprecated, and AppImage doesn't provide an official "solution" any more (it's not like appimaged and AppImageLauncher would be comparable UX wise anyway).
