### ISSUE TITLE
Libcurl13 dependency error: Package not available

### ISSUE THREAD

**Issue by arjunvijayanathakurup** [TheAssassin/AppImageLauncher#375]
**Describe the bug**
Installation failed due to lack of dependency issue

Tried installing the appimagelauncher_2.2.0-travis1016.48662df.xenial_amd64.deb package using `sudo apt install ./appimagelauncher_2.2.0-travis1016.48662df.xenial_amd64.deb` as well as using `sudo dpkg --install appimagelauncher_2.2.0-travis1016.48662df.xenial_amd64.deb`, but returned error as some packages (libcurl13) couldn't be installed.

**Expected behavior**

An error stating that I have unmet dependencies even after trying to install libcurl13(got a missing package error while trying to install manually). Currently, libcurl14 is available and the libcurl13 package is not available.

**To Reproduce**
1. Go to 'https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous'
2. Click on 'https://github.com/TheAssassin/AppImageLauncher/releases/download/continuous/appimagelauncher_2.2.0-travis1016.48662df.xenial_amd64.deb' and download it.
3. Try installing using `sudo apt install ./appimagelauncher_2.2.0-travis1016.48662df.xenial_amd64.deb` or using `sudo dpkg --install appimagelauncher_2.2.0-travis1016.48662df.xenial_amd64.deb`

**Screenshots**

**apt install error**
![image](https://user-images.githubusercontent.com/25499018/100418716-3e6eff00-30a9-11eb-8ada-f0676c9a10ee.png)

**dpkg install error**
![image](https://user-images.githubusercontent.com/25499018/100419657-fe108080-30aa-11eb-9a27-7354679a3ee3.png)

**System, software and AppImage information**

Distribution: Pop!_ OS 20.04 LTS, Ubuntu Xenial based.
Desktop Environment: GNOME

AppImageLauncher version installed: 2.2.0 (Obtained from GitHub releases) -->

**List of AppImages you tried:**
- appimagelauncher_2.2.0-travis1016.48662df.xenial_amd64.deb

**Comment by TheAssassin** [comment]
> Distribution: Pop!_ OS 20.04 LTS, Ubuntu Xenial based.

It is clearly *not* xenial based, but bionic based. The README already instructs you to install the `bionic` version. Please try that one, it should work just fine then.

**Comment by arjunvijayanathakurup** [comment]
> > Distribution: Pop!_ OS 20.04 LTS, Ubuntu Xenial based.
> 
> It is clearly _not_ xenial based, but bionic based. The README already instructs you to install the `bionic` version. Please try that one, it should work just fine then.

Absolutely, it was the issue with the `xenial-based` version. Installed successfully with the installation of the `bionic` version.
