### ISSUE TITLE
Appimage launcher not launching Tutanota's Image

### ISSUE THREAD

**Issue by najum98** [TheAssassin/AppImageLauncher#376]
Hello there,
I have installed appimagelauncher in Kali Linux latest release, I have configured Tutanota's appimage with it, but double clicking the image or through start menu isn't launching the Tutanota app, nothing happens. How can I fix it?

**Comment by dginovker** [comment]
Do you get any additional output if you run it through command line?

**Comment by najum98** [comment]
It runs if I execute it from terminal, but issue is when I try to launch it by clicking.

**Comment by TheAssassin** [comment]
Issues which do not follow the template won't be worked on any more. Feel free to fill in the required information, then this issue can be reopened.
