### ISSUE TITLE
Renaming icon when installing Appimage results in a separate dock item

### ISSUE THREAD

**Issue by xcffl** [TheAssassin/AppImageLauncher#377]
**Describe the bug**
~~On Wayland, `StartupWMClass` doesn't take any effect. As `AppImageLauncher` changes `Icon` field in desktop entry and the name of icons, on X11 it works well. However, [GNOME on Wayland GTK](https://developer.gnome.org/gtk4/stable/gtk-migrating-3-to-4.html#id-1.7.4.3.14 requires) same name of application id and icon. So the result is the (running) app won't get correct icon (will get an empty icon instead if the binary doesn't have an icon within). And~~ the running app on the dock will have an **distinct** item rather than merged with the pinned icon.

**Expected behavior**

App are decorated with correct icon on the dock/dash/tray.

**To Reproduce**
1. Go to Wayland (GNOME)
2. Pinned an appimage icon produced by `AppimageLauncher` to the dock/tray
3. Click on that pinned icon
4. There will be a distinct (duplicated) dock item for the running app

**Screenshots**

AppImageLauncher version installed: [...] (also include where you got it from, e.g., our release page, your distribution, ...) -->
https://github.com/TheAssassin/AppImageLauncher/releases/download/continuous/appimagelauncher-2.2.0-travis1016.48662df.x86_64.rpm
**List of AppImages you tried:**
- https://github.com/yang991178/fluent-reader

**Comment by xcffl** [comment]
Well, it's not quite true. `StartupWMClass` is still valid, and it should be set correctly (corrsponds to the application id) when creating the Appimage. If you see duplicated icon, set `StartupWMClass` to the name of the running app shown in the dock.

**Comment by TheAssassin** [comment]
Thanks for the follow-up. This'll help other people as well.
