### ISSUE TITLE
Disabling AppImageLauncher only for one app

### ISSUE THREAD

**Issue by simone-viozzi** [TheAssassin/AppImageLauncher#378]
**Describe the bug**

Appimage fail to integrate jetbrains toolbox, and after failing it continue to ask to integrate, but fail because the binary is already moved to `~/Apllications`. 
The toolbox put his files in `~/.local/share/JetBrains/Toolbox` and have it's own update system.
I saw that there is a flag to disable the integration for one app only (see #78), but it doesn't work for me (or i don't know how to use it).
While in the bin folder i launch:
`APPIMAGELAUNCHER_INTEGRATION=FALSE ./jetbrains-toolbox`
it trigger the popup asking to integrate anyway.  

**Expected behavior**

The popup does not appear and the app open.

**To Reproduce**
1. download the archive with [jetbrains toolbox](https://www.jetbrains.com/toolbox-app/download/download-thanks.html)
2. extract it and launch the installer
3. Appimage ask to integrate the app (twice actually), if you press "run once" it run fine.

**System, software and AppImage information**

OS: Manjaro Linux x86_64
DE: Plasma 5.20.4

AppImageLauncher version installed: 2.2.0

**List of AppImages you tried:**
- the jetbrains toolbox
- others work fine

**Comment by TheAssassin** [comment]
> `APPIMAGELAUNCHER_INTEGRATION`

That doesn't exist. There's `APPIMAGELAUNCHER_DISABLE`, though.

In general, this is likely a duplicate of #78 and #239.

**Comment by simone-viozzi** [comment]
oh, thanks, now it work!

thanks a lot!
