### ISSUE TITLE
Cannot add the rep on Ubuntu 20.10 - no dist template error

### ISSUE THREAD

**Issue by zilexa** [TheAssassin/AppImageLauncher#379]
```
sudo add-apt-repository -y ppa:appimagelauncher-team stable
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 330, in <module>
    addaptrepo = AddAptRepository()
  File "/usr/bin/add-apt-repository", line 35, in __init__
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Ubuntu/groovy
```
On a clean install of Ubuntu Budgie 20.10.

**Comment by TheAssassin** [comment]
I see there's a build on Launchpad: https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable
I found a package that installs fine in a Docker container: http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu/pool/main/a/appimagelauncher/appimagelauncher_202010290530-stable-0f91801~ubuntu20.10.1_amd64.deb

@shoogle any ideas? I am not sure what could cause that error... It might be a bug in `software-properties-common`?

@zilexa can you add any _other_ PPAs?

**Comment by zilexa** [comment]
Strange, this morning I tried again and did not have this error! But tonight that same laptop crashed: SSD failure. Must have had issues with the SSD last night.
Thanks for the quick reply. I'll close it.
