### ISSUE TITLE
Lack of support for libcurl4, issues in Ubuntu 20.10

### ISSUE THREAD

**Issue by CyanCoding** [TheAssassin/AppImageLauncher#383]
**Describe the bug**
I've used AppImageLauncher before and it has always worked. When upgrading my system to Ubuntu 20.10, I tried installing and it _partially_ 
failed because libcurl3 was not installed. It wouldn't launch without it.

In Ubuntu 20.10, libcurl3 isn't used anymore and when you try to install it, it tells you to use libcurl4 instead. However, AppImageLauncher does not appear to have support for libcurl4.

I tried a few other workarounds to allow my system to have both libcurl3 and libcurl4, like the solution [here](https://askubuntu.com/questions/1061431/how-to-have-both-libcurl3-and-libcurl4-installed-at-same-time), but that PPA doesn't work with Ubuntu 20.10.

**Expected behavior**
The AppImageLauncher should install with no issues and run fine with libcurl4 or another available workaround.

**To Reproduce**
1. Install AppImageLauncher on Ubuntu 20.10 (it won't even let you unless you're doing it from the terminal).
2. Try opening it - doesn't work.
3. Notice how the installation failed because of a lack of libcurl3, and you can't install libcurl3 on Ubuntu 20.10 from my knowledge.

**Screenshots**
[install fail](https://user-images.githubusercontent.com/30013496/103177133-50c19180-483d-11eb-9cac-0d136529d2af.png)
[libcurl3 issue](https://user-images.githubusercontent.com/30013496/103177134-515a2800-483d-11eb-9379-4b583e60a155.png)

**System, software and AppImage information**
Bodhi Linux running Ubuntu 20.10 x86_64
AppImageLauncher 2.2.0 from releases. I also tried launching the AppImage version, but it did not launch (don't worry, I made it executable first).

**List of AppImages you tried:**
- v2.2.0 Deb
- v2.2.0 AppImage
- v2.1.4 Deb

**Comment by TheAssassin** [comment]
Your bug report doesn't name the package you tried to install. But at least it shows you attempted to use the `xenial` one. The README provides an _explicit_ statement about this change, and instructs you to install the `bionic` package. 

To everyone else who will find this issue: Please stop opening new issues about this. We've seen more than one. For instance https://github.com/TheAssassin/AppImageLauncher/issues/375.

**Comment by TheAssassin** [comment]
Closing as resolved, also because author hasn't reacted yet.
