### ISSUE TITLE
duckstation packages not recognized

### ISSUE THREAD

**Issue by eadmaster** [TheAssassin/AppImageLauncher#384]
when i double click this package it just starts like a normal binary:
https://github.com/stenzek/duckstation/releases/download/latest/duckstation-qt-x64.AppImage

Passing it to AppImageLauncher as an arg has the same effect

**Comment by TheAssassin** [comment]
Issues that don't follow the issue template will not be worked on. I am not willing to ask the same questions that the form asks over and over again.
