### ISSUE TITLE
Monero GUI Wallet not Recognized

### ISSUE THREAD

**Issue by erassar** [TheAssassin/AppImageLauncher#389]
**Describe the bug**
The Monero GUI wallet is not recognized as an AppImage file by the Launcher. The error code is: "Not an Appimage: monero-wallet-gui-AppImage". AppImageLauncher is working fine for every other AppImage file. Launching AppImageLauncher via the shell with root permission leads to the exact same error code.

**Expected behavior**
I'd expect the AppImage file to be correctly integrated into the system.

**Screenshots**
[error code](https://imgur.com/RXWEos8)

**System, software and AppImage information**
[neofetch](https://imgur.com/8LTJiwu)

**AppImageLauncher version**
2.2.0 (appimagelauncher_2.2.0-travis995.0f91801.bionic_amd64.deb); downloaded from GitHub

**List of AppImages you tried:**
- Monero GUI
- Trezor Suite
- Electrum
- Balena Etcher

**Comment by TheAssassin** [comment]
You need to provide links to the _exact_ AppImages that don't work for you.

**Comment by TheAssassin** [comment]
No reply seen, closing.
