### ISSUE TITLE
can not run cmake for 2.2.0

### ISSUE THREAD

**Issue by jriddell** [TheAssassin/AppImageLauncher#393]
Downloading the v2.2.0 tar I can't run cmake successfully, it complains about git versions

AppImageLauncher-2.2.0/build>cmake..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/versioning.cmake:37 (message):
  Failed to gather commit ID via git command, trying to read cache file
Call Stack (most recent call first):
  CMakeLists.txt:6 (include)

CMake Error at cmake/versioning.cmake:43 (message):
  Could not find git commit cache file, git commit ID not available for
  versioning
Call Stack (most recent call first):
  CMakeLists.txt:6 (include)

-- Configuring incomplete, errors occurred!
See also "/home/jr/src/neon-packaging/appimagelauncher/tar/AppImageLauncher-2.2.0/build/CMakeFiles/CMakeOutput.log".

**Comment by TheAssassin** [comment]
@jriddell I wonder whether you're using the tarball or the Git repository. The source tarball from the release page should contain a `VERSION` file containing the git hash. When using Git instead, CMake expects to find the `.git` directory to be able to gather the commit information.

**Comment by jriddell** [comment]
mm yes I'm using the tar made from the tag not the .source.tar.gz file, sorted.
