### ISSUE TITLE
Appimagelauncher is in English however my system language is Chinese.

### ISSUE THREAD

**Issue by linlinger** [TheAssassin/AppImageLauncher#398]
**Describe the bug**

Appimagelauncher is English however my system language is Chinese
system spec:
Arch Linux with xfce4 installed 
LANG=zh_CN.UTF-8 in locale.conf 
If you need more I will show you 
**Expected behavior**

It should to show me some Chinese.BTW I did some translation
**To Reproduce**
1. echo "LANG=zh_CN.UTF-8: > /etc/locale.conf
2. Restart your Linux and reopen it

**Screenshots**

Arch Linux kernel 5.10.10 xfce 4.16
AppImageLauncher version installed: [...] (also include where you got it from, e.g., our release page, your distribution, ...) -->
I installed using aur .and the version is  2.2.0-4
**List of AppImages you tried:**
- 
-

**Comment by TheAssassin** [comment]
Duplicate of #335. Please stop opening duplicate issues.

**Comment by linlinger** [comment]
sorry for that. I will  search the issues before opening a new one
