### ISSUE TITLE
Missing integration popup on some AppImages

### ISSUE THREAD

**Issue by Janfel** [TheAssassin/AppImageLauncher#399]
**Describe the bug**

AIL does not ask me if I want to integrate [osu 2021.205.1](https://github.com/ppy/osu/releases/tag/2021.205.1). This only happens with this particular AppImage; integrating [Joplin](https://github.com/laurent22/joplin/releases/tag/v1.7.11) and [Bitwarden](https://github.com/bitwarden/desktop/releases/tag/v1.24.6) works without issue. Asking to integrate is turned on in the settings manager.

**Expected behavior**

When starting [osu 2021.205.1](https://github.com/ppy/osu/releases/tag/2021.205.1), AIL asks me if I want to integrate the AppImage.

**To Reproduce**
1. Download [osu 2021.205.1](https://github.com/ppy/osu/releases/tag/2021.205.1) from the Github releases page
2. Open the AppImage with AIL
3. The application starts immediately without integration popup

**System, software and AppImage information**

- Distribution: Manjaro Linux 20.2.1
- Desktop Environment: KDE Plasma 5.20.5
- AppImageLauncher: 2.2.0 from the Manjaro repositories

**List of AppImages you tried:**
- [osu 2021.205.1](https://github.com/ppy/osu/releases/tag/2021.205.1)
- [Joplin 1.7.10](https://github.com/laurent22/joplin/releases/tag/v1.7.10)
- [Joplin 1.7.11](https://github.com/laurent22/joplin/releases/tag/v1.7.11)
- [Bitwarden 1.24.6](https://github.com/bitwarden/desktop/releases/tag/v1.24.6)

**Additional Information**

Integrating the AppImage using `ail-cli` seems to work:

```
$ ail-cli integrate osu.AppImage
Processing /home/janfel/osu.AppImage
Moving AppImage to integration directory
WARNING: No icons found at "usr/share/icons"
WARNING: Using .DirIcon as default app icon
ERROR: Unable to load image.
ERROR: No icon was generated for: /home/janfel/.local/share/appimage/osu_055ca79305f29b9a1881f2d2384612fe.AppImage
WARNING: Unable to resize the application icon into a 128x128 image: "Unable to load image.". It will be written unchanged.
WARNING: Unable to resize the application icon into a 256x256 image: "Unable to load image.". It will be written unchanged.
```

**Comment by TheAssassin** [comment]
Dialog works fine on all four AppImages with the latest version except for `osu`, which is flagged as a terminal application:

```
# Desktop Entry Specification: https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
[Desktop Entry]
Type=Application
Name=osu!
Comment=A free-to-win rhythm game. Rhythm is just a *click* away!
Icon=osu!
Exec=osu!
Path=~
Terminal=true
Categories=Game;
```

So, broken AppImage rather than bug in AppImageLauncher.

`ail-cli` currently allows force-integrating AppImages regardless of whether AppImageLauncher would integrate it as well.
