### ISSUE TITLE
question: can appimage launcher identify actualizations

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#40]
Hello, some time ago I am using appimages, I have communicated some other issue (in my opinion) and I really like the simple way of downloading and executing. I have also tried other alternatives, such as flatpak and snap. I'm not really a programmer, just a user, and thanks to Lord Jesus, things in Linux are getting simpler in terms of package distribution, however; something that I find somewhat uncomfortable is the fact that the appimages do not show any kind of notification for updates, at this point I like the snap approach, that applications are updated to the latest version silently (of course, there are some people that this aspect bothers them, because of the control issue and all that, but not me) and that's why I ask if this tool will automatically identify this in general or each developer will have to enable that feature in their appimage?

**Comment by TheAssassin** [comment]
@Lvaskz you can update AppImages via a so-called desktop action (context menu entries in the launcher). This is also described in this nice article: http://linux-os.net/appimagelauncher-ejecuta-e-integra-facilmente-aplicaciones-en-appimage/

AppImageLauncher brings basic AppImage support to Linux distributions. Things like update management are out of scope of this project. But there's a couple of excellent app store like apps which could add this to your workflow. For instance, there's the [Nomad Software Center](https://github.com/nomad-desktop/nx-software-center).
