### ISSUE TITLE
AppImageLauncher --appimagelauncher-version raises errors on Ubuntu bionic

### ISSUE THREAD

**Issue by kellnerp** [TheAssassin/AppImageLauncher#406]
**Describe the bug**

Issuing the subject command in the cli on Ubuntu 18.04 raises Gtk error and then displays version.
**Expected behavior**

Should display something related to this version of the package: appimagelauncher_2.2.0-travis995.0f91801.bionic_amd64
**To Reproduce**
1. Go to 'command line and issue 'AppImageLauncher --appimagelauncher-version'
2. Watch the errors pile on and then the version appears
3. --appimagelauncher-help works OK, no Gtk junk appearing
4. Nothing appears in the syslog when this happens. 

**Screenshots**

Linux LAP1 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

AppImageLauncher version installed: [...] (also include where you got it from, e.g., our release page, your distribution, ...) -->
AppImageLauncher version 2.2.0 (git commit 0f91801), built on 2020-09-29 21:36:15 UTC
**List of AppImages you tried:**
Not applicatble.

Appimagelauncher appears to come up OK when I double click the icon. 
 
-

**Comment by TheAssassin** [comment]
I don't see any errors when executing that command. Please provide a screenshot and highlight what you consider an error.

**Comment by TheAssassin** [comment]
These "errors" are relatively harmless. Actually, I consider them warnings. They show up for most GTK+ themes whenever the Qt GTK integration is used on almost all distros. They're pretty annoying, but that's all there is to it. 

I have no explanation why one of the commands would not produce these issues, given the code...

As said, nothing can be done from our side with regards to these warnings.
