### ISSUE TITLE
Unable to see first dialog, if it is not first, as the app reinstalled

### ISSUE THREAD

**Issue by msangel** [TheAssassin/AppImageLauncher#408]
**Describe the bug**
Once the AppImageLauncher `knows` the app - no way to tell him forget it

  1) Double click on `duckstation-qt-x64.AppImage`
  2) AppImageLauncher dialog appears  
  3) click "integrate and run"
  4) delete the folder with integrated apps (~/Applications)
  5) create the folder from scratch
  6)  download `duckstation-qt-x64.AppImage` again
  7) double click run the application but the dialog from step 2 is not shown

**Expected behavior**
 1) Run in console `AppImageLauncher  --appimagelauncher-forget /path/to/duckstation-qt-x64.AppImage`
 2) On the next run of `duckstation-qt-x64.AppImage` the dialog with options `Integrate and run` and `Run once` appears

**System, software and AppImage information**
OS: Xubuntu 20.04.2 LTS x86_64
DE: Xfce
AppImageLauncher version 2.2.0 (git commit 0f91801), built on 2020-09-29 21:36:15 UTC

**Comment by TheAssassin** [comment]
> --appimagelauncher-forget

This flag does not exist. I don't know why you are using it. You may want to use `ail-cli unintegrate my.AppImage`.

**Comment by TheAssassin** [comment]
So, did the reply fix your problem?

**Comment by msangel** [comment]
yes, it just what I was looked for
