### ISSUE TITLE
AppImage not appearing in my applications menu

### ISSUE THREAD

**Issue by mathojojo** [TheAssassin/AppImageLauncher#409]
Hello,

My AppImage was in the Document directory. The daemons copied it automatically to Applications directory, as expected. But I never got a new entry in my applications list menu.

I don't understand why (and it's the first time I try AppImageLauncher).

I'm on KDE NEON (based on Ubuntu LTS 20.04)

Thank you

**Comment by TheAssassin** [comment]
There is *no* information in your report. The issue templates are there for a reason. Cannot work on issues that ignore them.
