### ISSUE TITLE
Hash sums and gpg signature

### ISSUE THREAD

**Issue by ManItaliano** [TheAssassin/AppImageLauncher#414]
Hello!
How I can verify checksums and gpg signature of deb packages? I am using debian and appimagelauncher is not represented in their official repo, so i need to download .deb package from github directly but there are no .sig files, but I need to verify it before installation. 
Thank you.

**Comment by TheAssassin** [comment]
Template not followed. 

There are no hash sums and no signatures.

**Comment by ManItaliano** [comment]
> 
> There are no hash sums and no signatures.

why?
