### ISSUE TITLE
App not working 

### ISSUE THREAD

**Issue by ManItaliano** [TheAssassin/AppImageLauncher#415]
Hello.
I have HP Laptop with Ryzen 5 CPU
OS:  MX Linux on debian 10
I downloaded from here: https://github.com/TheAssassin/AppImageLauncher/releases/tag/v2.2.0 
package named: appimagelauncher_2.2.0-travis995.0f91801.bionic_amd64.deb , installed it and rebooted my laptop.
Now i launch my .appimage files but appimagelaunched not launching (.appimage files are run as if appimagelauncher was not installed).

**Comment by TheAssassin** [comment]
Template not followed. Issue will not be worked on.
