### ISSUE TITLE
Dropping support for Ubuntu xenial/Debian stretch

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#417]
Now that Ubuntu 16.04 also known as xenial is now end-of-life (actually, it's in "extended support", i.e., paid support). Therefore, builds for this distro will be dropped soon.

Debian oldstable (stretch), which is supported by the xenial builds, has been in LTS mode (i.e., third-party maintenance) since June 2020 and will be until June 2022. I do not intend to provide special Debian builds at this point. Users of stretch, please comment to this issue if you are interested in continued support for your distribution. Ideally, you upgrade to the current stable, though.

**Comment by cobalt2727** [comment]
I assume 20.04 support will be in the next release - would it be worth the effort to host a package for 21.04 as well?

**Comment by cobalt2727** [comment]
Oh wait my bad - didn't see the "bionic" install works on anything newer too
I'm blind

**Comment by cobalt2727** [comment]
I assume it'll be renamed to something more generic like "Ubuntu" for the next release then?

**Comment by TheAssassin** [comment]
@cobalt2727 stable PPA has been updated, see #426. Daily is broken at the moment, for some weird dependency reason.
