### ISSUE TITLE
Taskwarrior-TUI - Failed to Register

### ISSUE THREAD

**Issue by Petemir** [TheAssassin/AppImageLauncher#421]
**Describe the bug**
I am having a problem with the app [taskwarrior-tui](https://github.com/kdheepak/taskwarrior-tui/releases/), whenever I try to integrate it into my system I get the `"Failed to register AppImage in system via libappimage"` error.

I attach the AppImageLint output for the image (no errors detected I think).

[taskwarrior-tui-AppImageLint.txt](https://github.com/TheAssassin/AppImageLauncher/files/6465422/taskwarrior-tui-AppImageLint.txt)

**Expected behavior**
It should integrate without any errors.

**To Reproduce**
1. Go to [taskwarrior-tui releases' page](https://github.com/kdheepak/taskwarrior-tui/releases/)
2. Download the latest release
3. Try to run it

It could be that this error only happens when a previous version of the app is already existing, in that case download the previous t latest release, run it, and then continue from step 2 :) .

**System, software and AppImage information**
* OS: Kubuntu 20.10
* AppImageLauncher: 2.1.2 (got commit e405182). Probably got it from my distribution.

**List of AppImages you tried:**
- [taskwarrior-tui](https://github.com/kdheepak/taskwarrior-tui/releases/)

Thanks!

**Comment by TheAssassin** [comment]
Thanks for attaching the appimagelint log, you're the first one to ever do this, and it really helps. You're right, there are no obvious bugs in there.

> Probably got it from my distribution.

I doubt this. Please run `apt policy appimagelauncher` and post the result.

Please run `ail-cli integrate <this AppImage>` and post the output here.

**Comment by Petemir** [comment]
> Thanks for attaching the appimagelint log, you're the first one to ever do this, and it really helps. You're right, there are no obvious bugs in there.

No problem. I searched on the issue tracker and saw that you asked for that everytime :smile: .

> I doubt this. Please run `apt policy appimagelauncher` and post the result.

```
appimagelauncher:
  Installed: 2.1.2-travis961~e405182+bionic
  Candidate: 2.1.2-travis961~e405182+bionic
  Version table:
 *** 2.1.2-travis961~e405182+bionic 100
        100 /var/lib/dpkg/status
```
 Just in case, between my last post and this I upgraded Kubuntu from 20.10 to 21.04, but the problem persists.

> Please run `ail-cli integrate <this AppImage>` and post the output here.
See attached file.
[2021-05-14-ail_cli_output.txt](https://github.com/TheAssassin/AppImageLauncher/files/6478847/2021-05-14-ail_cli_output.txt)

Sorry, I think I didn't mention this, but even though there is an error, the app gets effectively integrated (i.e., it gets moved to another folder, renamed, and I cannot integrate it again as it says it is already in the system)

**Comment by TheAssassin** [comment]
Ubuntu and derivatives don't provide packages for AIL, and the output of the `apt` command clearly shows that you installed a `.deb` from the release page. You should upgrade to the latest version.

> See attached file.
> 2021-05-14-ail_cli_output.txt

I cannot really tell why this is happening. Seems like a bug in the AppImage file. Please open an issue over at libappimage's tracker.

`ail-cli` should perhaps get a `test-integrate` command...

**Comment by Petemir** [comment]
Ok, I'll app the issue there and reference this issue just in case. By the way, I am unable to install the latest release, as it needs libcurl3 and I am already on libcurl4.

**Comment by Petemir** [comment]
I confirm this still happens with version 2.2.0 of AppImageLauncher. I'll create the other issue on libappimage soon.

**Comment by TheAssassin** [comment]
Please retry with the latest continuous release.
