### ISSUE TITLE
How can I uninstall app image launcher or prevent it from moving files automatically ? 

### ISSUE THREAD

**Issue by slechanii** [TheAssassin/AppImageLauncher#424]
Hello, I installed app image launcher on fedora31 and I'm having issues with it moving app images automatically.

I'm running another software in a docker container that creates and opens an app image the problem is that this software doesn't work anymore because it can't find the appimages since they are automatically moved as soon as they are downloaded.

I've tried uninstalling it but don't know how I could do so, I installed it using the .rpm and cannot find where the files are installed now.
I'd appreciate if someone could tell me how to uninstall or at least remove the automatic movement of files thanks.

**Comment by TheAssassin** [comment]
Run `sudo rpm -e appimagelauncher` in a terminal.

Source: https://www.howtoforge.com/community/threads/how-do-i-uninstall-rpm-packages.8/

Alternatively, use "AppImageLauncher settings" (run `AppImageLauncherSettings` from a terminal) and uncheck this box:

![screenshot_2021-05-18_22-33-57](https://user-images.githubusercontent.com/4503202/118719853-3fe3dd80-b829-11eb-89fd-76c2f7129129.png)
