### ISSUE TITLE
Missing icon field in the desktop entry

### ISSUE THREAD

**Issue by rattkin** [TheAssassin/AppImageLauncher#425]
When I try to register avidemux, I get "Failed to register appimage via libappimage

I tried running this:
```ail-cli integrate /home/rattkin/avidemuxLinux_2.7.8_GLIBC_2.28_amd64_917f5f7fa64bdf96cbf3cd9bf772e42e.appImage ```
Processing /home/rattkin/avidemuxLinux_2.7.8_GLIBC_2.28_amd64_917f5f7fa64bdf96cbf3cd9bf772e42e.appImage
Moving AppImage to integration directory
ERROR: appimage_register_in_system : Missing icon field in the desktop entry
Error: Failed to register AppImage in system via libappimage

Maybe there's a problem with the appimage.
I tried getting it as close to official source as possible
https://www.fosshub.com/Avidemux.html

my appimagelauncher:
  Installed: 2.2.0-travis995~0f91801+bionic
  Candidate: 2.2.0-travis995~0f91801+bionic
  Version table:
 *** 2.2.0-travis995~0f91801+bionic 100
        100 /var/lib/dpkg/status

**Comment by TheAssassin** [comment]
Essential information missing because template was ignored.

**Comment by TheAssassin** [comment]
That AppImage is pretty broken.

```
appimagelint.cli[7667] [INFO] Running check "Icons validity and location check"
appimagelint.icons_check[7667] [INFO] Extracting icon name from desktop file: /tmp/.mount_avidempZFKmG/avidemux.desktop
appimagelint.icons_check[7667] [ERROR] Could not find Icon= entry in desktop file
appimagelint.icons_check[7667] [INFO] [✖] Valid icon in AppDir root
appimagelint.icons_check[7667] [INFO] Checking resolution of icon: /tmp/.mount_avidempZFKmG/.DirIcon
```

Desktop file broken, no icon. libappimage can't and shouldn't invent an icon here. Ask the authors to fix it.
