### ISSUE TITLE
PPA missing builds for Ubuntu 21.04

### ISSUE THREAD

**Issue by azerupi** [TheAssassin/AppImageLauncher#426]
It seems that the PPA does not include builds for Ubuntu 21.04. When trying to add the repository I get the following errors:
```
E: The repository 'http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
And on the launchpad page the latest ubuntu version seems to be 20.10. Could builds for 21.04 be added?

**Comment by vvdaal** [comment]
Just be aware that as a workaround you simple change `hirsute` to `focal`. Seems to work perfectly fine.
Also read somewhere that the versions for Ubuntu should work for any Ubuntu distro.

**Comment by TheAssassin** [comment]
Took me quite a bit to figure out where to enable the new release. Launchpad's UI can be really annoying. Hirsute and Impish have been enabled, and should be built soon-ish.

The daily PPA fails to build at the moment, but I have not had time to figure out why yet.

**Comment by TheAssassin** [comment]
Looks like I had to manually trigger the builds (took me a bit to find out how), as the rebuilds are triggered only when a new release is published.

I also enabled builds for ARM (both 32-bit and 64-bit), also for `focal`.

https://code.launchpad.net/~appimagelauncher-team/+recipe/appimagelauncher-stable

Binaries will be available within the next minutes. Closing therefore.

**Comment by azerupi** [comment]
@TheAssassin thanks a lot! :slightly_smiling_face:

**Comment by mattcc23** [comment]
There are also no builds for Ubuntu 22.04

**Comment by TheAssassin** [comment]
Added to the [source recipes](https://code.launchpad.net/~appimagelauncher-team/+recipes), should be built overnight.

**Comment by mattcc23** [comment]
great thanks
