### ISSUE TITLE
AppImageLauncher Settings Appears Twice in App Drawer

### ISSUE THREAD

**Issue by SethFalco** [TheAssassin/AppImageLauncher#429]
**Describe the bug**
AppImageLauncher comes bunded with Manjaro/Plasma Mobile, and can be installed via the package manager.

However, when AppImageLauncher is installed, the "AppImageLauncher Settings" appears _twice_ in the app drawer. 

I also tried uninstalling and reinstalling the app:
* When uninstalled, both icons go away.
* When reinstalled, both icons come back.

**Expected behavior**

Presumably, the "AppImageLauncher Settings" icon is only meant to appear once.

**To Reproduce**
1. Install `AppImageLauncher` via pacman. (`sudo pacman -S appimagelauncher`)
2. See the app drawer

**Screenshots**

![Screenshot_20210603_145732](https://user-images.githubusercontent.com/22801583/120648677-3343c400-c47c-11eb-825f-b7cdb38b30c3.png)

**System, software and AppImage information**

OS: Manjaro ARM Linux aarch64
Host: Pine64 PinePhone (1.2)
Kernel: 5.12.8-2-MANJARO-ARM

AppImageLauncher version installed: community/appimagelauncher 2.2.0-4 via pacman on Manjaro

**Comment by TheAssassin** [comment]
Since it's a Manjaro package, you need to have them analyze and possibly fix the issue. It's not issued by this repository, nor maintained.
