### ISSUE TITLE
Ubuntu software shows AppImageLauncher license as proprietary

### ISSUE THREAD

**Issue by Foro38** [TheAssassin/AppImageLauncher#430]
**Describe the bug**
When trying to install the .deb file with "Ubuntu software", it shows the license as proprietary despite it being an MIT license

**Expected behavior**
Shows the license as free/MIT

**To Reproduce**
1. Boot up Ubuntu 20.10
2. Download appimagelauncher_2.2.0-gha53.3f901f6+bionic_amd64.deb from the releases page
3. Open the file with software install
4. Ubuntu shows appimagelauncher as proprietary instead of free

**Screenshots**

![Screenshot from 2021-06-04 21-51-57](https://user-images.githubusercontent.com/71207882/120851185-28268c00-c581-11eb-9b37-2200ebae03d4.png)

**System, software and AppImage information**
Distro: Ubuntu 20.10
DE: GNOME 3

AppImageLauncher version installed: 2.2.0 from the releases page.

**Comment by Foro38** [comment]
This looks like an ubuntu issue

**Comment by TheAssassin** [comment]
Do you know how that Ubuntu software reads such meta info? I assume you just need to add some files in special locations.

The packages here are generated by CMake. I'm not even sure we can actually fix this without maintaining the packaging ourselves.

**Comment by TheAssassin** [comment]
No idea how to fix that with CPack, it doesn't seem to add the necessary files to the packages. Please just ignore that.
