### ISSUE TITLE
AppImageLauncher appimage file

### ISSUE THREAD

**Issue by mattkwarren** [TheAssassin/AppImageLauncher#431]
I've tried to launch the appimage version of AppImageLauncher (v2.2.0) on Ubuntu 20.04, Fedora 33, and Debian 11. It simply won't launch. All other appimages I use launch fine. I gave the file permission to execute just as I did with the other appimages.

**Comment by TheAssassin** [comment]
You need to call it from a terminal. The installer it contains is a CLI application. This has been documented in the README ever since. https://github.com/TheAssassin/AppImageLauncher#differences-between-regular-and-lite-version
