### ISSUE TITLE
How do I uninstall the Lite edition of AppImageLauncher?

### ISSUE THREAD

**Issue by Sienna-Milady** [TheAssassin/AppImageLauncher#437]
I installed the Lite edition of AppImageLauncher and want to remove it, but I don't know how to.

I took these steps to install it:

1. Go [here](https://github.com/TheAssassin/AppImageLauncher/releases/latest).
2. Download the Lite edition of AppImageLauncher for i386.
3. Open a terminal.
4. Install AppImageLauncher Lite by running `~/Downloads/appimagelauncher-lite-*.AppImage install`.

I tried to remove it by running the following commands in a terminal:

```
rm -r ~/.local/lib/appimagelauncher-lite/
rm ~/.local/share/applications/appimagelauncher-lite-AppImageLauncherSettings.desktop
```

But, AppImages show up in the runner, so I guess I didn't uninstall it.

Additional information (given by `screenfetch`):

- OS: Ubuntu 21.04 hirsute
- Kernel: x86_64 Linux 5.11.0-25-generic
- DE: LXQt 0.16.0

**Comment by TheAssassin** [comment]
You just need to call the AppImage with `uninstall`. Just download a fresh copy, make it executable, and run it like this.

```sh
> chmod +x appimagelauncher-lite-2.2.0-travis995-0f91801-x86_64.AppImage 
> ./appimagelauncher-lite-2.2.0-travis995-0f91801-x86_64.AppImage 
Error: no option passed, use --help for more information
> ./appimagelauncher-lite-2.2.0-travis995-0f91801-x86_64.AppImage --help
Usage: /tmp/.mount_appimaqgsHYs/AppRun.wrapped <option> ...

Main options:
  install       Install AppImageLauncher into your user account
  uninstall     Uninstall AppImageLauncher from your user account
  help|--help   Display this help

Other options (mainly for use by AppImageLauncher Lite internally):
  appimagelauncherd          Run appimagelauncherd
  AppImageLauncherSettings   Display AppImageLauncher Lite configuration utility
  cli [or ali-cli]           Run AppImageLauncher cli (use "cli --help" for more information)
  remove <path>              Run removal helper to remove AppImage <path>
  update <path>              Run update helper to update AppImage <path>
```

It's really straightforward.
