### ISSUE TITLE
How Install AppimageLauncher on Mageia ?

### ISSUE THREAD

**Issue by Dantou07** [TheAssassin/AppImageLauncher#440]
Hi,
I'm french.
And what about Mageia 7 and 8 ?
Anybody would help me to install it ? 
Cheers, Dan

**Comment by jpenguin** [comment]
_

> `sudo usermod -a -G trusted  $(whoami); sudo zypper install --allow-unsigned-rpm https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm`

_

is what I use on OpenSUSE, replacing zypper with dnf should work

**Comment by TheAssassin** [comment]
See @jpenguin's answer.
