### ISSUE TITLE
Wrong App Name

### ISSUE THREAD

**Issue by hershko** [TheAssassin/AppImageLauncher#444]
I've installed the Franz appimage (from https://meetfranz.com/#download) on my system. It works (via AppImageLauncher) but the name I'm seeing in the launcher is "Franz (5.7.0.1852)" instead of just "Franz". 

I mounted the appimage to check the desktop file within, in case the issue is there - but it looks like the name there is correct (i.e. just "Franz"):

```
[Desktop Entry]
Name=Franz
Exec=AppRun %U
Terminal=false
Type=Application
Icon=franz
StartupWMClass=Franz
X-AppImage-Version=5.7.0.1852
Comment=Franz is your messaging app / former Emperor of Austria and combines chat & messaging services into one application. Franz currently supports Slack, WhatsApp, Gmail, Facebook Messenger, Telegram, Google Hangouts, GroupMe, Skype and many more. You can download Franz for free for Mac & Windows.
MimeType=x-scheme-handler/franz;
Categories=Network;InstantMessaging;
```

Am I missing something? Thanks.

**Comment by idadzie** [comment]
Hoping for a configuration option to opt out of this naming convention. 🙏

**Comment by TheAssassin** [comment]
```
X-AppImage-Version=5.7.0.1852
```

*Obviously* this is the version embedded in the AppImage. As you can maintain more than one AppImage of the same app at a time, it is recommended to include version numbers, which are then shown in those menus. Works as designed, there is absolutely no reason to change this behavior.

**Comment by matmicha** [comment]
maybe is there a way to put an option to display version in the app name only if there is only one version of the AppImage installed ?

**Comment by TheAssassin** [comment]
Asked and answered. You'd need to provide some strong convincing reasons.
