### ISSUE TITLE
uninstalling AppImageLauncher causes some damage!

### ISSUE THREAD

**Issue by sadnoises** [TheAssassin/AppImageLauncher#446]
Hi, thanks for the great work, the tool is awesome!.

but recently i noticed that by uninstalling **AppImageLauncher**.., **AppImages** are no longer can be invoked through **terminall** like: (**./app_name.AppImage**)

_the process has been tested multiple times on various appimages and settings like permissions._

**informations:**
_OS: GNU/Linux  (Fedora 34)_
_(please tell me if more informations are need)_

**Comment by TheAssassin** [comment]
Known issue on non-Debian distros. A reboot should fix the issue.
