### ISSUE TITLE
failure to launch VSCodium; GdkPixbuf error

### ISSUE THREAD

**Issue by iSmashButtons** [TheAssassin/AppImageLauncher#449]
Hi,
I am running Manjaro XFCE. 
All of the sudden it seems I cannot start VSCodium today. After trying to launch from my regular menu a few times, I tried executing directly from the terminal and got a lengthy error:

```
$ ./VSCodium-1.60.2-1632356529.glibc2.17-x86_64_ce2cf1cbe05af7a30046e6a674cacc34.AppImage

** (AppImageLauncher:4602): WARNING **: 17:24:21.985: Pixbuf theme: Cannot load pixmap file /usr/share/themes/Matcha-dark-sea/gtk-2.0/assets/trough-progressbar.png: Failed to load image “/usr/share/themes/Matcha-dark-sea/gtk-2.0/assets/trough-progressbar.png”: Fatal error in PNG image file: bad parameters to zlib


(AppImageLauncher:4602): GdkPixbuf-CRITICAL **: 17:24:21.985: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:4602): GdkPixbuf-CRITICAL **: 17:24:21.985: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

** (AppImageLauncher:4602): WARNING **: 17:24:21.985: Invalid borders specified for theme pixmap:
        /usr/share/themes/Matcha-dark-sea/gtk-2.0/assets/trough-progressbar.png,
borders don't fit within the image

(AppImageLauncher:4602): GdkPixbuf-CRITICAL **: 17:24:21.985: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:4602): GdkPixbuf-CRITICAL **: 17:24:21.985: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:4602): GdkPixbuf-CRITICAL **: 17:24:21.985: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
```
The last three lines repeat several times, finally ending with the error: `codium: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full`

A few days ago I used Qt5 Settings to change my Qt theme from "kvantum" to "gtk2". I remember doing this because I recently installed DigiKam and the interface was white so I changed that with Qt5 Settings. This is the only thing I've changed recently on my computer so on a hunch I switched the Qt theme back to "kvantum" and tried to launch VSCodium again. This time I only get the last error from above: `codium: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full`

I went to my desktop machine, which has never run VSCodium (but also has appimagelauncher, digikam, and same Qt5 settings), and my results were exactly the same. I have other AppImages on both machines (LBRY, Joplin), which I integrated with appimagelauncher and those applications run with no issues.

**Comment by TheAssassin** [comment]
Why do you think this is an AppImageLauncher issue? The error line clearly says `codium:`. Please ask them for help. I'm 99.99% sure it's not related to AppImageLauncher. (You could even test this by uninstalling AppImageLauncher temporarily.)

**Comment by TheAssassin** [comment]
By the way, these "errors" coming from GDK are not errors. They're some warnings. And totally outside our control.

**Comment by iSmashButtons** [comment]
I uninstalled AppImageLauncher and tried launching the AppImage. The program still doesn't start but i don't get any of the GDK/Pixbuf warnings. 

Sorry to be a bother. The `AppImageLauncher:4602` at the start of each line, lead me to believe the warnings were coming from AppImageLauncher.

**Comment by TheAssassin** [comment]
I know that, Gdk is annoying... you're not the first one to be misled.
