### ISSUE TITLE
No update right click feature

### ISSUE THREAD

**Issue by Samisafool** [TheAssassin/AppImageLauncher#459]
**Describe the bug**
When I right click on an AppImage icon, I get the remove AppImage feature as expected but there is no update feature.

**Expected behavior**
There should be an update feature.

**To Reproduce**
1. Integrate an AppImage
2. Right click on icon
3. See that there is no update option

**Screenshots**
I cannot add screenshots because keybinds don't work on KDE when a right click menu is open.

**System, software and AppImage information**
Fedora 34, KDE plasma 5.22.5, AppImage launcher 2.2.0

AppImageLauncher version installed: v2.2.0, from RPM in github releases

**List of AppImages you tried:**
- Bitwarden
- Ungoogled Chromium
- Subsurface (I don't use it regularly)

**Comment by TheAssassin** [comment]
Please open AppImageLauncher settings and verify whether the box next to the update feature label is checked.

**Comment by Samisafool** [comment]
Yes it is. Here is a screenshot to provide proof:

![image](https://user-images.githubusercontent.com/59611020/139582908-0457b9f0-69a7-473c-86d8-7c2c44c33ce2.png)

**Comment by TheAssassin** [comment]
Please provide links to the exact AppImages you tested. I am relatively sure they simply don't support updating...

**Comment by Samisafool** [comment]
here is download link for one of them, i dont have any for the rest since they were downloaded a long time ago

https://subsurface-divelog.org/downloads/daily/Subsurface-5.0.4-6-g94136db4e177-x86_64.AppImage

**Comment by TheAssassin** [comment]
This specific AppImage does not support updating. You can check the other two AppImages using the same command.

```
objdump -s -j .upd_info Subsurface-5.0.4-6-g94136db4e177-x86_64.AppImage
```
You will see only `0`s instead of text.

Thus: works as designed, not a bug at all.
