### ISSUE TITLE
appimagelauncher asks if I want to integrate or run, after having integrated applications to the system

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#46]
I have problems with Cpod.appimage. https: //github.com/z-------------/cumulonimbus/releases. Appimagelauncher integrated the cpod.appimage into the system, but every time I run it from the applications menu, the appimagelauncher window comes up asking me if I want to run or integrate into the system over and over again. At the moment it only happens with this cpod application. With libreoffice it does not happen
Ubuntu 18.04, 64 bit, gnome 3.28

**Comment by TheAssassin** [comment]
Could you try older versions of the AppImage? Perhaps the author made some changes that break AppImageLauncher.

**Comment by Lvaskz** [comment]
Now it is working, with the new version of cpod

**Comment by TheAssassin** [comment]
Found the bug, can reproduce it. The problem is the "content-aware" filenames. I'll fix this asap.

**Comment by Lvaskz** [comment]
Cool!!!!

**Comment by TheAssassin** [comment]
Please try with the new build published in a few minutes. If it still doesn't work, please reopen this issue.

**Comment by Lvaskz** [comment]
Ok, I will

**Comment by Lvaskz** [comment]
Hi, I tried it, but is not working

**Comment by TheAssassin** [comment]
Cannot reproduce this issue any more. Please remove the AppImage and try re-integrating it.

**Comment by Lvaskz** [comment]
I will reinstall appimagelauncher today version .I'll Remove appimage and I'll re-integrating it.
I hope all be fine

**Comment by TheAssassin** [comment]
I hope so, too. This is still beta software, and although I try my best to upgrade all data when changes are made, sometimes a bug is created in one revision, and can't be fixed properly any more.

**Comment by Lvaskz** [comment]
Well, thanks for your help. Anyway this version is being developed continuously and will surely be improved in the near future :)

**Comment by Lvaskz** [comment]
Hi, the problem persist, but I noted some interesting, this happen with the apps that have a instalation script. For other apps that have not this SCript, this is not a problem.

**Comment by Lvaskz** [comment]
Hi, same problem with cpod and minetime. appimage

**Comment by Lvaskz** [comment]
I made video. The same thing with linuxmint 18.3. Can you check it please?
[Issue.zip](https://github.com/TheAssassin/AppImageLauncher/files/2275331/Issue.zip)

**Comment by TheAssassin** [comment]
Please `ls -al ~/Applications`, and provide the output.

By the way, in your last translation attempt, you broke the syntax. It's `%1` as in `first string replacement`. That's why you see this `% 1 <spanish equivalent to "has not been integrated yet>` in the message box in the video. See https://github.com/TheAssassin/AppImageLauncher/commit/0dff6bca9bfcb9fa3738e9a6c340ecec60502f0d.

**Comment by Lvaskz** [comment]
~$ ls -al ~/Applications
total 1516972
drwxr-xr-x  3 amiel amiel      4096 ago  5 14:01 .
drwxr-xr-x 41 amiel amiel      4096 ago 10 05:59 ..
-rwxr-xr-x  1 amiel amiel  55172922 jul 14 22:14 CPod-1.25.5-x86_64_e55efccde2dcc62a86cd1c2297a52562.AppImage
-rwxr-xr-x  1 amiel amiel 279931176 jul 25 09:57 DesktopEditors-x86_64_c828af1f7f7a14f3bbad864585033eed.AppImage
-rwxr-xr-x  1 amiel amiel 233887672 jul 21 17:18 FreeCAD-13522.glibc2.17-x86_64_37d36a3c1549850aa2f7afa7a7d14b89.AppImage
-rwxr-xr-x  1 amiel amiel  17704888 jul 23 21:24 gmic_krita_qt-x86_64__8e9cb7f8fe200c42944223708290b7e3.appimage
-rwxr-xr-x  1 amiel amiel  22902712 ago  4 15:20 ksnip-317-f23aa95-x86_64_de04fe7d963fa61f8090a589b0a92924.AppImage
-rw-r--r--  1 amiel amiel 370386872 jul 30 05:46 LibreOffice-fresh.standard.help.-x86_64.AppImage
-rwxrwxr-x  1 amiel amiel 212664320 jul 22 21:25 PapagayoNG-1.4.2-2017.07.31-65704-linux-64bit.appimage
-rwxr-xr-x  1 amiel amiel  39608224 jul 28 08:48 pencil2d-linux-amd64-0.6.1.1_82c326fdf8f836562a70bbd9a652ebf8.AppImage
-rwxr-xr-x  1 amiel amiel  59619323 jul  9 18:27 Rambox-0.5.17-x64_82d701df7664226871a9b754659d8298.AppImage
-rwxr-xr-x  1 amiel amiel  32980896 may 22 04:08 Stacer-x86_64__6059897fa056fe85d95f0e0891297261.AppImage
-rwxrwxr-x  1 amiel amiel 103874560 jul 21 16:32 SynfigStudio-1.2.1-testing-17.09.09-linux64-113dd.appimage
-rwxrwxr-x  1 amiel amiel 124583936 jul 21 16:49 SynfigStudio-1.3.10-testing-18.07.21-linux64-bfd1c.appimage
drwxr-xr-x  2 amiel amiel      4096 ago  5 14:01 .trash
amiel@amiel-Inspiron-3442:~$

**Comment by Lvaskz** [comment]
~$ ls -al ~/Applications
total 1516972
drwxr-xr-x  3 amiel amiel      4096 ago  5 14:01 .
drwxr-xr-x 41 amiel amiel      4096 ago 10 05:59 ..
-rwxr-xr-x  1 amiel amiel  55172922 jul 14 22:14 CPod-1.25.5-x86_64_e55efccde2dcc62a86cd1c2297a52562.AppImage
-rwxr-xr-x  1 amiel amiel 279931176 jul 25 09:57 DesktopEditors-x86_64_c828af1f7f7a14f3bbad864585033eed.AppImage
-rwxr-xr-x  1 amiel amiel 233887672 jul 21 17:18 FreeCAD-13522.glibc2.17-x86_64_37d36a3c1549850aa2f7afa7a7d14b89.AppImage
-rwxr-xr-x  1 amiel amiel  17704888 jul 23 21:24 gmic_krita_qt-x86_64__8e9cb7f8fe200c42944223708290b7e3.appimage
-rwxr-xr-x  1 amiel amiel  22902712 ago  4 15:20 ksnip-317-f23aa95-x86_64_de04fe7d963fa61f8090a589b0a92924.AppImage
-rw-r--r--  1 amiel amiel 370386872 jul 30 05:46 LibreOffice-fresh.standard.help.-x86_64.AppImage
-rwxrwxr-x  1 amiel amiel 212664320 jul 22 21:25 PapagayoNG-1.4.2-2017.07.31-65704-linux-64bit.appimage
-rwxr-xr-x  1 amiel amiel  39608224 jul 28 08:48 pencil2d-linux-amd64-0.6.1.1_82c326fdf8f836562a70bbd9a652ebf8.AppImage
-rwxr-xr-x  1 amiel amiel  59619323 jul  9 18:27 Rambox-0.5.17-x64_82d701df7664226871a9b754659d8298.AppImage
-rwxr-xr-x  1 amiel amiel  32980896 may 22 04:08 Stacer-x86_64__6059897fa056fe85d95f0e0891297261.AppImage
-rwxrwxr-x  1 amiel amiel 103874560 jul 21 16:32 SynfigStudio-1.2.1-testing-17.09.09-linux64-113dd.appimage
-rwxrwxr-x  1 amiel amiel 124583936 jul 21 16:49 SynfigStudio-1.3.10-testing-18.07.21-linux64-bfd1c.appimage
drwxr-xr-x  2 amiel amiel      4096 ago  5 14:01 .trash
amiel@amiel-Inspiron-3442:~$

**Comment by Lvaskz** [comment]
![imagen](https://user-images.githubusercontent.com/29207169/43957135-fd881bec-9c63-11e8-8ab3-4db9270fca48.png)

**Comment by Lvaskz** [comment]
"By the way, in your last translation attempt, you broke the syntax. It's %1 as in first string replacement. That's why you see this % 1 <spanish equivalent to "has not been integrated yet> in the message box in the video. See 0dff6bc." I will fix it

**Comment by TheAssassin** [comment]
It's fixed already, I linked you the corresponding diff in my previous post. I just wanted to explain to you what this `%1` means, and what it's used for.

**Comment by Lvaskz** [comment]
amiel@amiel-Inspiron-3442:~$ ls -al ~/Applications
total 1578124
drwxr-xr-x  3 amiel amiel      4096 ago 10 15:58 .
drwxr-xr-x 41 amiel amiel      4096 ago 11 09:57 ..
-rwxr-xr-x  1 amiel amiel  55172922 jul 14 22:14 CPod-1.25.5-x86_64_e55efccde2dcc62a86cd1c2297a52562.AppImage
-rwxr-xr-x  1 amiel amiel 279931176 jul 25 09:57 DesktopEditors-x86_64_c828af1f7f7a14f3bbad864585033eed.AppImage
-rwxr-xr-x  1 amiel amiel 233887672 jul 21 17:18 FreeCAD-13522.glibc2.17-x86_64_37d36a3c1549850aa2f7afa7a7d14b89.AppImage
-rwxr-xr-x  1 amiel amiel  17704888 jul 23 21:24 gmic_krita_qt-x86_64__8e9cb7f8fe200c42944223708290b7e3.appimage
-rwxr-xr-x  1 amiel amiel  22902712 ago  4 15:20 ksnip-317-f23aa95-x86_64_de04fe7d963fa61f8090a589b0a92924.AppImage
-rw-r--r--  1 amiel amiel 370386872 jul 30 05:46 LibreOffice-fresh.standard.help.-x86_64.AppImage
-rwxrwxr-x  1 amiel amiel 212664320 jul 22 21:25 PapagayoNG-1.4.2-2017.07.31-65704-linux-64bit.appimage
-rwxr-xr-x  1 amiel amiel  39608224 jul 28 08:48 pencil2d-linux-amd64-0.6.1.1_82c326fdf8f836562a70bbd9a652ebf8.AppImage
-rwxr-xr-x  1 amiel amiel  62615075 ago 10 15:34 protonmail-desktop-0.5.8-x86_64_6c210ee5591b286194d3dd4058b014cb.AppImage
-rwxr-xr-x  1 amiel amiel  59619323 jul  9 18:27 Rambox-0.5.17-x64_82d701df7664226871a9b754659d8298.AppImage
-rwxr-xr-x  1 amiel amiel  32980896 may 22 04:08 Stacer-x86_64__6059897fa056fe85d95f0e0891297261.AppImage
-rwxrwxr-x  1 amiel amiel 103874560 jul 21 16:32 SynfigStudio-1.2.1-testing-17.09.09-linux64-113dd.appimage
-rwxrwxr-x  1 amiel amiel 124583936 jul 21 16:49 SynfigStudio-1.3.10-testing-18.07.21-linux64-bfd1c.appimage
drwxr-xr-x  2 amiel amiel      4096 ago 10 09:37 .trash
amiel@amiel-Inspiron-3442:~$

**Comment by Lvaskz** [comment]
Thanks, I'll look better next time. By the way, have you been able to find out something about the issue?, I already post the information you requested

**Comment by TheAssassin** [comment]
@Lvaskz I didn't have time to look into this yet. Your Applications directory looks fine at a first glance.

**Comment by Lvaskz** [comment]
I was doing several tests with different appimages, using appimageslauncher. I realized that those that have this issue are those that are built with electron; unofficial protonmail desktop, rambox, cpod, museeks, etc.
With those that are not built with electron as krita, libreoffice, stacer and others, this issue is non-existent.
At first I thought the problem was the integration script, but it's not like that, I was wrong, (I was only speculating anyway).
Can someone try what I suggest?

**Comment by TheAssassin** [comment]
@Lvaskz good catch, thanks. We'll try to find out what makes these AppImages break AppImageLauncher.

CC @probonopd

**Comment by probonopd** [comment]
Possibly the `AppRun` script used by electron-builder

**Comment by Lvaskz** [comment]
I find it strange that nobody else can reproduce this issue. Could someone else be using linux, try it please?

**Comment by tvanders** [comment]
Well, i can say i'm having the same issue.
```
OS: Manjaro Linux x86_64 
Host: MS-7850 1.0 
Kernel: 4.14.67-1-MANJARO 
Packages: 1050 (pacman) 
Shell: bash 4.4.23 
Resolution: 1920x1080 
DE: GNOME 3.28.3 
Terminal: tilix 
CPU: Intel i5-4440 (4) @ 3.300GHz 
GPU: NVIDIA GeForce GTX 750 Ti 
Memory: 1754MiB / 7909MiB 
```
these are the apps running. franz & Winds are giving me the issue. Bitwarden works fine.
```
Bitwarden-1.7.0-x86_64_0654c153bcc1723d9d69bfbc25158f44.AppImage
franz-5.0.0-beta.18-x86_64.AppImage
Winds-2.1.90-x86_64_af7d051f0e251b25a950814864390199.AppImage
```

**Comment by TheAssassin** [comment]
@tvanders thanks for chiming in. Are these AppImages Electron ones, too?

**Comment by TheAssassin** [comment]
Check the GitHub pages of the applications whether they're using JavaScript code...?

I don't know where you downloaded the files, and you didn't provide any links, so I can't look it up myself, unfortunately. If you post the download links, I might have a look.

**Comment by tvanders** [comment]
OK i had a look at them:

- [Franz](https://github.com/meetfranz/franz) is using electron i'm guessing

- [Bitwarden](https://github.com/bitwarden/desktop) is using electron and Angular

- [Winds](https://github.com/GetStream/Winds) i have no clue what it uses, better for you to have a look yourself.

Thanks already for your time and good hunting :)

**Comment by TheAssassin** [comment]
The issue is in https://github.com/AppImage/AppImageKit/blob/273311b89ecc55d69945459e657562aae2f095ca/src/shared.c#L1793. That line checks whether a thumbnail has been created for an AppImage. Apparently, there is no thumbnail created for some reason.

So, two things to do here:

  1) find out why that thumbnail is not created
  1) consider removing that check from the function

**Comment by TheAssassin** [comment]
I guess we don't insist on the thumbnail to be created, since the related function is a `void()`. Therefore I'm going to remove the check, and we'll rely on the check whether the desktop file is in place. CC @probonopd 

To be able to do this, I need to first transition to the new libappimage repository, then we can fix it in there.

**Comment by TheAssassin** [comment]
@Lvaskz @tvanders please test and reopen if there's still issues.

**Comment by Lvaskz** [comment]
Now it is working !!!!!!
