### ISSUE TITLE
integrate and run window doesn't apper

### ISSUE THREAD

**Issue by Patronon** [TheAssassin/AppImageLauncher#464]
I hope this is now the right place to put my issue

**Describe the bug**
Hi,
I installed it as recommended and changed the settings as recommended in Order to open an FreeCad Appimage file.
When I want to open the AppImage with Appimagelaucher it just runs it and does not ask me if I want to integrate it. The Window just does not open for me.(?)
Nice program so far anyways, thanks for the effort
I running on Linux Mint 20.2

**Expected behavior**
right klick open with 
window where I get ask to integrate and run it or just run it 

**Screenshots**
not available

**System, software and AppImage information**
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.2
DISTRIB_CODENAME=uma
DISTRIB_DESCRIPTION="Linux Mint 20.2 Uma"
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"

Desktop=Cinnamon

AppImageLauncher version installed:
sudo add-apt-repository ppa:appimagelauncher-team/stable
sudo apt update
sudo apt install appimagelauncher

**List of AppImages you tried:**
- FreeCAD

**Comment by TheAssassin** [comment]
> changed the settings as recommended

Where is changing any settings recommended? The settings do not have to be changed. What changes have you done?

**Comment by Patronon** [comment]
I meant by changes just the checkbox by Laucher-Dialog and the auto integration as well as Folder-direction to AppImage-files (I was not checkt by default)

**Comment by Patronon** [comment]
![g945](https://user-images.githubusercontent.com/84419208/146531859-de1feb13-c892-47f9-a9db-92165b4a4289.png)

**Comment by TheAssassin** [comment]
The checkbox should have been checked in the first place.

What is "a FreeCAD AppImage"? Do you expect me to guess which file you're trying to run? You need to post a link.

**Comment by Patronon** [comment]
https://www.freecad.org/downloads.php

**Comment by TheAssassin** [comment]
You need to post an exact link to the version you are testing.

You don't seem to be willing to assist in this...

**Comment by Patronon** [comment]
Pardon to you "TheAssassin" for my careless Link I did sent you without more close instructions.
Please follow the link I sent you and press the right BIG BLUE BUTTON  under the LINUX PENGUIN which is labeled with "64-BIT-AppImage".  After you have pressed the button, there will open an window and you are asked to download the AppImage FreeCAD_0.19.3-Linux-Conda_glibc2.12-x86_64.AppImage. That the one I downloaded and tested with your AppImage-Laucher.  
with best regards
