### ISSUE TITLE
Tabs open outside of pin

### ISSUE THREAD

**Issue by ShawnNogi** [TheAssassin/AppImageLauncher#465]
Integration appears to be inconsistent with applications. When opening Favorited application It creates a new tab outside of the pinned favorite instead of within it.

1. Download Cryptomator 
2. Add to favorite after integrating and running
3. Open from the taskbar/ favorite panel
4.  New Tab Opens outside of the specified tab.

Screenshot:
![Screenshot from 2021-12-18 03-33-52](https://user-images.githubusercontent.com/39767738/146635330-71b20ae7-3e96-4667-a7b1-1f767868f420.png)

Appimagelauncher version:
202110042219-stable-0f91801~ubuntu21.04.1

Ubuntu 20.04

appimages tried:
keepasxc - tab works as intended with tab inside of the pinned favorite
cryptomator - creates new tab
session messaging - tab works as intended with tab inside of the pinned favorite

Apologies if this is outside the scope of what the integration does. Feel free to close if this isn't a fix that's possible. If there's a way to force the tab to be in the favorited pin let me know.

**Comment by TheAssassin** [comment]
It is an issue in that AppImage's desktop file. It must specify the `StartupWMClass` property.

Next time follow the template.
