### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by 404Nick** [TheAssassin/AppImageLauncher#467]
**Describe the bug**

I cannot uninstall the AppImageLauncher

**Expected behavior**

I should (In theory) be able to

**To Reproduce**
In terminal: sudo apt-get remove --purge AppImageInstaller

**Screenshots**

Current version, Ubuntu

AppImageLauncher version installed: [...] (also include where you got it from, e.g., our release page, your distribution, ...) -->

**List of AppImages you tried:**
Only most recent

**Comment by TheAssassin** [comment]
Wrong package name. Why in the world would you assume the name is "AppImageInstaller"? Even the spelling is incorrect.

```
sudo apt purge appimagelauncher
