### ISSUE TITLE
Can't build on Solus because dl.bintray.com is dead

### ISSUE THREAD

**Issue by demonich** [TheAssassin/AppImageLauncher#469]
when do "make libappimage libappimageupdate libappimageupdate-qt" error appear

    `CMake Error at boost-EXTERNAL-stamp/download-boost-EXTERNAL.cmake:170 (message):
          Each download failed!

    error: downloading 'https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz' failed
          status_code: 22
          status_string: "HTTP response code said error" `

They changed URL
[https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html](url)

This is new release page:
[https://boostorg.jfrog.io/artifactory/main/release/](url)

**Comment by TheAssassin** [comment]
Reports that ignore the template are not going to be worked on.

Duplicate of #458
