### ISSUE TITLE
Appimagelauncher integrates icons to the application menu with low resolution

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#47]
I have integrated scribus 1.5.4 appimage with appimagelauncher. The icon that is shown in the applications menu of ubuntu 18.04, 64 bits is of low resolution, it has a blurred aspect. I installed appimaged and ran the appimaged command in the terminal and the same icon was corrected. But I do not pretend to have appimaged and appimagelauncher by now

**Comment by TheAssassin** [comment]
@Lvaskz this is most likely an issue in libappimage, `appimage_register_in_system` does apparently not copy the icons properly. CC @azubieta

**Comment by probonopd** [comment]
What does `find "$HOME/.local/share/icons" | grep appimagekit_ | grep -i scribus` say?

**Comment by probonopd** [comment]
And what does `find "$HOME/.local/share/applications" -iname '*scribus*' -and -iname '*.desktop' -exec grep -r "^Icon=*" {} \;` say?

**Comment by probonopd** [comment]
And most importantly, does the Scribus AppImage even have `usr/share/icons/hicolor/...` populated correctly?

**Comment by TheAssassin** [comment]
@Lvaskz we need more information, otherwise I will close the issue as non-reproducible.

**Comment by Lvaskz** [comment]
What kind of information?

**Comment by TheAssassin** [comment]
https://github.com/TheAssassin/AppImageLauncher/issues/47#issuecomment-390721269
https://github.com/TheAssassin/AppImageLauncher/issues/47#issuecomment-390752862
https://github.com/TheAssassin/AppImageLauncher/issues/47#issuecomment-390754190

**Comment by Lvaskz** [comment]
I will search that tonight, I hope could find it

**Comment by Lvaskz** [comment]
I will close this. I have not time. As soon as I have some free time, I will devote myself to doing a little research.
