### ISSUE TITLE
ppa repo not have a Release file

### ISSUE THREAD

**Issue by intijk** [TheAssassin/AppImageLauncher#470]
I don't know where to report this, not even sure if this is a real bug, but recently I saw below error when I add ppa repository, is this some thing wrong ?

E: The repository 'http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu bionic Release' does not have a Release file.

**Comment by TheAssassin** [comment]
Issues that *completely* ignore the issue template are not being worked on.
