### ISSUE TITLE
Electrum does not launch after first integration

### ISSUE THREAD

**Issue by gringofe** [TheAssassin/AppImageLauncher#474]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

After first integrating the Electrum bitcoin wallet into the system, it can no longer be launched from it's menu entry.

### Expected behavior

Electrum should launch when I click it's menu entry

### Steps to reproduce the issue

1. Download the Electrum appimage (https://download.electrum.org/4.1.5/electrum-4.1.5-x86_64.AppImage) 
2. Launch it
3. Click "integrate and run" in AppImageLauncher
4. Electrum launches
5. Close Electrum
6. Try to open Electrum from Cinnamon's menu

### Distribution and desktop environment

Linux Mint 19.3 Cinnamon

### Installed AppImageLauncher version

AppImageLauncher version 2.2.0 (git commit 0f91801), built on 2020-09-29 21:36:15 UTC

### List of AppImages you tried

- Electrum-4.1.5 https://download.electrum.org/4.1.5/electrum-4.1.5-x86_64.AppImage

**Comment by TheAssassin** [comment]
The desktop file they use looks pretty fishy. It does some manipulation of `$PATH`, things better done in an `AppRun` script. I presume the AppImage is just broken.

Please post the contents of `~/.local/share/applications/*Electrum_Bitcoin_Wallet.desktop`.

**Comment by gringofe** [comment]
```
# If you want Electrum to appear in a Linux app launcher ("start menu"), install this by doing:
# sudo desktop-file-install electrum.desktop

[Desktop Entry]
Comment=Lightweight Bitcoin Client
Exec=/opt/appimage/electrum-4.1.5-x86_64_d4385a074803475e7943e17933132991.AppImage -c PATH= "\\\\\$HOME/.local/bin:\\\\\$PATH\\; electrum %u"
GenericName[en_US]=Bitcoin Wallet
GenericName=Bitcoin Wallet
Icon=appimagekit_4989192e1979d529b4c2b36802fb13b3_electrum
Name[en_US]=Electrum Bitcoin Wallet
Name=Electrum Bitcoin Wallet
Categories=Finance;Network;
StartupNotify=true
StartupWMClass=electrum
Terminal=false
Type=Application
MimeType=x-scheme-handler/bitcoin;
Actions=Remove;

TryExec=/opt/appimage/electrum-4.1.5-x86_64_d4385a074803475e7943e17933132991.AppImage
X-AppImage-Old-Icon=electrum
X-AppImage-Identifier=4989192e1979d529b4c2b36802fb13b3
X-AppImageLauncher-Version=2.2.0 (git commit 0f91801), built on 2020-09-29 21:36:15 UTC

[Desktop Action Testnet]
Exec=/opt/appimage/electrum-4.1.5-x86_64_d4385a074803475e7943e17933132991.AppImage -c PATH= "\\\\\$HOME/.local/bin:\\\\\$PATH\\; electrum --testnet %u"
Name=Testnet mode

[Desktop Action Remove]
Name=Remove AppImage from system
Icon=AppImageLauncher
Exec=/usr/lib/x86_64-linux-gnu/appimagelauncher/remove "/opt/appimage/electrum-4.1.5-x86_64_d4385a074803475e7943e17933132991.AppImage"
Name[ast]=Desaniciar AppImage del sistema
Name[cs]=Odebrat AppImage ze systému
Name[de]=AppImage vom System entfernen
Name[en]=Remove AppImage from system
Name[es]=Eliminar Appimage del Sistema
Name[fr]=Supprimer l'AppImage du système
Name[it]=Rimuovi AppImage dal sistema
Name[nl]=AppImage deïnstalleren
Name[pl]=Usuń AppImage z systemu
Name[pt]=Remover AppImage do sistema
Name[pt_PT]=Remover AppImage do sistema
Name[ru]=Удалить AppImage из системы
Name[zh_Hans]=从系统中移除 AppImage
```

**Comment by acarlton** [comment]
I also encountered this issue with Electrum 4.1.5 and AppImageLauncher 2.2.0 (I believe).

FWIWI, when I manually edited the generated .desktop file and removed the `-c` parameter and everything following it, Electrum now starts on launch. I don't know if functionality is adversely affected though.

**Comment by TheAssassin** [comment]
Please open an issue with Electrum. This is not an issue of AppImageLauncher, in fact it works correctly. It can't automagically fix broken AppImages' contents, though.
