### ISSUE TITLE
uninstall appimagelauncher disables the appimages  

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#48]
I uninstalled appimagelauncher and appimaged and now the appimages that I have in my system do not work, they do not run at all. The problem now is that gnome software is not letting me install appimaged.deb or appimagelauncher.deb. And my appimages do not work, not even if I download them again. Does anyone know how to fix this?

**Comment by Lvaskz** [comment]
ALREADY SOLVED

**Comment by stevesbrain** [comment]
How'd you solve it? :)

**Comment by TheAssassin** [comment]
@stevesbrain you might want to open a new issue with more information.
Might seem a bit ridiculous to you, but have you actually tried to turn it off and on again? After uninstall, some configs won't be flushed until a proper reboot.
