### ISSUE TITLE
Provide AppImageLauncher itself as .AppImage

### ISSUE THREAD

**Issue by Semnodime** [TheAssassin/AppImageLauncher#482]
### Pre-submit checks

- [X] I checked for similar issues beforehand, but could not find any. I could not add my proposal to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Feature description

Provide AppImageLauncher itself as .AppImage

### Proposed solution

Provide AppImageLauncher itself as .AppImage

**Comment by TheAssassin** [comment]
AppImageLauncher Lite is shipped as an AppImage, as can be found in the README.

You have not filled out the template properly. Closing therefore. Feel free to add more information (e.g., your use cases).
