### ISSUE TITLE
rpm package fails to install on opensuse tumbleweed 

### ISSUE THREAD

**Issue by luvis** [TheAssassin/AppImageLauncher#484]
### Describe the bug

When trying to install the package (same issue with all releases i've tried) I get this error
`file /usr/share/mime from install of appimagelauncher-2.2.0-gha78~668270b.x86_64 conflicts with file from package filesystem-84.87-3.2.x86_64
`
I can't exactly uninstall the filesystem package because much of the system relies on it. 

### Expected behavior

I expect the rpm package to install

### Steps to reproduce the issue

1. sudo rpm -ivh appimagelauncher*
2. open it with discover and click install. Shows "too few items to process" "internal error"

### Distribution and desktop environment

Opensuse Tumbleweed

### Installed AppImageLauncher version

none installed. Tried travis987, gha78, travis995 and several more.

### Additional context

As this didn't work, I decided to try to compile it myself but ran into the issue that I don't know which boost package to install.. there are hundreds and they are all called something with lib and devel but none are called basic names like "core" so I'm lost on which package to install..
The following "categories" are available: atomic, chrono, container, context, couroutine, date_time, fiber, filesystem, graph, headers, iostreams, json, locale, log, math, mpi, nowide, numpy, program_options, python, random, regex, serialization, stacktrace, test, thread, timer, type and wave.. And several versions of every package.. Any idea on which one to install?

**Comment by TheAssassin** [comment]
Build running, ETA 30-60 minutes. Please try to install the files from the "continuous release" on https://github.com/TheAssassin/AppImageLauncher/releases/continuous once the new files are there. If it still doesn't work and a similar message is shown, please post a comment here, and I'll reopen the issue.

**Comment by luvis** [comment]
unfortunately the new build has the same install issue

` file /usr/share/mime/packages from install of appimagelauncher-2.2.0-gha82~1696707.x86_64 conflicts with file from package filesystem-84.87-3.2.x86_64`
And it aborts..
