### ISSUE TITLE
comply with FOSS software

### ISSUE THREAD

**Issue by Pantyhose-X** [TheAssassin/AppImageLauncher#486]
### Pre-submit checks

- [X] I checked for similar issues beforehand, but could not find any. I could not add my proposal to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Feature description

Now all Linux has a serious security hazard. Packages manager Do not comply with [FOSS](https://www.gnu.org/philosophy/floss-and-foss.en.html) software,
Archlinux and manjaro official repositories have begun to promote closed source software and Dependencies. such as Opera Browser. This is a very dangerous behavior that does not open source.

### Proposed solution

If all software in AppImageLauncher  Repositories meet [FOSS](https://www.gnu.org/philosophy/floss-and-foss.en.html)

**Comment by TheAssassin** [comment]
AppImageLauncher is not a package manager, and your proposal is pointless anyway.
