### ISSUE TITLE
How to Install AppImageLauncher on Solus Linux

### ISSUE THREAD

**Issue by KirMozor** [TheAssassin/AppImageLauncher#488]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

hello, I wanted to install your program in Solus Linux, but I did not find eopkg, I decided to build it from source
Started following the instructions in BUILD.md
But ran into an error
```
-- Checking for module 'librsvg-2.0'
--   No package 'librsvg-2.0' found
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  lib/libappimage/cmake/scripts.cmake:113 (pkg_check_modules)
  lib/libappimage/cmake/imported_dependencies.cmake:11 (import_pkgconfig_target)
  lib/libappimage/cmake/dependencies.cmake:7 (include)
  lib/libappimage/CMakeLists.txt:29 (include)
```
Although librsvg is installed
``` 
kirill@kirmozor ~/tools/appimagelauncher-0f91801.source/build $ sudo eopkg install librsvg
Password: 
The following package(s) are already installed and are not going to be installed again:
librsvg
No packages to install.
kirill@kirmozor ~/tools/appimagelauncher-0f91801.source/build $ 
```

### Expected behavior

Although the installation should have gone)

### Steps to reproduce the issue

`mkdir build`
`cd build`
`export PREFIX="/usr/local"`
`cmake .. -DCMAKE_INSTALL_PREFIX="$PREFIX"`

### Distribution and desktop environment

```
kirill@kirmozor
---------------
OS: Solus x86_64 
Uptime: 39 mins 
Packages: 867 (eopkg), 7 (flatpak) 
Shell: bash 5.1.16
Resolution: 1280x1024 
DE: MATE 1.26.0 
WM: Metacity (Marco) 
Theme: Plata-Noir [GTK2/3] 
Icons: Papirus [GTK2/3] 
Terminal: mate-terminal 
Terminal Font: Hack 9 
CPU: Intel Core 2 Duo E8500 (2) @ 2.962GHz 
GPU: NVIDIA GeForce GT 630 
Memory: 1272MiB / 5942MiB 
```

### Installed AppImageLauncher version

Latest from releases: Release build (v2.2.0)
Name file: appimagelauncher-0f91801.source.tar.xz

**Comment by TheAssassin** [comment]
Support for Solus has been rejected more than once before #139 #331 #405 #391. You need to install `librsvg-2.0` in a way so `pkg-config` can pick it up. If Solus doesn't provide a proper package, there's nothing I can do.

Also, you refer to `librsvg`, but the CMake scripts explicitly request `librsvg-2.0`. Not sure if that causes the issue.
