### ISSUE TITLE
Weird build error.

### ISSUE THREAD

**Issue by shadwalker9** [TheAssassin/AppImageLauncher#49]
So when attempting to build from the AUR I get this weird error. I can't seem to find much useful information as to what's going on (I'm a bit of noob)  but I'm on Manjaro GNOME.
Here's the end bit:
`Scanning dependencies of target l10n
/bin/sh: LRELEASE-NOTFOUND: command not found
make[2]: *** [i18n/CMakeFiles/l10n.dir/build.make:57: l10n] Error 127
make[1]: *** [CMakeFiles/Makefile2:3057: i18n/CMakeFiles/l10n.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

[AUR Readout.txt](https://github.com/TheAssassin/AppImageLauncher/files/2038384/AUR.Readout.txt)
`

**Comment by TheAssassin** [comment]
@shadwalker9 I'll fix the build dependencies later.

**Comment by TheAssassin** [comment]
Has been fixed.
