### ISSUE TITLE
Incorrect `Exec=` in desktop entry

### ISSUE THREAD

**Issue by ZhaoZuohong** [TheAssassin/AppImageLauncher#490]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

`Exec=` settings in auto-generated desktop entry is incorrect.

Audacity's AppImage sets `Exec` to `env UBUNTU_MENUPROXY=0 audacity %F` in the desktop entry file. In AppImageLauncher's desktop entry, `Exec` becomes `/opt/AppImages/audacity-linux-3.1.3-x86_64_e2b11597c4ef63e68e102b057c5cd759.AppImage UBUNTU_MENUPROXY=0 audacity %F`, which actually passes `UBUNTU_MENUPROXY=0`, `audacity` and `%F` as file list to open to audacity, which does not make sense.

### Expected behavior

AppImageLauncher should generate `Exec` correctly, for example, `Exec=/path_to_appimage %F`.

### Distribution and desktop environment

Linux Mint 20.3

### Installed AppImageLauncher version

```
qt5ct: using qt5ct plugin
AppImageLauncher version 2.2.0 (git commit aa114f1), built on 2022-01-14 01:25:01 UTC
```

### List of AppImages you tried

* Audacity 3.1.3 Not working: [https://www.audacityteam.org/download/linux/](https://www.audacityteam.org/download/linux/)

**Comment by TheAssassin** [comment]
The audacity team should not abuse `Exec` for setting env vars. They may use a shell script for their AppImage's `AppRun`. Please let them know about this. libappimage cannot/shouldn't guess whether people implement hacks like this to have environment variables set before their app launches.
