### ISSUE TITLE
Wiki corrections are required (unable to install app)

### ISSUE THREAD

**Issue by YuvanMichael** [TheAssassin/AppImageLauncher#492]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

When following the instructions provided in the wiki. The commands are wrong they don't work. The repository cannot be added. Therefore, the application cannot be installed. 

### Expected behavior

The commands are correct, repository should have been added and the application should have installed. 

### Steps to reproduce the issue

1. Follow the wiki on install AppImage Launcher on Ubuntu/Debian. 
2. Paste the add repository command 
3. There's your error. 

### Screenshots

![3](https://user-images.githubusercontent.com/86945563/154799270-fbac93fc-c3b1-41e7-98d0-472eddd35e7b.png)
![2](https://user-images.githubusercontent.com/86945563/154799273-643fd0e8-4fb3-4834-82ee-c159bee2e46f.png)
![1](https://user-images.githubusercontent.com/86945563/154799274-002c5f55-c0ff-43df-8050-343989f90858.png)
![4](https://user-images.githubusercontent.com/86945563/154799338-e004f0b7-fac3-4b83-8c1b-8bb672b79a29.png)

### Distribution and desktop environment

Elementary os 
Pantheon desktop

### Installed AppImageLauncher version

Not Installed

**Comment by TheAssassin** [comment]
ElementaryOS is not officially supported.

**Comment by YuvanMichael** [comment]
why not
