### ISSUE TITLE
AppImageLauncher's own AppImage should be self-installing

### ISSUE THREAD

**Issue by shoogle** [TheAssassin/AppImageLauncher#50]
If I follow these steps...

1. Download the AppImage version of AppImageLauncher
2. Set the executable bit
3. Run it by double-clicking on it in the file manager (i.e. don't run it from the terminal)

...then nothing happens.

Instead, what should happen is AppImageLauncher should detect whether it has been integrated into the system already, and if not, then it should offer to do so. (If it has already been integrated then it should display some kind of message to say it should be run from the command line.)

### Installing AppImageLauncher

For most AppImages, installation (or "integration") simply means copying the AppImage to `~/Applications` and adding a desktop file to `~/.local/share/applications`.

However, for AppImageLauncher's own AppImage, the following additional steps should be performed:

- Install the AppImage mimetypes to `~/.local/share/mime/packages`
- Set AppImageLauncher as the default open-with program for AppImages

If AppImageLauncher was run as root then it should install files to `/usr/local` rather than `~/.local`, and it can also register itself with `update-binfmts`.

### Advantages

Installing AppImageLauncher as a distribution package requires root privileges. This means it can only be done by system admins, who may not be aware of the AppImage format.

Installing to `~/.local` doesn't require root privileges, so users can install AppImageLauncher on work/uni machines where they don't have root acces, and gain full integration for any subsequent AppImages they install.

### Requirements

AppImageLauncher's AppImage will need to be installed to a location in the user's `$PATH`. Suitable locations are:

- `~/bin`
- `~/.local/bin`
- `~/Applications`

On most systems, only `~/bin` is in `$PATH` by default, so AppImageLauncher will need to check whether its location is in `$PATH` and add it if necessary.

Ideally, one of the above locations should be chosen as the default location for AppImages that are supposed to be run from the command line.

**Comment by TheAssassin** [comment]
Please see https://github.com/TheAssassin/AppImageLauncher#appimage. The AppImage is _only_ provided for evaluation purposes. AppImageLauncher integrates deeply into the system to provide its functionality, and I don't want to maintain my own installation framework for these purposes. Therefore native packages are provided.

It _cannot_ be installed via the AppImage. What the AppImage allows you to do is test the UI. You can call it like `./AppImageLauncher-*.AppImage some-other.AppImage`.

**Comment by shoogle** [comment]
I know it is (currently) provided only for evaluation purposes, but you're missing a __huge__ opportunity here. At the moment AppImageLauncher suffers from the same chicken-and-egg problem as `appimaged` where sysadmins are required to install it, whereas you could enable users to take the initiative and install it on their own.

Also, you don't have to maintain any installation framework unique to AppImageLauncher. Many apps would like to be able to full integrate themselves (MuseScore already does this, icons, mimetypes, manual and all), so the intallation framework should be built in to AppImageKit, `linuxdeployqt`, or its successor.

The framework is as simple as this:

- look inside the AppImage for `$APPDIR/share` or `$APPDIR/usr/share`
- if it exists, copy its contents to `~/.local/share` (or `/usr/local/share` if running as root)
- call `update-desktop-database` and friends to register the new desktop files, icons, etc

That's all! That's exactly what MuseScore does, and it gets you __full system integration__ without root being required at any stage.

**Comment by shoogle** [comment]
The main feature of AppImages that makes them the superior to other packaging formats is that they are not dependent of the distribution. If you are going to try persuading distros then I wish you all the luck in the world (seriously!). @probonopd has been trying to do that for years with no success.

**Comment by TheAssassin** [comment]
@shoogle there's distros shipping AppImageLauncher already, such as Netrunner (rolling). And I'm trying  to present this software on conferences. Once a few big players ship this (or DEs add it to their collection), it'll be shipped.

**Comment by shoogle** [comment]
Ah, well congrats then! Still, I highly doubt that you will get this in the big distros, at least not until literally all the smaller ones have it and you have sandboxing by default. The big distros are busy fighting amongst themselves over whether snaps or flatpak will be the next distribution-approved packaging format, so you will have a hard time asking them to support another format. This is especially true for AppImage, since it is an independent one that removes centralised control over repositories, so it's almost like asking distributions to sign their own death warrant.

You might have more luck with DEs, but last time I spoke to the folks at GNOME they told me:

1. It has to be via GNOME Software (i.e. double-clicking an AppImage runs GNOME Software)
2. It has to have sandboxing by default (and not be possible to run without sandboxing)
3. Even then they would be unlikely to do it (because they support flatpak).

**Comment by TheAssassin** [comment]
https://gitlab.gnome.org/GNOME/nautilus/merge_requests/229

**Comment by shoogle** [comment]
Yes I saw that, and it is good news, but it simply maintains the status quo. It is undoing a change that would have made life more difficult for AppImages, not making them 1st class citizens.

**Comment by TheAssassin** [comment]
@shoogle you might want to give this project some time to actually _talk_ to distros and DEs and other projects before any catastrophizing.
