### ISSUE TITLE
Update Appimage repository for Ubuntu Jammy (22.04)

### ISSUE THREAD

**Issue by motusRP** [TheAssassin/AppImageLauncher#503]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Following the instructions in the Wiki to install the AppImage Launcher repository under Ubuntu 22.04, no repository is found for the jammy release.

### Expected behavior

Expected the update to find a Jammy repository to install from.

### Steps to reproduce the issue

Install Ubuntu 22.04 on new computer.
Try to add the AppImage Launcher apt repository using the commands in the Wiki.
See results like above.

### Screenshots

![image](https://user-images.githubusercontent.com/54725635/164519838-88479c47-77d6-4ad5-9d2e-a8652fa76e37.png)

### Distribution and desktop environment

Ubuntu 22.04 Desktop

### Installed AppImageLauncher version

None, yet.

### List of AppImages you tried

None, yet.

**Comment by TheAssassin** [comment]
Context: #426.

I not only had to [edit the source recipes](https://github.com/TheAssassin/AppImageLauncher/issues/426#issuecomment-1103604313), but also [request](https://code.launchpad.net/~appimagelauncher-team/+recipe/appimagelauncher-stable/+request-builds) [a build](https://code.launchpad.net/~appimagelauncher-team/+recipe/appimagelauncher-daily/+request-builds) manually for some reason. Launchpad is currently building the packages.

**Comment by motusRP** [comment]
Darn, I looked for something related, I really, really did!  Thanks for setting it up.

**Comment by TheAssassin** [comment]
It's not a duplicate issue, though. Launchpad is done.

**Comment by motusRP** [comment]
Odd... It now sees the repository, but can't find the install package.  Maybe i'm being impatient?
![image](https://user-images.githubusercontent.com/54725635/164531584-f5a60877-c617-4de3-8540-cff69e14dbea.png)

**Comment by TheAssassin** [comment]
Try to `apt update` again. Then, run `apt policy appimagelauncher`.

**Comment by motusRP** [comment]
No luck yet.
![image](https://user-images.githubusercontent.com/54725635/164533918-cb2ceef7-bf60-4d56-93d9-bd08d9596237.png)

**Comment by TheAssassin** [comment]
For some reason amd64 was not built, ARM binaries are available. I'll check what's wrong.

**Comment by TheAssassin** [comment]
Launchpad seems to struggle starting new builds, but they're scheduled. ETA 4 hours until completion.

**Comment by TheAssassin** [comment]
Binaries have been published by launchpad.

**Comment by motusRP** [comment]
Confirmed, they work great now!  Thanks very much.
