### ISSUE TITLE
Updater cannot find libappimageupdate.so

### ISSUE THREAD

**Issue by dayllenger** [TheAssassin/AppImageLauncher#51]
I don't really know how fix it correctly, so I wrote this issue.
On Ubuntu 18.04 AppImage updater fails with following message:
```
/usr/lib/appimagelauncher/update: error while loading shared libraries: 
libappimageupdate.so: cannot open shared object file: No such file or directory
```
It works fine when I start it from `/usr/lib/appimagelauncher` directory or when I do `export LD_LIBRARY_PATH=/usr/lib/appimagelauncher/`.

**Comment by TheAssassin** [comment]
@dayllenger how did you install the application? Using the bionic .deb package?

**Comment by dayllenger** [comment]
Yes, of course.

**Comment by TheAssassin** [comment]
I'll set up a bionic VM later and will test it myself. I use the non-bionic .deb myself and notice issues quite quickly there, and I don't know why the bionic package doesn't work (it's all built with CMake, after all).

**Comment by TheAssassin** [comment]
Issue confirmed. Seems like the `rpath` isn't set properly in `libappimageupdate-qt.so` (set to the build directory on Travis, actually). It's missing entirely in `libappimageupdate.so` and `libappimage.so`.

I think with some CMake magic, it should be possible to resolve the issues.

**Comment by TheAssassin** [comment]
Tested with the freshly built binaries. Works fine.

**Comment by dayllenger** [comment]
Thanks, it works, but it would be great to make [error messages visible](https://github.com/TheAssassin/AppImageLauncher/blob/master/src/update_main.cpp#L101).

**Comment by TheAssassin** [comment]
It's on the TODO list. Would you like to create a separate issue for that, please?

**Comment by Djeremaille** [comment]
Hello.
I'm on kde neon based on ubuntu 20.04 and I have this error too.
I installed it via ppa.
My libappimage:
`
lrwxrwxrwx 1 root root   20 mai   28 22:37 /usr/lib/x86_64-linux-gnu/libappimage.so.1.0 -> libappimage.so.1.0.2
-rw-r--r-- 1 root root 471K mai   28 22:37 /usr/lib/x86_64-linux-gnu/libappimage.so.1.0.2
`
