### ISSUE TITLE
mate: Removed programs remain in the menu until a logout

### ISSUE THREAD

**Issue by LyzardKing** [TheAssassin/AppImageLauncher#52]
I believe this happens because nothing triggers a refresh of the menus.
Everything is fine if I manually refresh the menus:
`sudo update-desktop-database`
I'm not sure if there's a non root way to do it..

I'm running ubuntu-mate 18.04 with the brisk menu

**Comment by TheAssassin** [comment]
@LyzardKing thanks for the hint. Seems like AppImageLauncher needs to run `update-desktop-database`. There is a non-root way, just specify the directory as parameter.

**Comment by LyzardKing** [comment]
How can it know that I deleted an appimage from the folder, is it watching that folder constantly? if so a file deletion could trigger an update-desktop-database

**Comment by TheAssassin** [comment]
@LyzardKing there is a little removal tool which takes care of removing the actual file (and removing the integration files a.k.a. desktop file and icon). We can just run `update-desktop-database` at the end of that tool.

**Comment by LyzardKing** [comment]
Ok, I had not noticed that.
I still think it should integrate with the manual removal of the file,
but this is good

**Comment by TheAssassin** [comment]
Well, the "manual removal" is not monitored. This relies on the `TryExec` desktop file key. Apparently MATE doesn't implement this flag properly.

We are discussing a little daemon monitoring `~/Applications` and taking care of integration and removal calling the appropriate hooks that might fix the issue for the other workflow as well.

**Comment by LyzardKing** [comment]
I thought AppImageLauncher already monitored the Applications folder,
but I might be confused with appimaged...
Since AppImageLauncher only manages one folder, it might be useful to add
a monitor capability for that..just to avoid issues like this.

**Comment by TheAssassin** [comment]
If/when we implement the monitoring, we're going to implement this there as well.

**Comment by TheAssassin** [comment]
Make sure to also check out the update entry!

**Comment by LyzardKing** [comment]
Yes, that I'm aware of. Not sure how it works...
If I build an appimage, do I have to do anything specific to enable updates?
But that's not related to the launcher, is it?

**Comment by TheAssassin** [comment]
Not really. AppImageLauncher uses AppImageUpdate (https://github.com/AppImage/AppImageUpdate). Check https://github.com/AppImage/AppImageKit#command-line-arguments how to embed update information and enable updates.
