### ISSUE TITLE
AIL doesn't have an upgrade option in PopOS (Ubuntu 22.04LTS)

### ISSUE THREAD

**Issue by life5ign** [TheAssassin/AppImageLauncher#526]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

The docs mention that I should see an "upgrade" option in the context menu in the desktop menu by right-clicking.  I don't see this in PopOS (Ubuntu 22.04 LTS base).  Here's an exampe for `logseq`:

![image](https://user-images.githubusercontent.com/63751140/187043970-9d0db455-543f-4292-9184-213df4493697.png)

Also, in the ail settings, the upgrade box is unchecked:
![image](https://user-images.githubusercontent.com/63751140/187044015-c25e516a-b7df-4494-a0a3-ad6ec368a3c1.png)

### Expected behavior

I expected to see something about upgrading the appimage.

### Steps to reproduce the issue

Press Super, find the program installed via appimage, and right-click it; see no upgrade option.

### Screenshots

See above

### Distribution and desktop environment

Pop!_OS 22.04LTS:
![image](https://user-images.githubusercontent.com/63751140/187044092-30794f21-e103-4f20-96e1-13cbeffc72ef.png)

### Installed AppImageLauncher version

```
❯ AppImageLauncher --appimagelauncher-version                                                                                                                               
Qt: Session management error: Could not open network socket
AppImageLauncher version 2.2.0 (git commit 0f91801), built on 2022-04-22 02:10:10 UTC
```

### List of AppImages you tried

- https://github.com/logseq/logseq
- https://filen.io/apps

**Comment by TheAssassin** [comment]
The PPA has never supported updating since Ubuntu doesn't provide packages for libappimageupdate. This should be mentioned in the PPA description.

**Comment by TheAssassin** [comment]
By the way, the settings dialog shows that updating is not supported, too. To make use of the integrated updater feature, use the packages provided on the GitHub release page.

**Comment by TheAssassin** [comment]
To answer your other question, yes, still maintained, but time's extremely limited. I think this application is working very very well (I use it every day) anyway. A 3.0 is on the way, though.

**Comment by TheAssassin** [comment]
2.2.0 has been released over two years ago, so its libappimage's become quite old by now. You may want to test the latest continuous (pre)release, which also works very stable and gives you some of the latest features.

**Comment by TheAssassin** [comment]
See https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous. The daily PPA is broken at the moment apparently according to Launchpad's mails. Have not found time to have a look at it yet.
