### ISSUE TITLE
Appimagelauncher causes nautilus to change from show hidden files to hidden files again

### ISSUE THREAD

**Issue by XRohitKS** [TheAssassin/AppImageLauncher#527]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

hidden files got hidden again after everytime appimage launcher runs

### Expected behavior

it does not interfare with nautilus settings

### Steps to reproduce the issue

1. show hidden files in nautilus
2. run a appimage using appimage launcher
3. after some time hidden files got hidden again
4. then need to show hidden files again.

### Distribution and desktop environment

Using Ubuntu 22.04.1 amd64
windowing system x11

### Installed AppImageLauncher version

202204211752-stable-0f91801~ubuntu22.04.1

### List of AppImages you tried

try any...
Upscayl-1.2.0.AppImage

**Comment by XRohitKS** [comment]
please make option so that we can use it without modifying system setting or nautilus settings

**Comment by TheAssassin** [comment]
AppImageLauncher does not interact with any file browser settings.

**Comment by XRohitKS** [comment]
how to resolve this issue then...
it causing issue to nautilus??? 
do you check if it is reproduced for you ..
Any way to trace what causing hidden files settings on off??

**Comment by TheAssassin** [comment]
Why do you even claim AppImageLauncher had anything to do with it? A timing correlation does not necessarily imply a causality.

You're not providing any useful information. The "describe the bug" and "expected behavior" fields do not even contain full sentences. There's no video or GIF that shows this behavior. The behavior cannot be observed in a vanilla VM using a live ISO of your distribution.

**Comment by XRohitKS** [comment]
It is appimage issue i am using not launcher , got it!! appimage tweaking the settings when i uing it.
Still the experience is great with AppimageLauncher
I started using the AppimageLauncher and the New appimage of app at same time so get false idea!!
 Sorry for inconvenience.

**Comment by TheAssassin** [comment]
No problem, glad you figured it out eventually!
