### ISSUE TITLE
Krita fails with appimagelauncher

### ISSUE THREAD

**Issue by LyzardKing** [TheAssassin/AppImageLauncher#53]
Hi.
If I load krita with appimagelauncher
even if I select run once, it fails to set the python path properly.
If I remove appimagelauncher it starts properly.
It's not a bug in krita, since I reported it upstream and a but has been fixed.
I believe appimagelauncher is doing something to these appimages.

**Comment by TheAssassin** [comment]
Please provide a link to the Krita AppImage so I can test it myself.

**Comment by LyzardKing** [comment]
It's the latest beta
https://download.kde.org/unstable/krita/4.1.0-beta.2/krita-4.1.0-beta.2-x86_64.appimage

**Comment by LyzardKing** [comment]
I'm running ubuntu mate 18.04 x86_64
I first tried running the appimage with appimagelauncher and I got an error,
after a removal it starts properly

**Comment by TheAssassin** [comment]
@LyzardKing I don't see how the PYTHONPATH could be an issue here, actually. Could you elaborate on that, please?

**Comment by TheAssassin** [comment]
Launches fine with the latest AppImageLauncher installed on my system. `PYTHONPATH` seems to be set properly.

```
[...]
/tmp/.mount_krita-mPsy0p/usr/lib/krita-python-libs/krita added to PYTHONPATH
[...]
```

**Comment by LyzardKing** [comment]
This is the upstream bug report
The gist is that krita bundles python, and if I run appimagelauncher, for some reason
on my system it doesn't set PYTHONPATH correctly. Since my system is clean, and it works if I remove 
the launcher I suppose it might have something to do with that..

**Comment by LyzardKing** [comment]
I get this on my system:
```

krita.scripting: Setting python paths: "/home/galileo/.local/share/krita/:/tmp/.mount_runtimYB8nTd/usr/share/krita/:/home/galileo/.local/share/krita/pykrita/:/tmp/.mount_runtimYB8nTd/usr/share/krita/pykrita/:/tmp/.mount_runtimYB8nTd/usr/share/pykrita/:/tmp/.mount_runtimYB8nTd/usr/lib/krita-python-libs:/tmp/.mount_runtimYB8nTd/usr/lib/sip"
krita.scripting: Initializing Python interpreter
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
```

It's not loading the python libraries.
The strange thing is that this issue only appears with the launcher installed

**Comment by TheAssassin** [comment]
Can you tell any differences in this log when running with and without AppImageLauncher installed?

**Comment by LyzardKing** [comment]
Yes, this error is missing without the launcher installed.
It doesn't even mention the python3.5 bundled python unless I run with debug options
But it runs.
If I have the launcher installed I get the error and it segfaults (because it's missing python)

**Comment by TheAssassin** [comment]
Upstream bug report: https://bugs.kde.org/show_bug.cgi?id=395606

boud and I found the issue, it's in https://phabricator.kde.org/source/krita/browse/master/plugins/extensions/pykrita/plugin/utilities.cpp$322, line . It'll be fixed there soon, and should be fixed in the next release. Closing here.
