### ISSUE TITLE
Keep original Desktop Actions if present

### ISSUE THREAD

**Issue by Korkman** [TheAssassin/AppImageLauncher#534]
### Pre-submit checks

- [X] I checked for similar issues beforehand, but could not find any. I could not add my proposal to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Feature description

Currently it seems desktop actions present in the contained application .desktop file are simply overwritten with the "Remove from system" entry rather than keeping existing entries. It would be nice to keep them along with any AppImageLauncher specific options.

Since the main desktop entry "Exec" path is updated to the new location, the same should happen for the author's desktop actions (keeping all their arguments, of course).

### Proposed solution

Merged desktop actions from AppImage authors and AppImageLauncher.

**Comment by TheAssassin** [comment]
This should be a bug report, not a feature request, since this should be the case with libappimage already. In fact it's working for me usually. So please open a bug report.

**Comment by Korkman** [comment]
Opened and closed a [bug report](https://github.com/TheAssassin/AppImageLauncher/issues/536), turns out the [stable ppa](https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable) release for Ubuntu 22.04 is simply outdated.
