### ISSUE TITLE
No "remove" entry in the context menu

### ISSUE THREAD

**Issue by rdgh8** [TheAssassin/AppImageLauncher#538]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

The README for appimagelauncer says to remove an appimage, you "Click the "Remove" entry in the context menu in the application launcher and the removal tool will ask you to confirm". I cannot find this entry anywhere. 

### Expected behavior

Expected a remove entry in the right click menu for the appimage. 

### Steps to reproduce the issue

These are the exact things I did:
1. Install the appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm downloaded from [here](https://github.com/TheAssassin/AppImageLauncher/releases/tag/v2.2.0)
2. Go onto [the Jetbrains Toolbox website](https://www.jetbrains.com/toolbox-app/) and download the tar.gz for the toolbox app
3. Go to the Downloads folder in Nautilus, double click the tar.gz to unpack it
4. Enter the new folder containing Jetbrains Toolbox
5. Right click on the jetbrains-toolbox file and open it with appimagelauncher
6. Don't remember exactly what happened here, but I think appimagelauncher asked me about where applications should be installed to since it is my first time using it. I just left the defaults and hit ok. 
7. Attempt to delete jetbrains tollbox in the app menu 

### Screenshots

![Screenshot from 2022-10-12 15-09-30](https://user-images.githubusercontent.com/66289396/195429509-e6d571c3-b98e-438e-9420-8d289f5c0c3d.png)

### Distribution and desktop environment

Fedora 36 on Wayland, Gnome 42.5

### Installed AppImageLauncher version

AppImageLauncher version 2.2.0 (git commit 0f91801), built on 2020-09-29 21:36:22 UTC

### List of AppImages you tried

[Jetbrains toolbox ](https://www.jetbrains.com/toolbox-app/)

### Additional context

Not sure if it's intended behaviour, but nowhere in the process was a ~/Applications folder created or populated. The jetbrains-toolbox file was just left in the Downloads folder where I had unpacked it to.

**Comment by TheAssassin** [comment]
Every couple of months, Jetbrains' toolbox comes up. They now got `X-AppImage-Integrate=false` in their AppImage's desktop file, which means AppImageLauncher will ignore it. Whatever integration they run, it's got _nothing_ to do with AppImageLauncher.

Try `ail-cli would-integrate jetbrains-toolbox`, you'll see:

```sh
terminate called after throwing an instance of 'appimagelauncher::cli::commands::WouldNotIntegrateError'
  what():  AppImage should not be integrated
```

See https://github.com/TheAssassin/AppImageLauncher/issues/239#issuecomment-531541551.
