### ISSUE TITLE
Cannon install appimagelauncher

### ISSUE THREAD

**Issue by jeffsauer** [TheAssassin/AppImageLauncher#539]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

On a fully updated endeavouros system, yay -S appimagelauncher fails with fatal: transport 'file' not allowed error:

yay -S appimagelauncher
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  appimagelauncher-2.2.0-6

  1 appimagelauncher                 (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 1
:: Deleting (1/1): /home/jsauer/.cache/yay/appimagelauncher
:: (1/1) Downloaded PKGBUILD: appimagelauncher
  1 appimagelauncher                 (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: appimagelauncher
==> Making package: appimagelauncher 2.2.0-6 (Wed 19 Oct 2022 06:55:48 AM MST)
==> Retrieving sources...
  -> Cloning AppImageLauncher git repo...
Cloning into bare repository '/home/jsauer/.cache/yay/appimagelauncher/AppImageLauncher'...
remote: Enumerating objects: 7017, done.
remote: Counting objects: 100% (761/761), done.
remote: Compressing objects: 100% (336/336), done.
remote: Total 7017 (delta 477), reused 611 (delta 419), pack-reused 6256
Receiving objects: 100% (7017/7017), 1.89 MiB | 4.05 MiB/s, done.
Resolving deltas: 100% (4806/4806), done.
  -> Cloning AppImageUpdate git repo...
Cloning into bare repository '/home/jsauer/.cache/yay/appimagelauncher/AppImageUpdate'...
remote: Enumerating objects: 2788, done.
remote: Counting objects: 100% (760/760), done.
remote: Compressing objects: 100% (277/277), done.
remote: Total 2788 (delta 488), reused 721 (delta 459), pack-reused 2028
Receiving objects: 100% (2788/2788), 554.28 KiB | 1.92 MiB/s, done.
Resolving deltas: 100% (1757/1757), done.
  -> Cloning libappimage git repo...
Cloning into bare repository '/home/jsauer/.cache/yay/appimagelauncher/libappimage'...
remote: Enumerating objects: 5419, done.
remote: Counting objects: 100% (437/437), done.
remote: Compressing objects: 100% (239/239), done.
remote: Total 5419 (delta 220), reused 322 (delta 163), pack-reused 4982
Receiving objects: 100% (5419/5419), 2.29 MiB | 4.44 MiB/s, done.
Resolving deltas: 100% (3928/3928), done.
  -> Cloning zsync2 git repo...
Cloning into bare repository '/home/jsauer/.cache/yay/appimagelauncher/zsync2'...
remote: Enumerating objects: 1079, done.
remote: Counting objects: 100% (234/234), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 1079 (delta 136), reused 208 (delta 122), pack-reused 845
Receiving objects: 100% (1079/1079), 497.41 KiB | 1.66 MiB/s, done.
Resolving deltas: 100% (672/672), done.
  -> Cloning sanitizers-cmake git repo...
Cloning into bare repository '/home/jsauer/.cache/yay/appimagelauncher/sanitizers-cmake'...
remote: Enumerating objects: 291, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 291 (delta 26), reused 28 (delta 13), pack-reused 243
Receiving objects: 100% (291/291), 70.48 KiB | 869.00 KiB/s, done.
Resolving deltas: 100% (184/184), done.
  -> Cloning googletest git repo...
Cloning into bare repository '/home/jsauer/.cache/yay/appimagelauncher/googletest'...
remote: Enumerating objects: 50073, done.
remote: Counting objects: 100% (558/558), done.
remote: Compressing objects: 100% (278/278), done.
remote: Total 50073 (delta 351), reused 384 (delta 232), pack-reused 49515
Receiving objects: 100% (50073/50073), 27.96 MiB | 8.22 MiB/s, done.
Resolving deltas: 100% (34575/34575), done.
  -> Cloning cpr git repo...
Cloning into bare repository '/home/jsauer/.cache/yay/appimagelauncher/cpr'...
remote: Enumerating objects: 2954, done.
remote: Total 2954 (delta 0), reused 0 (delta 0), pack-reused 2954
Receiving objects: 100% (2954/2954), 476.35 KiB | 1.41 MiB/s, done.
Resolving deltas: 100% (1969/1969), done.
  -> Cloning args git repo...
Cloning into bare repository '/home/jsauer/.cache/yay/appimagelauncher/args'...
remote: Enumerating objects: 4318, done.
remote: Counting objects: 100% (401/401), done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 4318 (delta 233), reused 358 (delta 212), pack-reused 3917
Receiving objects: 100% (4318/4318), 2.71 MiB | 4.88 MiB/s, done.
Resolving deltas: 100% (3565/3565), done.
  -> Found appimage-binfmt-remove.hook
==> Validating source files with sha256sums...
    AppImageLauncher ... Skipped
    AppImageUpdate ... Skipped
    libappimage ... Skipped
    zsync2 ... Skipped
    sanitizers-cmake ... Skipped
    googletest ... Skipped
    cpr ... Skipped
    args ... Skipped
    appimage-binfmt-remove.hook ... Passed
==> Making package: appimagelauncher 2.2.0-6 (Wed 19 Oct 2022 06:56:02 AM MST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating AppImageLauncher git repo...
  -> Updating AppImageUpdate git repo...
  -> Updating libappimage git repo...
  -> Updating zsync2 git repo...
  -> Updating sanitizers-cmake git repo...
  -> Updating googletest git repo...
  -> Updating cpr git repo...
  -> Updating args git repo...
  -> Found appimage-binfmt-remove.hook
==> Validating source files with sha256sums...
    AppImageLauncher ... Skipped
    AppImageUpdate ... Skipped
    libappimage ... Skipped
    zsync2 ... Skipped
    sanitizers-cmake ... Skipped
    googletest ... Skipped
    cpr ... Skipped
    args ... Skipped
    appimage-binfmt-remove.hook ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of AppImageLauncher git repo...
Cloning into 'AppImageLauncher'...
done.
Switched to a new branch 'makepkg'
  -> Creating working copy of AppImageUpdate git repo...
Cloning into 'AppImageUpdate'...
done.
  -> Creating working copy of libappimage git repo...
Cloning into 'libappimage'...
done.
  -> Creating working copy of zsync2 git repo...
Cloning into 'zsync2'...
done.
  -> Creating working copy of sanitizers-cmake git repo...
Cloning into 'sanitizers-cmake'...
done.
  -> Creating working copy of googletest git repo...
Cloning into 'googletest'...
done.
  -> Creating working copy of cpr git repo...
Cloning into 'cpr'...
done.
  -> Creating working copy of args git repo...
Cloning into 'args'...
done.
==> Starting prepare()...
Submodule 'lib/AppImageUpdate' (https://github.com/AppImage/AppImageUpdate.git) registered for path 'lib/AppImageUpdate'
Submodule 'lib/libappimage' (https://github.com/AppImage/libappimage.git) registered for path 'lib/libappimage'
Cloning into '/home/jsauer/.cache/yay/appimagelauncher/src/AppImageLauncher/lib/AppImageUpdate'...
fatal: transport 'file' not allowed
fatal: clone of '/home/jsauer/.cache/yay/appimagelauncher/src/AppImageUpdate' into submodule path '/home/jsauer/.cache/yay/appimagelauncher/src/AppImageLauncher/lib/AppImageUpdate' failed
Failed to clone 'lib/AppImageUpdate'. Retry scheduled
Cloning into '/home/jsauer/.cache/yay/appimagelauncher/src/AppImageLauncher/lib/libappimage'...
fatal: transport 'file' not allowed
fatal: clone of '/home/jsauer/.cache/yay/appimagelauncher/src/libappimage' into submodule path '/home/jsauer/.cache/yay/appimagelauncher/src/AppImageLauncher/lib/libappimage' failed
Failed to clone 'lib/libappimage'. Retry scheduled
Cloning into '/home/jsauer/.cache/yay/appimagelauncher/src/AppImageLauncher/lib/AppImageUpdate'...
fatal: transport 'file' not allowed
fatal: clone of '/home/jsauer/.cache/yay/appimagelauncher/src/AppImageUpdate' into submodule path '/home/jsauer/.cache/yay/appimagelauncher/src/AppImageLauncher/lib/AppImageUpdate' failed
Failed to clone 'lib/AppImageUpdate' a second time, aborting
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: appimagelauncher

### Expected behavior

expected to install cleanly

### Steps to reproduce the issue

yay -S appimagelauncher

### Distribution and desktop environment

EndeavourOS KDE Plasma

### Installed AppImageLauncher version

2.2.0-6

**Comment by TheAssassin** [comment]
No support for third-party packaging. Ask the AUR maintainer.

**Comment by jeffsauer** [comment]
OK.. thanks... I resolved the issue, just to comment on it here: turned out to be an issue with git 2.38.1 update...

https://bbs.archlinux.org/viewtopic.php?id=280571

git config --global protocol.file.allow always

resolved the issue.

**Comment by TheAssassin** [comment]
Good. You might want to let the AUR people know. I think users can leave comments there.
