### ISSUE TITLE
Display update error messages

### ISSUE THREAD

**Issue by dayllenger** [TheAssassin/AppImageLauncher#54]
If updater fails to check updates for some reason, the error messages are not displayed. Good if detailed info will appear in [the message box](https://github.com/TheAssassin/AppImageLauncher/blob/master/src/update_main.cpp#L101).

**Comment by TheAssassin** [comment]
AppImageUpdate's Qt UI module lacks support for fetching error messages at the moment. We should add it there, and then make use of it here.

**Comment by TheAssassin** [comment]
Implemented the prerequisites in libappimageupdate-qt in https://github.com/AppImage/AppImageUpdate/commit/6f8f5154051bb109f0f245683018d6b868f17908.
