### ISSUE TITLE
Add 22.10 kinetic kudu to ppa

### ISSUE THREAD

**Issue by acarlton** [TheAssassin/AppImageLauncher#540]
### Pre-submit checks

- [X] I checked for similar issues beforehand, but could not find any. I could not add my proposal to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Feature description

Please add support in the ppa for Ubuntu 22.10 Kinetic Kudu. Upon upgrading today I was unable to download updates.

### Proposed solution

Not sure how it works, but add a build and upload to PPA repo with kinetic keyword.

### Alternative solutions you considered

Using a target for older Ubuntu version in custom ppa definition.

**Comment by TheAssassin** [comment]
Fixed. Please use Launchpad to reach out for such questions, though.
