### ISSUE TITLE
can't add " --no-sandbox" to exec, AppImageLauncher deletes its desktop file

### ISSUE THREAD

**Issue by j2l** [TheAssassin/AppImageLauncher#543]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Fantasia Archive Appimage [doesn't work as is](https://github.com/Elvanos/fantasia-archive/issues/25#issuecomment-1321248728)
I tested that simply launching the AppImage with `--no-sandbox` using Terminal works.
So I'd like to add it to the desktop entry.
`Exec="/home/pm/Documents/Fantasia Archive-0.1.9-linux_7332f2cfa207792da20db412abb97b6e.AppImage" --no-sandbox %U` + removing TryExec works, only once and is deleted by AppImageLauncher.
If I click integrate "Integrate and Run", it doesn't keep `--no-sandbox` so the AppImage crashes.

### Expected behavior

Launch the Fantasia Archive AppImage :)
(add/keep `--no-sandbox`)

### Steps to reproduce the issue

1. Download Fantasia
2. Try to launch on Ubuntu 22.04.1
3. Using terminal, launch it using `--no-sandbox`
4. try to add `--no-sandbox` to generated .desktop file
5. launch and choose to delete desktop file or integrate and loose `--no-sandbox` -> AppImage doesn't launch

### Distribution and desktop environment

Ubuntu 22.04 (PopOS)

### Installed AppImageLauncher version

AppImageLauncher version 2.2.0 (git commit 0f91801), built on 2020-09-29 21:36:15 UTC

### List of AppImages you tried

[Fantasia 0.1.9](https://github.com/Elvanos/fantasia-archive/releases)

**Comment by TheAssassin** [comment]
Everyone, please stop opening new issues about desktop files being overwritten. This is normal, expected behavior.

You need to fix the AppImage, not the extracted desktop file: extract the AppImage's contents, fix the desktop file, repack it with appimagetool and then open an issue upstream.

**Comment by j2l** [comment]
Generally speaking, I think adapting a .desktop file manually is pretty needed, but it's true in this case, the appimage needs a fix. I don't build appimages at all, so I can't fix them.
I had to uninstall your nice appimagelauncher to make it work for now.

**Comment by TheAssassin** [comment]
Well, these files are extracted automatically. Updating the files while preserving user changes imposes significant challenges. AppImageLauncher has to update the files on every update, since the integration code may have changed.

A viable workaround is to just copy the desktop file, e.g., append some `(fixed)` suffix, fix the `Exec` key and ignore the original entry in your application menu.
