### ISSUE TITLE
Adding PPA repository failed on Ubuntu 22.04

### ISSUE THREAD

**Issue by KrishnanS2006** [TheAssassin/AppImageLauncher#548]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

When running the command `sudo add-apt-repository ppa:appimagelauncher-team/stable` to install AppImageLauncher on Ubuntu, it raises a `TimeoutError: [Errno 110] Connection timed out` (see screenshot)

### Expected behavior

"OK" and PPA gets installed, so `sudo apt install appimagelauncher` works as expected

### Steps to reproduce the issue

Run the command `sudo add-apt-repository ppa:appimagelauncher-team/stable`

### Screenshots

![image](https://user-images.githubusercontent.com/62958782/206342810-a7eff8e1-7846-4d02-8d64-432ce58a6300.png)

### Distribution and desktop environment

Ubuntu 22.04.1 LTS x86_64

AMD Ryzen 7 5700G

### Installed AppImageLauncher version

N/A

### List of AppImages you tried

N/A

**Comment by TheAssassin** [comment]
This is clearly not an issue of AppImageLauncher or its PPA but the tool `add-apt-repository`, most likely a temporary one. Try adding any other PPA. If that works and this PPA explicitly doesn't, please reopen.

**Comment by lwpamihiranga** [comment]
I had the same issue. Try disabling IPv6:

```
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
```

Original answer found in: https://askubuntu.com/questions/1415009/add-apt-respository-keeps-timing-out
