### ISSUE TITLE
Failed to register AppImage in system via libappimage for OpenShot

### ISSUE THREAD

**Issue by logix2** [TheAssassin/AppImageLauncher#55]
Trying to integrate / run OpenShot 2.4.2 downloaded from here: https://www.openshot.org/download/ results in this error message being displayed by AppImageLauncher: "Failed to register AppImage in system via libappimage". This occurs in Ubuntu 18.04 64bit. 

I'm not sure how to debug this further but let me know what else I can do to help.

**Comment by TheAssassin** [comment]
@logix2 could you try with the AppImageLauncher AppImage and see whether it works with it? The bionic packages needed some workarounds to work as intended, but the AppImage uses the same binaries as the "normal" .deb package.

**Comment by logix2** [comment]
It doesn't work - I get the same error. Other apps work, so it's related to the OpenShot AppImage in some way.

**Comment by TheAssassin** [comment]
I can reproduce this issue. And I noticed that we should undo moving the AppImage to `~/Applications` when integrating it fails. I will use my debugger to see where it fails.

**Comment by TheAssassin** [comment]
OpenShot still use type 1. Type 1 support is limited. Could you please ask them to switch to type 2?
Nevertheless, the issue is you faced was apparently a bug in libappimage. Fixing it there, then updating the AppImageKit submodule.
