### ISSUE TITLE
Not prompted to choose "integrate and run"

### ISSUE THREAD

**Issue by mpeter50** [TheAssassin/AppImageLauncher#553]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

When "executing" an AppImage file, the software in it is automatically ran without asking if I want to integrate it.
In other words, opening the AppImage file results in the same outcome as it did before I installed AppImageLauncher.

### Expected behavior

I expected this prompt to appear, as it is written in the readme:

![](https://github.com/TheAssassin/AppImageLauncher/raw/master/resources/doc/screenshot.png)

### Steps to reproduce the issue

1. Open an AppImage file (for example by double clicking on it in KDE Dolphin, or right clicking on it and selecting "Open with AppImageLauncher")
2. See outcome: the software has opened instead of the prompt. The software has not been intergrated to the system either.

### Distribution and desktop environment

- openSUSE Leap 15.4
- KDE Plasma 5.24.4
- Linux kernel 5.14.21
- Graphics platform: Wayland

### Installed AppImageLauncher version

Release 2.2.0, from this file: https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm

### List of AppImages you tried

- LibreWolf 108.0-1 (broken), https://gitlab.com/api/v4/projects/24386000/packages/generic/librewolf/108.0-1/LibreWolf.x86_64.AppImage

### Additional context

AppImageLauncher's settings tool is available in the launcher, and I can also open it.

I had issues with installing the RPM package: initially it was opened in KDE Discover, with recognized it, but failed to install it. It made 3 "toast" messages (like on Android), that said the following: "Internal error", "Too few items to process", "Too few items to process".
Installing with this command succeeded, however:
```
rpm -ivh Downloads/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm
```

I have rebooted since installing AppImageLauncher, but it did not fix this issue.

**Comment by mpeter50** [comment]
I have tried installing the AppImage with `ail-cli integrate <file path>`, and it seems it ran successfully.
LibreWolf has appeared in the launcher. However it also ignored my setting to not move the file to the separate directory.

I will keep this issue open. Please feel free to ask for more info if needed.

**Comment by mpeter50** [comment]
I have also discovered that moving the AppImage file back to where it was will make its entry disappear from the launcher.

**Comment by mpeter50** [comment]
I have fixed the icon problem with manually editing the Desktop file at `~/.local/share/applications/appimagekit_<id>-<appname>.desktop`, by changing the value of the Icon key to the full path of the icon file (extension not necessary).
Originally the value of this field was the file name only (but it was correct), without path.
The icon is in `~/.local/share/icons/hicolor/128x128/apps/...`, as it was written in the warning by the integration command that it wasnt able to resize it.

**Comment by TheAssassin** [comment]
> and it also ignored my setting to not move (and rename) the file to the separate directory.

What setting? Such a setting does not exist.

**Comment by mpeter50** [comment]
This one:

![image](https://user-images.githubusercontent.com/83356418/209558878-743681e7-027a-49e9-9b6f-bc36ce122c2e.png)

Isn't this the configuration utility of AIL?

**Comment by TheAssassin** [comment]
This disables the integration dialog completely. iit doesn't leave it enabled but stop moving files into the integration directory. I think the language could be improved.

**Comment by mpeter50** [comment]
The integration directory is `~/.local/share/applications/`, right?
If AppImage files are moved there, it is ok.
I wanted to have this setting turned off because I was in the impression that AIL wants to move the AppImage file to `~/Applications`, and I already have too much directories and files in there.

**Comment by TheAssassin** [comment]
> The integration directory is ~/.local/share/applications/, right?

No, never has been. This is where desktop files need to be placed.

> I wanted to have this setting turned off because I was in the impression that AIL wants to move the AppImage file to ~/Applications, and I already have too much directories and files in there.

Yep, that's the default, and it works pretty well for most people. You can adjust it. I'd however recommend not to use `~/.local/share/applications`. How about `~/.Applications` or `~/.local/appimages`?

**Comment by mpeter50** [comment]
> No, never has been. This is where desktop files need to be placed.

Yeah, thats why I mixed it up. Sorry!
I have to admit, I haven't used AppImages before.

> How about `~/.Applications` or `~/.local/appimages`?

These sound good. How would I set them up?

**Comment by TheAssassin** [comment]
There's a directory picker in the settings which you can use.

**Comment by mpeter50** [comment]
Oh, well, I've missed that. Sorry!
I'll close this issue now.
