### ISSUE TITLE
AppImageLauncher PPA on Chromebook

### ISSUE THREAD

**Issue by minimlr** [TheAssassin/AppImageLauncher#556]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

I'm trying to install AppImageLauncher on my Chromebook through Terminal. It is not installing the PPA as expected like I have on my Pop!_OS install. Is the application supported on Chromebooks? 

**I get the following message:**
Note: PPA packages do *not* support updating.
 More info: https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable
Press [ENTER] to continue or ctrl-c to cancel adding it
^CTraceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 143, in <module>
    sys.stdin.readline()
KeyboardInterrupt

### Expected behavior

I was expecting to add the PPA location to my Chromebook through terminal.

### Distribution and desktop environment

![Screenshot 2023-02-05 7 08 03 AM](https://user-images.githubusercontent.com/77010337/216806397-4e8cd3d3-130e-43d4-8a47-2c9d038887e3.png)
Acer Spin 713 (2021) Chromebook - Inte i5 11th Gen / 8GB MEM / 128GB SDD

### Installed AppImageLauncher version

202211022349-stable-0f91801~ubuntu22.04.1

### List of AppImages you tried

None.

**Comment by cobalt2727** [comment]
The Linux virtual machine on Chrome OS is running Debian, not Ubuntu - adding PPAs to a Debian install isn't supported.
This should be relabeled to `wontfix` - see https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian for more info.
(Pop_!OS uses Ubuntu as a base, so it can handle PPAs just fine.)
This is [mentioned](https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian#use-the-ppas) in the documentation, noting that the PPAs are only available for Ubuntu, so you'll want to follow the "Installing directly from GitHub" bit of the wiki instead. The obvious downside to this method is that you'll have to manually download and install new updates every time they come out...

**Comment by TheAssassin** [comment]
Thank you @cobalt2727 for pointing this out. You are completely right.

@minimlr Debian is supported via the `.deb` packages provided on the release page.
