### ISSUE TITLE
Overwriting of existing .desktop files for downloaded appimages

### ISSUE THREAD

**Issue by Flashwalker** [TheAssassin/AppImageLauncher#557]
### Pre-submit checks

- [X] I checked for similar issues beforehand, but could not find any. I could not add my proposal to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Feature description

I already have Appimages and .desktop files for them.

If I install AppImageLauncher and put my Appimages in the Applications folder, will it overwrite the existing .desktop files in ~/.local/... ?

### Proposed solution

Not overwrite, just keep em

**Comment by TheAssassin** [comment]
Yes. By design. As told in a variety of other issues. You clearly ignored the pre-submit checks.

**Comment by Flashwalker** [comment]
How about to open Discussions
Or place this info to the README as warning
