### ISSUE TITLE
AppImageLauncher may cause issues with Docker containers that extract AppImages

### ISSUE THREAD

**Issue by josealeixopc** [TheAssassin/AppImageLauncher#567]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

I'm unsure whether this should be classified as a bug, as it's not an issue with AppImageLauncher, but rather a side-effect that may be unaccounted for.

I installed AppImageLauncher on a fresh install in Ubuntu 22.04 after having installed a bunch of other tools, including Docker.

One of my repositories has a `docker-compose` file which, among a lot of things, creates a CentOS 7 container and extracts an AppImage using a command similar to:

```bash
./<app>.AppImage --appimage-extract
```

This command was failing with the following error:

```bash
sh: ./<app>.AppImage: /lib64/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
```

I checked that the `ld-linux-x86-64.so.2` indeed existed in my host machine and also inside the container. I could not get anyone to replicate my error, so I assumed it was some issue I had locally. As the local setup was rather fresh, my suspicion turned towards AppImageLauncher, so I uninstalled it using `apt remove` and restarted the computer.

After the restart, the error disappeared and I was able to run the container properly.

I apologize for the vagueness of this description, but I do not know enough to investigate the issue further. Just thought I should register it here, in case it is relevant for someone else.

### Expected behavior

n.a.

### Distribution and desktop environment

Ubuntu 22.04

### Installed AppImageLauncher version

v2.2.0

**Comment by TheAssassin** [comment]
Try the continuous release, it should fix exactly this problem. It's stable enough for daily use.

A release is due, actually, but the packaging is in a very sad state. Working on new packaging consumes a lot of time (also due to required extensive testing on various distributions), but is expected to finish in the next weeks.
