### ISSUE TITLE
Updater not available: can't look for AppImages updates

### ISSUE THREAD

**Issue by painkiller1717** [TheAssassin/AppImageLauncher#581]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

I downloaded the app 3 times, but always I uninstalled because the main feature of this, to update the AppImages, isn't available with an red ❌ next of it.

### Expected behavior

The updater should be available to can update the AppImages downloaded I have.

### Steps to reproduce the issue

1. Open AppImageLauncher
2. In the first tab, on available features, there is a ❌ with the message _updater not available._
3. Can't update my AppImages with this.

### Screenshots

![Selección_036](https://github.com/TheAssassin/AppImageLauncher/assets/77559296/2dfb7644-2e75-48bc-b372-987546cb7b57)

### Distribution and desktop environment

Linux Mint 21.1 Cinnamon

### Installed AppImageLauncher version

**AppImageLauncher 202211022349-stable-0f91801~ubuntu22.04.1** _(downloaded by terminal adding the repository previously)_

**Comment by TheAssassin** [comment]
Seems to be a PPA build. Updater is not (yet) available there. Works as expected.

If you need th eupdater, try installing the latest continuous release `.deb` from https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous. I'd love to get feedback on it.
