### ISSUE TITLE
Not Installing on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by SOG-web** [TheAssassin/AppImageLauncher#583]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

sudo apt-get install -f ./appimagelauncher_2.2.0-travis995.0f91801.bionic_arm64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'appimagelauncher:arm64' instead of './appimagelauncher_2.2.0-travis995.0f91801.bionic_arm64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 appimagelauncher:arm64 : Depends: libc6:arm64 (>= 2.27) but it is not installable
                          Depends: libcairo2:arm64 (>= 1.2.4) but it is not installable
                          Depends: libcurl4:arm64 (>= 7.16.2) but it is not installable
                          Depends: libgcc1:arm64 (>= 1:3.0) but it is not installable
                          Depends: libglib2.0-0:arm64 (>= 2.39.4) but it is not installable
                          Depends: libqt5core5a:arm64 (>= 5.7.0) but it is not installable
                          Depends: libqt5dbus5:arm64 (>= 5.0.2) but it is not installable
                          Depends: libqt5gui5:arm64 (>= 5.7.0) but it is not installable
                          Depends: libqt5widgets5:arm64 (>= 5.2.0~alpha1) but it is not installable
                          Depends: librsvg2-2:arm64 (>= 2.14.4) but it is not installable
                          Depends: libstdc++6:arm64 (>= 6) but it is not installable
                          Depends: zlib1g:arm64 (>= 1:1.1.4) but it is not installable
E: Unable to correct problems, you have held broken packages.
sogtheimmortal@sogtheimmortal:~/Downloads$ 

### Expected behavior

to be installed

### Steps to reproduce the issue

download the latest release and try to install

### Distribution and desktop environment

Ubuntu 22.04.2 LTS

### Installed AppImageLauncher version

appimagelauncher_2.2.0-travis995.0f91801.bionic_arm64.deb

**Comment by Jayy001** [comment]
Hi, this is most likely because you're trying to use an Ubuntu Bionic (18.0.4) based release on an Ubuntu Jammy (22.04) version. I'd recommend using the appimage release, or they also offer a PPA, which you can install from (and should be up to date).

https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian

**Comment by TheAssassin** [comment]
Try the latest [continuous release](https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous).

**Comment by Lythenas** [comment]
FYI for me on Ubuntu 22.04 the package appimagelauncher_2.2.0-travis995.0f91801.bionic_amd64.deb worked fine.

Maybe the issue of the was that he tried to install the arm64 package on an x86 system. It should be amd64 not arm64.

**Comment by TheAssassin** [comment]
Likely. Closing.
