### ISSUE TITLE
Provide "stable" names for artifacts

### ISSUE THREAD

**Issue by serpro69** [TheAssassin/AppImageLauncher#588]
### Pre-submit checks

- [X] I checked for similar issues beforehand, but could not find any. I could not add my proposal to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Feature description

Release artifacts contain some additional information in their names (travis build number or ?) , which makes it very hard to work with programmatically. 

If I want to download an artifact in some automated way, I'd need to be able to determine the artifact name . Currently I can get the latest release tag from github , but there's no way for me to get the build number that was used to produce the artifact.

### Proposed solution

Instead of:
appimagelauncher-lite-2.2.0-travis995-0f91801-i386.AppImage
appimagelauncher-lite-2.2.0-travis995-0f91801-x86_64.AppImage 

only use the version and platform identifiers in the artifact names, e.g.:
appimagelauncher-lite-2.2.0-i386.AppImage
appimagelauncher-lite-2.2.0-x86_64.AppImage

**Comment by TheAssassin** [comment]
If your tool can't handle semantic versioning, I'd consider that a bug on your end. `travis<num>-<git hash>` is part of the build metadata, but doesn't have any effect on the version number. I don't see any convincing argument in your issue.

**Comment by serpro69** [comment]
Hi,

I think you misunderstood me :) I don't have any problem getting the version , what I'm having problems with is `travis<num>-<git hash>`. How would one get build metadata for the latest release, for example?

The artifact with the name pattern like `appimagelauncher-lite-<version>-travis<num>-<git>-x86_64.AppImage` is impossible to determine w/o having metadata of a build which was used to produce the said artifact.
At the same time `appimagelauncher-lite-<version>-x86_64.AppImage` would be very easy to figure out by just getting latest tag from git, or by parsing `latest` version output from github.

Also I'm not really sure what benefits having `travis<num>-<git hash>` in the final artifact name gives you in the first place.

**Comment by TheAssassin** [comment]
It's relatively simple for you to parse anyway. And the build metadata _is_ needed, for instance in issues or when rebuilding tags due to problems.

I'm not sure what you want to do. All you write is "handle programmatically", which lacks any details on your use case.

You can list the available downloads for a specific release using the (public) GitHub API. You can easily filter for the binary you need.
