### ISSUE TITLE
3 days of failures... Trying to get this working on a chromebook... Why so hard?

### ISSUE THREAD

**Issue by Higherselfhiphop** [TheAssassin/AppImageLauncher#589]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Tried all packages and repositories... yet ALL errors.... Whats up with that?

### Expected behavior

Need a Deb file that just works... or a repo that can be added...

### Distribution and desktop environment

Debian on Chromebook

### Installed AppImageLauncher version

Tried all packages and methods...

**Comment by TheAssassin** [comment]
There is no information in this issue, just vague complaints. Closing for now. Feel free to open a *detailed* issue that describes your problem.
