### ISSUE TITLE
Question: Has a conflict with appimage launcher, the instalation script of appimages 

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#61]
Hi, I have several appimages integrates with appimagelauncher, but many of them have not a menu icon, I mean the icon is missing. Talking about synfig studio and whiteboard, they have a script to instalation. Curiously appimagelauncher integrate the appimages but when I run the app from menu the script runs asking me if iI want to install etc etc. I noticed that appimaged, integrates appimages and recognizes icon menu, but some others appimages as CPOD not, but appimagelauncher does. 
![2-appimalauncher](https://user-images.githubusercontent.com/29207169/43271676-61e37646-90b5-11e8-8494-bb10880df32e.png)

**Comment by TheAssassin** [comment]
@Lvaskz AppImageLauncher cannot "deactivate" any proprietary "install" system thingies. It already suppresses the [old desktopintegration dialog](https://github.com/AppImage/AppImageKit/blob/master/desktopintegration). This works by setting `$DESKTOPINTEGRATION` in the environment (in our case, it will contain `AppImageLauncher`, but if a payload application wants to make use of this feature, it should not show its own integration dialog. Also, if someone really wants to provide a "standalone" integration feature (and this is really not recommended any more by us, as we try to get our solutions into the distributions or actually want the distros/DEs to provide their own tools), they should make sure it's compatible with what libappimage does.

If the AppImages have been packed properly, AppImageLauncher can install the icons inside, and provide proper desktop integration. If that is not the case, you will have to ask the authors of these AppImages to add the icons to `usr/share/icons/hicolor/<res>/apps/<icon>`, where they're found by the libappimage desktop integration.

Also, you could ask the authors of those AppImages to remove their own desktop integration solution, and switch to AppImageLauncher resp. one of the alternatives described in https://docs.appimage.org/user-guide/run-appimage.html#integrating-appimages-into-the-desktop.

Regarding missing/wrong icons in launchers: AppImageLauncher updates icon caches on integration to make launchers show the new icons. If an AppImage has been bundled properly, but the icons aren't shown (or are shown wrong), we need to improve https://github.com/TheAssassin/AppImageLauncher/blob/master/src/shared.cpp#L154.

Regarding the detection of AppImages: AppImageLauncher and appimaged use different techniques to "detect" AppImages. Perhaps that explains why AppImageLauncher is more reliable.

**Comment by TheAssassin** [comment]
@Lvaskz well, the question which case applies to you?

Is it that icons are missing? Then there's probably no/broken/wrong icons in `~/.local/share/icons` (resp. `<AppDir>/usr/share/icons` in the AppImage).

Is the problem that only low-res icons are shown in your launcher, and you use e.g., 4K monitors? The behavior in this case is DE dependent. KDE for instance tends to show small icons in their original size, and doesn't perform upscaling. Anyway, if that's the case, the only good way to solve this is to have the author either bundle vector graphics (`.svg`), or add more pixel graphics in higher resolutions.

In either case, you can find out easily by mounting/extracting the AppImage. Please see https://docs.appimage.org/user-guide/run-appimages.html#mount-or-extract-appimages for more information.

https://github.com/TheAssassin/linuxdeploy is going to receive some kind of "AppDir validation", which is supposed to show warnings if icons are too small for proper high-resolution support, etc. Maybe that'll help preventing such situations in the future.

**Comment by Lvaskz** [comment]
#62 I think?

**Comment by TheAssassin** [comment]
#62 has been resolved, the binaries will be available soon. I just tested it with the pencil2d AppImage, works fine.

**Comment by Lvaskz** [comment]
Thanks. Can you tell me when can I download the binaries? 
thanks again !!!

**Comment by TheAssassin** [comment]
Closing as resolved.
