### ISSUE TITLE
Signing key for Kinetic PPA not available.

### ISSUE THREAD

**Issue by CamaradaPrestes** [TheAssassin/AppImageLauncher#613]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Just set the Kinetic PPA in my repositories, but it couldn't find the signing key, said it's not public.

### Expected behavior

The PPA should work.

### Steps to reproduce the issue

1. create a file manually: "/etc/apt/sources.list.d/appimagelauncher.list"
2. `sudo apt update`
3. it can't find the signing key.

### Distribution and desktop environment

Xubuntu Mantic.

### Installed AppImageLauncher version

Kinetic.

**Comment by TheAssassin** [comment]
Kinetic is 22.10 which has gone EOL months ago. Of course it's not provided any more.
