### ISSUE TITLE
lies

### ISSUE THREAD

**Issue by RoanBrand** [TheAssassin/AppImageLauncher#616]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

roan@roan-amd:~$ sudo add-apt-repository ppa:appimagelauncher-team/stable
PPA publishes dbgsym, you may need to include 'main/debug' component
Repository: 'Types: deb
URIs: https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu/
Suites: mantic
Components: main
'
Description:
Latest stable version of AppImageLauncher for all Ubuntu flavours.

AppImageLaucher is a helper program that makes it easier to organise and update AppImages on Linux. Learn more at https://github.com/TheAssassin/AppImageLauncher.

Note: PPA packages do *not* support updating.
More info: https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Found existing deb entry in /etc/apt/sources.list.d/appimagelauncher-team-ubuntu-stable-mantic.sources
Hit:1 https://repo.steampowered.com/steam stable InRelease
Hit:2 https://brave-browser-apt-release.s3.brave.com stable InRelease
Hit:3 https://dl.winehq.org/wine-builds/ubuntu mantic InRelease
Hit:4 http://za.archive.ubuntu.com/ubuntu mantic InRelease                                                                                                            
Hit:5 http://za.archive.ubuntu.com/ubuntu mantic-updates InRelease                                                                     
Hit:6 http://za.archive.ubuntu.com/ubuntu mantic-backports InRelease                                   
Hit:7 http://security.ubuntu.com/ubuntu mantic-security InRelease                                      
Ign:8 https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu mantic InRelease
Err:9 https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu mantic Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu mantic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Expected behavior

to work

### Distribution and desktop environment

ubunut 23

### Installed AppImageLauncher version

latest

### Additional context

![image](https://github.com/TheAssassin/AppImageLauncher/assets/14920090/81fef777-bcbb-4f35-bd4f-91b7b1b79028)

**Comment by TheAssassin** [comment]
Please refrain from ever opening any issues on GitHub or elsewhere ever again.
