### ISSUE TITLE
Problem to detect icons  for some appimages with appimagelauncher

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#62]
Hello, I opened an issue for pencil2d.appimage because the icon does not appear in the applications menu. I told them that I use APPIMAGELAUNCHER, to integrate the appimages and they told me that appimagelauncher generated the error, so the icon is not observed properly. Here is the link to read the answer: https://github.com/pencil2d/pencil/issues/1027#issuecomment-408188729

I leave part of the conversation:

**Comment by Lvaskz** [comment]
Hello, thanks for your efforts for this application, it is very useful for me, but unfortunately I do not know why the improvements you make do not apply to me. That is frustrating!!!. I did what you recommended, I made a virtual machine with linuxmint 18.3 and I used the last binary of appimagelauncher and ran pencil2d, and It gave me the same error, the icon does not appear in the list of applications. I used a live usb of linuxmint 18.3 and the result was the same. I use Ubuntu 18.04, with gnome 3.28, 64 bits. With respect to the DE, I have no idea what that is? Show me.
 I'm about to record a video tonight (Central American time) and send it to you to see if that helps. Thanks again for your effort.

**Comment by TheAssassin** [comment]
Well, the icon part _should_ be resolved, at least. This is really strange. I will have a look again tonight.

**Comment by Lvaskz** [comment]
I have seen several of those in my system. The problem is that I can give you this information until later, it is that I am with the work computer, not on my personal computer.

**Comment by TheAssassin** [comment]
Fixed it. I hope the problem is fixed now.

Note for myself: Actually _look_ into the installed desktop files next time.

**Comment by Lvaskz** [comment]
Thanks for this. I will download right now. I will try in the night thanks

**Comment by Lvaskz** [comment]
Hi, now it works thanks
