### ISSUE TITLE
64-bit time_t transistion for the .deb package (noble series and up)

### ISSUE THREAD

**Issue by erkinalp** [TheAssassin/AppImageLauncher#634]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Cannot be installed due to dependency mismatch

### Expected behavior

Can install and run app images normally

### Steps to reproduce the issue

install the debian package

### Distribution and desktop environment

ubuntu 24.04

### Installed AppImageLauncher version

202211022348-stable-0f91801~ubuntu22.10.1

### List of AppImages you tried

happens during installation of appimagelauncher itself

**Comment by erkinalp** [comment]
This also means the daily build [at there](https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/daily?field.series_filter=noble) cannot be installed.

**Comment by TheAssassin** [comment]
Your issue lacks information. How does a build error cause trouble with the installlation of the PPA package? And why are you using an incompatible package with 24.04? Also, have you tried the upstream `.deb` as explained in #641?

**Comment by erkinalp** [comment]
solved in the release version of 24.04, was broken during betas
