### ISSUE TITLE
AppImageLauncher breaks non-AppImage

### ISSUE THREAD

**Issue by JulianGro** [TheAssassin/AppImageLauncher#637]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Opening a .run file while AppImageLauncher is installed, opens the integration prompt and ultimately fails.

### Expected behavior

AppImageLauncher should not intervene with non-AppImages

### Steps to reproduce the issue

Try running this on a system with AppImageLauncher installed: 
[newshosting_x64_installer.run.zip](https://github.com/TheAssassin/AppImageLauncher/files/15041176/newshosting_x64_installer.run.zip) (I cannot vouch for the safety of this, as it is a proprietary application.)

### Distribution and desktop environment

Debian Testing with Cinnamon

### Installed AppImageLauncher version

AppImageLauncher version 2.2.0 (git commit 0f91801), built on 2020-09-29 21:36:15 UTC

**Comment by TheAssassin** [comment]
What makes you think that `.run` thing is _not_ an AppImage? It is! It is that company that needs to "hide" that if they want to. But AppImageLauncher is entirely right there.
