### ISSUE TITLE
Install des AppImageLauncher fehlgeschlagen, Site nicht gefunden "404 Not Found" bei sudo apt update

### ISSUE THREAD

**Issue by Pitti60** [TheAssassin/AppImageLauncher#638]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Gemäß Wiki https://github.com/TheAssassin/AppImageLauncher/wiki habe ich die Installation des AppImageLauncher durchgeführt. Für Ubuntu, meine verwendete Distribution, bin ich der Empfehlung gefolgt und auf die Seite https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian verzweigt.

Dort habe ich die Anweisungen
sudo apt install software-properties-common
sudo add-apt-repository ppa:appimagelauncher-team/stable
sudo apt update
sudo apt install appimagelauncher

vorgenommen. 
Bei der Ausführung der Anweisung 
sudo add-apt-repository ppa:appimagelauncher-team/stable
erhalte ich den Fehler 
ehl:15 https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu mantic Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]

Bei der Anweisung 
sudo apt update
den Fehler 
Fehl:11 https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu mantic Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]
Terminal-Meldung: E: Das Depot »https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu mantic Release« enthält keine Release-Datei.

### Expected behavior

Meine Erwartung wäre gewesen das die Installation des AppImageLauncher fehlerfrei stattgefunden hätte.

### Distribution and desktop environment

      Systemsignatur
    • Betriebssystem: Ubuntu 23.10
    • Gnome-Version: 45.2
    • Fenstermanager Wayland
    • Linux Kernelversion: Linux 6.5.0-27-generic
    • Hardware: HP HP EliteDesk 800 G3 DM 65W
    • Processor: Intel® Core™ i7-7700 × 8 (64 Bit)
    • Speicher: 32,0 GiB
    • Grafikkarte: Intel® HD Graphics 630 (KBL GT2)

### Installed AppImageLauncher version

Den AppImageLauncher möchte ich in der neuesten Version installieren.

**Comment by TheAssassin** [comment]
Issues in languages other than German are not supported. Also, this is the X-th duplicate of the ever same issue.
