### ISSUE TITLE
Failing to install on arch Linux

### ISSUE THREAD

**Issue by starsprinter92** [TheAssassin/AppImageLauncher#644]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

It exits with status 4 
![image](https://github.com/TheAssassin/AppImageLauncher/assets/97267759/795382cd-278c-4ee3-a746-91b40949f941)

### Expected behavior

It should install

### Steps to reproduce the issue

Install on arch Linux

### Distribution and desktop environment

EndeavourOS
Hyprland

### Installed AppImageLauncher version

Git

**Comment by Anaphylaxis** [comment]
I built it from the AUR fine using the appimagelauncher package so this may be fixed
