### ISSUE TITLE
Stopped working on Fedora 40

### ISSUE THREAD

**Issue by ad-on-is** [TheAssassin/AppImageLauncher#647]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

None of the installed apps open anymore, neither does AppImageLauncher

### Expected behavior

Apps should open again

### Steps to reproduce the issue

Trying to execute an app manually, by copying the exec-command into the terminal, yields to errors:

`$: AppImageLauncher`  or
`$: /home/user/Applications/Insomnium.Core-0.2.3-a_d2d6d4d6efb84980c0a519dfadfae4cd.AppImage` 

```
AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

zsh: IOT instruction (core dumped)  AppImageLauncher
```
https://stackoverflow.com/a/74888186 suggests the following

QT_QPA_PLATFORM="xcb" ./Insomnium.Core-0.2.3-a_d2d6d4d6efb84980c0a519dfadfae4cd.AppImage and this works.

### Distribution and desktop environment

Fedora 40
awesomewm

### Installed AppImageLauncher version

2.2.0-gha111~d9d4c73, but also stopped working for 2.2.0 from stable release

**Comment by Ice4375** [comment]
Same Problem

**Comment by ad-on-is** [comment]
I updated my system and restarted, now it works again.
