### ISSUE TITLE
AppImageLauncher broke ArduinoIDE and all other AppImages, how to un-integrate and wipe cleanly?

### ISSUE THREAD

**Issue by schnittchen** [TheAssassin/AppImageLauncher#654]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

I first installed the lite version, but 80% of the time ArduinoIDE would not launch, but I could still launch it from the console without problem.

I then uninstalled the lite version and installed the rpm. Same problem.

So I decided to `ail-cli unintegrate path_to_appimage` and uninstall AppImageLauncher. The result is that I cannot launch ArduinoIDE at all, even though it's the exact same download that worked before I touched AppImageLauncher.

Here is what I get:
```
 ~/Appimage ✓ ./arduino-ide_2.3.2_Linux_64bit.AppImage --no-sandbox
bash: ./arduino-ide_2.3.2_Linux_64bit.AppImage: cannot execute: required file not found
```

In fact, when downloading a different Appimage and chmoding it, I get the same error.

### Expected behavior

I expect somebody to help me remove all traces of AppImageLauncher and be able to use AppImages again.

### Distribution and desktop environment

Fedora 40

### Installed AppImageLauncher version

Not applicable, uninstalled

**Comment by TheAssassin** [comment]
That's a mixture of a bug report (that lacks a lot of details) and a request for assistance. I suggest that you start a discussion instead.

**Comment by IriaSomobu** [comment]
Same problem, but on archlinux.

1. `yay -S appimagelauncher` to install AppimageLauncher
2. ` ./Lagrange-1.3.1.AppImage` to launch Lagrange -- works fine
3. `yay -R appimagelauncher` to remove AppimageLauncher
4. ` ./Lagrange-1.3.1.AppImage` to launch it again -- breaks with:
5. `bash: ./Lagrange-1.3.1.AppImage: cannot execute: required file not found`

**Comment by IriaSomobu** [comment]
Reboot solves the problem. Dunno what it was

**Comment by TheAssassin** [comment]
The uninstall scripts suggest you to reboot because some distros don't handle the un-registration of the binfmt_misc integration properly.

Please beware that I cannot support third-party packaging like AUR.

Also, I assume that both of you should have used the latest 3.0.0-alpha-4 release and it would have fixed all your issues.
