### ISSUE TITLE
Add Esperanto language

### ISSUE THREAD

**Issue by je-sendra** [TheAssassin/AppImageLauncher#668]
### Pre-submit checks

- [X] I checked for similar issues beforehand, but could not find any. I could not add my proposal to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Feature description

Language support for Esperanto could be added. Since translations come from Weblate, there is not a lot of work that needs to be done before the language can start being supported.

Esperanto is adopted in some niche communities, including FOSS ones.

### Proposed solution

Add Esperanto support.

**Comment by TheAssassin** [comment]
Feel free to contribute Esperanto on Weblate. The translations will be pulled in on new releases. If there is anything for me to do, please reopen the issue.
