### ISSUE TITLE
Please support PPA for Ubuntu 24.10 (Oracular Oriole)

### ISSUE THREAD

**Issue by chrishart0** [TheAssassin/AppImageLauncher#669]
### Pre-submit checks

- [X] I checked for similar issues beforehand, but could not find any. I could not add my proposal to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Feature description

I would like to be able to use apt to install AppImageLauncher form your PPA so I can get updates. 

### Proposed solution

Adding PPA support for Ubuntu 24.10 (Oracular Oriole).

## Method 1

I tried to "trick" apt into downloading the AppImageLaucnher version for the closest version available, focal by editing `/etc/apt/sources.list.d/appimagelauncher-team-ubuntu-stable-oracular.sources` and replacing `Suites: Oracular` with `Suites: focal`

This did let me run `sudo apt update` successfully.  Now `sudo apt install appimagelauncher` returns:
```
$ sudo apt install appimagelauncher
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 appimagelauncher : Depends: libappimage0 (>= 0.1.6) but it is not installable
Error: Unable to correct problems, you have held broken packages.
```

Ubuntu 24.10 does not have `libappimage0` available:
```
 apt search libappimage
libappimage-dev/oracular 1.0.4-5-4ubuntu1 amd64
  Development files for libappimage

libappimage1.0abi1t64/oracular,now 1.0.4-5-4ubuntu1 amd64 [installed]
  Core library for appimage
```

## Method 2

Install the .deb by hand, but now I won't get updates. I do want to get security and feature patches.

**Comment by chrishart0** [comment]
If there is anything I can do to help just let me know. I can confirm that the .deb works just fine with my install of Ubuntu 24.10.

**Comment by TheAssassin** [comment]
Please stop opening these duplicate issues. I'm not interested in maintaining a PPA. It's way too much effort. I hardly find time to fix actual bugs.

**Comment by Snowflake6** [comment]
@TheAssassin Maybe it would make sense to udpate the Wiki to remove the direction to use the PPA's when they currently do not work.

**Comment by ricperry** [comment]
Someone needs to fork this since TheAssassin doesn't seem interested. Can't even be bothered to update outdated documentation that actively directs people to follow broken procedures. Yes, I'm salty on this issue because it's been a long time thing.

**Comment by Snowflake6** [comment]
> Someone needs to fork this since TheAssassin doesn't seem interested. Can't even be bothered to update outdated documentation that actively directs people to follow broken procedures. Yes, I'm salty on this issue because it's been a long time thing.

Maybe fork the documentation, update it, and submit a pull request?  GitHub is intended to be collaborative.
