### ISSUE TITLE
Please integrate with Nemo (Linux Mint)

### ISSUE THREAD

**Issue by salvadhor** [TheAssassin/AppImageLauncher#67]
Hi,

In Linux Mint and its file manager Nemo there's no integration with AppImageLauncher. I can use this app, however there's nothing in context menu after right click on *.appimage. No update, no remove.

**Comment by TheAssassin** [comment]
The entries are not available from the file manager, but in the launcher only.

**Comment by TheAssassin** [comment]
Closing as resolved. Please open new issues if you want to request new features.
