### ISSUE TITLE
Support for ubuntu 24.04 Noble Numbat

### ISSUE THREAD

**Issue by mateMathieu** [TheAssassin/AppImageLauncher#671]
### Feature description

Hi, after 6 months of release, I decided to install the updated version of ubuntu.
Can you please add a new branch to the PPA, and make it happen for the lastest version?
It ships with KDE Neon and many other u-based distributions.
The dependencies are preventing to install 22.04 version.

Thanks for considering

### Proposed solution
- update dependencies
- new PPA branch

**Comment by TheAssassin** [comment]
Stop opening duplicates please.
