### ISSUE TITLE
Make AppImageLauncher work over SSH

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#68]
When trying to use CLI AppImages over an SSH connection to a computer which has AppImageLauncher installed, AppImageLauncher will refuse to work as it cannot spawn its UI.

To fix this issue, we have to move the creation of the `QApplication` to a point right before the UI is supposed to be shown.

**Comment by azubieta** [comment]
This will be fixed at https://github.com/TheAssassin/AppImageLauncher/commit/7b213c70903e5a57313e7d14b0e58e4dc69afeb2
If the "DISPLAY" or "WAYLAND_DISPLAY" variables are set a QApplication will be created otherwise a QCoreApplication will be created.

**Comment by TheAssassin** [comment]
Side note: this could've been worked around by simply using `ssh -X`, which forwards X stuff from the target system to the current host.
