### ISSUE TITLE
Ask user to confirm desktop integration before overwriting files in integration directory

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#7]
The current behavior is to simply overwrite the existing file. There is no check whether the AppImages are bit wise the same, only the filenames are compared. We need a better solution for this.

**Comment by TheAssassin** [comment]
In #8, an algorithm has been implemented to prevent duplicate entries in desktop environments' launchers. In order to improve the user experience further, we could ask the user whether to "replace" (well, remove and put in the new file) the colliding AppImage with the newly integrated one. This extends the idea of checking for filename collisions to checking the actual desktop files, and could help avoiding adding the same version twice to the menu (especially with the new versioning support for AppImages).

Of course, the user needs to confirm such an action, there are for sure valid use cases in which a user would want to have the same app twice in their launcher (for example, if the version number is the same, or there's no version number so only a number could be appended, etc., or two files are falsely claimed to be the same app by our algorithm, which is of course prone to false positives).

In cases the user wants to keep both versions, the filename should be edited in order to avoid collisions in the target integration directory. I would suggest to add the version number if it's lacking, and, if the "collision resolving strategy" is "append monotonically increasing number in brackets", add that number (in brackets, of course) to the filename.

This further allows a user to directly draw a relation between the entry in their launcher, and the actual file on-disk. Right now, the filename is left untouched, but the name of the app in the launcher might be edited. This drastically improves the user experience for removing an AppImage from disk without using the provided desktop action (which isn't available on some platforms, e.g., XFCE).

**Comment by TheAssassin** [comment]
The solution is something I'd call "content aware filename". I'm going to generate a checksum (probably an MD5 hash, like AppImage uses elsewhere), and append it to the integrated AppImage's filename.This allows for comparing new AppImages with already integrated ones, and this finally allows to check whether an AppImage has been integrated in a reliable way.

There are some performance questions left, especially for large AppImages on low end devices.

There's a discussion in AppImageUpdate whether to add some "unique identifier" when generating the AppImage. This value could perhaps be reused if available, to avoid having to hash an AppImage every time AppImageLauncher is called. This value should be content-aware as well, but since we can't simply calculate a hash and then embed it in the AppImage ELF header (that'd change the hash of the entire file, obviously), we thought about hashing the squashfs image only. We might miss changes in the header (e.g., updates of the update information), though.

For the beginning, we should check for filename collisions, and eventually hook into this discussion in AppImageUpdate/AppImageKit to add this use case. I believe we can figure out a solution for all these issues.

**Comment by TheAssassin** [comment]
CC @probonopd.

**Comment by probonopd** [comment]
I have _not_ read the whole thread but we should avoid asking users at all cost. At least in the appimaged implementation, a hash of the path to the file (according to what XDG specifies for thumbnail images) is used, so there cannot be any collissions and hence no "overwriting". Can you please describe in which circumstances you noticed collissions/overwriting?

**Comment by TheAssassin** [comment]
Well, you should probably read at least the initial post. This is not about appimaged, nor about libappimage. This is an AppImageLauncher issue.

The issue with overwriting always occurs when for example an AppImage has been downloaded a second time and is executed. You can't just overwrite the existing file. Furthermore, you shouldn't rely on the filename and assume the file is the same. I'd rather check whether something _really_ changed. If it's the same app (including all metadata, update information etc.), then overwriting is not an issue. However, if an app is released with the exactly same filename, but it's a newer version, you should ideally not "just" overwrite the old file.

For now, I'm implementing a rudimentary version checking only for filename collisions, and asking the user what to do.

However, the reason I highlighted you is that I was primarily trying to get feedback for these reproducible "unique identifiers" for AppImages, and whether they should be added.

**Comment by probonopd** [comment]
> This is not about appimaged, nor about libappimage. 

I know, this is why I wrote how we solved it _in appimaged_.

> Furthermore, you shouldn't rely on the filename and assume the file is the same. I'd rather check whether something really changed

_appimaged_ puts a _hash_ of the _full path to the AppImage_ into the filename of the files for desktop integration, and since two different files can never have the same path on a system, there  cannot be collissions.

**Comment by TheAssassin** [comment]
This whole post isn't quite describing the actual situation.

First of all, there's a functional difference between appimaged and AppImageLauncher. AppImageLauncher moves files into a central directory, appimaged doesn't. The fact that it moves the files leads to the question, "what to do if there's a file with the same filename in the target location".

I _know_ what that function does, and I even use it, indirectly via `appimage_register_in_system`. The function is called _after_ moving AppImages to the target location, in order to register them in the system. The reason there's a function provided in libappimage is obviously to allow all tools using libappimage (and appimaged is such a tool, too) to use the same methods and therefore be compatible. You could uninstall AppImageLauncher and use appimaged, and it'd continue to work.

The question is still not whether to move files or what to do about them to _integrate_ them. I already told you I need feedback regarding this "unique identifier" I proposed in this issue and also in AppImageUpdate. The question is, how can we add a "content-aware" identifier which can be embedded in the AppImage itself, is content-aware (i.e., doesn't break reproducibility, we can't just use a random value), and can be used to quickly compare two AppImages without having to hash them?

My first idea was to just hash the squashfs image and embed that hash in the header, but if an AppImage's header changes (e.g., when the update information is updated, or the runtime is updated, and the file is re-uploaded without creating a new release (replacing the old file), the squashfs image would be the same, and you'd miss these changes), so it's a suboptimal solution. Sure, if we'd like to play with probabilities, how likely is it that somebody will release an AppImage with changed update information _without_ also increasing some version number? But on the other hand, we shouldn't risk creating such a vector for future issues, which is also something not even we might think of while debugging it.

Therefore I ask you how we could create a reproducible identifier for an entire AppImage. What I want to avoid is having to hash both the existing and new AppImage, as that is merely a waste of time and CPU cycles, and delays the application startup. However, with old AppImages which don't embed such a "unique ID" that can be compared, the whole process needs to be reproducible, i.e., I need to be able to recompute the identifier at any time from a given AppImage (scenario: existing AppImage doesn't have one, new one does, I'd just calculate it for the old one, saving at least half of the processing time instead of having to hash both).

Maybe we need to hash the entire AppImage, but skip/replace the section in the header in which the hash would be embedded, similar to the signature section.

As said before, this algorithm would serve multiple purposes, and would be useful for AppImageUpdate, too. Please keep that in mind.

**Comment by TheAssassin** [comment]
Talking about signatures: When the file is signed, we could just (bitwise) compare the signatures of both files. The signature algorithm skips the signature section internally, and therefore, such a signature is exactly the kind of "unique identifier" for an AppImage that I am looking for. For AppImageLauncher, all constraints would be satisfied by this method.

However, it is rather uncommon to see signed AppImages already. Also, for AppImageUpdate, this is not a suitable method to check for updates. As the value would have to be embedded in the `.zsync` files that get uploaded to servers, it'd bloat these files by ~4kB, which is quite a lot more than a simple MD5 checksum. Also, it'd have to be encoded, as newlines aren't allowed in the `.zsync` header. Therefore, we should think about hashing the entire AppImage (skipping the hash section in the header), and using that hash for such purposes.

**Comment by probonopd** [comment]
> The fact that it moves the files leads to the question, "what to do if there's a file with the same filename in the target location".

Ah ok, I forgot. Well, I don't like this in the first place. If the user wants to move something somewhere, then he can do that using the file manager. After all, that is what it is for...

**Comment by TheAssassin** [comment]
Again, this is ***NOT*** a discussion about the basic AppImageLauncher workflow. And it's not going to be changed. The users and I like it, it's a lot cleaner than leaving everything scattered around the system. And you can just hit `Run once` if you don't want this to happen at all.

Anyway, if you don't want to talk about the other aspect, well, I can't make you to.

**Comment by probonopd** [comment]
> how we could create a reproducible identifier for an entire AppImage

I think you already described most of the options. If you look at how the signature mechanism works, actually it does not sign the AppImage but a _digest_ of it. Maybe we could use that _digest_ as the identifier you are looking for?

**Comment by TheAssassin** [comment]
You're absolutely right, we already _have_ an algorithm implemented to calculate such an identifier. We just need to embed it.

**Comment by TheAssassin** [comment]
We just calculate the hash that is used for signatures, but we _always_ do that. Then, we embed it in an extra section. We could alternatively just occupy the first x bytes of the existing signature section, however that'd prevent users of older libappimage versions to verify signatures, as they'd get confused with this preamble. Therefore, adding a small extra section would be a better idea.

I don't think that'd add much complexity, honestly. There's much more complexity elsewhere, this doesn't overcomplicate anything. On the other hand, it highly improves update checks, and we don't break with old libappimage versions.

By the way, I found the AppImageUpdate I was referring to: https://github.com/AppImage/AppImageUpdate/issues/83.

**Comment by TheAssassin** [comment]
CC @pamarcos @azubieta

**Comment by probonopd** [comment]
> We could alternatively just occupy the first x bytes of the existing signature section

If we use the _last_ x bytes of the existing signature section, it might even work without the downsides you described.

**Comment by TheAssassin** [comment]
To be tested, I guess. But I'd prefer to do it "properly" and add a separate section.

**Comment by probonopd** [comment]
As far as I remember I left plenty of space in the section, more than needed for the signature. But please double check.

**Comment by TheAssassin** [comment]
With 4096 bytes large keys, it's pretty much all occupied.

The extra section is of course optional. We, the reference implementation, can add such features. I don't see where the problem is...

**Comment by probonopd** [comment]
Complexity. Imagine someone who, for some reason, needs to re-implement the spec. Are 4096 bytes large keys common?

**Comment by TheAssassin** [comment]
Still, how does adding a header field to our runtime add any kind of complexity? Actually, this is a lot better than having to fiddle with multiple values in the same field. The level of abstraction makes it a really nice alternative. And it doesn't break anything nor does it bloat the header too much. We're talking about what, 128 bit? That's nothing, really. And reading a separate section is _way_ less complex, code wise.

**Comment by pamarcos** [comment]
There's a lot said here. I read it all, but please forgive if I miss something. Here's my two cents:

Basically, you're proposing embedding a checksum of the AppImage within it but skipping both the signature and the place where we store the checksum itself, correct? If that's the case, I'm all for it. I actually thought this was the solution from the beginning. It's like "what we did with the signature, but with the checksum", but I read a while ago you discarded this option for some reason.

If it's up to me, I'd add that checksum in a new ELF section right after the signature section, for sanity. Then, we just skip both sections when calculating the hash. For the signature, we only need to skip the signature section itself. Still, I do understand @probonopd's point of view trying to keep backwards compatibility. I'm not sure of everyone else was jumping the "signature" section. Is it reading how long it is or just blindly jumping a hard-coded size. If it's the latter, we may just include a new section because we'd be breaking backwards compatibility with that implementation anyways. If it's the former, we should consider increasing the size of that section and embedding the checksum right **after** the signature.

**Comment by TheAssassin** [comment]
You can fetch the size and position of a section, and based on that, you can read the correct length.

We can't just embed the checksum right after the signature. What about cases when AppImages are not signed? Software relying on the fact that the section is empty if not signed will think "oh, cool, a signature", and then continue like "that signature is broken". I think even the spec says that the section must either be empty or contain a signature. If not, then we should state that clearly asap.

Adding a separate section is the way to go, IMO. But other than that, you got the whole idea 100% correctly.

**Comment by TheAssassin** [comment]
> I know, but I was wondering how people implemented that. In any case, it's true that if they hard-coded the length instead of reading an ELF section properly, it's their fault.

One of the reasons we provide libappimage for.

**Comment by TheAssassin** [comment]
JFYI working on this hash thingy at the moment.

**Comment by TheAssassin** [comment]
We have three options when implementing this feature:

1. skip both signature and digest sections in both the signature and digest calculation
1. skip signature and digest section when calculating the digest, but include digest into signature calculation
1. skip signature and digest section when calculating the signature, but include signature in digest calculation

I think we can safely go for option 1. @pamarcos please think about this for a few minutes, perhaps you come up with some issues. It's pretty simple to make changes after I implement this feature, but once we have it, we can't alter the algorithms any more safely, so we should make sure it'll work fine.

We should consider backwards compatibility, too. I just thought it might break backwards compatibility not to include the new digest section in the signature verification. If an old version of libappimage checks the signatures and doesn't skip the digest section, it can't know it needs to skip the digest section. So I think we need to go for the 2nd option...
