### ISSUE TITLE
Integrate AppImage XDG Thumbnailer

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#74]
Please integrate the AppImage XDG Thumbnailer similar to the one one in appimaged

**Comment by TheAssassin** [comment]
Already performed by libappimage by default. Should work already.

**Comment by probonopd** [comment]
KDE Plasma 5 seems not to use XDG thumbnails?

**Comment by azubieta** [comment]
No, they don't use them. Instead they have their own thumbnail system. Also there is an implementation of an AppImage thumbnailer already merged upstream.

**Comment by TheAssassin** [comment]
@azubieta do you recall what the reason was for them not to use it?

**Comment by azubieta** [comment]
Because they wanted to have more control over the thumbnail generation. In order to add decorations and stuff like that.

**Comment by probonopd** [comment]
Ah, I see. Thanks for the clarification.
