### ISSUE TITLE
Allow for more than one directory in which AppImages live

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#77]
Allow for more than one directory in which AppImages live. E.g., I keep many AppImages on `/isodevice/Applications` and would like `appimagelauncherd` to watch `$HOME/Downloads`.

**Comment by TheAssassin** [comment]
What do you expect to happen in these directories? We need to decide on a UX.

I assume you want appimagelauncherd to monitor the directories and perform desktop integration for files within these directories.
I further assume you want AppImageLauncher not to ask any more about desktop integration if files are in these directories (unless they're not integrated yet (e.g., when appimagelauncherd is not running), then AppImageLauncher will ask whether to integrate the AppImage).
In case AppImages are not integrated yet and are not in the integration directory, I woul like AppImageLauncher to ask about integration as currently.

I guess the easiest way to add this feature is to add a config file parameter which takes a list of directories to monitor additionally to the primary integration directory, e.g., colon separated.

**Comment by probonopd** [comment]
Yes, everything you assumed I agree with.

**Comment by TheAssassin** [comment]
Tracked in #154 from now on.

**Comment by probonopd** [comment]
Please reopen this one, since #154 is about monitoring the defined directories on all mountpoints. This one is about being able to specify more than one directory, e.g., `$HOME/Applications` and `$HOME/bin` .
