### ISSUE TITLE
Allow disabling AppImageLauncher

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#78]
https://forum.manjaro.org/t/how-to-disable-appimage-desktop-integration/56018/5

**Comment by TheAssassin** [comment]
Define "disable dialog boxes". Disable AppImageLauncher completely? Rememer decision for single AppImage? What exactly do you propose?

**Comment by probonopd** [comment]
That user writes:

> Hello, I just moved from Kubuntu to Manjaro KDE Edition, and there is one little issue that I’m facing. Whenever I try to run an AppImage, I receive the Desktop Integration dialog box which gives me only two options; Integrate and run or Run Once. Back when I was using Kubuntu there was an option to remember your preference of __not integrating AppImages and never bothering you with a dialog box ever again__.
>
> I just changed enable_daemon from true to false, but this doesn’t seem to have any effect, as __I’m still getting those desktop integration dialog boxes whenever I try to run an AppImage__.

Sounds to me like this user _never wants to see any dialog box_, and doesn't want desktop integration at all.

**Comment by TheAssassin** [comment]
Two options: Uninstall AppImageLauncher (already possible), or deactivate AppImageLauncher per-user (e.g., `disable = true` in `appimagelauncher.cfg`). The latter would have to be implemented by us.

I guess we really need to implement some AppImageLauncherControlPanel thingy.

**Comment by azubieta** [comment]
Which would be the behavior on AppImage files without execution permission?

**Comment by probonopd** [comment]
Ask the user whether it should be made executable. Ideally the file manager would do this for all ELF binaries since it is not AppImage specific.

**Comment by TheAssassin** [comment]
If AppImageLauncher is deactivated, it shouldn't modify the files. That's my opinion.

**Comment by probonopd** [comment]
Right. The file manager should. Has nothing to do with AppImage or AppImageLauncher.
E.g.,
https://gitlab.gnome.org/GNOME/nautilus/issues/443

**Comment by TheAssassin** [comment]
It's more of a UX decision. "Deactivating" IMO means completely disabling the functionality. Of course a user can't remove binfmt integration or alike, but we can just make AppImageLauncher a simple, transparent wrapper, without showing any dialogs.

**Comment by shoogle** [comment]
I ran into this just now when trying run some benchmarking tests of nightly builds. The UI pops up each time asking for integration, which means I can't run benchmarks with the `time` command unless I uninstall AppImageLauncher or integrate the application (which I don't want to do for lots of nightly builds).

It would be nice to be able to temporarily disable the integration dialog via an environment variable. Something along the lines of:

```bash

APPIMAGELAUNCHER_INTEGRATION=FALSE time MyApp.AppImage
```

**Comment by TheAssassin** [comment]
An easy and straightforward option. Will implement something like that later. Good suggestion, thanks!

**Comment by TheAssassin** [comment]
Added `APPIMAGELAUNCHER_DISABLE`. Just set it to something, and AppImageLauncher will "just run" any AppImage.

**Comment by TheAssassin** [comment]
Also there's a setting for that now in the config.

**Comment by B-Nerd** [comment]
where should i add the line APPIMAGELAUNCHER_DISABLE
