### ISSUE TITLE
Strategy for duplicate entries in launcher

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#8]
In some cases, there might be duplicate entries in launchers, which is annoying for the user, as it's impossible to differ between those, especially when they have the same icon as well.

This happens every time two desktop files have the same `Name=` entries. Situations in which this might be the case involve:

  - The user installed an app via traditional package management, and integrated an AppImage for the same application.
  - The user integrated multiple versions of an application.
  - Combinations of these examples.

This is especially annoying in cases where there's multiple AppImages for the same app involved. As the AppImages are all single files and technically independent from each other, you can't just "replace" the old version with the newer one. Also, due to the lack of easily available version information (there are so many versioning systems there is no good way in supporting them all, hence AppImage doesn't have any versioning support), one can't just display the version numbers in the launchers, to allow a user to differentiate between different versions.

There is no really good method to detect "collisions", as I'd call them. We need to compare the `Name=` keys of all existing desktop entries. Then, we can "resolve" these collisions.

Strategies to solve a collision:

  - Inform user that the entry has been created for an AppImage. We could append e.g., `[AppImage]` to such entries (full example: `Firefox [AppImage]`). This would solve collisions of AppImages and system apps. Also, it's a little more transparent to the user.
  - Allow AppImage creators to add a "version information" to their AppImages. They could add the version to the `Name` key already, sure, but that doesn't allow us to detect conflicts any more. We might want to ask users to "remove" old versions one day, and we can't detect collisions any more, as we'd need to support their versioning scheme in order to parse it out of the `Name=` entry, which could then be compared again. Therefore, we should offer them a custom key, e.g., `X-App-Version` which they can set that is then appended to the `Name=` entry on integration. When running a collision detection check, the value of that key can be removed from the patched `Name=` entry, and we have the original value again. We could even store the original `Name=` entry in such a key on integration.
  - File managers have had a solution for duplicate files for decades: simply append a monotonically increasing number to the `Name=` key on collisions. Of course, this is the worst of all these solutions, as it's less meaningful, but it provides a method to create unique `Name=` entries, which are easy to memorize for users, as this is a well known method for users which they know already from their file managers.

Parts of this issue need to be discussed in AppImageKit/libappimage upstream (e.g., appending `[AppImage]` to AppImages' entries is something that should be performed consistently across all AppImage tools, if we decide to implement it).

**Comment by TheAssassin** [comment]
CC @azubieta -- I'd appreciate feedback on the suggestions I make here.

**Comment by TheAssassin** [comment]
CC @probonopd -- you might have a few valuable comments as well.

**Comment by probonopd** [comment]
> We could append e.g., [AppImage] to such entries (full example: Firefox [AppImage]).

Please don't. We want to make AppImage feel "native" to the system, not this "alien thing". Grandma does not even need to know what an "AppImage" is.

> Allow AppImage creators to add a "version information" to their AppImages

Yes, this is long overdue.

Then we could have `appimaged` create `Name=$NAME $VERSION`.

**Comment by TheAssassin** [comment]
>> We could append e.g., [AppImage] to such entries (full example: Firefox [AppImage]).
> 
> Please don't. We want to make AppImage feel "native" to the system, not this "alien thing". Grandma does not even need to know what an "AppImage" is.

Well, I'd like to show a difference between a "system-wide installed app" and a "user only app". How about appending something like `[user app]`?

> Then we could have appimaged create Name=$NAME $VERSION.

As said before, this is something that'll go into the desktop integration code in libappimage, which is used by appimaged, AppImageLauncher, ...

**Comment by probonopd** [comment]
> How about appending something like [user app]?

This is a feature desktop managers imho would need to support (independently of AppImages or whatever), not something we should hack in using the application name displayed in menus. Let's not fall into the trap of making AppImage handling overly different from all other per-user and/or system-wide applications (apart from what is needed due to AppImage specifics).

> As said before, this is something that'll go into the desktop integration code in libappimage

Yes 👍

**Comment by TheAssassin** [comment]
@probonopd so what would you suggest to solve conflicts of AppImages and system wide installed

**Comment by TheAssassin** [comment]
This issue is the next one to work on with priority.

**Comment by azubieta** [comment]
From my point of view this is not an AppImage issue and we should NOT do anything about it.
The problem of having different versions of the same application installed is not new to Linux and if someone should address this, it should be the software authors or the users by removing one of the apps.
Take in cont that adding any kind of suffix to the AppImage desktop entry name like the ones you purpose it's extremely invasive and will affect the user experience.

**Comment by probonopd** [comment]
I kinda agree with @azubieta - it never has been a huge problem for me but I can see that people would want to keep around multiple versions of the same app and still not be confused in the menu. I think adding the version number to either the application name or the application comment in the desktop file might be a sensible solution.

**Comment by TheAssassin** [comment]
@azubieta of course it's an AppImage issue if AppImages in the menu can't be used by the user because they can't know which one to call.

Especially the lack of version information is annoying. If I need multiple versions, I can't have them integrated or I won't be able to use them? Come on, you don't see how urgent it is that we find a solution?

I would continue as suggested initially. If you don't like it, I will implement it in AppImageLauncher. But it is going to be implemented.

**Comment by probonopd** [comment]
Please do not suggest that this is AppImage specific. It's just that before AppImage, few users had installed multiple versions of the same application on their system. So to be precise, this is a [Linux Desktop Platform Issue](https://github.com/AppImage/AppImageKit/wiki/Desktop-Linux-Platform-Issues). Nothing to do with AppImage. We should ask KDE, GNOME, XFCE etc. to come up with a solution, preferably as an XDG standard.

Adding `Firefox [AppImage]` does not allow the user to distinguish between versions. Doing something AppImage-specific here just feels wrong and further adds to the perception that AppImage has issues, when in fact the Linux Desktop has issues.

**Comment by probonopd** [comment]
We should, imho:

1. Propose a proper(!) key that describes the application version to the [Desktop Entry Specification](https://standards.freedesktop.org/desktop-entry-spec/latest/) (though https://lists.freedesktop.org/mailman/listinfo/xdg?)
2. Ask desktop environments to use it

**Comment by TheAssassin** [comment]
@probonopd the `[AppImage]` part has been dropped comments ago. Please _read_ the thread. You guys seem to ignore the other two proposed suggestions...

**Comment by probonopd** [comment]
> Please read the thread.

OK, sorry, I was just a bit hectic when I read you were gonna "implement it anyhow" ;-)

**Comment by probonopd** [comment]
What I'd like to see is to append the version number to the Name= string, _if we know it_ (which we don't, most of the time, actually...)

Hence, I'm still pushing to do https://github.com/TheAssassin/AppImageLauncher/issues/8#issuecomment-379241124

**Comment by TheAssassin** [comment]
@probonopd nobody prevents you from sending them a mail.

**Comment by probonopd** [comment]
...besides my calendar ;-)

**Comment by TheAssassin** [comment]
The "append number in brackets" part has been implemented in 3faf17a. As @probonopd and @azubieta weren't convinced of the idea, I implemented it in AppImageLauncher, together with a collision detection algorithm which is used to calculate the number that needs to be appended. Works fine in my tests, but if you should detect bugs, please report them here as soon as possible.

The "append version number if set" part will follow next week in libappimage. I will then adapt the collision detection algorithm to support these changes.

**Comment by TheAssassin** [comment]
https://github.com/AppImage/AppImageKit/issues/672 has been merged, so that version handling is now available in libappimage.

I wrote the code so that no changes are necessary in AppImageLauncher, it should "just work". I will test this with some example AppImages, and will reopen the issue if I find bugs.

**Comment by probonopd** [comment]
How can we benefit from it in `appimaged`, too?

**Comment by TheAssassin** [comment]
@probonopd the version handling is done in the same functions appimaged uses. The only thing appimaged lacks is the algorithm to add the numbers in brackets, which has been implemented solely in AppImageLauncher.

**Comment by probonopd** [comment]
> appimaged lacks is the algorithm to add the numbers in brackets, which has been implemented solely in AppImageLauncher

Ah, I thought that was part of the library, too. What exactly is needed to make it work in `appimaged`, too?

**Comment by probonopd** [comment]
> @probonopd you did initially insist on not adding this algorithm to libappimage

Where did I say that? I said the right place to add this would be in the system, not in something related to AppImage. But since we are now working on a workaround (fixing what should be fixed for desktop Linux overall, not just for AppImages) we should at least do it consistently (everywhere).

**Comment by TheAssassin** [comment]
@probonopd I thought in some conversation (might as well have been a private one) I understood you as "I don't want this feature, I would only allow the `X-AppImage-Version` part, the other thing is not a problem for me". I might have taken you wrong there, and I also thought this should work consistently.

As long as you adhere to the Desktop Entry standard, you must actually show the `Name`s in the desktop files as-is. This is more of a problem of the standard, in my opinion. The distributions just implement it correctly. All they could do at the moment is allow adding a custom key (e.g., `X-GNOME-App-Version` or something similar), and "display" that value in the launcher, but I doubt this is going to happen, regarding the development of the desktop environments at the moment.

I will consider contributing the algorithm to libappimage. However, it is, right now, a nice, little piece of code that would suffer from having to be written in pure C, The lack of dynamic arrays, the memory management etc. would make this an annoying task. My job was to get this functionality into AppImageLauncher somehow.

If I were a mean person, I'd use this algorithm as a USP (= "unique selling proposition", marketing lingo) to push AppImageLauncher as a solution instead of appimaged...


<img src="https://user-images.githubusercontent.com/4503202/38646889-153d2dfa-3dea-11e8-8f3f-7bb606055710.png" align="center" height="350" >

**Comment by probonopd** [comment]
> The distributions just implement it correctly. All they could do at the moment is allow adding a custom key (e.g., X-GNOME-App-Version or something similar), and "display" that value in the launcher, but I doubt this is going to happen, regarding the development of the desktop environments at the moment.

The proper thing to do would be to propose to XDG a new key (e.g., `SoftwareVersion=`, as `Version=` is already taken). This should not be an `X-...` something key. It should become an official part of the standard, imho.

**Comment by TheAssassin** [comment]
@probonopd that is the obvious solution, I guess, but I doubt they'll release a new version of the standard in a reasonable amount of time, if at all. But even if they did, please imagine how long it'd take until this new standard propagated across the variety of distros and desktop environments. And once that has been solved, you'd need legacy support for older systems. This could easily take a decade until we'd be able to actually _introduce_ it in AppImageKit (we could not use a newer version of the standard until the oldest supported distro supports the standard, which happens to be CentOS ([regularly annoying](https://github.com/AppImage/AppImageKit/commit/ef1a238373be5caf2241a99b36b735e7265eef39#commitcomment-28509558)), and CentOS supports old releases [a decade long](https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule) at the moment. 

Working around this issue seems the way to go. We have no idea how the whole "desktop" concept is going to evolve in the next decade, and whether desktop files will play a role in it. I personally don't want to put up the efforts and discuss this upstream. I'd support such a proposal, though.

**Comment by TheAssassin** [comment]
@probonopd regarding support in libappimage, would you like to open an issue there to make sure it won't be forgotten?

**Comment by probonopd** [comment]
Well, if they made it an XDG standard in 6/2018, then it could already be supported in GNOME in 7/2018, and it could be then in Ubuntu 18.10. As for older distributions, they will never learn how to handle multiple versions of the same app (which is ok imho - there must be a reason to use new distributions...)

**Comment by probonopd** [comment]
Yes, unknown keys are silently ignored.

**Comment by TheAssassin** [comment]
Then it'd be viable to send a proposal. Help welcome.
