### ISSUE TITLE
AppImageLauncher control panel

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#80]
Since we started to allow for configuration of several aspects of AppImageLauncher in a configuration file, I started thinking about a control panel application that is shipped together with AppImageLauncher that wraps the config file into a UI.

By providing a UI for the purpose, we:
  - make it easier for users to configure AppImageLauncher, we could add help texts etc., which could even be translated
  - can restart services if their configuration changes

Additionally, we need to better document the configuration file, what single settings do, etc.

CC @azubieta

**Comment by azubieta** [comment]
We had one of those at the old appimage-desktop-integration. I can make the port if you want.

**Comment by TheAssassin** [comment]
Link?

**Comment by azubieta** [comment]
https://github.com/Nitrux/appimage-desktop-integration

**Comment by azubieta** [comment]
![Screenshot_20190527_165556](https://user-images.githubusercontent.com/1138094/58440558-6ccce200-80a0-11e9-8624-1289ec64d26c.png)
Opinions ?

**Comment by TheAssassin** [comment]
Texts should be more similar to what's in the first run panel, otherwise looks quite nice. I like it.

"Show launcher dialog" is not precise enough. It's also redundant to the question below. Please double check with the config settings, there's no "two" settings for this.

What's "defaults" supposed to do?

What's "auto integration" supposed to mean? Is it to disable the daemon? Should be reworded in that case.

Regarding text changes, I can do that, too, once the panel's there. IMO they should elaborate a bit more, or there should be some hover popup or some question mark button nearby that contains explanations.

What about using tabs by the way? Are they still modern? Could be used to separate GUI and daemon (and maybe future FS or other options) form each other.

**Comment by azubieta** [comment]
> "Show launcher dialog" is not precise enough. It's also redundant to the question below. Please double check with the config settings, there's no "two" settings for this.

Wasn't sure if the dialog if shown for something else than asking if the files should be moved or not. Will remove that one.


> What's "defaults" supposed to do?

Restore the default watched directories, by example: 
```
/usr/bin
/usr/local/bin
$HOME/Applications
```

> What's "auto integration" supposed to mean? Is it to disable the daemon? Should be reworded in that case.

This one was on purpose, I think that regular users doesn't know/care about daemons but do know/care about a having given feature enabled or not.

> What about using tabs by the way? Are they still modern? Could be used to separate GUI and daemon (and maybe future FS or other options) form each other.

If another settings box is required then we will have to use tabs.

**Comment by TheAssassin** [comment]
You should download and try software before making dialogs, I guess...

The default is $integration_dir, anything there is additional. I don't think we need that. There should rather be a "reset to defaults" button as in the first run dialog, which resets the entire config to defaults (there's a call to set up a "default" config where everything is commented, this might come in handy here).


I guess your recommendation is to leave it as-is until there's more settings then?

Regarding the daemon config, I think us developers should never belittle users. I think it's more sane to put in something along "enable daemon" with an extended description somewhere nearby.

**Comment by TheAssassin** [comment]
Closed by #163.
