### ISSUE TITLE
Appimagelauncher has conflicts with freecad.appimage

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncher#82]
I'm having this problem. I have freecad integrated in the desktop by appimagelauncher, but after I run it from the freecad application menu it gives me this error:
![freecad](https://user-images.githubusercontent.com/29207169/45261027-51a43000-b3b4-11e8-8688-30922cd89613.png)
If I run freecad.appimage from the applications folder, it does not generate any conflict.
link for appimage freecad: 
https://github.com/FreeCAD/FreeCAD/releases/download/0.17/FreeCAD-0.17.13541.9948ee4.glibc2.17-x86_64.AppImage
Here a video:

[freecad.zip](https://github.com/TheAssassin/AppImageLauncher/files/2363981/freecad.zip)

**Comment by TheAssassin** [comment]
With the latest version of AppImageLauncher, the AppImage seems to run fine.

Please provide the output of `cat ~/.local/share/applications/appimagekit*-freecad.desktop`.

**Comment by TheAssassin** [comment]
Possibly duplicate #79.

**Comment by TheAssassin** [comment]
@Lvaskz I need you to check again whether latest version of AppImageLauncher fixes the bug.

Also, in the future, please provide the version of AppImageLauncher right away, that'd be _very_ helpful:

```bash
$ AppImageLauncher --version
```

**Comment by Lvaskz** [comment]
Hi, I just installed appimagelauncher appimagelauncher_1-alpha-travis305.git20180914.64e1fd6.bionic_amd64.deb, but the issue still persists in freecad version 0.17. With the freecad conda version, it seems to work fine, but freecad conda has a problem that does not allow me to see the menus.
This is output file:
[Desktop Entry]
Version=1.0
Name=FreeCAD (13528.glibc2.17)
Comment=Feature based Parametric Modeler
Comment[de_DE]=Feature-basierter parametrischer Modellierer
Comment[fr]=Modeleur paramétrique à base de fonctions
GenericName=CAD Application
GenericName[de_DE]=CAD-Anwendung
GenericName[fr]=Application de CAO
Exec=/home/amiel/Applications/FreeCAD-13528.glibc2.17-x86_64(1)_fb973c218aa319d875fa0f76e1e863be.AppImage --single-instance %U
Terminal=false
Type=Application
Icon=appimagekit_5c061ddc94fa95da6fab516d3023ffd6_freecad
Categories=Graphics;Science;Engineering;
StartupNotify=true
MimeType=application/x-extension-fcstd;
X-AppImage-Version=13528.glibc2.17
TryExec=/home/amiel/Applications/FreeCAD-13528.glibc2.17-x86_64(1)_fb973c218aa319d875fa0f76e1e863be.AppImage
X-AppImage-Old-Icon=freecad
X-AppImage-Old-Name=FreeCAD
X-AppImage-Identifier=5c061ddc94fa95da6fab516d3023ffd6
Actions=Remove;Update;
X-AppImageLauncher-Version=1-alpha (git commit 64e1fd6), built on 2018-09-14 02:30:55 UTC

[Desktop Action Remove]
Name=Remove AppImage from system
Exec=/usr/lib/appimagelauncher/remove /home/amiel/Applications/FreeCAD-13528.glibc2.17-x86_64(1)_fb973c218aa319d875fa0f76e1e863be.AppImage
Name[de]=AppImage vom System entfernen
Name[en]=Remove AppImage from system
Name[es]=Eliminar Appimage del Sistema
Name[fr]=Supprimer l'AppImage du système
Name[ru]=Удалить AppImage из системы

[Desktop Action Update]
Name=Update AppImage
Exec=/usr/lib/appimagelauncher/update /home/amiel/Applications/FreeCAD-13528.glibc2.17-x86_64(1)_fb973c218aa319d875fa0f76e1e863be.AppImage
Name[de]=AppImage aktualisieren
Name[en]=Update AppImage
Name[es]=Actualizar Appimage
Name[fr]=Mettre à jour l'AppImage
Name[ru]=Обновить AppImage

**Comment by Lvaskz** [comment]
This is output file with freecad conda:
[Desktop Entry]
Version=1.0
Name=FreeCAD Conda
Exec=/home/amiel/Applications/FreeCAD_0.18_Conda_Py3Qt5_glibc2.12-x86_64_58260cbce782b3b88e7308c5234b895b.AppImage
Icon=appimagekit_3aadb5e8e7478d5f17ad042b8313d63e_freecad_conda
Type=Application
Categories=Engineering;
Comment=Feature based Parametric Modeler
Terminal=false
StartupNotify=true
NoDisplay=false
MimeType=application/x-extension-fcstd;
TryExec=/home/amiel/Applications/FreeCAD_0.18_Conda_Py3Qt5_glibc2.12-x86_64_58260cbce782b3b88e7308c5234b895b.AppImage
X-AppImage-Old-Icon=freecad_conda
X-AppImage-Identifier=3aadb5e8e7478d5f17ad042b8313d63e
Actions=Remove;Update;
X-AppImageLauncher-Version=1-alpha (git commit adec9be), built on 2018-09-06 11:18:52 UTC

[Desktop Action Remove]
Name=Remove AppImage from system
Exec=/usr/lib/appimagelauncher/remove /home/amiel/Applications/FreeCAD_0.18_Conda_Py3Qt5_glibc2.12-x86_64_58260cbce782b3b88e7308c5234b895b.AppImage
Name[de]=AppImage vom System entfernen
Name[en]=Remove AppImage from system
Name[es]=Eliminar Appimage del Sistema
Name[fr]=Supprimer l'AppImage du système
Name[ru]=Удалить AppImage из системы

[Desktop Action Update]
Name=Update AppImage
Exec=/usr/lib/appimagelauncher/update /home/amiel/Applications/FreeCAD_0.18_Conda_Py3Qt5_glibc2.12-x86_64_58260cbce782b3b88e7308c5234b895b.AppImage
Name[de]=AppImage aktualisieren
Name[en]=Update AppImage
Name[es]=Actualizar Appimage
Name[fr]=Mettre à jour l'AppImage
Name[ru]=Обновить AppImage

**Comment by Lvaskz** [comment]
I noted a difference in the exec line, in conda has not indicate "single ui"

**Comment by Lvaskz** [comment]
any progress?

**Comment by Lvaskz** [comment]
Hi, I made a VM with linuxmit 19 and the issue remains.
It is not only in my machine, Can some one try it?

**Comment by Lvaskz** [comment]
![ksnip_20180920-163609](https://user-images.githubusercontent.com/29207169/45850437-66a58b00-bcf3-11e8-887f-dd76b6ea6b80.png)

**Comment by joel6890** [comment]
I get exactly the same error. Fresh install of Kubuntu 18.04, and FreeCAD development release.

I'm using this FreeCAD image: https://github.com/FreeCAD/FreeCAD/releases/download/0.18_pre/FreeCAD_0.18.14796.glibc2.17-x86_64.AppImage

I'll edit this comment with the FreeCAD version once I figure out how to find it. I just found, and installed, appimagelauncher today though, so it should be the latest... I installed via apt-get after adding the repo per official instructions.

![screenshot_20180928_141738](https://user-images.githubusercontent.com/2159416/46226131-5449d380-c329-11e8-8c31-108f59c9d109.png)

**Comment by TheAssassin** [comment]
Is this still an issue with 1.0.0 beta 3?

**Comment by Lvaskz** [comment]
I will try.

**Comment by Lvaskz** [comment]
Yes the issue remains

**Comment by TheAssassin** [comment]
All I can tell is I can't reproduce this behavior with this file and the latest version of AppImageLauncher in a fresh Kubuntu 18.04 VM.

You as a long-time user might have some broken files on your system which prevent this from working. I'd like to invite you to #appimage on Freenode and try to fix this issue on your specific system.

**Comment by Lvaskz** [comment]
Sure.
By the way, when I reported this issue I was in ubuntu 18.04, later I made a VM in Linuxmint 19. 
And later I decided not using ubuntu 18.03 because it was to much heavy to my light computer, so I changes it to linuxmint 19 in november month around. 
I think broken files in my system is not the case, but any way I will try #appimage on freenode. Only I asking you is what is that and where find it? Can you send me a link?

**Comment by TheAssassin** [comment]
It's an IRC channel.

- Webchat: https://webchat.freenode.net/?channels=AppImage
- Guidelines for IRC newbies (really worth reading): https://workaround.org/getting-help-on-irc/

**Comment by Lvaskz** [comment]
I used liveusb kde neon and same problem. I will try webchat to see if there is a solution. I'll take some time untill read guidelines.

**Comment by Lvaskz** [comment]
With Freecad 0.18 works well. 
Closing......
