### ISSUE TITLE
Only show update desktop action if update information is available in AppImage

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#85]
See title. It's a quite obvious change, actually, I don't know why I didn't have the idea earlier. I think we should implement it after merging the UI refreshment @azubieta prepares.

**Comment by maverick74** [comment]
A few questions:

1st, Clarify me about something: We're talking about only showing the Update context option when there are updates available for a specific App, right?

If so, why not also show an icon over the Application's Icon indicating there are updates available?
This way there would not be the need to right click it just to see if there are updates.

Also, is it possible to set an option saying that one wants the app to always get updated as soon as a new update is available?

**Comment by TheAssassin** [comment]
> 1st, Clarify me about something: We're talking about only showing the Update context option when there are updates available for a specific App, right?

No. We check whether the author embedded the information so that AppImageUpdate could check for updates. The first is a static check requiring to read some data from the file, whereas the latter reads that data, constructs a HTTP URL from it, and then makes HTTP requests to it.

**Comment by maverick74** [comment]
@TheAssassin I see! I misunderstand it, then!
So, an auto-update option would not fit with AppImageLauncher but probably more on the NX Software Center...
You just make use of the already "built in" features of appimage...

(I think now i got it ;) Thank you :)

**Comment by TheAssassin** [comment]
It's just that I wanted to avoid the need for additional tools to manage integrated AppImages. The launcher has all the functionality built in already. By using that stuff, we can provide a *very* subtle but powerful AppImage user experience.

**Comment by maverick74** [comment]
Yes, but AppImageLauncher works just as well on Plasma as it does on Gnome, right?

`lease let me know about changes to the translations`

Translations done ;)

**Comment by TheAssassin** [comment]
AppImageLauncher works fine on Plasma, yes. I am using this every day. That's the idea behind AppImageLancher -- use only features that work on all desktop environments (at least the ones who implement the basic XDG/FreeDesktop specifications).

**Comment by TheAssassin** [comment]
Oh, by the way, I said most desktop environments don't support AppImages natively.

Here's a positive example: Nitrux. They really like AppImage, and today, they announced native AppImageUpdate support in their desktop environment: https://plus.google.com/+NitruxInside/posts/QRuhPY3fEzX

**Comment by maverick74** [comment]
@TheAssassin how's the _big-ui-refactoring_ coming along?

**Comment by TheAssassin** [comment]
Tracked now in #150.

Closing this issue as resolved.
