### ISSUE TITLE
Uninstalling AppImageLauncher Problems

### ISSUE THREAD

**Issue by Y0Mamma** [TheAssassin/AppImageLauncher#86]
Hi. Your software looks like it will serve a good purpose. 
I have been trying it out on Linux Mint 19 and now I want to uninstall it and test it on another machine.
I have looked everywhere and can't figure out how to uninstall.

1) I couldn't find anything with Synaptic when searching for "AppImage"
2) I tried ->  sudo apt remove appimagelauncher
3) I tried ->  sudo apt remove appimagelauncher*

I think what happened was that I installed the wrong package ( AppImageLauncher-travis305-git20180914.64e1fd6-x86_64.AppImage )

I only have 4 appimages on my system and the appimagelauncher is only appearing when I try to start the KeepassXC appimage.

AppImageLauncher doesn't appear for krita-4.1.1-x86_64.AppImage, qTox-v1.16.3.x86_64.AppImage, or Stacer-x64.AppImage

I did a system restore from a week ago using TimeShift, but AppImageLauncher still appears when trying to launch KeepassXC.

Any ideas?

**Comment by Y0Mamma** [comment]
Hi. I had already done the steps you suggested, but I did them again to
make sure.
It didn't fix the problem.
I have 4 appimages. Strangely, the only time I get the appimagelauncher
screen is when I try to run the KeePassXC appimage.
I've attached the screen shots. I answer no to each question.
[image: 1.jpg]
[image: 2.jpg]


---------
Shane

**Comment by TheAssassin** [comment]
Closing due to lack of reply. Feel free to reopen if you get interested again.
