### ISSUE TITLE
Document AppImageLauncher configuration, e.g., in the Wiki

### ISSUE THREAD

**Issue by azubieta** [TheAssassin/AppImageLauncher#93]
We should add a link in the generated config file to a wiki page explaining the available options. That's been requested earlier.

**Comment by LongLiveCHIEF** [comment]
For reference until this is completed, can you tell me where the config file is located?

**Comment by TheAssassin** [comment]
Should be at `.config/appimagelauncher.cfg`.

**Comment by LongLiveCHIEF** [comment]
Thanks!

**Comment by LongLiveCHIEF** [comment]
Tell ya what, I'll start to put together a wiki page as I look to configure things. Right now I'm looking into how the icons are generated to see if the reason my icon for Slic3r is almost completely transparent due to a bug with AppImageLauncher or just how it was packaged.

**Comment by TheAssassin** [comment]
Please note that the configuration file is in a sort of beta state right now, it's not complete and likely to be replaced in the future.

**Comment by LongLiveCHIEF** [comment]
After spending 5 minutes going through the code, I can definitely see that :-) No worries.

**Comment by TheAssassin** [comment]
JFYI we have a configuration UI now that is shipped with AppImageLauncher.

**Comment by azubieta** [comment]
To be used in the documentation 
![Screenshot_20190709_114739](https://user-images.githubusercontent.com/1138094/60907876-1a1f4200-a26a-11e9-9225-2cb290807bc1.png)

**Comment by azubieta** [comment]
WIP: https://github.com/TheAssassin/AppImageLauncher/wiki/Configuration

**Comment by TheAssassin** [comment]
@azubieta has documented most of it. Everyone is welcome to improve it. We will try to remember updating the document on future changes.
