### ISSUE TITLE
Does not recognize different versions of Cacher.io as the same application

### ISSUE THREAD

**Issue by pykong** [TheAssassin/AppImageLauncher#94]
@TheAssassin Thank you very much for putting up this very useful tool!

The snippet manager tool cacher is now shipping via AppImage.
This app is young and under heavy development, hences updates are rolled out frequently.
Just yesterday there were two updates on a single day.

Unfortunately AppImageLauncher does not recognize a new version of Cacher to belong to the same app.

Supposedly this is due to the file names which contain the version numer itself.

```
cacher-1.6.7-x86_64.AppImage
```

I do not know whether this is a more general issue with AppImageLauncher or a problem with Cacher.
It might even be a fundamental limitation at hand here that can not be worked around.

**Potential solutions:**
- use different update mechanism (AppImageUpdater?)
- source additional information about image to determine which application it belongs to

_As a side note: A donate link would be great._

**Comment by TheAssassin** [comment]
@pykong AppImages are treated as independent applications. There is no "application name" matching, or "filename" matching of any kind. We only use the file's hash to compare different files and avoid re-integrating the exact same file twice.

We consider being able to use multiple versions of an app by having multiple AppImages on the system.
![](https://user-images.githubusercontent.com/4503202/46235751-16c26600-c37c-11e8-8fe1-bf9606996ef2.png)
By setting `$VERSION` to a meaningful value during AppImage creation (e.g., `export VERSION=1.2.3`), the version is added to the AppImage filename and also the desktop file (which is what AppImageLauncher uses to set up the entries as demonstrated above).

Ideally, cacher set up [AppImageUpdate](https://docs.appimage.org/packaging-guide/optional/updates.html), then you can simply use the context manager to update the application (and even have it remove the old one after completing the update during the process, if you wish to do so).

**Comment by TheAssassin** [comment]
Regarding donations: we never felt the need to set up donations so far. We will discuss this again.

**Comment by pykong** [comment]
@TheAssassin Thanks for enlightening me about the version management of AppImages.
I will pass on the idea of using AppImageUpdate in Cacher to its creator.

**Comment by TheAssassin** [comment]
Feel free to pass by in #appimage on Freenode if you have more questions.
